In [605]:
!jupyter nbconvert --to notebook --execute preprocess.ipynb --inplace

[NbConvertApp] Converting notebook preprocess.ipynb to notebook
[NbConvertApp] Writing 120652 bytes to preprocess.ipynb

In [708]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from pulp import *
from scipy.stats import poisson, norm
from pulp import LpProblem, LpMaximize, LpVariable, LpStatus, lpSum, value, PULP_CBC_CMD

In [709]:
OUT_CSV = "fantasy_enriched.csv"


| Position        | Point Source         | Points | Description                                                                 |
| --------------- | -------------------- | -----: | --------------------------------------------------------------------------- |
| **All Players** | Appearance (<60 min) |     +1 | Plays any minutes up to 59:59                                               |
| **All Players** | Appearance (60+ min) |     +1 | Additional point for reaching 60+ minutes (total appearance = **2 points**) |
| **All Players** | Assist               |     +3 | Provides an assist                                                          |
| **All Players** | Yellow Card          |     -1 | Receives a yellow card                                                      |
| **All Players** | Red Card             |     -2 | Receives a red card                                                         |
| **All Players** | Own Goal             |     -2 | Scores an own goal                                                          |
| **All Players** | Winning a Penalty    |     +2 | Wins a penalty for their team                                               |
| **All Players** | Conceding a Penalty  |     -1 | Commits a foul leading to a penalty                                         |

| Position       | Point Source                  | Points | Description                                        |
| -------------- | ----------------------------- | -----: | -------------------------------------------------- |
| **Goalkeeper** | Clean Sheet                   |     +5 | Plays 60+ minutes and team keeps a clean sheet     |
| **Goalkeeper** | First Goal Conceded           |      0 | No deduction for conceding the first goal          |
| **Goalkeeper** | Each Additional Goal Conceded |     -1 | Every goal conceded after the first                |
| **Goalkeeper** | Goal Scored                   |     +9 | Scores a goal                                      |
| **Goalkeeper** | Penalty Save                  |     +3 | Saves a penalty during normal play (not shootouts) |
| **Goalkeeper** | Every 3 Saves                 |     +1 | Earns 1 point for every 3 saves                    |

| Position     | Point Source                  | Points | Description                                    |
| ------------ | ----------------------------- | -----: | ---------------------------------------------- |
| **Defender** | Clean Sheet                   |     +5 | Plays 60+ minutes and team keeps a clean sheet |
| **Defender** | First Goal Conceded           |      0 | No deduction for conceding the first goal      |
| **Defender** | Each Additional Goal Conceded |     -1 | Every goal conceded after the first            |
| **Defender** | Goal Scored                   |     +7 | Scores a goal                                  |

| Position       | Point Source                | Points | Description                                    |
| -------------- | --------------------------- | -----: | ---------------------------------------------- |
| **Midfielder** | Clean Sheet                 |     +1 | Plays 60+ minutes and team keeps a clean sheet |
| **Midfielder** | Goal Scored                 |     +6 | Scores a goal                                  |
| **Midfielder** | Every 3 Tackles             |     +1 | Earns 1 point for every 3 tackles              |
| **Midfielder** | Every 2 Big Chances Created |     +1 | Earns 1 point for every 2 big chances created  |

| Position    | Point Source            | Points | Description                               |
| ----------- | ----------------------- | -----: | ----------------------------------------- |
| **Forward** | Goal Scored             |     +5 | Scores a goal                             |
| **Forward** | Every 2 Shots on Target |     +1 | Earns 1 point for every 2 shots on target |

| Position                | Point Source          | Points | Description                                                                                                                                                                        |
| ----------------------- | --------------------- | -----: | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **Bonus (All Players)** | Direct Free-Kick Goal |     +1 | Additional bonus for scoring directly from a free kick (on top of goal points)                                                                                                     |
| **Bonus (All Players)** | Scouting Bonus        |     +2 | Scores **more than 4 base fantasy points** in a match **and** is selected by **<5%** of fantasy teams. Captaincy and booster points do **not** count toward the 4-point threshold. |


## Core identity / player info

| Column | Type | Description |
|---|---|---|
| `fifa_id` | int | Unique FIFA fantasy player ID |
| `name` | str | Player name |
| `squad_id` | int | Internal squad/nation ID |
| `team` | str | National team |
| `position` | str | DEF / MID / FWD / GK |
| `price` | float | Fantasy price |
| `status` | str | Availability status |
| `total_points` | int | Total tournament points |
| `avg_points` | float | Average points per match |
| `matches_played` | int | Matches with participation |
| `percent_selected` | float | Selection rate (%) |
| `next_fixture` | int | Next match ID |


## Round fantasy points

| Column | Type | Description |
|---|---|---|
| `round_1_points` | int | Points in round 1 |
| `round_2_points` | int | Points in round 2 |
| `round_3_points` | int | Points in round 3 |
| `round_4_points` | int | Points in round 4 |


## Betting / scorer mapping

| Column | Type | Description |
|---|---|---|
| `betano_matched_name` | str | Matched Betano market name |
| `betano_match_score` | float | Name matching confidence (0–100) |
| `anytime_scorer_prob` | float | Probability player scores anytime |
| `first_scorer_prob` | float | Probability scores first goal |
| `last_scorer_prob` | float | Probability scores last goal |


## Match context

| Column | Type | Description |
|---|---|---|
| `match_home` | str | Home team |
| `match_away` | str | Away team |
| `is_home` | bool | Player team is home |
| `opponent` | str | Opponent team |


## Match probabilities 

| Column | Type | Description |
|---|---|---|
| `match_home_win_prob` | float | Home win probability |
| `match_draw_prob` | float | Draw probability |
| `match_away_win_prob` | float | Away win probability |
| `match_btts_prob` | float | Both teams score probability |
| `match_over_25_prob` | float | Over 2.5 goals probability |
| `match_over_35_prob` | float | Over 3.5 goals probability |
| `team_score_prob` | float | Team scores ≥1 goal probability |
| `team_score_2_prob` | float | Team scores ≥2 goals probability |
| `team_cs_prob` | float | Team clean sheet probability |
| `opp_score_prob` | float | Opponent scores ≥1 goal probability |
| `opp_cs_prob` | float | Opponent clean sheet probability |
| `team_over_05_prob` | float | Team scores ≥1 goal probability |
| `team_over_15_prob` | float | Team scores ≥2 goals probability |
| `team_qualify_prob` | float | Team advances probability |
| `team_win2_prob` | float | Team wins by 2+ goals probability |
| `opp_over_05_prob` | float | Opponent scores ≥1 goal probability |


## Raw cumulative stats

| Column | Type | Description |
|---|---|---|
| `stat_GS` | int | Goals |
| `stat_AS` | int | Assists |
| `stat_CS` | int | Clean sheets |
| `stat_GC` | int | Goals conceded |
| `stat_MP` | int | Minutes played |
| `stat_YC` | int | Yellow cards |
| `stat_RC` | int | Red cards |
| `stat_ST` | int | Shots on target |
| `stat_SB` | int | Shots blocked |
| `stat_CC` | int | Chances created |
| `stat_PS` | int | Penalties saved |
| `stat_T` | int | Tackles |
| `stat_S` | int | Saves |
| `stat_SXI` | int | Starts (XI appearances) |
| `stat_OG` | int | Own goals |
| `stat_PC` | int | Penalties committed |
| `stat_PW` | int | Penalties won |
| `stat_FK` | int | Free kicks won |



## Round-by-round stats (1–4)

| Pattern | Type | Description |
|---|---|---|
| `round_i_SXI` | int | Started (0/1) |
| `round_i_MP` | int | Minutes |
| `round_i_AS` | int | Assists |
| `round_i_YC` | int | Yellow cards |
| `round_i_RC` | int | Red cards |
| `round_i_OG` | int | Own goals |
| `round_i_PW` | int | Penalties won |
| `round_i_PC` | int | Penalties committed |
| `round_i_CS` | int | Clean sheets |
| `round_i_GS` | int | Goals |
| `round_i_GC` | int | Goals conceded |
| `round_i_PS` | int | Penalties saved |
| `round_i_T` | int | Tackles |
| `round_i_CC` | int | Chances created |
| `round_i_ST` | int | Shots on target |
| `round_i_FK` | int | Free kicks |
| `round_i_S` | int | Saves |
| `round_i_SB` | int | Shots blocked |



## External matching / enrichment

| Column | Type | Description |
|---|---|---|
| `clubstats_matched_player` | str | External player match |
| `clubs_match_dist` | float | Matching distance score |



## Form / usage trends

| Column | Type | Description |
|---|---|---|
| `started_last_match` | int | Started last match |
| `starts_last_3` | int | Starts last 3 matches |
| `starts_last_5` | int | Starts last 5 matches |
| `start_rate` | float | Start frequency |
| `minutes_last_3_avg` | float | Avg minutes last 3 |
| `minutes_last_5_avg` | float | Avg minutes last 5 |



## Performance rates

| Column | Type | Description |
|---|---|---|
| `goal_rate` | float | Goals per minute |
| `goals_per_start` | float | Goals per start |
| `shots_on_target_per90` | float | SOT per 90 |
| `goals_per_shot_on_target` | float | Conversion rate |
| `assist_rate` | float | Assists per minute |
| `chance_created_per90` | float | Chances per 90 |
| `tackles_per90` | float | Tackles per 90 |
| `cc_per90` | float | Chances created per 90 |
| `sot_per90` | float | Shots on target per 90 |
| `saves_per90` | float | Saves per 90 |
| `yc_per90` | float | Yellow cards per 90 |
| `rc_per90` | float | Red cards per 90 |
| `penalty_conceded_rate` | float | Penalties conceded per 90 |
| `own_goal_rate` | float | Own goals per 90 |
| `penalties_won_per90` | float | Penalties won per 90 |



## Recent / streak features

| Column | Type | Description |
|---|---|---|
| `recent_goals_last3` | int | Goals last 3 matches |
| `goal_streak` | int | Consecutive scoring matches |
| `recent_assists_last3` | int | Assists last 3 matches |
| `recent_chances_created_per90` | float | Recent creation rate |
| `recent_cs_rate` | float | Clean sheet rate |
| `recent_tackles_per90` | float | Recent tackles |
| `recent_cc_per90` | float | Recent chances created |
| `recent_sot_per90` | float | Recent shots on target |
| `recent_saves_per90` | float | Recent saves |
| `recent_penalties_won` | int | Penalties won last 3 |



## Expected value features

| Column | Type | Description |
|---|---|---|
| `goal_expectation` | float | Scoring proxy |
| `goal_expectation2` | float | Scoring proxy (2+ goals) |
| `assist_expectation` | float | Assist proxy |
| `cs_expectation` | float | Clean sheet proxy |
| `expected_minutes` | float | Expected minutes |
| `expected_gc_penalty` | float | Defensive penalty |
| `expected_tackle_points` | float | Tackles contribution |
| `expected_cc_points` | float | Chance creation points |
| `expected_sot_points` | float | Shot contribution points |
| `expected_save_points` | float | Save contribution points |



## Fantasy points dynamics

| Column | Type | Description |
|---|---|---|
| `points_last1` | int | Last match points |
| `points_last3_avg` | float | Avg last 3 |
| `points_last5_avg` | float | Avg last 5 |
| `weighted_points` | float | Recency weighted |
| `rolling_std_points` | float | Variance last 5 |
| `rolling_max_points` | int | Max last 5 |



## Team-position ranking features

| Column | Type | Description |
|---|---|---|
| `price_rank_team_position` | float | Price rank |
| `selected_rank_team_position` | float | Selection rank |
| `points_rank_team_position` | float | Points rank |
| `minutes_rank_team_position` | float | Minutes rank |
| `starts_rank_team_position` | float | Starts rank |
| `anytime_rank_team_position` | float | Scoring odds rank |
| `shots_rank_team_position` | float | Shooting rank |
| `cc_rank_team_position` | float | Chance creation rank |
| `tackles_rank_team_position` | float | Tackles rank |

In [710]:
df= pd.read_csv("fantasy_enriched.csv")

In [711]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [712]:
df = df[df["status"] == "playing"].copy()

In [713]:
# probability of playing a minute

raw_any = (
    0.2* df["minutes_rank_team_position"]
  + 0.10 * df["stat_MP"]        # minutes needs to be very team stratified since while for other point sources players are all eligible
  + 0.15 * df["starts_rank_team_position"]
  + 0.10 * df["price_rank_team_position"]     # for minutes its a team stratified signal.
  + 0.1 * df["selected_rank_team_position"]
  + 0.25 * df["minutes_last_3_avg"]
  + 0.1 * df["has_betano_match"] # having odd at all means likeliness of playing is higher.

)

df["prob_plays_any"] = sigmoid((raw_any - 0.5) * 6)

In [714]:
df.loc[
    :,
    [
        "prob_plays_any",
        "name",
        "team",
        "position",
        "stat_MP",
        "minutes_rank_team_position",
        "starts_rank_team_position",
        "selected_rank_team_position",
        "price_rank_team_position",
        "anytime_rank_team_position",
    ],
].sort_values("prob_plays_any", ascending=False).head(30)

,prob_plays_any,name,team,position,stat_MP,minutes_rank_team_position,starts_rank_team_position,selected_rank_team_position,price_rank_team_position,anytime_rank_team_position
10,0.937027,Emiliano Martínez,Argentina,GK,1.000000,1.000000,0.666667,1.000000,1.000000,1.000000
211,0.931775,Gustavo Gómez,Paraguay,DEF,1.000000,1.000000,0.571429,1.000000,1.000000,1.000000
394,0.931263,Achraf Hakimi,Morocco,DEF,1.000000,1.000000,0.562500,1.000000,1.000000,1.000000
148,0.920195,Kylian Mbappé,France,FWD,0.900000,1.000000,0.666667,1.000000,1.000000,1.000000
127,0.918872,Harry Kane,England,FWD,0.907692,1.000000,0.625000,1.000000,1.000000,1.000000
86,0.915806,Luis Díaz,Colombia,MID,0.917949,1.000000,0.545455,1.000000,1.000000,1.000000
350,0.915676,Cristiano Ronaldo,Portugal,FWD,0.900000,1.000000,0.600000,1.000000,1.000000,1.000000
65,0.915617,Jonathan David,Canada,FWD,0.848718,1.000000,0.583333,1.000000,1.000000,1.000000
285,0.913635,Breel Embolo,Switzerland,FWD,0.889744,1.000000,0.600000,1.000000,1.000000,1.000000
48,0.912136,Vinícius Júnior,Brazil,MID,0.900000,1.000000,0.550000,1.000000,1.000000,1.000000
41,0.911742,Gabriel Magalhães,Brazil,DEF,0.923077,0.937500,0.562500,1.000000,1.000000,0.625000
277,0.911742,Manuel Akanji,Switzerland,DEF,0.923077,0.937500,0.562500,1.000000,1.000000,0.687500
185,0.908473,Ismael Saibari,Morocco,MID,0.930769,0.888889,0.555556,1.000000,1.000000,1.000000
5,0.905064,Lionel Messi,Argentina,FWD,0.820513,1.000000,0.625000,1.000000,1.000000,1.000000
232,0.902548,Nuno Mendes,Portugal,DEF,0.874359,0.875000,0.562500,1.000000,1.000000,1.000000
107,0.902362,Mohamed Hany,Egypt,DEF,1.000000,1.000000,0.562500,0.862500,0.500000,0.500000
250,0.902235,Bruno Fernandes,Portugal,MID,0.853846,1.000000,0.550000,1.000000,1.000000,0.900000
39,0.901551,Youri Tielemans,Belgium,MID,0.987179,1.000000,0.545455,0.700000,0.727273,0.500000
359,0.900698,Mohamed Salah,Egypt,MID,0.866667,0.900000,0.550000,1.000000,1.000000,1.000000
112,0.898316,Omar Marmoush,Egypt,FWD,0.810256,1.000000,0.625000,1.000000,1.000000,0.875000
42,0.898220,Marquinhos,Brazil,DEF,0.923077,0.937500,0.562500,0.862500,0.875000,0.125000
272,0.898151,Granit Xhaka,Switzerland,MID,0.923077,1.000000,0.550000,0.780000,0.850000,0.600000
82,0.894740,Dávinson Sánchez,Colombia,DEF,0.923077,0.937500,0.562500,0.862500,0.812500,0.625000
379,0.894740,Alistair Johnston,Canada,DEF,0.923077,1.000000,0.562500,0.862500,0.687500,0.625000
143,0.894634,Dayot Upamecano,France,DEF,0.887179,1.000000,0.555556,0.877778,0.833333,0.888889
298,0.894506,Weston McKennie,USA,MID,0.907692,1.000000,0.550000,0.780000,0.850000,0.600000
19,0.894497,Alexis Mac Allister,Argentina,MID,0.843590,1.000000,0.545455,1.000000,0.909091,0.454545
124,0.893199,Ezri Konsa,England,DEF,0.923077,1.000000,0.555556,0.755556,0.777778,0.500000
344,0.893129,Leandro Trossard,Belgium,MID,0.925641,0.909091,0.545455,0.900000,0.818182,0.863636
257,0.891881,Marc Cucurella,Spain,DEF,0.923077,0.937500,0.562500,1.000000,0.625000,0.625000

In [715]:
# probability of starting / playing 60 minutes

raw_any = (
    0.15 * df["minutes_rank_team_position"]
  + 0.10 * df["starts_rank_team_position"]
  + 0.15 * df["stat_MP"]
  + 0.05 * df["selected_rank_team_position"]
  + 0.35 * df["minutes_last_3_avg"]
  + 0.15 * df["round_4_MP"]
  + 0.05 * df["has_betano_match"] # having odd at all means likeliness of playing is higher.

)

df["prob_plays_60min"] = sigmoid((raw_any - 0.5) * 6)

In [716]:
cols = [
    "name",
    "team",
    "position",
    "prob_plays_60min",
    "minutes_rank_team_position",
    "starts_rank_team_position",
    "price_rank_team_position",
    "selected_rank_team_position",
    "minutes_last_3_avg",
    "round_4_MP",
    "anytime_rank_team_position",
]

df[cols].sort_values("prob_plays_60min", ascending=False).head(30)

,name,team,position,prob_plays_60min,minutes_rank_team_position,starts_rank_team_position,price_rank_team_position,selected_rank_team_position,minutes_last_3_avg,round_4_MP,anytime_rank_team_position
10,Emiliano Martínez,Argentina,GK,0.942676,1.000000,0.666667,1.000000,1.000000,1.000000,1.000000,1.000000
211,Gustavo Gómez,Paraguay,DEF,0.939509,1.000000,0.571429,1.000000,1.000000,1.000000,1.000000,1.000000
394,Achraf Hakimi,Morocco,DEF,0.939204,1.000000,0.562500,1.000000,1.000000,1.000000,1.000000,1.000000
107,Mohamed Hany,Egypt,DEF,0.936805,1.000000,0.562500,0.500000,0.862500,1.000000,1.000000,0.500000
28,Brandon Mechele,Belgium,DEF,0.934625,1.000000,0.555556,0.277778,0.755556,1.000000,1.000000,0.777778
39,Youri Tielemans,Belgium,MID,0.930263,1.000000,0.545455,0.727273,0.700000,0.983333,1.000000,0.500000
401,Neil El Aynaoui,Morocco,MID,0.928121,1.000000,0.555556,0.444444,0.633333,0.976667,1.000000,0.555556
360,Andrés Cubas,Paraguay,MID,0.927574,1.000000,0.555556,0.277778,0.388889,1.000000,1.000000,0.222222
340,Thibaut Courtois,Belgium,GK,0.924142,1.000000,0.666667,1.000000,1.000000,1.000000,1.000000,0.666667
227,Orlando Gill,Paraguay,GK,0.924142,1.000000,0.666667,0.333333,1.000000,1.000000,1.000000,0.666667
393,Yassine Bounou,Morocco,GK,0.924142,1.000000,0.666667,1.000000,1.000000,1.000000,1.000000,0.666667
111,Yasser Ibrahim,Egypt,DEF,0.923769,0.875000,0.562500,0.187500,1.000000,0.953333,1.000000,0.500000
117,Mostafa Shobeir,Egypt,GK,0.922371,1.000000,0.625000,0.375000,1.000000,1.000000,1.000000,0.500000
185,Ismael Saibari,Morocco,MID,0.915987,0.888889,0.555556,1.000000,1.000000,0.913333,1.000000,1.000000
209,Matías Galarza,Paraguay,MID,0.909457,0.777778,0.555556,0.444444,1.000000,0.993333,1.000000,0.722222
344,Leandro Trossard,Belgium,MID,0.905769,0.909091,0.545455,0.818182,0.900000,0.903333,0.908333,0.863636
359,Mohamed Salah,Egypt,MID,0.904995,0.900000,0.550000,1.000000,1.000000,0.873333,1.000000,1.000000
127,Harry Kane,England,FWD,0.901582,1.000000,0.625000,1.000000,1.000000,0.880000,0.750000,1.000000
86,Luis Díaz,Colombia,MID,0.900602,1.000000,0.545455,1.000000,1.000000,0.896667,0.741667,1.000000
5,Lionel Messi,Argentina,FWD,0.899661,1.000000,0.625000,1.000000,1.000000,0.800000,1.000000,1.000000
379,Alistair Johnston,Canada,DEF,0.899531,1.000000,0.562500,0.687500,0.862500,0.900000,0.750000,0.625000
100,Marwan Attia,Egypt,MID,0.898334,1.000000,0.550000,0.300000,0.615000,0.846667,0.991667,0.250000
65,Jonathan David,Canada,FWD,0.898334,1.000000,0.583333,1.000000,1.000000,0.900000,0.750000,1.000000
41,Gabriel Magalhães,Brazil,DEF,0.898167,0.937500,0.562500,1.000000,1.000000,0.900000,0.750000,0.625000
277,Manuel Akanji,Switzerland,DEF,0.898167,0.937500,0.562500,1.000000,1.000000,0.900000,0.750000,0.687500
257,Marc Cucurella,Spain,DEF,0.898167,0.937500,0.562500,0.625000,1.000000,0.900000,0.750000,0.625000
148,Kylian Mbappé,France,FWD,0.897936,1.000000,0.666667,1.000000,1.000000,0.870000,0.708333,1.000000
272,Granit Xhaka,Switzerland,MID,0.896578,1.000000,0.550000,0.850000,0.780000,0.900000,0.750000,0.600000
19,Alexis Mac Allister,Argentina,MID,0.896554,1.000000,0.545455,0.909091,1.000000,0.796667,1.000000,0.454545
124,Ezri Konsa,England,DEF,0.896207,1.000000,0.555556,0.777778,0.755556,0.900000,0.750000,0.500000

There is a phenomenon where a player will be overvalued, such as Lukaku here for belgium. He has not played much, but since Belgium only has 3 forward and only him has significative minutes he ranks number 1 for all ranks in BEL,FWD. Need to include more general sums and beware with manual selection.

In [ ]:
df["lambda_goal"] = -np.log(
    (1 - df["anytime_scorer_prob"]).clip(lower=0.001)  # clip prevents log(0)
)

lambda_adj = (
    0.80 * df["lambda_goal"]                          # dominant: Betano's model
      + 0.05 * df["recent_goals_last3"]
      + 0.05 * df["team_score_2_prob"]
      + 0.02 * df["stat_GS"]
      + 0.03 * df["stat_ST"]
      + 0.05 * df["price"]
  )

# expected_goals is λ (not a probability — can exceed 1 for elite strikers)
df["prob_scores"] = lambda_adj.clip(lower=0) * df["prob_plays_60min"] * 1.1

In [755]:
cols = [
    "name",
    "team",
    "position",
    "prob_scores",
    "goal_expectation",
    "anytime_scorer_prob",
    "recent_goals_last3",
    "recent_sot_per90",
    "goal_rate",
    "shots_on_target_per90",
    "stat_GS",
    "stat_ST",
    "price_rank_team_position",
]

df[cols].sort_values("prob_scores", ascending=False).head(30)

,name,team,position,prob_scores,goal_expectation,anytime_scorer_prob,recent_goals_last3,recent_sot_per90,goal_rate,shots_on_target_per90,stat_GS,stat_ST,price_rank_team_position
148,Kylian Mbappé,France,FWD,0.924373,0.558959,0.6536,1.00,0.034483,0.324786,0.351852,0.857143,0.866667,1.000000
5,Lionel Messi,Argentina,FWD,0.852061,0.499396,0.6173,1.00,0.045833,0.415625,0.445312,1.000000,1.000000,1.000000
48,Vinícius Júnior,Brazil,MID,0.585635,0.369341,0.4717,0.75,0.034483,0.216524,0.270655,0.571429,0.666667,1.000000
261,Mikel Oyarzabal,Spain,FWD,0.580401,0.378873,0.4950,1.00,0.033175,0.252492,0.252492,0.571429,0.533333,1.000000
149,Ousmane Dembélé,France,MID,0.539992,0.407246,0.4762,1.00,0.024038,0.263889,0.164931,0.571429,0.333333,1.000000
198,Erling Haaland,Norway,FWD,0.524094,0.306133,0.4717,0.75,0.027778,0.351852,0.316667,0.714286,0.600000,1.000000
127,Harry Kane,England,FWD,0.515050,0.282523,0.4167,0.75,0.022727,0.268362,0.241525,0.714286,0.600000,1.000000
185,Ismael Saibari,Morocco,MID,0.461903,0.306347,0.4049,0.50,0.007299,0.157025,0.078512,0.428571,0.200000,1.000000
350,Cristiano Ronaldo,Portugal,FWD,0.457495,0.248913,0.3846,0.75,0.026820,0.162393,0.189459,0.428571,0.466667,1.000000
49,Matheus Cunha,Brazil,FWD,0.430282,0.326276,0.4167,0.75,0.024272,0.242553,0.202128,0.428571,0.333333,1.000000
31,Romelu Lukaku,Belgium,FWD,0.415859,0.335493,0.4587,0.50,0.013072,0.214689,0.107345,0.285714,0.133333,1.000000
318,Lautaro Martínez,Argentina,FWD,0.404757,0.371088,0.4587,0.25,0.005319,0.078189,0.078189,0.142857,0.133333,0.750000
259,Lamine Yamal,Spain,MID,0.394012,0.303711,0.3968,0.25,0.029126,0.084444,0.253333,0.142857,0.400000,1.000000
161,Michael Olise,France,MID,0.375879,0.305392,0.3571,0.00,0.013761,0.000000,0.154221,0.000000,0.333333,0.909091
86,Luis Díaz,Colombia,MID,0.359462,0.240487,0.3390,0.00,0.014870,0.053073,0.132682,0.142857,0.333333,1.000000
331,Bradley Barcola,France,MID,0.337215,0.328910,0.3846,0.25,0.010101,0.182692,0.137019,0.285714,0.200000,0.772727
6,Julián Alvarez,Argentina,FWD,0.335663,0.371088,0.4587,0.00,0.012121,0.000000,0.095000,0.000000,0.133333,0.500000
285,Breel Embolo,Switzerland,FWD,0.335510,0.195326,0.3175,0.25,0.011673,0.109510,0.109510,0.285714,0.266667,1.000000
344,Leandro Trossard,Belgium,MID,0.307428,0.200404,0.2740,0.50,0.011070,0.105263,0.078947,0.285714,0.200000,0.818182
169,Julián Quiñones,Mexico,FWD,0.298435,0.178105,0.2857,0.50,0.011811,0.171171,0.142643,0.428571,0.333333,0.714286
88,Luis Suárez,Colombia,FWD,0.287370,0.240487,0.3390,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000
65,Jonathan David,Canada,FWD,0.276641,0.128422,0.2299,0.75,0.022222,0.172205,0.200906,0.428571,0.466667,1.000000
53,Rayan,Brazil,FWD,0.275962,0.252596,0.3226,0.00,0.004505,0.000000,0.042793,0.000000,0.066667,0.400000
140,Jude Bellingham,England,MID,0.275223,0.173839,0.2564,0.25,0.017094,0.121019,0.181529,0.285714,0.400000,0.900000
313,Christian Pulisic,USA,MID,0.272015,0.282837,0.3891,0.00,0.016667,0.000000,0.115152,0.000000,0.133333,1.000000
402,Brahim Díaz,Morocco,MID,0.266936,0.225845,0.2985,0.00,0.000000,0.000000,0.031879,0.000000,0.066667,0.888889
40,Kevin De Bruyne,Belgium,MID,0.256888,0.200404,0.2740,0.25,0.013953,0.063123,0.126246,0.142857,0.266667,0.954545
39,Youri Tielemans,Belgium,MID,0.254366,0.157324,0.2151,0.50,0.010169,0.098701,0.074026,0.285714,0.200000,0.727273
168,Raúl Jiménez,Mexico,FWD,0.254064,0.201109,0.3226,0.25,0.012987,0.165217,0.165217,0.285714,0.266667,1.000000
298,Weston McKennie,USA,MID,0.253756,0.188776,0.2597,0.00,0.003788,0.000000,0.026836,0.000000,0.066667,0.850000

In [719]:
prob_assists = (
    0.15 * df["chance_created_per90"]
  + 0.20 * df["stat_CC"]
  + 0.15 * df["prob_scores"]
  + 0.15 * df["team_score_2_prob"]
  + 0.15 * df["recent_assists_last3"]
  + 0.10 * df["price"]
  + 0.15 * df["stat_AS"]
)

df["lambda_assist"] = -np.log(
    (1 - prob_assists).clip(lower=0.001)
)

df["expected_assists"] = df["lambda_assist"].clip(lower=0) * df["prob_plays_60min"]

In [720]:
cols = [
    "name",
    "team",
    "position",
    "expected_assists",
    "assist_expectation",
    "stat_CC",
    "recent_cc_per90",
    "team_score_2_prob",
    "recent_assists_last3",
    "price",
    "prob_plays_60min",
    "stat_AS",
]

df[cols].sort_values("expected_assists", ascending=False).head(30)

,name,team,position,expected_assists,assist_expectation,stat_CC,recent_cc_per90,team_score_2_prob,recent_assists_last3,price,prob_plays_60min,stat_AS
161,Michael Olise,France,MID,1.328938,1.249481,1.0,0.178899,0.7634,1.00,0.857143,0.845736,1.0
148,Kylian Mbappé,France,FWD,0.737536,0.219282,0.2,0.049808,0.7634,0.50,1.000000,0.897936,0.4
5,Lionel Messi,Argentina,FWD,0.663625,0.910125,0.8,0.216667,0.6452,0.00,0.928571,0.899661,0.0
321,Bruno Guimarães,Brazil,MID,0.657239,0.621794,0.6,0.150000,0.5714,0.75,0.471429,0.875022,0.8
257,Marc Cucurella,Spain,DEF,0.555977,0.574050,0.6,0.096296,0.5464,0.75,0.228571,0.898167,0.6
149,Ousmane Dembélé,France,MID,0.531818,0.267250,0.2,0.062500,0.7634,0.50,0.928571,0.801957,0.4
171,Roberto Alvarado,Mexico,FWD,0.520762,0.660071,0.8,0.156000,0.3425,0.50,0.257143,0.865252,0.6
285,Breel Embolo,Switzerland,FWD,0.509784,0.478686,0.6,0.050584,0.3390,0.50,0.571429,0.889168,0.4
48,Vinícius Júnior,Brazil,MID,0.450838,0.200769,0.2,0.049808,0.5714,0.25,0.928571,0.894919,0.2
140,Jude Bellingham,England,MID,0.409848,0.582994,0.6,0.166667,0.4049,0.25,0.685714,0.855402,0.2
369,Martin Ødegaard,Norway,MID,0.400011,0.447586,0.4,0.072222,0.3774,0.50,0.600000,0.781991,0.6
261,Mikel Oyarzabal,Spain,FWD,0.384761,0.228857,0.2,0.061611,0.5464,0.25,0.657143,0.848337,0.2
189,Patrick Berg,Norway,MID,0.370351,0.748846,0.6,0.173333,0.3774,0.50,0.300000,0.775912,0.4
344,Leandro Trossard,Belgium,MID,0.360853,0.364687,0.4,0.095941,0.4878,0.25,0.442857,0.905769,0.2
402,Brahim Díaz,Morocco,MID,0.352007,0.457007,0.4,0.055794,0.5181,0.25,0.414286,0.803428,0.4
19,Alexis Mac Allister,Argentina,MID,0.350388,0.221307,0.2,0.000000,0.6452,0.25,0.442857,0.896554,0.4
394,Achraf Hakimi,Morocco,DEF,0.345336,0.349200,0.4,0.086667,0.5181,0.25,0.357143,0.939204,0.2
271,Johan Manzambi,Switzerland,MID,0.344298,0.830520,0.6,0.148571,0.3390,0.50,0.300000,0.685473,0.4
359,Mohamed Salah,Egypt,MID,0.334965,0.120382,0.2,0.049618,0.2000,0.25,0.928571,0.904995,0.4
250,Bruno Fernandes,Portugal,MID,0.332310,0.349838,0.4,0.106996,0.3676,0.25,0.714286,0.854701,0.2
185,Ismael Saibari,Morocco,MID,0.321835,0.375174,0.4,0.094891,0.5181,0.00,0.471429,0.915987,0.0
198,Erling Haaland,Norway,FWD,0.319134,0.216333,0.2,0.072222,0.3774,0.00,1.000000,0.807380,0.2
331,Bradley Barcola,France,MID,0.305346,0.370038,0.2,0.065657,0.7634,0.25,0.642857,0.698293,0.2
53,Rayan,Brazil,FWD,0.305283,0.634865,0.4,0.117117,0.5714,0.25,0.300000,0.772645,0.2
86,Luis Díaz,Colombia,MID,0.284994,0.178341,0.2,0.000000,0.4444,0.00,0.657143,0.900602,0.2
229,Julio Enciso,Paraguay,MID,0.277437,0.231294,0.4,0.055085,0.1786,0.25,0.442857,0.821783,0.4
139,Declan Rice,England,MID,0.269348,0.729323,0.6,0.145251,0.4049,0.00,0.500000,0.753382,0.2
293,Rubén Vargas,Switzerland,MID,0.266575,0.222361,0.2,0.076471,0.3390,0.50,0.471429,0.713842,0.4
127,Harry Kane,England,FWD,0.263518,0.000000,0.0,0.000000,0.4049,0.00,1.000000,0.901582,0.0
75,Nathan Saliba,Canada,MID,0.262612,0.552462,0.4,0.142857,0.2778,0.50,0.228571,0.704711,0.4

In [721]:
position_yc_modifier = {
    "GK": 0.15,
    "FWD": 0.35,
    "DEF": 0.45,
    "MID": 0.55,
}

df["position_yc_modifier"] = df["position"].map(position_yc_modifier)

raw_yc = (
    0.4 * df["yc_per90"]
  + 0.25 * df["tackles_per90"]
  + 0.20 * df["opp_over_05_prob"]
  + 0.05 * df["rc_per90"]
  + 0.1 * df["position_yc_modifier"]
)

df["prob_yellow_card"] = raw_yc * df["prob_plays_60min"]

In [722]:
cols = [
    "name",
    "team",
    "position",
    "prob_yellow_card",
    "yc_per90",
    "stat_YC",
    "tackles_per90",
    "recent_tackles_per90",
    "opp_over_05_prob",
    "prob_plays_60min",
    "rc_per90",
]

df[cols].sort_values("prob_yellow_card", ascending=False).head(30)

,name,team,position,prob_yellow_card,yc_per90,stat_YC,tackles_per90,recent_tackles_per90,opp_over_05_prob,prob_plays_60min,rc_per90
209,Matías Galarza,Paraguay,MID,0.335370,0.255034,1.0,0.046980,0.234899,1.000000,0.909457,0.000000
111,Yasser Ibrahim,Egypt,DEF,0.285791,0.202128,1.0,0.018617,0.104895,0.894349,0.923769,0.000000
360,Andrés Cubas,Paraguay,MID,0.281007,0.097436,0.5,0.035897,0.150000,1.000000,0.927574,0.000000
216,Juan José Cáceres,Paraguay,DEF,0.263572,0.108883,0.5,0.051576,0.240741,1.000000,0.874355,0.000000
100,Marwan Attia,Egypt,MID,0.253704,0.110465,0.5,0.017442,0.059055,0.894349,0.898334,0.000000
212,Júnior Alonso,Paraguay,DEF,0.243877,0.126667,0.5,0.026667,0.142857,1.000000,0.806649,0.000000
211,Gustavo Gómez,Paraguay,DEF,0.232589,0.000000,0.0,0.010256,0.050000,1.000000,0.939509,0.000000
59,Casemiro,Brazil,MID,0.227225,0.262976,1.0,0.041522,0.225410,0.521910,0.826414,0.000000
218,Miguel Almirón,Paraguay,MID,0.226822,0.177570,0.5,0.032710,0.185185,1.000000,0.611949,0.728972
189,Patrick Berg,Norway,MID,0.225200,0.162393,0.5,0.017094,0.066667,0.830040,0.775912,0.000000
347,Rúben Dias,Portugal,DEF,0.222874,0.140741,0.5,0.018519,0.092593,0.784669,0.847881,0.000000
107,Mohamed Hany,Egypt,DEF,0.218130,0.000000,0.0,0.035897,0.133333,0.894349,0.936805,0.000000
236,Renato Veiga,Portugal,DEF,0.218096,0.105556,0.5,0.008333,0.018519,0.784669,0.885709,0.000000
379,Alistair Johnston,Canada,DEF,0.217621,0.105556,0.5,0.002778,0.000000,0.770053,0.899531,0.000000
359,Mohamed Salah,Egypt,MID,0.212320,0.000000,0.0,0.002959,0.000000,0.894349,0.904995,0.000000
22,Timothy Castagne,Belgium,DEF,0.212317,0.127517,0.5,0.033557,0.123967,0.700513,0.868378,0.000000
229,Julio Enciso,Paraguay,MID,0.212075,0.000000,0.0,0.012270,0.042373,1.000000,0.821783,0.000000
75,Nathan Saliba,Canada,MID,0.211955,0.208791,0.5,0.032967,0.164835,0.770053,0.704711,0.000000
28,Brandon Mechele,Belgium,DEF,0.211225,0.097436,0.5,0.007692,0.016667,0.700513,0.934625,0.000000
272,Granit Xhaka,Switzerland,MID,0.208883,0.105556,0.5,0.013889,0.092593,0.661417,0.896578,0.000000
44,Danilo,Brazil,DEF,0.208210,0.241270,1.0,0.006349,0.037037,0.521910,0.841332,0.000000
103,Emam Ashour,Egypt,MID,0.207418,0.000000,0.0,0.009346,0.040000,0.894349,0.878122,0.000000
21,Maxim De Cuyper,Belgium,DEF,0.202640,0.130137,0.5,0.010274,0.038760,0.700513,0.845297,0.000000
62,Derek Cornelius,Canada,DEF,0.202501,0.120635,0.5,0.015873,0.022222,0.770053,0.806031,0.000000
227,Orlando Gill,Paraguay,GK,0.198690,0.000000,0.0,0.000000,0.000000,1.000000,0.924142,0.000000
279,Nico Elvedi,Switzerland,DEF,0.197739,0.105556,0.5,0.008333,0.055556,0.661417,0.892366,0.000000
409,Tyler Adams,USA,MID,0.197098,0.140741,0.5,0.025926,0.138889,0.713969,0.756406,0.000000
108,Ramy Rabia,Egypt,DEF,0.195257,0.000000,0.0,0.014388,0.077220,0.894349,0.858397,0.000000
230,Diego Gómez,Paraguay,MID,0.194831,0.322034,1.0,0.033898,0.192308,1.000000,0.496654,0.000000
112,Omar Marmoush,Egypt,FWD,0.190559,0.000000,0.0,0.012658,0.066372,0.894349,0.878011,0.000000

In [723]:
raw_pw = (
    0.10 * df["stat_PW"]                    
  + 0.3 * df["anytime_scorer_prob"]      
  + 0.10 * df["chance_created_per90"]     
  + 0.2 * df["stat_CC"]                  # recent form in 
  + 0.2 * df["team_score_2_prob"]        # team expected to attack heavily
  + 0.10 * df["price"] # quality proxy
)

df["prob_pen_won"] = 0.2 * sigmoid((raw_pw - 0.65) * 5) * df["prob_plays_60min"]

In [724]:
cols = [
    "name",
    "team",
    "position",
    "prob_pen_won",
    "stat_PW",
    "anytime_scorer_prob",
    "assist_expectation",
    "chance_created_per90",
    "team_score_2_prob",
    "price_rank_team_position",
    "prob_plays_60min",
]

df[cols].sort_values("prob_pen_won", ascending=False).head(30)

,name,team,position,prob_pen_won,stat_PW,anytime_scorer_prob,assist_expectation,chance_created_per90,team_score_2_prob,price_rank_team_position,prob_plays_60min
5,Lionel Messi,Argentina,FWD,0.074291,0.0,0.6173,0.910125,0.125000,0.6452,1.000000,0.899661
161,Michael Olise,France,MID,0.066213,0.0,0.3571,1.249481,0.162338,0.7634,0.909091,0.845736
148,Kylian Mbappé,France,FWD,0.055986,0.0,0.6536,0.219282,0.028490,0.7634,1.000000,0.897936
318,Lautaro Martínez,Argentina,FWD,0.042710,1.0,0.4587,0.299630,0.041152,0.6452,0.750000,0.697257
149,Ousmane Dembélé,France,MID,0.040338,0.0,0.4762,0.267250,0.034722,0.7634,1.000000,0.801957
48,Vinícius Júnior,Brazil,MID,0.038558,0.0,0.4717,0.200769,0.028490,0.5714,1.000000,0.894919
185,Ismael Saibari,Morocco,MID,0.034491,0.0,0.4049,0.375174,0.055096,0.5181,1.000000,0.915987
261,Mikel Oyarzabal,Spain,FWD,0.033136,0.0,0.4950,0.228857,0.033223,0.5464,1.000000,0.848337
39,Youri Tielemans,Belgium,MID,0.032822,1.0,0.2151,0.170977,0.025974,0.4878,0.727273,0.930263
285,Breel Embolo,Switzerland,FWD,0.032288,0.0,0.3175,0.478686,0.086455,0.3390,1.000000,0.889168
140,Jude Bellingham,England,MID,0.031986,0.0,0.2564,0.582994,0.095541,0.4049,0.900000,0.855402
132,Noni Madueke,England,FWD,0.031535,1.0,0.2151,0.753333,0.123457,0.4049,0.250000,0.668247
198,Erling Haaland,Norway,FWD,0.030767,0.0,0.4717,0.216333,0.037037,0.3774,1.000000,0.807380
321,Bruno Guimarães,Brazil,MID,0.030187,0.0,0.1538,0.621794,0.088235,0.5714,0.700000,0.875022
171,Roberto Alvarado,Mexico,FWD,0.028586,0.0,0.2000,0.660071,0.117647,0.3425,0.500000,0.865252
331,Bradley Barcola,France,MID,0.028428,0.0,0.3846,0.370038,0.048077,0.7634,0.772727,0.698293
344,Leandro Trossard,Belgium,MID,0.027933,0.0,0.2740,0.364687,0.055402,0.4878,0.818182,0.905769
127,Harry Kane,England,FWD,0.027384,0.0,0.4167,0.000000,0.000000,0.4049,1.000000,0.901582
86,Luis Díaz,Colombia,MID,0.026563,0.0,0.3390,0.178341,0.027933,0.4444,1.000000,0.900602
402,Brahim Díaz,Morocco,MID,0.026030,0.0,0.2985,0.457007,0.067114,0.5181,0.888889,0.803428
53,Rayan,Brazil,FWD,0.025965,0.0,0.3226,0.634865,0.090090,0.5714,0.400000,0.772645
257,Marc Cucurella,Spain,DEF,0.025800,0.0,0.1081,0.574050,0.083333,0.5464,0.625000,0.898167
394,Achraf Hakimi,Morocco,DEF,0.025525,0.0,0.1852,0.349200,0.051282,0.5181,1.000000,0.939204
259,Lamine Yamal,Spain,MID,0.025239,0.0,0.3968,0.000000,0.000000,0.5464,1.000000,0.779433
250,Bruno Fernandes,Portugal,MID,0.024824,0.0,0.2151,0.349838,0.060060,0.3676,1.000000,0.854701
19,Alexis Mac Allister,Argentina,MID,0.024458,0.0,0.2151,0.221307,0.030395,0.6452,0.909091,0.896554
350,Cristiano Ronaldo,Portugal,FWD,0.024406,0.0,0.3846,0.000000,0.000000,0.3676,1.000000,0.891340
330,Jules Koundé,France,DEF,0.024108,0.0,0.0833,0.459510,0.059701,0.7634,1.000000,0.846911
232,Nuno Mendes,Portugal,DEF,0.023630,0.0,0.1333,0.512446,0.087977,0.3676,1.000000,0.887945
49,Matheus Cunha,Brazil,FWD,0.022827,0.0,0.4167,0.000000,0.000000,0.5714,1.000000,0.792376

In [725]:
raw_cs = (
    0.90 * df["team_cs_prob"]            # strongest signal
  + 0.05 * df["stat_CS"]               # tournament history
  + 0.05 * (1 - df["stat_GC"])         # fewer goals conceded is better
)

base_cs = sigmoid((raw_cs - 0.5) * 6)

df["prob_clean_sheet"] = base_cs * df["prob_plays_60min"]

df.loc[df["position"] == "FWD", "prob_clean_sheet"] = 0.0

In [726]:
cols = [
    "name",
    "team",
    "position",
    "prob_clean_sheet",
    "team_cs_prob",
    "prob_plays_60min",
    "stat_CS",
    "stat_GC",
    "minutes_rank_team_position",
    "tackles_per90",
]

df[cols].sort_values("prob_clean_sheet", ascending=False).head(30)

,name,team,position,prob_clean_sheet,team_cs_prob,prob_plays_60min,stat_CS,stat_GC,minutes_rank_team_position,tackles_per90
143,Dayot Upamecano,France,DEF,0.552690,0.5811,0.887167,0.50,0.285714,1.000000,0.020231
152,Mike Maignan,France,GK,0.548444,0.5811,0.880352,0.50,0.285714,1.000000,0.000000
10,Emiliano Martínez,Argentina,GK,0.536918,0.5479,0.942676,0.50,0.428571,1.000000,0.000000
19,Alexis Mac Allister,Argentina,MID,0.536313,0.5479,0.896554,0.75,0.285714,1.000000,0.036474
330,Jules Koundé,France,DEF,0.527611,0.5811,0.846911,0.50,0.285714,0.888889,0.032836
161,Michael Olise,France,MID,0.526879,0.5811,0.845736,0.50,0.285714,1.000000,0.012987
149,Ousmane Dembélé,France,MID,0.521462,0.5811,0.801957,0.75,0.142857,0.909091,0.010417
314,Lisandro Martínez,Argentina,DEF,0.501811,0.5479,0.865129,0.50,0.285714,1.000000,0.010000
20,Enzo Fernández,Argentina,MID,0.496180,0.5479,0.855420,0.50,0.285714,0.909091,0.020000
329,William Saliba,France,DEF,0.485502,0.5811,0.766993,0.50,0.142857,0.777778,0.007407
155,Adrien Rabiot,France,MID,0.459098,0.5811,0.725280,0.50,0.142857,0.772727,0.007407
331,Bradley Barcola,France,MID,0.454056,0.5811,0.698293,0.75,0.142857,0.545455,0.014423
0,Cristian Romero,Argentina,DEF,0.452075,0.5479,0.779383,0.50,0.285714,0.750000,0.019455
315,Facundo Medina,Argentina,DEF,0.447518,0.5479,0.757934,0.50,0.142857,0.875000,0.031008
2,Nahuel Molina,Argentina,DEF,0.431432,0.5479,0.743795,0.50,0.285714,0.625000,0.025105
14,Rodrigo De Paul,Argentina,MID,0.430066,0.5479,0.728377,0.50,0.142857,0.818182,0.019531
159,Aurélien Tchouaméni,France,MID,0.408506,0.5811,0.674982,0.25,0.285714,0.772727,0.051852
146,Lucas Digne,France,DEF,0.390334,0.5811,0.607153,0.50,0.000000,0.555556,0.005952
18,Thiago Almada,Argentina,MID,0.380072,0.5479,0.624656,0.75,0.142857,0.727273,0.023474
394,Achraf Hakimi,Morocco,DEF,0.374014,0.4414,0.939204,0.25,0.571429,1.000000,0.017949
401,Neil El Aynaoui,Morocco,MID,0.369601,0.4414,0.928121,0.25,0.571429,1.000000,0.039164
393,Yassine Bounou,Morocco,GK,0.368016,0.4414,0.924142,0.25,0.571429,1.000000,0.000000
185,Ismael Saibari,Morocco,MID,0.364768,0.4414,0.915987,0.25,0.571429,0.888889,0.008264
396,Noussair Mazraoui,Morocco,DEF,0.361555,0.4414,0.826803,0.50,0.285714,0.625000,0.030303
86,Luis Díaz,Colombia,MID,0.352816,0.3848,0.900602,0.75,0.142857,1.000000,0.002793
82,Dávinson Sánchez,Colombia,DEF,0.350360,0.3848,0.894331,0.75,0.142857,0.937500,0.011111
81,Jhon Lucumí,Colombia,DEF,0.347204,0.3848,0.886278,0.75,0.142857,0.937500,0.002778
90,Camilo Vargas,Colombia,GK,0.344883,0.3848,0.880352,0.75,0.142857,1.000000,0.000000
94,Gustavo Puerta,Colombia,MID,0.343731,0.3848,0.877412,0.75,0.142857,0.909091,0.005714
398,Issa Diop,Morocco,DEF,0.343120,0.4414,0.819033,0.25,0.285714,0.750000,0.000000

In [727]:
position_rc_modifier = {
    "GK": 0.04,
    "FWD": 0.08,
    "DEF": 0.12,
    "MID": 0.14,
}

df["position_rc_modifier"] = df["position"].map(position_rc_modifier)

raw_rc = (
    0.10 * df["position_rc_modifier"]   # strongest prior
  + 0.25 * df["rc_per90"]              # direct history
  + 0.15 * df["tackles_per90"]         # physical involvement
  + 0.25 * df["prob_yellow_card"]      # disciplinary tendency
  + 0.25 * df["opp_over_05_prob"]      # more defending -> more challenges
)

df["prob_red_card"] = 0.1 * sigmoid((raw_rc - 0.5) * 5) * df["prob_plays_60min"]

In [728]:
cols = [
    "name",
    "team",
    "position",
    "prob_red_card",
    "position_rc_modifier",
    "rc_per90",
    "tackles_per90",
    "prob_yellow_card",
    "opp_over_05_prob",
    "prob_plays_any",
]

df[cols].sort_values("prob_red_card", ascending=False).head(30)

,name,team,position,prob_red_card,position_rc_modifier,rc_per90,tackles_per90,prob_yellow_card,opp_over_05_prob,prob_plays_any
218,Miguel Almirón,Paraguay,MID,0.031198,0.14,0.728972,0.032710,0.226822,1.000000,0.657963
209,Matías Galarza,Paraguay,MID,0.029664,0.14,0.000000,0.046980,0.335370,1.000000,0.863946
360,Andrés Cubas,Paraguay,MID,0.028721,0.14,0.000000,0.035897,0.281007,1.000000,0.858149
211,Gustavo Gómez,Paraguay,DEF,0.027320,0.12,0.000000,0.010256,0.232589,1.000000,0.931775
216,Juan José Cáceres,Paraguay,DEF,0.026700,0.12,0.000000,0.051576,0.263572,1.000000,0.805304
111,Yasser Ibrahim,Egypt,DEF,0.025746,0.12,0.000000,0.018617,0.285791,0.894349,0.867291
227,Orlando Gill,Paraguay,GK,0.025189,0.04,0.000000,0.000000,0.198690,1.000000,0.845535
107,Mohamed Hany,Egypt,DEF,0.024783,0.12,0.000000,0.035897,0.218130,0.894349,0.902362
100,Marwan Attia,Egypt,MID,0.024482,0.14,0.000000,0.017442,0.253704,0.894349,0.837974
212,Júnior Alonso,Paraguay,DEF,0.023898,0.12,0.000000,0.026667,0.243877,1.000000,0.755859
229,Julio Enciso,Paraguay,MID,0.023657,0.14,0.000000,0.012270,0.212075,1.000000,0.870817
359,Mohamed Salah,Egypt,MID,0.023556,0.14,0.000000,0.002959,0.212320,0.894349,0.900698
103,Emam Ashour,Egypt,MID,0.022834,0.14,0.000000,0.009346,0.207418,0.894349,0.835737
117,Mostafa Shobeir,Egypt,GK,0.022376,0.04,0.000000,0.000000,0.178820,0.894349,0.843895
112,Omar Marmoush,Egypt,FWD,0.022020,0.08,0.000000,0.012658,0.190559,0.894349,0.898316
108,Ramy Rabia,Egypt,DEF,0.021969,0.12,0.000000,0.014388,0.195257,0.894349,0.785657
164,César Montes,Mexico,DEF,0.021489,0.12,0.577778,0.007407,0.134832,0.588517,0.687914
236,Renato Veiga,Portugal,DEF,0.020814,0.12,0.000000,0.008333,0.218096,0.784669,0.835668
379,Alistair Johnston,Canada,DEF,0.020769,0.12,0.000000,0.002778,0.217621,0.770053,0.894740
232,Nuno Mendes,Portugal,DEF,0.020240,0.12,0.000000,0.014663,0.182561,0.784669,0.902548
347,Rúben Dias,Portugal,DEF,0.020133,0.12,0.000000,0.018519,0.222874,0.784669,0.834676
28,Brandon Mechele,Belgium,DEF,0.020102,0.12,0.000000,0.007692,0.211225,0.700513,0.882881
357,Mostafa Zico,Egypt,MID,0.019847,0.14,0.000000,0.016949,0.184803,0.894349,0.746086
61,Richie Laryea,Canada,DEF,0.019813,0.12,0.000000,0.025496,0.180316,0.770053,0.851868
250,Bruno Fernandes,Portugal,MID,0.019810,0.14,0.000000,0.024024,0.186273,0.784669,0.902235
350,Cristiano Ronaldo,Portugal,FWD,0.019705,0.08,0.000000,0.005698,0.172348,0.784669,0.915676
39,Youri Tielemans,Belgium,MID,0.019663,0.14,0.000000,0.010390,0.183913,0.700513,0.901551
65,Jonathan David,Canada,FWD,0.019512,0.08,0.000000,0.003021,0.170473,0.770053,0.915617
189,Patrick Berg,Norway,MID,0.019405,0.14,0.000000,0.017094,0.225200,0.830040,0.733802
298,Weston McKennie,USA,MID,0.019161,0.14,0.000000,0.022599,0.181178,0.713969,0.894506

In [729]:
position_og_modifier = {
    "GK": 0.05,
    "FWD": 0.02,
    "MID": 0.04,
    "DEF": 0.08,
}

df["position_og_modifier"] = df["position"].map(position_og_modifier)

raw_og = (
    0.4 * df["position_og_modifier"]
  + 0.5 * df["opp_over_05_prob"]
  + 0.10 * (1 - df["stat_GC"])
)

df["prob_own_goal"] = 0.03 * sigmoid((raw_og - 0.5) * 5) * df["prob_plays_60min"]

In [730]:
cols = [
    "name",
    "team",
    "position",
    "prob_own_goal",
    "position_og_modifier",
    "own_goal_rate",
    "opp_over_05_prob",
    "tackles_per90",
    "stat_GC",
    "prob_plays_any",
]

df[cols].sort_values("prob_own_goal", ascending=False).head(30)

,name,team,position,prob_own_goal,position_og_modifier,own_goal_rate,opp_over_05_prob,tackles_per90,stat_GC,prob_plays_any
209,Matías Galarza,Paraguay,MID,0.017038,0.04,0.000000,1.000000,0.046980,0.142857,0.863946
211,Gustavo Gómez,Paraguay,DEF,0.016210,0.08,0.000000,1.000000,0.010256,0.714286,0.931775
216,Juan José Cáceres,Paraguay,DEF,0.015542,0.08,0.000000,1.000000,0.051576,0.571429,0.805304
227,Orlando Gill,Paraguay,GK,0.015537,0.05,0.000000,1.000000,0.000000,0.714286,0.845535
360,Andrés Cubas,Paraguay,MID,0.015458,0.04,0.000000,1.000000,0.035897,0.714286,0.858149
111,Yasser Ibrahim,Egypt,DEF,0.015111,0.08,0.000000,0.894349,0.018617,0.428571,0.867291
107,Mohamed Hany,Egypt,DEF,0.014825,0.08,0.005128,0.894349,0.035897,0.571429,0.902362
108,Ramy Rabia,Egypt,DEF,0.014496,0.08,0.000000,0.894349,0.014388,0.285714,0.785657
117,Mostafa Shobeir,Egypt,GK,0.014182,0.05,0.000000,0.894349,0.000000,0.571429,0.843895
100,Marwan Attia,Egypt,MID,0.014159,0.04,0.000000,0.894349,0.017442,0.428571,0.837974
212,Júnior Alonso,Paraguay,DEF,0.013918,0.08,0.000000,1.000000,0.026667,0.714286,0.755859
359,Mohamed Salah,Egypt,MID,0.013780,0.04,0.000000,0.894349,0.002959,0.571429,0.900698
229,Julio Enciso,Paraguay,MID,0.013695,0.04,0.000000,1.000000,0.012270,0.714286,0.870817
112,Omar Marmoush,Egypt,FWD,0.013576,0.02,0.000000,0.894349,0.012658,0.428571,0.898316
103,Emam Ashour,Egypt,MID,0.013370,0.04,0.000000,0.894349,0.009346,0.571429,0.835737
232,Nuno Mendes,Portugal,DEF,0.013178,0.08,0.000000,0.784669,0.014663,0.285714,0.902548
236,Renato Veiga,Portugal,DEF,0.013145,0.08,0.000000,0.784669,0.008333,0.285714,0.835668
347,Rúben Dias,Portugal,DEF,0.013038,0.08,0.000000,0.784669,0.018519,0.142857,0.834676
346,Diogo Costa,Portugal,GK,0.012670,0.05,0.000000,0.784669,0.000000,0.285714,0.870326
379,Alistair Johnston,Canada,DEF,0.012623,0.08,0.000000,0.770053,0.002778,0.428571,0.894740
350,Cristiano Ronaldo,Portugal,FWD,0.012428,0.02,0.000000,0.784669,0.005698,0.285714,0.915676
61,Richie Laryea,Canada,DEF,0.012320,0.08,0.000000,0.770053,0.025496,0.428571,0.851868
250,Bruno Fernandes,Portugal,MID,0.012172,0.04,0.000000,0.784669,0.024024,0.285714,0.902235
382,Stephen Eustaquio,Canada,MID,0.012167,0.04,0.000000,0.770053,0.023256,0.142857,0.829640
70,Maxime Crépeau,Canada,GK,0.011960,0.05,0.000000,0.770053,0.002778,0.428571,0.870326
357,Mostafa Zico,Egypt,MID,0.011818,0.04,0.000000,0.894349,0.016949,0.571429,0.746086
65,Jonathan David,Canada,FWD,0.011805,0.02,0.000000,0.770053,0.003021,0.428571,0.915617
249,João Neves,Portugal,MID,0.011687,0.04,0.000000,0.784669,0.029900,0.285714,0.829357
190,Kristoffer Ajer,Norway,DEF,0.011443,0.08,0.000000,0.830040,0.025926,0.571429,0.831372
28,Brandon Mechele,Belgium,DEF,0.011425,0.08,0.000000,0.700513,0.007692,0.571429,0.882881

In [731]:
position_pc_modifier = {
    "GK": 0.08,
    "FWD": 0.01,
    "MID": 0.05,
    "DEF": 0.14,
}

df["position_pc_modifier"] = df["position"].map(position_pc_modifier)

raw_pc = (
    0.20 * df["position_pc_modifier"]
  + 0.15 * df["penalty_conceded_rate"]
  + 0.15 * df["tackles_per90"]
  + 0.35 * df["prob_yellow_card"]
  + 0.15 * df["opp_over_05_prob"]
)

df["prob_penalty_committed"] = 0.08 * sigmoid((raw_pc - 0.5) * 5) * df["prob_plays_60min"]

In [732]:
cols = [
    "name",
    "team",
    "position",
    "prob_penalty_committed",
    "position_pc_modifier",
    "penalty_conceded_rate",
    "tackles_per90",
    "prob_yellow_card",
    "opp_over_05_prob",
    "prob_plays_any",
]

df[cols].sort_values("prob_penalty_committed", ascending=False).head(30)

,name,team,position,prob_penalty_committed,position_pc_modifier,penalty_conceded_rate,tackles_per90,prob_yellow_card,opp_over_05_prob,prob_plays_any
209,Matías Galarza,Paraguay,MID,0.018474,0.05,0.0,0.046980,0.335370,1.000000,0.863946
211,Gustavo Gómez,Paraguay,DEF,0.017461,0.14,0.0,0.010256,0.232589,1.000000,0.931775
111,Yasser Ibrahim,Egypt,DEF,0.017435,0.14,0.0,0.018617,0.285791,0.894349,0.867291
360,Andrés Cubas,Paraguay,MID,0.017425,0.05,0.0,0.035897,0.281007,1.000000,0.858149
216,Juan José Cáceres,Paraguay,DEF,0.017337,0.14,0.0,0.051576,0.263572,1.000000,0.805304
107,Mohamed Hany,Egypt,DEF,0.016297,0.14,0.0,0.035897,0.218130,0.894349,0.902362
227,Orlando Gill,Paraguay,GK,0.015558,0.08,0.0,0.000000,0.198690,1.000000,0.845535
212,Júnior Alonso,Paraguay,DEF,0.015364,0.14,0.0,0.026667,0.243877,1.000000,0.755859
100,Marwan Attia,Egypt,MID,0.015125,0.05,0.0,0.017442,0.253704,0.894349,0.837974
108,Ramy Rabia,Egypt,DEF,0.014287,0.14,0.0,0.014388,0.195257,0.894349,0.785657
359,Mohamed Salah,Egypt,MID,0.014259,0.05,0.0,0.002959,0.212320,0.894349,0.900698
379,Alistair Johnston,Canada,DEF,0.014241,0.14,0.0,0.002778,0.217621,0.770053,0.894740
236,Renato Veiga,Portugal,DEF,0.014202,0.14,0.0,0.008333,0.218096,0.784669,0.835668
117,Mostafa Shobeir,Egypt,GK,0.014176,0.08,0.0,0.000000,0.178820,0.894349,0.843895
28,Brandon Mechele,Belgium,DEF,0.014101,0.14,0.0,0.007692,0.211225,0.700513,0.882881
229,Julio Enciso,Paraguay,MID,0.013863,0.05,0.0,0.012270,0.212075,1.000000,0.870817
103,Emam Ashour,Egypt,MID,0.013794,0.05,0.0,0.009346,0.207418,0.894349,0.835737
347,Rúben Dias,Portugal,DEF,0.013770,0.14,0.0,0.018519,0.222874,0.784669,0.834676
232,Nuno Mendes,Portugal,DEF,0.013595,0.14,0.0,0.014663,0.182561,0.784669,0.902548
61,Richie Laryea,Canada,DEF,0.013369,0.14,0.0,0.025496,0.180316,0.770053,0.851868
22,Timothy Castagne,Belgium,DEF,0.013329,0.14,0.0,0.033557,0.212317,0.700513,0.842701
112,Omar Marmoush,Egypt,FWD,0.013064,0.01,0.0,0.012658,0.190559,0.894349,0.898316
279,Nico Elvedi,Switzerland,DEF,0.012900,0.14,0.0,0.008333,0.197739,0.661417,0.887089
21,Maxim De Cuyper,Belgium,DEF,0.012618,0.14,0.0,0.010274,0.202640,0.700513,0.866755
62,Derek Cornelius,Canada,DEF,0.012591,0.14,0.0,0.015873,0.202501,0.770053,0.785560
39,Youri Tielemans,Belgium,MID,0.012554,0.05,0.0,0.010390,0.183913,0.700513,0.901551
277,Manuel Akanji,Switzerland,DEF,0.012446,0.14,0.0,0.019444,0.163596,0.661417,0.911742
250,Bruno Fernandes,Portugal,MID,0.012296,0.05,0.0,0.024024,0.186273,0.784669,0.902235
272,Granit Xhaka,Switzerland,MID,0.012271,0.05,0.0,0.013889,0.208883,0.661417,0.898151
190,Kristoffer Ajer,Norway,DEF,0.012188,0.14,0.0,0.025926,0.170227,0.830040,0.831372

In [733]:
df["lambda_opp"] = -np.log(df["team_cs_prob"].clip(lower=0.01))

df["prob_gc_0"] = np.exp(-df["lambda_opp"])
df["prob_gc_1"] = df["lambda_opp"] * np.exp(-df["lambda_opp"])
df["prob_gc_2"] = (df["lambda_opp"] ** 2 / 2) * np.exp(-df["lambda_opp"])
df["prob_gc_3"] = (df["lambda_opp"] ** 3 / 6) * np.exp(-df["lambda_opp"])
df["prob_gc_4plus"] = 1 - (
    df["prob_gc_0"]
    + df["prob_gc_1"]
    + df["prob_gc_2"]
    + df["prob_gc_3"]
)

# RAW expected goals conceded (true intensity)
df["expected_goals_conceded"] = df["lambda_opp"]

# Normalize ONLY as auxiliary feature (separate column)
scaler = MinMaxScaler()
df["expected_goals_conceded_norm"] = scaler.fit_transform(
    df[["expected_goals_conceded"]]
)

# Player exposure to goals conceded (correct)
df["expected_player_goals_conceded"] = (
    df["lambda_opp"] * df["prob_plays_60min"]
)

# GC penalty MUST use raw λ (correct Poisson expectation)
df["expected_gc_penalty"] = (
    -(df["lambda_opp"] - 1 + np.exp(-df["lambda_opp"]))
    * df["prob_plays_60min"]
)

df.loc[df["position"].isin(["MID", "FWD"]), [
    "expected_player_goals_conceded",
    "expected_gc_penalty"
]] = 0.0

In [734]:
cols = [
    "name",
    "team",
    "position",
    "prob_plays_60min",
    "team_cs_prob",
    "lambda_opp",
    "prob_gc_0",
    "prob_gc_1",
    "prob_gc_2",
    "prob_gc_3",
    "prob_gc_4plus",
    "expected_player_goals_conceded",
    "expected_gc_penalty",
]

df[df["position"].isin(["GK", "DEF"])][cols] \
    .sort_values("expected_gc_penalty") \
    .head(30)

,name,team,position,prob_plays_60min,team_cs_prob,lambda_opp,prob_gc_0,prob_gc_1,prob_gc_2,prob_gc_3,prob_gc_4plus,expected_player_goals_conceded,expected_gc_penalty
211,Gustavo Gómez,Paraguay,DEF,0.939509,0.1448,1.932402,0.1448,0.279812,0.270354,0.174144,0.130889,1.815508,-1.012040
227,Orlando Gill,Paraguay,GK,0.924142,0.1448,1.932402,0.1448,0.279812,0.270354,0.174144,0.130889,1.785813,-0.995487
216,Juan José Cáceres,Paraguay,DEF,0.874355,0.1448,1.932402,0.1448,0.279812,0.270354,0.174144,0.130889,1.689605,-0.941857
212,Júnior Alonso,Paraguay,DEF,0.806649,0.1448,1.932402,0.1448,0.279812,0.270354,0.174144,0.130889,1.558769,-0.868923
107,Mohamed Hany,Egypt,DEF,0.936805,0.1910,1.655482,0.1910,0.316197,0.261729,0.144429,0.086644,1.550864,-0.792988
111,Yasser Ibrahim,Egypt,DEF,0.923769,0.1910,1.655482,0.1910,0.316197,0.261729,0.144429,0.086644,1.529283,-0.781954
117,Mostafa Shobeir,Egypt,GK,0.922371,0.1910,1.655482,0.1910,0.316197,0.261729,0.144429,0.086644,1.526968,-0.780770
108,Ramy Rabia,Egypt,DEF,0.858397,0.1910,1.655482,0.1910,0.316197,0.261729,0.144429,0.086644,1.421060,-0.726617
232,Nuno Mendes,Portugal,DEF,0.887945,0.2346,1.449873,0.2346,0.340140,0.246580,0.119170,0.059510,1.287408,-0.607775
236,Renato Veiga,Portugal,DEF,0.885709,0.2346,1.449873,0.2346,0.340140,0.246580,0.119170,0.059510,1.284166,-0.606244
346,Diogo Costa,Portugal,GK,0.880352,0.2346,1.449873,0.2346,0.340140,0.246580,0.119170,0.059510,1.276399,-0.602578
379,Alistair Johnston,Canada,DEF,0.899531,0.2434,1.413049,0.2434,0.343936,0.242999,0.114457,0.055208,1.271081,-0.590496
190,Kristoffer Ajer,Norway,DEF,0.782690,0.2170,1.527858,0.2170,0.331545,0.253277,0.128990,0.069187,1.195839,-0.582993
347,Rúben Dias,Portugal,DEF,0.847881,0.2346,1.449873,0.2346,0.340140,0.246580,0.119170,0.059510,1.229320,-0.580352
70,Maxime Crépeau,Canada,GK,0.880352,0.2434,1.413049,0.2434,0.343936,0.242999,0.114457,0.055208,1.243981,-0.577906
61,Richie Laryea,Canada,DEF,0.877945,0.2434,1.413049,0.2434,0.343936,0.242999,0.114457,0.055208,1.240580,-0.576326
202,Ørjan Nyland,Norway,GK,0.760983,0.2170,1.527858,0.2170,0.331545,0.253277,0.128990,0.069187,1.162674,-0.566824
194,David Møller Wolfe,Norway,DEF,0.753155,0.2170,1.527858,0.2170,0.331545,0.253277,0.128990,0.069187,1.150715,-0.560994
217,José Canale,Paraguay,DEF,0.517476,0.1448,1.932402,0.1448,0.279812,0.270354,0.174144,0.130889,0.999972,-0.557427
196,Torbjørn Heggem,Norway,DEF,0.726889,0.2170,1.527858,0.2170,0.331545,0.253277,0.128990,0.069187,1.110584,-0.541429
28,Brandon Mechele,Belgium,DEF,0.934625,0.2731,1.297917,0.2731,0.354461,0.230031,0.099520,0.042888,1.213065,-0.533687
62,Derek Cornelius,Canada,DEF,0.806031,0.2434,1.413049,0.2434,0.343936,0.242999,0.114457,0.055208,1.138961,-0.529118
340,Thibaut Courtois,Belgium,GK,0.924142,0.2731,1.297917,0.2731,0.354461,0.230031,0.099520,0.042888,1.199460,-0.527701
213,Omar Alderete,Paraguay,DEF,0.478428,0.1448,1.932402,0.1448,0.279812,0.270354,0.174144,0.130889,0.924516,-0.515364
192,Marcus Pedersen,Norway,DEF,0.691522,0.2170,1.527858,0.2170,0.331545,0.253277,0.128990,0.069187,1.056547,-0.515086
22,Timothy Castagne,Belgium,DEF,0.868378,0.2731,1.297917,0.2731,0.354461,0.230031,0.099520,0.042888,1.127083,-0.495859
21,Maxim De Cuyper,Belgium,DEF,0.845297,0.2731,1.297917,0.2731,0.354461,0.230031,0.099520,0.042888,1.097125,-0.482679
306,Alexander Freeman,USA,DEF,0.813929,0.2686,1.314532,0.2686,0.353083,0.232070,0.101688,0.044559,1.069935,-0.474628
277,Manuel Akanji,Switzerland,DEF,0.898167,0.2906,1.235808,0.2906,0.359126,0.221905,0.091411,0.036959,1.109961,-0.472802
279,Nico Elvedi,Switzerland,DEF,0.892366,0.2906,1.235808,0.2906,0.359126,0.221905,0.091411,0.036959,1.102793,-0.469748

In [735]:
raw_save = (
    0.35 * df["expected_goals_conceded_norm"]  # opportunity
  + 0.40 * df["saves_per90"]             # ability
  + 0.05 * df["recent_saves_per90"]      # recent form
  + 0.20 * df["price"]                   # overall GK quality
)

# Expected saves (λ)
df["expected_saves"] = (
    sigmoid((raw_save - 0.5) * 6) * 4
) * df["prob_plays_60min"]

df.loc[df["position"] != "GK", "expected_saves"] = 0.0

In [736]:
cols = [
    "name",
    "team",
    "expected_saves",
    "expected_goals_conceded",
    "saves_per90",
    "recent_saves_per90",
    "price",
    "expected_goals_conceded_norm",
]

df[df["position"] == "GK"][cols] \
    .sort_values("expected_saves", ascending=False) \
    .head(30)

,name,team,expected_saves,expected_goals_conceded,saves_per90,recent_saves_per90,price,expected_goals_conceded_norm
227,Orlando Gill,Paraguay,3.018138,1.932402,0.876923,0.960000,0.000000,1.000000
346,Diogo Costa,Portugal,2.233683,1.449873,0.700000,0.866667,0.200000,0.652750
288,Gregor Kobel,Switzerland,1.772131,1.235808,0.650000,0.666667,0.171429,0.498698
117,Mostafa Shobeir,Egypt,1.766566,1.655482,0.461538,0.420000,0.000000,0.800715
340,Thibaut Courtois,Belgium,1.399126,1.297917,0.415385,0.420000,0.200000,0.543395
56,Alisson Becker,Brazil,1.345255,1.046969,0.550000,0.600000,0.214286,0.362801
202,Ørjan Nyland,Norway,1.331678,1.527858,0.400000,0.600000,0.100000,0.708871
70,Maxime Crépeau,Canada,0.989761,1.413049,0.250000,0.200000,0.071429,0.626249
311,Matt Freese,USA,0.967453,1.314532,0.333333,0.500000,0.100000,0.555352
176,Raúl Rangel,Mexico,0.797179,1.133204,0.310345,0.279070,0.057143,0.424859
203,Egil Selvik,Norway,0.785097,1.527858,1.000000,1.000000,0.042857,0.708871
133,Jordan Pickford,England,0.729773,0.976572,0.300000,0.200000,0.185714,0.312139
265,Unai Simón,Spain,0.669775,1.041854,0.200000,0.200000,0.214286,0.359120
393,Yassine Bounou,Morocco,0.581636,0.817804,0.276923,0.120000,0.171429,0.197882
152,Mike Maignan,France,0.561238,0.542832,0.400000,0.400000,0.214286,0.000000
90,Camilo Vargas,Colombia,0.543973,0.955032,0.200000,0.200000,0.114286,0.296638
10,Emiliano Martínez,Argentina,0.397340,0.601662,0.184615,0.240000,0.214286,0.042337
225,Roberto Fernández,Paraguay,0.151607,1.932402,0.000000,0.000000,0.071429,1.000000
310,Matt Turner,USA,0.150114,1.314532,0.000000,0.000000,0.071429,0.555352
226,Gastón Olveira,Paraguay,0.134337,1.932402,0.000000,0.000000,0.042857,1.000000
118,Mohamed Alaa,Egypt,0.126061,1.655482,0.000000,0.000000,0.000000,0.800715
115,Mohamed El Shenawy,Egypt,0.105888,1.655482,0.000000,0.000000,0.014286,0.800715
244,Rui Silva,Portugal,0.095866,1.449873,0.000000,0.000000,0.171429,0.652750
116,El Mahdy Soliman,Egypt,0.091504,1.655482,0.000000,0.000000,0.014286,0.800715
245,José Sá,Portugal,0.086999,1.449873,0.000000,0.000000,0.171429,0.652750
36,Senne Lammens,Belgium,0.078221,1.297917,0.000000,0.000000,0.157143,0.543395
366,Sander Tangvik,Norway,0.078171,1.527858,0.000000,0.000000,0.000000,0.708871
55,Ederson,Brazil,0.077462,1.046969,0.000000,0.000000,0.214286,0.362801
72,Owen Goodman,Canada,0.077266,1.413049,0.000000,0.000000,0.000000,0.626249
174,Guillermo Ochoa,Mexico,0.074553,1.133204,0.000000,0.000000,0.100000,0.424859

In [737]:
raw_pen_save = (
    0.55 * df["price"]                    
  + 0.30 * df["expected_goals_conceded_norm"]
  + 0.15 * df["stat_PS"]
)

# Strong compression because penalty saves are exceptionally rare
df["prob_penalty_save"] = sigmoid((raw_pen_save - 0.5) * 3) / 20 * df["prob_plays_60min"]

df.loc[df["position"] != "GK", "prob_penalty_save"] = 0.0

In [738]:
cols = [
    "name",
    "team",
    "prob_penalty_save",
    "price",
    "expected_goals_conceded",
    "opp_over_05_prob",
    "prob_plays_60min",
    "stat_PS",
]

df[df["position"] == "GK"][cols] \
    .sort_values("prob_penalty_save", ascending=False) \
    .head(30)

,name,team,prob_penalty_save,price,expected_goals_conceded,opp_over_05_prob,prob_plays_60min,stat_PS
117,Mostafa Shobeir,Egypt,0.019296,0.000000,1.655482,0.894349,0.922371,1.0
227,Orlando Gill,Paraguay,0.016373,0.000000,1.932402,1.000000,0.924142,0.0
346,Diogo Costa,Portugal,0.015774,0.200000,1.449873,0.784669,0.880352,0.0
340,Thibaut Courtois,Belgium,0.015528,0.200000,1.297917,0.700513,0.924142,0.0
152,Mike Maignan,France,0.014640,0.214286,0.542832,0.000000,0.880352,1.0
288,Gregor Kobel,Switzerland,0.013947,0.171429,1.235808,0.661417,0.880352,0.0
70,Maxime Crépeau,Canada,0.013473,0.071429,1.413049,0.770053,0.880352,0.0
56,Alisson Becker,Brazil,0.013460,0.214286,1.046969,0.521910,0.880352,0.0
265,Unai Simón,Spain,0.013429,0.214286,1.041854,0.521910,0.880352,0.0
202,Ørjan Nyland,Norway,0.012650,0.100000,1.527858,0.830040,0.760983,0.0
133,Jordan Pickford,England,0.012609,0.185714,0.976572,0.460815,0.880352,0.0
393,Yassine Bounou,Morocco,0.012075,0.171429,0.817804,0.312290,0.924142,0.0
10,Emiliano Martínez,Argentina,0.011698,0.214286,0.601662,0.071591,0.942676,0.0
311,Matt Freese,USA,0.011512,0.100000,1.314532,0.713969,0.760983,0.0
176,Raúl Rangel,Mexico,0.011475,0.057143,1.133204,0.588517,0.868079,0.0
90,Camilo Vargas,Colombia,0.011457,0.114286,0.955032,0.441558,0.880352,0.0
203,Egil Selvik,Norway,0.003946,0.042857,1.527858,0.830040,0.253070,0.0
310,Matt Turner,USA,0.003704,0.071429,1.314532,0.713969,0.253070,0.0
55,Ederson,Brazil,0.002443,0.214286,1.046969,0.521910,0.159762,0.0
225,Roberto Fernández,Paraguay,0.002357,0.071429,1.932402,1.000000,0.123467,0.0
118,Mohamed Alaa,Egypt,0.002348,0.000000,1.655482,0.894349,0.149313,0.0
174,Guillermo Ochoa,Mexico,0.002153,0.100000,1.133204,0.588517,0.154686,0.0
244,Rui Silva,Portugal,0.002146,0.171429,1.449873,0.784669,0.123467,0.0
226,Gastón Olveira,Paraguay,0.002077,0.042857,1.932402,1.000000,0.112047,0.0
36,Senne Lammens,Belgium,0.001978,0.157143,1.297917,0.700513,0.123467,0.0
115,Mohamed El Shenawy,Egypt,0.001977,0.014286,1.655482,0.894349,0.123738,0.0
245,José Sá,Portugal,0.001947,0.171429,1.449873,0.784669,0.112047,0.0
264,David Raya,Spain,0.001883,0.214286,1.041854,0.521910,0.123467,0.0
72,Owen Goodman,Canada,0.001739,0.000000,1.413049,0.770053,0.123467,0.0
116,El Mahdy Soliman,Egypt,0.001709,0.014286,1.655482,0.894349,0.106929,0.0

In [739]:
raw_tackles = (
    0.50 * df["tackles_per90"]
  + 0.15 * df["recent_tackles_per90"]
  + 0.15 * df["expected_goals_conceded_norm"]
  + 0.20 * df["match_over_25_prob"]
)

df["lambda_tackles"] = -np.log(
    (1 - raw_tackles).clip(lower=0.001)
)

df["expected_tackles"] = (
    df["lambda_tackles"].clip(lower=0)
    * df["prob_plays_60min"]
)

df.loc[df["position"] != "MID", "expected_tackles"] = 0.0

In [740]:
cols = [
    "name",
    "team",
    "expected_tackle_points",
    "tackles_per90",
    "recent_tackles_per90",
    "expected_goals_conceded",
    "match_over_25_prob",
    "price",
    "prob_plays_60min",
]

df[df["position"] == "MID"][cols] \
    .sort_values("expected_tackle_points", ascending=False) \
    .head(30)

,name,team,expected_tackle_points,tackles_per90,recent_tackles_per90,expected_goals_conceded,match_over_25_prob,price,prob_plays_60min
209,Matías Galarza,Paraguay,0.233753,0.046980,0.234899,1.932402,0.5718,0.185714,0.909457
360,Andrés Cubas,Paraguay,0.219508,0.035897,0.150000,1.932402,0.5718,0.171429,0.927574
229,Julio Enciso,Paraguay,0.170678,0.012270,0.042373,1.932402,0.5718,0.442857,0.821783
100,Marwan Attia,Egypt,0.151411,0.017442,0.059055,1.655482,0.4816,0.114286,0.898334
218,Miguel Almirón,Paraguay,0.147274,0.032710,0.185185,1.932402,0.5718,0.357143,0.611949
249,João Neves,Portugal,0.145433,0.029900,0.189573,1.449873,0.5141,0.428571,0.820629
298,Weston McKennie,USA,0.143209,0.022599,0.151515,1.314532,0.5365,0.371429,0.890555
103,Emam Ashour,Egypt,0.142975,0.009346,0.040000,1.655482,0.4816,0.157143,0.878122
228,Damián Bobadilla,Paraguay,0.142137,0.036842,0.241379,1.932402,0.5718,0.285714,0.563233
359,Mohamed Salah,Egypt,0.140672,0.002959,0.000000,1.655482,0.4816,0.928571,0.904995
250,Bruno Fernandes,Portugal,0.139916,0.024024,0.102881,1.449873,0.5141,0.714286,0.854701
186,Sander Berge,Norway,0.139762,0.022222,0.138889,1.527858,0.5352,0.171429,0.783991
369,Martin Ødegaard,Norway,0.136824,0.022989,0.111111,1.527858,0.5352,0.600000,0.781991
357,Mostafa Zico,Egypt,0.136131,0.016949,0.114155,1.655482,0.4816,0.100000,0.776133
39,Youri Tielemans,Belgium,0.133071,0.010390,0.050847,1.297917,0.5365,0.371429,0.930263
268,Rodri,Spain,0.132932,0.039216,0.222222,1.041854,0.5141,0.571429,0.891979
344,Leandro Trossard,Belgium,0.131178,0.013850,0.055351,1.297917,0.5365,0.442857,0.905769
189,Patrick Berg,Norway,0.129420,0.017094,0.066667,1.527858,0.5352,0.300000,0.775912
382,Stephen Eustaquio,Canada,0.128006,0.023256,0.141509,1.413049,0.4373,0.214286,0.838929
59,Casemiro,Brazil,0.127242,0.041522,0.225410,1.046969,0.5352,0.400000,0.826414
297,Malik Tillman,USA,0.124474,0.022556,0.163043,1.314532,0.5365,0.371429,0.767428
321,Bruno Guimarães,Brazil,0.121814,0.029412,0.134615,1.046969,0.5352,0.471429,0.875022
409,Tyler Adams,USA,0.121496,0.025926,0.138889,1.314532,0.5365,0.257143,0.756406
230,Diego Gómez,Paraguay,0.120434,0.033898,0.192308,1.932402,0.5718,0.471429,0.496654
248,Vitinha,Portugal,0.117330,0.006711,0.046512,1.449873,0.5141,0.414286,0.781545
272,Granit Xhaka,Switzerland,0.115697,0.013889,0.092593,1.235808,0.4306,0.385714,0.896578
274,Remo Freuler,Switzerland,0.114966,0.016713,0.092593,1.235808,0.4306,0.342857,0.884368
270,Pedri,Spain,0.112723,0.025890,0.136986,1.041854,0.5141,0.657143,0.836037
75,Nathan Saliba,Canada,0.112174,0.032967,0.164835,1.413049,0.4373,0.228571,0.704711
401,Neil El Aynaoui,Morocco,0.109595,0.039164,0.187713,0.817804,0.4373,0.300000,0.928121

In [741]:
raw_cc = (
    0.25 * df["recent_cc_per90"]
  + 0.25 * df["stat_CC"]
  + 0.25 * df["match_over_25_prob"]
  + 0.15 * df["anytime_scorer_prob"]
  + 0.10 * df["price"]
)

df["lambda_cc"] = -np.log(
    (1 - raw_cc).clip(lower=0.001)
)

df["expected_chances_created"] = (
    df["lambda_cc"].clip(lower=0)
    * df["prob_plays_60min"]
)

df.loc[df["position"] != "MID", "expected_chances_created"] = 0.0

In [742]:
cols = [
    "name",
    "team",
    "position",
    "expected_cc_points",
    "cc_per90",
    "recent_cc_per90",
    "stat_CC",
    "match_over_25_prob",
    "anytime_scorer_prob",
    "price",
    "prob_plays_60min",
]

df[cols].sort_values("expected_cc_points", ascending=False).head(30)

,name,team,position,expected_cc_points,cc_per90,recent_cc_per90,stat_CC,match_over_25_prob,anytime_scorer_prob,price,prob_plays_60min
161,Michael Olise,France,MID,0.778191,0.162338,0.178899,1.0,0.5718,0.3571,0.857143,0.845736
140,Jude Bellingham,England,MID,0.455714,0.095541,0.166667,0.6,0.4076,0.2564,0.685714,0.855402
321,Bruno Guimarães,Brazil,MID,0.449912,0.088235,0.150000,0.6,0.5352,0.1538,0.471429,0.875022
48,Vinícius Júnior,Brazil,MID,0.404543,0.028490,0.049808,0.2,0.5352,0.4717,0.928571,0.894919
250,Bruno Fernandes,Portugal,MID,0.384913,0.060060,0.106996,0.4,0.5141,0.2151,0.714286,0.854701
149,Ousmane Dembélé,France,MID,0.382573,0.034722,0.062500,0.2,0.5718,0.4762,0.928571,0.801957
185,Ismael Saibari,Morocco,MID,0.381955,0.055096,0.094891,0.4,0.4373,0.4049,0.471429,0.915987
344,Leandro Trossard,Belgium,MID,0.381914,0.055402,0.095941,0.4,0.5365,0.2740,0.442857,0.905769
189,Patrick Berg,Norway,MID,0.373049,0.128205,0.173333,0.6,0.5352,0.1176,0.300000,0.775912
357,Mostafa Zico,Egypt,MID,0.340402,0.101695,0.178082,0.6,0.4816,0.1852,0.100000,0.776133
139,Declan Rice,England,MID,0.338202,0.119522,0.145251,0.6,0.4076,0.1333,0.500000,0.753382
359,Mohamed Salah,Egypt,MID,0.325858,0.029586,0.049618,0.2,0.4816,0.2151,0.928571,0.904995
382,Stephen Eustaquio,Canada,MID,0.323242,0.099668,0.122642,0.6,0.4373,0.0769,0.214286,0.838929
229,Julio Enciso,Paraguay,MID,0.320979,0.061350,0.055085,0.4,0.5718,0.1667,0.442857,0.821783
369,Martin Ødegaard,Norway,MID,0.319783,0.076628,0.072222,0.4,0.5352,0.1639,0.600000,0.781991
271,Johan Manzambi,Switzerland,MID,0.309629,0.150000,0.148571,0.6,0.4306,0.2326,0.300000,0.685473
402,Brahim Díaz,Morocco,MID,0.291337,0.067114,0.055794,0.4,0.4373,0.2985,0.414286,0.803428
331,Bradley Barcola,France,MID,0.279243,0.048077,0.065657,0.2,0.5718,0.3846,0.642857,0.698293
86,Luis Díaz,Colombia,MID,0.277071,0.027933,0.000000,0.2,0.4306,0.3390,0.657143,0.900602
60,Lucas Paquetá,Brazil,MID,0.273970,0.127119,0.222857,0.6,0.5352,0.0067,0.428571,0.550358
94,Gustavo Puerta,Colombia,MID,0.264534,0.057143,0.048148,0.4,0.4306,0.1639,0.257143,0.877412
403,Azzedine Ounahi,Morocco,MID,0.259748,0.076923,0.133333,0.4,0.4373,0.2247,0.385714,0.698816
39,Youri Tielemans,Belgium,MID,0.258997,0.025974,0.000000,0.2,0.5365,0.2151,0.371429,0.930263
313,Christian Pulisic,USA,MID,0.255436,0.121212,0.000000,0.4,0.5365,0.3891,0.500000,0.608442
270,Pedri,Spain,MID,0.247640,0.032362,0.000000,0.2,0.5141,0.1471,0.657143,0.836037
259,Lamine Yamal,Spain,MID,0.247533,0.000000,0.000000,0.0,0.5141,0.3968,0.928571,0.779433
338,Luis Romo,Mexico,MID,0.243162,0.096618,0.125604,0.4,0.4076,0.1333,0.285714,0.762184
19,Alexis Mac Allister,Argentina,MID,0.241683,0.030395,0.000000,0.2,0.4816,0.2151,0.442857,0.896554
209,Matías Galarza,Paraguay,MID,0.236966,0.033557,0.043624,0.2,0.5718,0.1176,0.185714,0.909457
404,Bilal El Khannouss,Morocco,MID,0.224632,0.029326,0.049808,0.2,0.4373,0.2247,0.385714,0.845285

In [743]:
raw_sot = (
    0.35 * df["sot_per90"]
  + 0.15 * df["stat_GS"]
  + 0.20 * df["match_over_25_prob"]
  + 0.20 * df["anytime_scorer_prob"]
  + 0.10 * df["price"]
)

df["lambda_sot"] = -np.log(
    (1 - raw_sot).clip(lower=0.001)
)

df["expected_shots_on_target"] = (
    df["lambda_sot"].clip(lower=0)
    * df["prob_plays_60min"]
)

df.loc[df["position"] != "FWD", "expected_shots_on_target"] = 0.0

In [744]:
cols = [
    "name",
    "team",
    "position",
    "expected_sot_points",
    "sot_per90",
    "goal_rate",
    "stat_GS",
    "match_over_25_prob",
    "anytime_scorer_prob",
    "price",
    "prob_plays_60min",
]

df[cols].sort_values("expected_sot_points", ascending=False).head(30)

,name,team,position,expected_sot_points,sot_per90,goal_rate,stat_GS,match_over_25_prob,anytime_scorer_prob,price,prob_plays_60min
5,Lionel Messi,Argentina,FWD,0.904992,0.445312,0.415625,1.000000,0.4816,0.6173,0.928571,0.899661
148,Kylian Mbappé,France,FWD,0.863703,0.351852,0.324786,0.857143,0.5718,0.6536,1.000000,0.897936
198,Erling Haaland,Norway,FWD,0.640658,0.316667,0.351852,0.714286,0.5352,0.4717,1.000000,0.807380
127,Harry Kane,England,FWD,0.588515,0.241525,0.268362,0.714286,0.4076,0.4167,1.000000,0.901582
261,Mikel Oyarzabal,Spain,FWD,0.525946,0.252492,0.252492,0.571429,0.5141,0.4950,0.657143,0.848337
350,Cristiano Ronaldo,Portugal,FWD,0.479638,0.189459,0.162393,0.428571,0.5141,0.3846,0.928571,0.891340
49,Matheus Cunha,Brazil,FWD,0.388650,0.202128,0.242553,0.428571,0.5352,0.4167,0.542857,0.792376
65,Jonathan David,Canada,FWD,0.338614,0.200906,0.172205,0.428571,0.4373,0.2299,0.500000,0.898334
31,Romelu Lukaku,Belgium,FWD,0.292613,0.107345,0.214689,0.285714,0.5365,0.4587,0.557143,0.719496
285,Breel Embolo,Switzerland,FWD,0.291908,0.109510,0.109510,0.285714,0.4306,0.3175,0.571429,0.889168
169,Julián Quiñones,Mexico,FWD,0.277396,0.142643,0.171171,0.428571,0.4076,0.2857,0.300000,0.865384
318,Lautaro Martínez,Argentina,FWD,0.256411,0.078189,0.078189,0.142857,0.4816,0.4587,0.757143,0.697257
168,Raúl Jiménez,Mexico,FWD,0.228694,0.165217,0.165217,0.285714,0.4076,0.3226,0.500000,0.668707
287,Dan Ndoye,Switzerland,FWD,0.221951,0.203863,0.081545,0.142857,0.4306,0.2326,0.471429,0.727146
6,Julián Alvarez,Argentina,FWD,0.201239,0.095000,0.000000,0.000000,0.4816,0.4587,0.728571,0.595449
112,Omar Marmoush,Egypt,FWD,0.191987,0.030063,0.000000,0.000000,0.4816,0.1852,0.614286,0.878011
53,Rayan,Brazil,FWD,0.178903,0.042793,0.000000,0.000000,0.5352,0.3226,0.300000,0.772645
88,Luis Suárez,Colombia,FWD,0.153539,0.000000,0.000000,0.000000,0.4306,0.3390,0.314286,0.778496
199,Alexander Sørloth,Norway,FWD,0.148317,0.000000,0.000000,0.000000,0.5352,0.2667,0.471429,0.670656
113,Trezeguet,Egypt,FWD,0.148298,0.197917,0.131944,0.142857,0.4816,0.1852,0.300000,0.531286
67,Tajon Buchanan,Canada,FWD,0.143274,0.064626,0.000000,0.000000,0.4373,0.1429,0.285714,0.798905
171,Roberto Alvarado,Mexico,FWD,0.139515,0.000000,0.000000,0.000000,0.4076,0.2000,0.257143,0.865252
66,Cyle Larin,Canada,FWD,0.134022,0.234568,0.234568,0.285714,0.4373,0.2000,0.385714,0.402477
260,Ferran Torres,Spain,FWD,0.130484,0.119497,0.000000,0.000000,0.5141,0.3846,0.614286,0.406832
132,Noni Madueke,England,FWD,0.125089,0.039095,0.000000,0.000000,0.4076,0.2151,0.371429,0.668247
308,Ricardo Pepi,USA,FWD,0.124968,0.000000,0.000000,0.000000,0.5365,0.3891,0.342857,0.531923
405,Soufiane Rahimi,Morocco,FWD,0.118510,0.311475,0.311475,0.142857,0.4373,0.3390,0.300000,0.317728
33,Dodi Lukébakio,Belgium,FWD,0.114025,0.098958,0.000000,0.000000,0.5365,0.2564,0.342857,0.465937
183,Ayoub El Kaabi,Morocco,FWD,0.113098,0.271429,0.000000,0.000000,0.4373,0.3509,0.342857,0.346160
69,Tani Oluwaseyi,Canada,FWD,0.112877,0.144670,0.000000,0.000000,0.4373,0.1818,0.200000,0.545899

In [745]:
df["expected_qualification_points"] = df["team_qualify_prob"] * 2

In [746]:
cols = [
    "name",
    "team",
    "position",
    "expected_qualification_points",
    "team_qualify_prob",
    "price",
    "prob_plays_60min",
]

df[cols].sort_values("expected_qualification_points", ascending=False).head(30)

,name,team,position,expected_qualification_points,team_qualify_prob,price,prob_plays_60min
332,Jean-Philippe Mateta,France,FWD,1.886792,0.943396,0.428571,0.181230
329,William Saliba,France,DEF,1.886792,0.943396,0.257143,0.766993
330,Jules Koundé,France,DEF,1.886792,0.943396,0.271429,0.846911
331,Bradley Barcola,France,MID,1.886792,0.943396,0.642857,0.698293
153,Brice Samba,France,GK,1.886792,0.943396,0.142857,0.112047
157,Manu Koné,France,MID,1.886792,0.943396,0.371429,0.435794
155,Adrien Rabiot,France,MID,1.886792,0.943396,0.414286,0.725280
141,Theo Hernández,France,DEF,1.886792,0.943396,0.214286,0.418340
328,Robin Risser,France,GK,1.886792,0.943396,0.000000,0.123467
152,Mike Maignan,France,GK,1.886792,0.943396,0.214286,0.880352
151,Désiré Doué,France,MID,1.886792,0.943396,0.571429,0.476354
150,Marcus Thuram,France,FWD,1.886792,0.943396,0.571429,0.109030
149,Ousmane Dembélé,France,MID,1.886792,0.943396,0.928571,0.801957
148,Kylian Mbappé,France,FWD,1.886792,0.943396,1.000000,0.897936
147,Malo Gusto,France,DEF,1.886792,0.943396,0.228571,0.157342
146,Lucas Digne,France,DEF,1.886792,0.943396,0.214286,0.607153
145,Lucas Hernández,France,DEF,1.886792,0.943396,0.242857,0.100954
144,Ibrahima Konaté,France,DEF,1.886792,0.943396,0.200000,0.127896
156,Warren Zaïre-Emery,France,MID,1.886792,0.943396,0.371429,0.100652
142,Maxence Lacroix,France,DEF,1.886792,0.943396,0.142857,0.245583
143,Dayot Upamecano,France,DEF,1.886792,0.943396,0.257143,0.887167
160,Rayan Cherki,France,MID,1.886792,0.943396,0.642857,0.218056
159,Aurélien Tchouaméni,France,MID,1.886792,0.943396,0.428571,0.674982
158,Maghnes Akliouche,France,MID,1.886792,0.943396,0.414286,0.112834
161,Michael Olise,France,MID,1.886792,0.943396,0.857143,0.845736
154,N'Golo Kanté,France,MID,1.886792,0.943396,0.228571,0.106215
9,José Manuel López,Argentina,FWD,1.754386,0.877193,0.257143,0.122063
12,Juan Musso,Argentina,GK,1.754386,0.877193,0.114286,0.112047
11,Gerónimo Rulli,Argentina,GK,1.754386,0.877193,0.142857,0.123467
6,Julián Alvarez,Argentina,FWD,1.754386,0.877193,0.728571,0.595449

In [747]:
df.to_csv(OUT_CSV, index=False)

print(f"\nSaved {OUT_CSV} {df.shape[0]} rows x {df.shape[1]} cols")

Saved fantasy_enriched.csv 414 rows x 229 cols

In [748]:
BUDGET = 105.0
MAX_PER_COUNTRY = 4
SQUAD_SIZE = 15
XI_SIZE = 11
BENCH_WEIGHT = 0.6  

def compute_total_expected_points(df):
    df = df.copy()

    cs_value = {"GK": 5, "DEF": 5, "MID": 1, "FWD": 0}
    goal_value = {"GK": 9, "DEF": 7, "MID": 6, "FWD": 5}

    df["goal_pts_value"] = df["position"].map(goal_value)
    df["cs_pts_value"] = df["position"].map(cs_value)

    # appearance: 1pt for playing any, +1 if 60+
    e_appearance = df["prob_plays_any"] * 1 + df["prob_plays_60min"] * 1

    # goal
    e_goal = df["prob_scores"] * df["goal_pts_value"]

    # assist
    e_assist = df["expected_assists"] * 3

    # clean sheet: gated by 60min, value depends on position
    e_cs = df["prob_clean_sheet"] * df["cs_pts_value"]

    # goals conceded penalty: GK and DEF only
    e_gc = df["expected_gc_penalty"].copy()
    e_gc[~df["position"].isin(["GK", "DEF"])] = 0.0

    # saves bonus: GK only, every 3 saves = +1
    e_saves = (df["expected_saves"] / 3).copy()
    e_saves[df["position"] != "GK"] = 0.0

    # penalty save: GK only
    e_pen_save = (df["prob_penalty_save"] * 3).copy()
    e_pen_save[df["position"] != "GK"] = 0.0

    # tackles bonus: MID only, every 3 tackles = +1
    e_tackles = df["expected_tackle_points"].copy()
    e_tackles[df["position"] != "MID"] = 0.0

    # big chances created: MID only, every 2 = +1
    e_cc = df["expected_cc_points"].copy()
    e_cc[df["position"] != "MID"] = 0.0

    # shots on target: FWD only, every 2 = +1
    e_sot = df["expected_sot_points"].copy()
    e_sot[df["position"] != "FWD"] = 0.0

    # yellow card
    e_yc = df["prob_yellow_card"] * -1

    # red card
    e_rc = df["prob_red_card"] * -2

    # own goal
    e_og = df["prob_own_goal"] * -2

    # penalty won
    e_pw = df["prob_pen_won"] * 2

    # penalty committed
    e_pc = df["prob_penalty_committed"] * -1

    # qualification bonus: +2 per player in XI who advances, requires playing
    # captain's quali bonus is NOT doubled per rules
    e_quali = df["expected_qualification_points"] * df["prob_plays_any"]

    # scouting bonus: +2 if differential==1 AND player scores >4 base pts
    # model: use Poisson confidence interval on expected base points
    # base pts = everything except scouting and captain multiplier
    base_ep = (
        e_appearance + e_goal + e_assist + e_cs + e_gc +
        e_saves + e_pen_save + e_tackles + e_cc + e_sot +
        e_yc + e_rc + e_og + e_pw + e_pc + e_quali
    )

    # Poisson 90% CI: lower = ppf(0.05, mu), upper = ppf(0.95, mu)
    mu = base_ep.clip(lower=0.01)
    lower_ci = pd.Series(poisson.ppf(0.05, mu), index=df.index)
    upper_ci = pd.Series(poisson.ppf(0.95, mu), index=df.index)

    # if lower CI > 4: full +2 expected
    # if upper CI < 4: 0
    # if CI straddles 4: scale by P(X>4 | mu) * 2
    p_exceeds_4 = pd.Series(1 - poisson.cdf(4, mu), index=df.index)

    scouting_ep = pd.Series(0.0, index=df.index)
    eligible = df["differential"] == 1
    full_bonus = eligible & (lower_ci > 4)
    no_bonus = eligible & (upper_ci < 4)
    partial = eligible & ~full_bonus & ~no_bonus

    scouting_ep[full_bonus] = 2.0
    scouting_ep[no_bonus] = 0.0
    scouting_ep[partial] = p_exceeds_4[partial] * 2.0

    df["e_appearance"] = e_appearance
    df["e_goal"] = e_goal
    df["e_assist"] = e_assist
    df["e_cs"] = e_cs
    df["e_gc"] = e_gc
    df["e_saves"] = e_saves
    df["e_pen_save"] = e_pen_save
    df["e_tackles"] = e_tackles
    df["e_cc"] = e_cc
    df["e_sot"] = e_sot
    df["e_yc"] = e_yc
    df["e_rc"] = e_rc
    df["e_og"] = e_og
    df["e_pw"] = e_pw
    df["e_pc"] = e_pc
    df["e_quali"] = e_quali
    df["e_scouting"] = scouting_ep
    df["expected_points"] = base_ep + scouting_ep

    return df

In [749]:

def optimize_squad(df, budget=BUDGET, max_per_country=MAX_PER_COUNTRY):
    idx = df.index.tolist()

    x = LpVariable.dicts("squad", idx, cat="Binary")
    s = LpVariable.dicts("xi", idx, cat="Binary")
    b = LpVariable.dicts("bench", idx, cat="Binary")    
    cap = LpVariable.dicts("cap", idx, cat="Binary")

    model = LpProblem("fantasy", LpMaximize)

    
    model += lpSum(
        df.loc[i, "expected_points"] * s[i]
        + df.loc[i, "expected_points"] * cap[i]
        + df.loc[i, "expected_points"] * BENCH_WEIGHT * b[i]
        for i in idx
    )

    # squad = 15, xi = 11, bench = 4
    model += lpSum(x[i] for i in idx) == 15
    model += lpSum(s[i] for i in idx) == 11
    model += lpSum(b[i] for i in idx) == 4

    for i in idx:
        model += s[i] + b[i] == x[i]

    # budget
    model += lpSum(df.loc[i, "price_raw"] * x[i] for i in idx) <= budget

    # squad composition: 2 GK, 5 DEF, 5 MID, 3 FWD
    for pos, count in [("GK", 2), ("DEF", 5), ("MID", 5), ("FWD", 3)]:
        p_idx = df[df["position"] == pos].index.tolist()
        model += lpSum(x[i] for i in p_idx) == count

    # country limit
    for country in df["team"].unique():
        c_idx = df[df["team"] == country].index.tolist()
        model += lpSum(x[i] for i in c_idx) <= max_per_country

    # XI formation: 1 GK starts, valid outfield formation
    gk_idx = df[df["position"] == "GK"].index.tolist()
    model += lpSum(s[i] for i in gk_idx) == 1
    model += lpSum(b[i] for i in gk_idx) == 1

    for pos, lo, hi in [("DEF", 3, 5), ("MID", 3, 5), ("FWD", 1, 3)]:
        p_idx = df[df["position"] == pos].index.tolist()
        model += lpSum(s[i] for i in p_idx) >= lo
        model += lpSum(s[i] for i in p_idx) <= hi

    # captain: exactly 1, must be in XI
    model += lpSum(cap[i] for i in idx) == 1
    for i in idx:
        model += cap[i] <= s[i]

    model.solve(PULP_CBC_CMD(msg=0))

    if LpStatus[model.status] != "Optimal":
        print(f"Solver status: {LpStatus[model.status]}")
        return None

    in_squad = [i for i in idx if value(x[i]) > 0.5]
    in_xi = [i for i in idx if value(s[i]) > 0.5]
    on_bench = [i for i in idx if value(b[i]) > 0.5]
    captain = next(i for i in idx if value(cap[i]) > 0.5)

    return {
        "squad": df.loc[in_squad].copy(),
        "xi": df.loc[in_xi].copy(),
        "bench": df.loc[on_bench].copy(),
        "captain": captain,
        "total_ep": value(model.objective),
        "cost": df.loc[in_squad, "price_raw"].sum(),
    }

In [750]:
def optimize_ideal_xi(df, max_per_country=MAX_PER_COUNTRY):
    # best possible 11 ignoring bench constraint, just 11 players
    idx = df.index.tolist()

    s = LpVariable.dicts("xi", idx, cat="Binary")
    cap = LpVariable.dicts("cap", idx, cat="Binary")

    model = LpProblem("ideal_xi", LpMaximize)

    # optimize_ideal_xi objective — NO bench term
    model += lpSum(
        df.loc[i, "expected_points"] * s[i]
        + df.loc[i, "expected_points"] * cap[i]
        for i in idx
    )

    model += lpSum(s[i] for i in idx) == 11

    # no budget constraint for ideal XI comparison
    # country limit still applies
    for country in df["team"].unique():
        c_idx = df[df["team"] == country].index.tolist()
        model += lpSum(s[i] for i in c_idx) <= max_per_country

    gk_idx = df[df["position"] == "GK"].index.tolist()
    model += lpSum(s[i] for i in gk_idx) == 1

    for pos, lo, hi in [("DEF", 3, 5), ("MID", 3, 5), ("FWD", 1, 3)]:
        p_idx = df[df["position"] == pos].index.tolist()
        model += lpSum(s[i] for i in p_idx) >= lo
        model += lpSum(s[i] for i in p_idx) <= hi

    model += lpSum(cap[i] for i in idx) == 1
    for i in idx:
        model += cap[i] <= s[i]

    model.solve(PULP_CBC_CMD(msg=0))

    if LpStatus[model.status] != "Optimal":
        return None

    in_xi = [i for i in idx if value(s[i]) > 0.5]
    captain = next(i for i in idx if value(cap[i]) > 0.5)

    return {
        "xi": df.loc[in_xi].copy(),
        "captain": captain,
        "total_ep": value(model.objective),
    }


def print_team(result, ideal=None):
    pos_order = {"GK": 0, "DEF": 1, "MID": 2, "FWD": 3}
    cap = result["captain"]

    xi = result["xi"].copy()
    xi["_ord"] = xi["position"].map(pos_order)
    xi = xi.sort_values(["_ord", "expected_points"], ascending=[True, False])

    bench = result["bench"].copy()
    bench["_ord"] = bench["position"].map(pos_order)
    bench = bench.sort_values(["_ord", "expected_points"], ascending=[True, False])

    print(f"\nExpected points: {result['total_ep']:.2f}   Cost: ${result['cost']:.1f}M\n")

    print("Starting XI")
    for i, row in xi.iterrows():
        tag = " [C]" if i == cap else ""
        scout = " [SCOUT]" if row.get("differential", 0) == 1 else ""
        print(f"  {row['position']:3}  {row['name']:<28} {row['team']:<22} ${row['price_raw']:.1f}  EP:{row['expected_points']:.2f}{tag}{scout}")

    print("\nBench")
    for rank, (i, row) in enumerate(bench.iterrows(), 1):
        print(f"  [{rank}] {row['position']:3}  {row['name']:<28} {row['team']:<22} ${row['price_raw']:.1f}  EP:{row['expected_points']:.2f}")

    print(f"\nCountry breakdown: {dict(result['squad']['team'].value_counts())}")

    if ideal:
        ideal_xi = ideal["xi"].copy()
        ideal_xi["_ord"] = ideal_xi["position"].map(pos_order)
        ideal_xi = ideal_xi.sort_values(["_ord", "expected_points"], ascending=[True, False])
        ideal_cap = ideal["captain"]

        print(f"\nIdeal XI (no budget constraint, 11 only, EP: {ideal['total_ep']:.2f})")
        for i, row in ideal_xi.iterrows():
            tag = " [C]" if i == ideal_cap else ""
            in_squad = i in result["squad"].index
            flag = "" if in_squad else " [NOT IN SQUAD]"
            print(f"  {row['position']:3}  {row['name']:<28} {row['team']:<22} ${row['price_raw']:.1f}  EP:{row['expected_points']:.2f}{tag}{flag}")
            
if __name__ == "__main__":
    df = pd.read_csv("fantasy_enriched.csv")
    df = df[df["status"] == "playing"].copy()
    df = df.reset_index(drop=True)

    df = compute_total_expected_points(df)

    result = optimize_squad(df, budget=BUDGET, max_per_country=MAX_PER_COUNTRY)
    ideal = optimize_ideal_xi(df, max_per_country=MAX_PER_COUNTRY)

    print_team(result, ideal)

Expected points: 130.66   Cost: $104.7M

Starting XI
  GK   Emiliano Martínez            Argentina              $5.0  EP:7.96
  DEF  Dayot Upamecano              France                 $5.3  EP:7.72
  DEF  Achraf Hakimi                Morocco                $6.0  EP:7.65
  DEF  Lisandro Martínez            Argentina              $4.6  EP:7.34
  MID  Michael Olise                France                 $9.5  EP:11.53
  MID  Ousmane Dembélé              France                 $10.0  EP:9.76
  MID  Vinícius Júnior              Brazil                 $10.0  EP:9.34
  MID  Alexis Mac Allister          Argentina              $6.6  EP:8.48 [SCOUT]
  MID  Ismael Saibari               Morocco                $6.8  EP:8.22
  FWD  Kylian Mbappé                France                 $10.5  EP:12.23 [C]
  FWD  Lionel Messi                 Argentina              $10.0  EP:11.47

Bench
  [1] GK   Yassine Bounou               Morocco                $4.7  EP:6.89
  [2] DEF  Dávinson Sánchez             Colombia               $4.3  EP:6.66
  [3] DEF  Chadi Riad                   Morocco                $3.9  EP:6.51
  [4] FWD  Breel Embolo                 Switzerland            $7.5  EP:7.87

Country breakdown: {'Argentina': np.int64(4), 'France': np.int64(4), 'Morocco': np.int64(4), 'Brazil': np.int64(1), 'Colombia': np.int64(1), 'Switzerland': np.int64(1)}

Ideal XI (no budget constraint, 11 only, EP: 113.91)
  GK   Emiliano Martínez            Argentina              $5.0  EP:7.96
  DEF  Dayot Upamecano              France                 $5.3  EP:7.72
  DEF  Achraf Hakimi                Morocco                $6.0  EP:7.65
  DEF  Lisandro Martínez            Argentina              $4.6  EP:7.34
  MID  Michael Olise                France                 $9.5  EP:11.53
  MID  Ousmane Dembélé              France                 $10.0  EP:9.76
  MID  Vinícius Júnior              Brazil                 $10.0  EP:9.34
  MID  Alexis Mac Allister          Argentina              $6.6  EP:8.48
  MID  Ismael Saibari               Morocco                $6.8  EP:8.22
  FWD  Kylian Mbappé                France                 $10.5  EP:12.23 [C]
  FWD  Lionel Messi                 Argentina              $10.0  EP:11.47

In [751]:
def optimize_with_transfers(df, current_team_names, free_transfers=4, budget=BUDGET, max_per_country=MAX_PER_COUNTRY):

    current_idx = set()
    unmatched = []
    for name in current_team_names:
        match = df[df["name"].str.lower().str.strip() == name.lower().strip()]
        if len(match) == 0:
            match = df[df["name"].str.lower().str.contains(name.lower().strip(), na=False)]
        if len(match) > 0:
            current_idx.add(match.index[0])
        else:
            unmatched.append(name)

  
    if unmatched:
        print(f"Eliminated players: {unmatched}")

    forced_transfers = len(unmatched)

    idx = df.index.tolist()

    x         = LpVariable.dicts("squad", idx, cat="Binary")
    s         = LpVariable.dicts("xi",    idx, cat="Binary")
    b         = LpVariable.dicts("bench", idx, cat="Binary")
    cap       = LpVariable.dicts("cap",   idx, cat="Binary")
    transfer_out = LpVariable.dicts("out", idx, cat="Binary")

    model = LpProblem("fantasy_transfers", LpMaximize)

    transfers_made = lpSum(transfer_out[i] for i in idx)   # voluntary drops only

    n_extra = LpVariable("n_extra", lowBound=0)

    # CHANGE 2: total transfers = voluntary + forced. Penalty fires when
    # (voluntary + forced) > free_transfers, not just voluntary > free_transfers.
    model += n_extra >= transfers_made + forced_transfers - free_transfers

    model += (
        lpSum(
            df.loc[i, "expected_points"] * s[i]
            + df.loc[i, "expected_points"] * cap[i]
            + df.loc[i, "expected_points"] * BENCH_WEIGHT * b[i]
            for i in idx
        )
        - 3 * n_extra
    )

    for i in idx:
        if i in current_idx:
            model += transfer_out[i] == 1 - x[i]
        else:
            model += transfer_out[i] == 0

    model += lpSum(x[i] for i in idx) == 15
    model += lpSum(s[i] for i in idx) == 11
    model += lpSum(b[i] for i in idx) == 4

    for i in idx:
        model += s[i] + b[i] == x[i]

    model += lpSum(df.loc[i, "price_raw"] * x[i] for i in idx) <= budget

    for pos, count in [("GK", 2), ("DEF", 5), ("MID", 5), ("FWD", 3)]:
        p_idx = df[df["position"] == pos].index.tolist()
        model += lpSum(x[i] for i in p_idx) == count

    for country in df["team"].unique():
        c_idx = df[df["team"] == country].index.tolist()
        model += lpSum(x[i] for i in c_idx) <= max_per_country

    gk_idx = df[df["position"] == "GK"].index.tolist()
    model += lpSum(s[i] for i in gk_idx) == 1
    model += lpSum(b[i] for i in gk_idx) == 1

    for pos, lo, hi in [("DEF", 3, 5), ("MID", 3, 5), ("FWD", 1, 3)]:
        p_idx = df[df["position"] == pos].index.tolist()
        model += lpSum(s[i] for i in p_idx) >= lo
        model += lpSum(s[i] for i in p_idx) <= hi

    model += lpSum(cap[i] for i in idx) == 1
    for i in idx:
        model += cap[i] <= s[i]

    model.solve(PULP_CBC_CMD(msg=0))

    if LpStatus[model.status] != "Optimal":
        print(f"Solver status: {LpStatus[model.status]}")
        return None

    in_squad  = [i for i in idx if value(x[i]) > 0.5]
    in_xi     = [i for i in idx if value(s[i]) > 0.5]
    on_bench  = [i for i in idx if value(b[i]) > 0.5]
    captain   = next(i for i in idx if value(cap[i]) > 0.5)

    new_squad_idx  = set(in_squad)
    voluntary_out  = [i for i in current_idx if i not in new_squad_idx]
    transfers_in   = [i for i in new_squad_idx if i not in current_idx]

    # CHANGE 3: total = voluntary drops of matched players + forced drops of eliminated.
    n_transfers = len(voluntary_out) + forced_transfers
    penalty     = max(0, n_transfers - free_transfers) * 3

    return {
        "squad":         df.loc[in_squad].copy(),
        "xi":            df.loc[in_xi].copy(),
        "bench":         df.loc[on_bench].copy(),
        "captain":       captain,
        "total_ep":      value(model.objective),
        "cost":          df.loc[in_squad, "price_raw"].sum(),
        "transfers_out": df.loc[voluntary_out, "name"].tolist() + unmatched,  # eliminated shown in OUT
        "transfers_in":  df.loc[transfers_in, "name"].tolist(),
        "n_transfers":   n_transfers,
        "penalty":       penalty,
        "forced_out":    unmatched,   # separate field for clarity
    }

def print_transfers(result):
    if result is None:
        print("No solution.")
        return

    print(f"\nTransfers made: {result['n_transfers']} ({result['n_transfers'] - 4} penalised at -3 each)" if result['n_transfers'] > 4 else f"\nTransfers made: {result['n_transfers']} (all free)")
    print(f"Point penalty: -{result['penalty']}")

    if result["transfers_out"]:
        print("\nOUT:")
        for name in result["transfers_out"]:
            print(f"  {name}")
        print("IN:")
        for name in result["transfers_in"]:
            print(f"  {name}")

    print_team(result)


if __name__ == "__main__":
    df = pd.read_csv("fantasy_enriched.csv")
    df = df[df["status"] == "playing"].copy()
    df = df.reset_index(drop=True)
    df = compute_total_expected_points(df)

    current_team = [
        "Jordan Pickford", "Lisandro Martínez", "Sergiño Dest", "Nico O'Reilly", "Marc Cucurella",
        "Ousmane Dembélé", "Jamal Musiala", "Vinícius Júnior", "Christian Pulisic", "Kylian Mbappé", "Harry Kane",
        "Camilo Vargas", "Facundo Medina", "Lionel Messi", "Johan Manzambi"
    ]

    result = optimize_with_transfers(df, current_team, free_transfers=4, budget=BUDGET, max_per_country=MAX_PER_COUNTRY)
    ideal = optimize_ideal_xi(df, max_per_country=MAX_PER_COUNTRY)
    print_transfers(result)

    print("\nIdeal XI for comparison:")
    if ideal:
        pos_order = {"GK": 0, "DEF": 1, "MID": 2, "FWD": 3}
        xi = ideal["xi"].copy()
        xi["_ord"] = xi["position"].map(pos_order)
        xi = xi.sort_values(["_ord", "expected_points"], ascending=[True, False])
        cap = ideal["captain"]
        for i, row in xi.iterrows():
            tag = " [C]" if i == cap else ""
            in_squad = i in result["squad"].index if result else False
            flag = "" if in_squad else " [NOT IN SQUAD]"
            print(f"  {row['position']:3}  {row['name']:<28} {row['team']:<22} ${row['price_raw']:.1f}  EP:{row['expected_points']:.2f}{tag}{flag}")

Eliminated players: ['Jamal Musiala']

Transfers made: 4 (all free)
Point penalty: -0

OUT:
  Jordan Pickford
  Christian Pulisic
  Sergiño Dest
  Jamal Musiala
IN:
  Michael Olise
  Ismael Saibari
  Emiliano Martínez
  Dávinson Sánchez

Expected points: 124.18   Cost: $104.9M

Starting XI
  GK   Emiliano Martínez            Argentina              $5.0  EP:7.96
  DEF  Lisandro Martínez            Argentina              $4.6  EP:7.34
  DEF  Marc Cucurella               Spain                  $5.1  EP:6.91
  DEF  Dávinson Sánchez             Colombia               $4.3  EP:6.66 [SCOUT]
  MID  Michael Olise                France                 $9.5  EP:11.53
  MID  Ousmane Dembélé              France                 $10.0  EP:9.76
  MID  Vinícius Júnior              Brazil                 $10.0  EP:9.34
  MID  Ismael Saibari               Morocco                $6.8  EP:8.22
  FWD  Kylian Mbappé                France                 $10.5  EP:12.23 [C]
  FWD  Lionel Messi                 Argentina              $10.0  EP:11.47
  FWD  Harry Kane                   England                $10.5  EP:7.29

Bench
  [1] GK   Camilo Vargas                Colombia               $4.3  EP:6.04
  [2] DEF  Facundo Medina               Argentina              $4.0  EP:6.09
  [3] DEF  Nico O'Reilly                England                $4.7  EP:5.01
  [4] MID  Johan Manzambi               Switzerland            $5.6  EP:4.95

Country breakdown: {'Argentina': np.int64(4), 'France': np.int64(3), 'Colombia': np.int64(2), 'England': np.int64(2), 'Brazil': np.int64(1), 'Morocco': np.int64(1), 'Spain': np.int64(1), 'Switzerland': np.int64(1)}

Ideal XI for comparison:
  GK   Emiliano Martínez            Argentina              $5.0  EP:7.96
  DEF  Dayot Upamecano              France                 $5.3  EP:7.72 [NOT IN SQUAD]
  DEF  Achraf Hakimi                Morocco                $6.0  EP:7.65 [NOT IN SQUAD]
  DEF  Lisandro Martínez            Argentina              $4.6  EP:7.34
  MID  Michael Olise                France                 $9.5  EP:11.53
  MID  Ousmane Dembélé              France                 $10.0  EP:9.76
  MID  Vinícius Júnior              Brazil                 $10.0  EP:9.34
  MID  Alexis Mac Allister          Argentina              $6.6  EP:8.48 [NOT IN SQUAD]
  MID  Ismael Saibari               Morocco                $6.8  EP:8.22
  FWD  Kylian Mbappé                France                 $10.5  EP:12.23 [C]
  FWD  Lionel Messi                 Argentina              $10.0  EP:11.47

In [752]:
for pos in ["GK", "DEF", "MID", "FWD"]:
    print(f"\n--- {pos} ---")
    print(df[df["position"] == pos].nlargest(10, "expected_points")[["name", "team", "price_raw", "expected_points"]].to_string(index=False))

--- GK ---
             name        team  price_raw  expected_points
Emiliano Martínez   Argentina        5.0         7.956293
     Mike Maignan      France        5.0         7.176301
   Yassine Bounou     Morocco        4.7         6.891817
    Camilo Vargas    Colombia        4.3         6.041175
   Alisson Becker      Brazil        5.0         5.119327
       Unai Simón       Spain        5.0         5.099955
     Gregor Kobel Switzerland        4.7         4.870678
  Jordan Pickford     England        4.8         4.734632
 Thibaut Courtois     Belgium        4.9         4.291078
      Matt Freese         USA        4.2         4.152908

--- DEF ---
             name      team  price_raw  expected_points
  Dayot Upamecano    France        5.3         7.716034
    Achraf Hakimi   Morocco        6.0         7.645619
     Jules Koundé    France        5.4         7.477421
Lisandro Martínez Argentina        4.6         7.340416
    Nahuel Molina Argentina        4.4         7.140207
   Marc Cucurella     Spain        5.1         6.911743
  Cristian Romero Argentina        4.9         6.704544
 Dávinson Sánchez  Colombia        4.3         6.660945
   William Saliba    France        5.3         6.537969
       Chadi Riad   Morocco        3.9         6.505249

--- MID ---
               name      team  price_raw  expected_points
      Michael Olise    France        9.5        11.525498
    Ousmane Dembélé    France       10.0         9.755003
    Vinícius Júnior    Brazil       10.0         9.337062
    Bradley Barcola    France        8.0         8.510530
Alexis Mac Allister Argentina        6.6         8.478359
     Ismael Saibari   Morocco        6.8         8.222830
        Brahim Díaz   Morocco        6.4         8.000107
     Enzo Fernández Argentina        7.5         7.724672
    Youri Tielemans   Belgium        6.1         7.061645
          Luis Díaz  Colombia        8.1         7.032353

--- FWD ---
            name        team  price_raw  expected_points
   Kylian Mbappé      France       10.5        12.230442
    Lionel Messi   Argentina       10.0        11.471880
 Mikel Oyarzabal       Spain        8.1         8.026890
    Breel Embolo Switzerland        7.5         7.866649
Lautaro Martínez   Argentina        8.8         7.674091
      Harry Kane     England       10.5         7.292743
   Romelu Lukaku     Belgium        7.4         7.148539
  Erling Haaland      Norway       10.5         6.963468
 Julián Quiñones      Mexico        5.6         6.504741
Roberto Alvarado      Mexico        5.3         6.436818

In [753]:
player1 = "Harry Kane"
player2 = "Breel Embolo"

cols = [
    "name", "team", "position", "price_raw", "expected_points",
    "e_appearance", "e_goal", "e_assist", "e_cs", "e_gc",
    "e_saves", "e_pen_save", "e_tackles", "e_cc", "e_sot",
    "e_yc", "e_rc", "e_og", "e_pw", "e_pc",
    "e_quali", "e_scouting"
]

comparison = df.loc[
    df["name"].isin([player1, player2]),
    cols
].set_index("name").T

print(comparison)

name            Harry Kane Breel Embolo
team               England  Switzerland
position               FWD          FWD
price_raw             10.5          7.5
expected_points   7.292743     7.866649
e_appearance      1.820453     1.802803
e_goal            3.090299     2.013058
e_assist          0.790555     1.529352
e_cs                   0.0          0.0
e_gc                   0.0          0.0
e_saves                0.0          0.0
e_pen_save             0.0          0.0
e_tackles              0.0          0.0
e_cc                   0.0          0.0
e_sot             0.588515     0.291908
e_yc             -0.115285    -0.149384
e_rc             -0.026975    -0.033944
e_og             -0.014313    -0.020781
e_pw              0.054767     0.064575
e_pc             -0.009058    -0.010709
e_quali           1.113784      0.86192
e_scouting             0.0     1.517851