In [1]:
!jupyter nbconvert --to notebook --execute preprocess.ipynb --inplace

[NbConvertApp] Converting notebook preprocess.ipynb to notebook
[NbConvertApp] Writing 124929 bytes to preprocess.ipynb

In [51]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from pulp import *
from scipy.stats import poisson, norm
from pulp import LpProblem, LpMaximize, LpVariable, LpStatus, lpSum, value, PULP_CBC_CMD

In [52]:
OUT_CSV = "fantasy_enriched.csv"


| Position        | Point Source         | Points | Description                                                                 |
| --------------- | -------------------- | -----: | --------------------------------------------------------------------------- |
| **All Players** | Appearance (<60 min) |     +1 | Plays any minutes up to 59:59                                               |
| **All Players** | Appearance (60+ min) |     +1 | Additional point for reaching 60+ minutes (total appearance = **2 points**) |
| **All Players** | Assist               |     +3 | Provides an assist                                                          |
| **All Players** | Yellow Card          |     -1 | Receives a yellow card                                                      |
| **All Players** | Red Card             |     -2 | Receives a red card                                                         |
| **All Players** | Own Goal             |     -2 | Scores an own goal                                                          |
| **All Players** | Winning a Penalty    |     +2 | Wins a penalty for their team                                               |
| **All Players** | Conceding a Penalty  |     -1 | Commits a foul leading to a penalty                                         |

| Position       | Point Source                  | Points | Description                                        |
| -------------- | ----------------------------- | -----: | -------------------------------------------------- |
| **Goalkeeper** | Clean Sheet                   |     +5 | Plays 60+ minutes and team keeps a clean sheet     |
| **Goalkeeper** | First Goal Conceded           |      0 | No deduction for conceding the first goal          |
| **Goalkeeper** | Each Additional Goal Conceded |     -1 | Every goal conceded after the first                |
| **Goalkeeper** | Goal Scored                   |     +9 | Scores a goal                                      |
| **Goalkeeper** | Penalty Save                  |     +3 | Saves a penalty during normal play (not shootouts) |
| **Goalkeeper** | Every 3 Saves                 |     +1 | Earns 1 point for every 3 saves                    |

| Position     | Point Source                  | Points | Description                                    |
| ------------ | ----------------------------- | -----: | ---------------------------------------------- |
| **Defender** | Clean Sheet                   |     +5 | Plays 60+ minutes and team keeps a clean sheet |
| **Defender** | First Goal Conceded           |      0 | No deduction for conceding the first goal      |
| **Defender** | Each Additional Goal Conceded |     -1 | Every goal conceded after the first            |
| **Defender** | Goal Scored                   |     +7 | Scores a goal                                  |

| Position       | Point Source                | Points | Description                                    |
| -------------- | --------------------------- | -----: | ---------------------------------------------- |
| **Midfielder** | Clean Sheet                 |     +1 | Plays 60+ minutes and team keeps a clean sheet |
| **Midfielder** | Goal Scored                 |     +6 | Scores a goal                                  |
| **Midfielder** | Every 3 Tackles             |     +1 | Earns 1 point for every 3 tackles              |
| **Midfielder** | Every 2 Big Chances Created |     +1 | Earns 1 point for every 2 big chances created  |

| Position    | Point Source            | Points | Description                               |
| ----------- | ----------------------- | -----: | ----------------------------------------- |
| **Forward** | Goal Scored             |     +5 | Scores a goal                             |
| **Forward** | Every 2 Shots on Target |     +1 | Earns 1 point for every 2 shots on target |

| Position                | Point Source          | Points | Description                                                                                                                                                                        |
| ----------------------- | --------------------- | -----: | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **Bonus (All Players)** | Direct Free-Kick Goal |     +1 | Additional bonus for scoring directly from a free kick (on top of goal points)                                                                                                     |
| **Bonus (All Players)** | Scouting Bonus        |     +2 | Scores **more than 4 base fantasy points** in a match **and** is selected by **<5%** of fantasy teams. Captaincy and booster points do **not** count toward the 4-point threshold. |


## Core identity / player info

| Column | Type | Description |
|---|---|---|
| `fifa_id` | int | Unique FIFA fantasy player ID |
| `name` | str | Player name |
| `squad_id` | int | Internal squad/nation ID |
| `team` | str | National team |
| `position` | str | DEF / MID / FWD / GK |
| `price` | float | Fantasy price |
| `status` | str | Availability status |
| `total_points` | int | Total tournament points |
| `avg_points` | float | Average points per match |
| `matches_played` | int | Matches with participation |
| `percent_selected` | float | Selection rate (%) |
| `next_fixture` | int | Next match ID |


## Round fantasy points

| Column | Type | Description |
|---|---|---|
| `round_1_points` | int | Points in round 1 |
| `round_2_points` | int | Points in round 2 |
| `round_3_points` | int | Points in round 3 |
| `round_4_points` | int | Points in round 4 |


## Betting / scorer mapping

| Column | Type | Description |
|---|---|---|
| `betano_matched_name` | str | Matched Betano market name |
| `betano_match_score` | float | Name matching confidence (0–100) |
| `anytime_scorer_prob` | float | Probability player scores anytime |
| `first_scorer_prob` | float | Probability scores first goal |
| `last_scorer_prob` | float | Probability scores last goal |


## Match context

| Column | Type | Description |
|---|---|---|
| `match_home` | str | Home team |
| `match_away` | str | Away team |
| `is_home` | bool | Player team is home |
| `opponent` | str | Opponent team |


## Match probabilities 

| Column | Type | Description |
|---|---|---|
| `match_home_win_prob` | float | Home win probability |
| `match_draw_prob` | float | Draw probability |
| `match_away_win_prob` | float | Away win probability |
| `match_btts_prob` | float | Both teams score probability |
| `match_over_25_prob` | float | Over 2.5 goals probability |
| `match_over_35_prob` | float | Over 3.5 goals probability |
| `team_score_prob` | float | Team scores ≥1 goal probability |
| `team_score_2_prob` | float | Team scores ≥2 goals probability |
| `team_cs_prob` | float | Team clean sheet probability |
| `opp_score_prob` | float | Opponent scores ≥1 goal probability |
| `opp_cs_prob` | float | Opponent clean sheet probability |
| `team_over_05_prob` | float | Team scores ≥1 goal probability |
| `team_over_15_prob` | float | Team scores ≥2 goals probability |
| `team_qualify_prob` | float | Team advances probability |
| `team_win2_prob` | float | Team wins by 2+ goals probability |
| `opp_over_05_prob` | float | Opponent scores ≥1 goal probability |


## Raw cumulative stats

| Column | Type | Description |
|---|---|---|
| `stat_GS` | int | Goals |
| `stat_AS` | int | Assists |
| `stat_CS` | int | Clean sheets |
| `stat_GC` | int | Goals conceded |
| `stat_MP` | int | Minutes played |
| `stat_YC` | int | Yellow cards |
| `stat_RC` | int | Red cards |
| `stat_ST` | int | Shots on target |
| `stat_SB` | int | Shots blocked |
| `stat_CC` | int | Chances created |
| `stat_PS` | int | Penalties saved |
| `stat_T` | int | Tackles |
| `stat_S` | int | Saves |
| `stat_SXI` | int | Starts (XI appearances) |
| `stat_OG` | int | Own goals |
| `stat_PC` | int | Penalties committed |
| `stat_PW` | int | Penalties won |
| `stat_FK` | int | Free kicks won |



## Round-by-round stats (1–4)

| Pattern | Type | Description |
|---|---|---|
| `round_i_SXI` | int | Started (0/1) |
| `round_i_MP` | int | Minutes |
| `round_i_AS` | int | Assists |
| `round_i_YC` | int | Yellow cards |
| `round_i_RC` | int | Red cards |
| `round_i_OG` | int | Own goals |
| `round_i_PW` | int | Penalties won |
| `round_i_PC` | int | Penalties committed |
| `round_i_CS` | int | Clean sheets |
| `round_i_GS` | int | Goals |
| `round_i_GC` | int | Goals conceded |
| `round_i_PS` | int | Penalties saved |
| `round_i_T` | int | Tackles |
| `round_i_CC` | int | Chances created |
| `round_i_ST` | int | Shots on target |
| `round_i_FK` | int | Free kicks |
| `round_i_S` | int | Saves |
| `round_i_SB` | int | Shots blocked |



## External matching / enrichment

| Column | Type | Description |
|---|---|---|
| `clubstats_matched_player` | str | External player match |
| `clubs_match_dist` | float | Matching distance score |



## Form / usage trends

| Column | Type | Description |
|---|---|---|
| `started_last_match` | int | Started last match |
| `starts_last_3` | int | Starts last 3 matches |
| `starts_last_5` | int | Starts last 5 matches |
| `start_rate` | float | Start frequency |
| `minutes_last_3_avg` | float | Avg minutes last 3 |
| `minutes_last_5_avg` | float | Avg minutes last 5 |



## Performance rates

| Column | Type | Description |
|---|---|---|
| `goal_rate` | float | Goals per minute |
| `goals_per_start` | float | Goals per start |
| `shots_on_target_per90` | float | SOT per 90 |
| `goals_per_shot_on_target` | float | Conversion rate |
| `assist_rate` | float | Assists per minute |
| `chance_created_per90` | float | Chances per 90 |
| `tackles_per90` | float | Tackles per 90 |
| `cc_per90` | float | Chances created per 90 |
| `sot_per90` | float | Shots on target per 90 |
| `saves_per90` | float | Saves per 90 |
| `yc_per90` | float | Yellow cards per 90 |
| `rc_per90` | float | Red cards per 90 |
| `penalty_conceded_rate` | float | Penalties conceded per 90 |
| `own_goal_rate` | float | Own goals per 90 |
| `penalties_won_per90` | float | Penalties won per 90 |



## Recent / streak features

| Column | Type | Description |
|---|---|---|
| `recent_goals_last3` | int | Goals last 3 matches |
| `goal_streak` | int | Consecutive scoring matches |
| `recent_assists_last3` | int | Assists last 3 matches |
| `recent_chances_created_per90` | float | Recent creation rate |
| `recent_cs_rate` | float | Clean sheet rate |
| `recent_tackles_per90` | float | Recent tackles |
| `recent_cc_per90` | float | Recent chances created |
| `recent_sot_per90` | float | Recent shots on target |
| `recent_saves_per90` | float | Recent saves |
| `recent_penalties_won` | int | Penalties won last 3 |



## Expected value features

| Column | Type | Description |
|---|---|---|
| `goal_expectation` | float | Scoring proxy |
| `goal_expectation2` | float | Scoring proxy (2+ goals) |
| `assist_expectation` | float | Assist proxy |
| `cs_expectation` | float | Clean sheet proxy |
| `expected_minutes` | float | Expected minutes |
| `expected_gc_penalty` | float | Defensive penalty |
| `expected_tackle_points` | float | Tackles contribution |
| `expected_cc_points` | float | Chance creation points |
| `expected_sot_points` | float | Shot contribution points |
| `expected_save_points` | float | Save contribution points |



## Fantasy points dynamics

| Column | Type | Description |
|---|---|---|
| `points_last1` | int | Last match points |
| `points_last3_avg` | float | Avg last 3 |
| `points_last5_avg` | float | Avg last 5 |
| `weighted_points` | float | Recency weighted |
| `rolling_std_points` | float | Variance last 5 |
| `rolling_max_points` | int | Max last 5 |



## Team-position ranking features

| Column | Type | Description |
|---|---|---|
| `price_rank_team_position` | float | Price rank |
| `selected_rank_team_position` | float | Selection rank |
| `points_rank_team_position` | float | Points rank |
| `minutes_rank_team_position` | float | Minutes rank |
| `starts_rank_team_position` | float | Starts rank |
| `anytime_rank_team_position` | float | Scoring odds rank |
| `shots_rank_team_position` | float | Shooting rank |
| `cc_rank_team_position` | float | Chance creation rank |
| `tackles_rank_team_position` | float | Tackles rank |

In [53]:
df= pd.read_csv("fantasy_enriched.csv")

In [54]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [55]:
df = df[df["status"] == "playing"].copy()

In [56]:
df.loc[df["name"] == "Johan Manzambi", "status"] = "injured"  # :(
df.loc[df["name"] == "Nicolás Tagliafico", "status"] = "injured"  # :(

In [57]:
# probability of playing a minute

raw_any = (
    0.2* df["minutes_rank_team_position"]
  + 0.10 * df["stat_MP"]        # minutes needs to be very team stratified since while for other point sources players are all eligible
  + 0.15 * df["starts_rank_team_position"]
  + 0.10 * df["price_rank_team_position"]     # for minutes its a team stratified signal.
  + 0.1 * df["selected_rank_team_position"]
  + 0.25 * df["minutes_last_3_avg"]
  + 0.1 * df["has_betano_match"] # having odd at all means likeliness of playing is higher.

)

df["prob_plays_any"] = sigmoid((raw_any - 0.5) * 6)

In [58]:
df.loc[
    :,
    [
        "prob_plays_any",
        "name",
        "team",
        "position",
        "stat_MP",
        "minutes_rank_team_position",
        "starts_rank_team_position",
        "selected_rank_team_position",
        "price_rank_team_position",
        "anytime_rank_team_position",
    ],
].sort_values("prob_plays_any", ascending=False).head(30)

,prob_plays_any,name,team,position,stat_MP,minutes_rank_team_position,starts_rank_team_position,selected_rank_team_position,price_rank_team_position,anytime_rank_team_position
10,0.937027,Emiliano Martínez,Argentina,GK,1.000000,1.000000,0.666667,1.000000,1.000000,1.000000
5,0.930377,Lionel Messi,Argentina,FWD,0.883333,1.000000,0.625000,1.000000,1.000000,1.000000
27,0.923055,Harry Kane,England,FWD,0.938333,1.000000,0.625000,1.000000,1.000000,1.000000
19,0.922397,Alexis Mac Allister,Argentina,MID,0.898333,1.000000,0.545455,1.000000,0.909091,0.136364
81,0.914217,Lisandro Martínez,Argentina,DEF,0.850000,1.000000,0.562500,1.000000,0.750000,0.250000
47,0.905805,Kylian Mbappé,France,FWD,0.863333,1.000000,0.666667,1.000000,1.000000,1.000000
71,0.900628,Mikel Oyarzabal,Spain,FWD,0.781667,1.000000,0.625000,1.000000,1.000000,1.000000
20,0.897104,Enzo Fernández,Argentina,MID,0.800000,0.909091,0.545455,0.900000,1.000000,0.136364
42,0.895974,Dayot Upamecano,France,DEF,0.876667,1.000000,0.555556,1.000000,0.833333,0.888889
39,0.895923,Jude Bellingham,England,MID,0.858333,0.900000,0.550000,1.000000,0.900000,1.000000
60,0.893681,Michael Olise,France,MID,0.813333,1.000000,0.545455,1.000000,0.909091,0.772727
0,0.887905,Cristian Romero,Argentina,DEF,0.751667,0.875000,0.562500,0.725000,1.000000,0.937500
24,0.886458,Ezri Konsa,England,DEF,0.898333,1.000000,0.555556,0.877778,0.777778,0.388889
22,0.880794,Marc Guéhi,England,DEF,0.805000,0.888889,0.555556,0.755556,0.888889,0.388889
67,0.877989,Marc Cucurella,Spain,DEF,0.900000,0.937500,0.562500,1.000000,0.625000,0.500000
33,0.873651,Jordan Pickford,England,GK,0.950000,1.000000,0.666667,1.000000,1.000000,0.666667
48,0.871651,Ousmane Dembélé,France,MID,0.770000,0.909091,0.545455,0.900000,1.000000,1.000000
69,0.867872,Lamine Yamal,Spain,MID,0.675000,0.818182,0.545455,1.000000,1.000000,1.000000
88,0.867318,Jules Koundé,France,DEF,0.853333,0.888889,0.555556,0.755556,1.000000,0.555556
65,0.859420,Aymeric Laporte,Spain,DEF,0.898333,0.750000,0.562500,0.862500,0.875000,0.250000
51,0.854118,Mike Maignan,France,GK,0.900000,1.000000,0.666667,1.000000,1.000000,0.666667
87,0.850340,William Saliba,France,DEF,0.750000,0.777778,0.555556,0.877778,0.833333,0.166667
78,0.850306,Rodri,Spain,MID,0.895000,1.000000,0.545455,0.500000,0.636364,0.181818
68,0.849862,Pau Cubarsí,Spain,DEF,0.900000,0.937500,0.562500,0.725000,0.500000,0.125000
75,0.841212,Unai Simón,Spain,GK,0.900000,1.000000,0.666667,1.000000,0.833333,0.666667
37,0.837461,Elliot Anderson,England,MID,0.888333,1.000000,0.550000,0.560000,0.300000,0.200000
21,0.835304,Nico O'Reilly,England,DEF,0.756667,0.777778,0.555556,1.000000,0.666667,1.000000
80,0.830091,Pedri,Spain,MID,0.715000,0.909091,0.545455,0.800000,0.909091,0.181818
6,0.804646,Julián Alvarez,Argentina,FWD,0.681667,0.750000,0.625000,0.725000,0.500000,0.625000
64,0.789352,Pedro Porro,Spain,DEF,0.600000,0.625000,0.562500,0.587500,0.875000,0.812500

In [59]:
# probability of starting / playing 60 minutes

raw_any = (
    0.25 * df["minutes_rank_team_position"]
  + 0.05 * df["starts_rank_team_position"]
  + 0.20 * df["stat_MP"]
  + 0.05 * df["selected_rank_team_position"]
  + 0.40 * df["minutes_last_3_avg"]
  + 0.05 * df["has_betano_match"] # having odd at all means likeliness of playing is higher.

)

df["prob_plays_60min"] = sigmoid((raw_any - 0.5) * 6)

In [60]:
cols = [
    "prob_plays_60min",
    "name",
    "team",
    "position",
    "minutes_rank_team_position",
    "starts_rank_team_position",
    "price_rank_team_position",
    "selected_rank_team_position",
    "minutes_last_3_avg",
    "round_5_MP",
    "anytime_rank_team_position",
]

df[cols].sort_values("prob_plays_60min", ascending=False).head(30)

,prob_plays_60min,name,team,position,minutes_rank_team_position,starts_rank_team_position,price_rank_team_position,selected_rank_team_position,minutes_last_3_avg,round_5_MP,anytime_rank_team_position
10,0.947846,Emiliano Martínez,Argentina,GK,1.000000,0.666667,1.000000,1.000000,1.000000,1.000000,1.000000
5,0.939772,Lionel Messi,Argentina,FWD,1.000000,0.625000,1.000000,1.000000,1.000000,1.000000,1.000000
19,0.939439,Alexis Mac Allister,Argentina,MID,1.000000,0.545455,0.909091,1.000000,1.000000,1.000000,0.136364
81,0.936360,Lisandro Martínez,Argentina,DEF,1.000000,0.562500,0.750000,1.000000,1.000000,1.000000,0.250000
27,0.930088,Harry Kane,England,FWD,1.000000,0.625000,1.000000,1.000000,0.906061,0.988889,1.000000
33,0.910668,Jordan Pickford,England,GK,1.000000,0.666667,1.000000,1.000000,0.909091,1.000000,0.666667
42,0.907401,Dayot Upamecano,France,DEF,1.000000,0.555556,0.833333,1.000000,0.818182,1.000000,0.888889
37,0.906508,Elliot Anderson,England,MID,1.000000,0.550000,0.300000,0.560000,0.863636,0.833333,0.200000
24,0.905882,Ezri Konsa,England,DEF,1.000000,0.555556,0.777778,0.877778,0.815152,1.000000,0.388889
39,0.905626,Jude Bellingham,England,MID,0.900000,0.550000,0.900000,1.000000,0.881818,1.000000,1.000000
20,0.903705,Enzo Fernández,Argentina,MID,0.909091,0.545455,1.000000,0.900000,0.909091,1.000000,0.136364
67,0.901911,Marc Cucurella,Spain,DEF,0.937500,0.562500,0.625000,1.000000,0.818182,1.000000,0.500000
0,0.898839,Cristian Romero,Argentina,DEF,0.875000,0.562500,1.000000,0.725000,0.951515,0.988889,0.937500
22,0.897935,Marc Guéhi,England,DEF,0.888889,0.555556,0.888889,0.755556,0.909091,1.000000,0.388889
47,0.897406,Kylian Mbappé,France,FWD,1.000000,0.666667,1.000000,1.000000,0.763636,1.000000,1.000000
60,0.897238,Michael Olise,France,MID,1.000000,0.545455,0.909091,1.000000,0.803030,1.000000,0.772727
78,0.895788,Rodri,Spain,MID,1.000000,0.545455,0.636364,0.500000,0.818182,1.000000,0.181818
68,0.894366,Pau Cubarsí,Spain,DEF,0.937500,0.562500,0.500000,0.725000,0.818182,1.000000,0.125000
71,0.891084,Mikel Oyarzabal,Spain,FWD,1.000000,0.625000,1.000000,1.000000,0.781818,0.988889,1.000000
75,0.885303,Unai Simón,Spain,GK,1.000000,0.666667,0.833333,1.000000,0.818182,1.000000,0.666667
51,0.885303,Mike Maignan,France,GK,1.000000,0.666667,1.000000,1.000000,0.818182,1.000000,0.666667
65,0.868398,Aymeric Laporte,Spain,DEF,0.750000,0.562500,0.875000,0.862500,0.815152,1.000000,0.250000
88,0.868000,Jules Koundé,France,DEF,0.888889,0.555556,1.000000,0.755556,0.763636,1.000000,0.555556
48,0.862021,Ousmane Dembélé,France,MID,0.909091,0.545455,1.000000,0.900000,0.754545,0.933333,1.000000
87,0.853248,William Saliba,France,DEF,0.777778,0.555556,0.833333,0.877778,0.818182,1.000000,0.166667
69,0.849180,Lamine Yamal,Spain,MID,0.818182,0.545455,1.000000,1.000000,0.803030,1.000000,1.000000
54,0.842181,Adrien Rabiot,France,MID,0.818182,0.545455,0.409091,0.400000,0.818182,1.000000,0.454545
21,0.840173,Nico O'Reilly,England,DEF,0.777778,0.555556,0.666667,1.000000,0.757576,0.822222,1.000000
6,0.829565,Julián Alvarez,Argentina,FWD,0.750000,0.625000,0.500000,0.725000,0.806061,0.988889,0.625000
2,0.812974,Nahuel Molina,Argentina,DEF,0.750000,0.562500,0.562500,0.587500,0.793939,0.811111,0.250000

There is a phenomenon where a player will be overvalued, such as Lukaku here for belgium. He has not played much, but since Belgium only has 3 forward and only him has significative minutes he ranks number 1 for all ranks in BEL,FWD. Need to include more general sums and beware with manual selection.

In [61]:
df["lambda_goal"] = -np.log(
    (1 - df["anytime_scorer_prob"]).clip(lower=0.001)
)

lambda_adj = (
    0.70 * df["lambda_goal"]
  + 0.1 * df["recent_goals_last3"]
  + 0.02 * df["team_score_2_prob"]
  + 0.1 * df["stat_GS"]
  + 0.05 * df["stat_ST"]
  + 0.03 * df["price"]
)

df["prob_scores"] = (
    lambda_adj.clip(lower=0)
    * df["prob_plays_60min"]
    * 1.5
)

df.loc[df["position"] == "GK", "prob_scores"] = 0.
df.loc[df["position"] == "DEF", "prob_scores"] = df["prob_scores"] * 0.7

In [62]:
cols = [
    "name",
    "team",
    "position",
    "prob_scores",
    "goal_expectation",
    "anytime_scorer_prob",
    "recent_goals_last3",
    "recent_sot_per90",
    "goal_rate",
    "shots_on_target_per90",
    "stat_GS",
    "stat_ST",
    "price_rank_team_position",
]

df[cols].sort_values("prob_scores", ascending=False).head(30)

,name,team,position,prob_scores,goal_expectation,anytime_scorer_prob,recent_goals_last3,recent_sot_per90,goal_rate,shots_on_target_per90,stat_GS,stat_ST,price_rank_team_position
47,Kylian Mbappé,France,FWD,1.033491,0.363478,0.4950,1.00,0.555556,0.926641,0.770270,1.000,1.000000,1.000000
5,Lionel Messi,Argentina,FWD,0.860019,0.277814,0.4167,0.50,0.381818,0.905660,0.713208,1.000,0.947368,1.000000
27,Harry Kane,England,FWD,0.787765,0.262876,0.3891,0.75,0.280936,0.639432,0.447602,0.750,0.631579,1.000000
39,Jude Bellingham,England,MID,0.605109,0.177818,0.2632,1.00,0.384880,0.699029,0.448544,0.750,0.578947,0.900000
71,Mikel Oyarzabal,Spain,FWD,0.601010,0.237498,0.3448,0.50,0.325581,0.511727,0.447761,0.500,0.526316,1.000000
48,Ousmane Dembélé,France,MID,0.494531,0.212874,0.2899,0.25,0.056225,0.649351,0.272727,0.625,0.315789,1.000000
69,Lamine Yamal,Spain,MID,0.414520,0.205607,0.2985,0.00,0.422642,0.148148,0.518519,0.125,0.526316,1.000000
6,Julián Alvarez,Argentina,FWD,0.365949,0.177809,0.2667,0.25,0.105263,0.146699,0.205379,0.125,0.210526,0.500000
60,Michael Olise,France,MID,0.319521,0.172781,0.2353,0.00,0.158491,0.000000,0.215164,0.000,0.263158,0.909091
89,Bradley Barcola,France,MID,0.232252,0.172781,0.2353,0.25,0.256098,0.425532,0.297872,0.250,0.210526,0.772727
85,Lautaro Martínez,Argentina,FWD,0.213110,0.177809,0.2667,0.25,0.114754,0.397351,0.208609,0.250,0.157895,0.750000
50,Désiré Doué,France,MID,0.198386,0.172781,0.2353,0.00,0.347107,0.187500,0.459375,0.125,0.368421,0.636364
19,Alexis Mac Allister,Argentina,MID,0.197504,0.070204,0.1053,0.25,0.084848,0.111317,0.116883,0.125,0.157895,0.909091
20,Enzo Fernández,Argentina,MID,0.197461,0.070204,0.1053,0.25,0.140000,0.125000,0.131250,0.125,0.157895,1.000000
79,Dani Olmo,Spain,MID,0.193406,0.125224,0.1818,0.00,0.057851,0.000000,0.061404,0.000,0.052632,0.727273
62,Álex Baena,Spain,MID,0.183973,0.125224,0.1818,0.00,0.208955,0.182927,0.256098,0.125,0.210526,0.181818
70,Ferran Torres,Spain,FWD,0.177881,0.199683,0.2899,0.00,0.000000,0.000000,0.200957,0.000,0.105263,0.750000
30,Anthony Gordon,England,MID,0.172070,0.120662,0.1786,0.00,0.073684,0.000000,0.192661,0.000,0.157895,0.450000
28,Bukayo Saka,England,MID,0.158537,0.125121,0.1852,0.00,0.173913,0.000000,0.235955,0.000,0.157895,1.000000
78,Rodri,Spain,MID,0.152602,0.083483,0.1212,0.00,0.000000,0.000000,0.000000,0.000,0.000000,0.636364
54,Adrien Rabiot,France,MID,0.150186,0.096634,0.1316,0.00,0.051852,0.000000,0.046667,0.000,0.052632,0.409091
80,Pedri,Spain,MID,0.145517,0.083483,0.1212,0.00,0.000000,0.000000,0.048951,0.000,0.052632,0.909091
0,Cristian Romero,Argentina,DEF,0.139928,0.074070,0.1111,0.25,0.044586,0.133038,0.046563,0.125,0.052632,1.000000
38,Declan Rice,England,MID,0.126513,0.077221,0.1143,0.00,0.000000,0.000000,0.054404,0.000,0.052632,0.450000
37,Elliot Anderson,England,MID,0.123996,0.065939,0.0976,0.00,0.000000,0.000000,0.039400,0.000,0.052632,0.300000
64,Pedro Porro,Spain,DEF,0.123870,0.065574,0.0952,0.25,0.051852,0.166667,0.116667,0.125,0.105263,0.875000
14,Rodrigo De Paul,Argentina,MID,0.118748,0.074070,0.1111,0.00,0.059574,0.000000,0.051597,0.000,0.052632,0.409091
13,Leandro Paredes,Argentina,MID,0.118251,0.080804,0.1212,0.00,0.059322,0.000000,0.062874,0.000,0.052632,0.181818
32,Noni Madueke,England,FWD,0.110527,0.102353,0.1515,0.00,0.000000,0.000000,0.072917,0.000,0.052632,0.250000
81,Lisandro Martínez,Argentina,DEF,0.104428,0.040402,0.0606,0.25,0.084848,0.117647,0.082353,0.125,0.105263,0.750000

In [63]:
prob_assists = (
    0.5 * df["chance_created_per90"]
  + 0.15 * df["team_score_2_prob"]
  + 0.1 * df["prob_scores"]
  + 0.1 * df["assist_rate"]
  + 0.15 * df["stat_AS"]
)

df["lambda_assist"] = -np.log(
    (1 - prob_assists).clip(lower=0.001)
)

df["expected_assists"] = df["lambda_assist"].clip(lower=0) * df["prob_plays_60min"]

In [64]:
df.loc[df["position"] == "GK", "expected_assists"] = df["expected_assists"] * 0.1
df.loc[df["position"] == "DEF", "expected_assists"] = df["expected_assists"] * 0.9

In [65]:
cols = [
    "name",
    "team",
    "position",
    "expected_assists",
    "assist_expectation",
    "assist_rate",
    "chance_created_per90",
    "team_score_2_prob",
    "recent_assists_last3",
    "prob_plays_60min",
    "stat_AS",
]

df[cols].sort_values("expected_assists", ascending=False).head(30)

,name,team,position,expected_assists,assist_expectation,assist_rate,chance_created_per90,team_score_2_prob,recent_assists_last3,prob_plays_60min,stat_AS
60,Michael Olise,France,MID,0.787642,0.677121,0.184426,0.625000,0.4762,0.666667,0.897238,1.0
5,Lionel Messi,Argentina,FWD,0.762537,0.679279,0.067925,0.690566,0.3846,0.666667,0.939772,0.4
48,Ousmane Dembélé,France,MID,0.421481,0.429136,0.077922,0.396104,0.4762,0.333333,0.862021,0.4
39,Jude Bellingham,England,MID,0.365948,0.354198,0.034951,0.355340,0.4049,0.000000,0.905626,0.2
47,Kylian Mbappé,France,FWD,0.364878,0.127581,0.104247,0.117761,0.4762,0.333333,0.897406,0.6
67,Marc Cucurella,Spain,DEF,0.340061,0.344400,0.100000,0.338889,0.4219,0.666667,0.901911,0.6
38,Declan Rice,England,MID,0.332624,0.472570,0.046632,0.474093,0.4049,0.000000,0.785850,0.2
30,Anthony Gordon,England,MID,0.321650,0.371890,0.165138,0.373089,0.4049,1.000000,0.693773,0.6
79,Dani Olmo,Spain,MID,0.310127,0.362526,0.105263,0.356725,0.4219,0.333333,0.770041,0.4
28,Bukayo Saka,England,MID,0.304432,0.455461,0.202247,0.456929,0.4049,0.333333,0.567316,0.6
32,Noni Madueke,England,FWD,0.268503,0.633375,0.000000,0.635417,0.4049,0.000000,0.544112,0.0
85,Lautaro Martínez,Argentina,FWD,0.252189,0.596056,0.059603,0.605960,0.3846,0.333333,0.465996,0.2
27,Harry Kane,England,FWD,0.239334,0.108000,0.031972,0.108348,0.4049,0.333333,0.930088,0.2
71,Mikel Oyarzabal,Spain,FWD,0.223981,0.132179,0.038380,0.130064,0.4219,0.000000,0.891084,0.2
19,Alexis Mac Allister,Argentina,MID,0.210459,0.111323,0.066790,0.113173,0.3846,0.333333,0.939439,0.4
54,Adrien Rabiot,France,MID,0.175623,0.146860,0.040000,0.135556,0.4762,0.000000,0.842181,0.2
88,Jules Koundé,France,DEF,0.173068,0.258152,0.000000,0.238281,0.4762,0.000000,0.868000,0.0
62,Álex Baena,Spain,MID,0.163083,0.189000,0.054878,0.185976,0.4219,0.333333,0.691256,0.2
37,Elliot Anderson,England,MID,0.162092,0.114079,0.033771,0.114447,0.4049,0.000000,0.906508,0.2
14,Rodrigo De Paul,Argentina,MID,0.159806,0.147428,0.044226,0.149877,0.3846,0.000000,0.810613,0.2
89,Bradley Barcola,France,MID,0.153588,0.234351,0.063830,0.216312,0.4762,0.000000,0.561818,0.2
81,Lisandro Martínez,Argentina,DEF,0.148404,0.117653,0.035294,0.119608,0.3846,0.333333,0.936360,0.2
59,Rayan Cherki,France,MID,0.143385,1.083393,0.000000,1.000000,0.4762,0.000000,0.166740,0.0
65,Aymeric Laporte,Spain,DEF,0.138189,0.115013,0.033395,0.113173,0.4219,0.000000,0.868398,0.2
8,Nico González,Argentina,MID,0.137075,0.329687,0.098901,0.335165,0.3846,0.000000,0.428761,0.2
50,Désiré Doué,France,MID,0.136811,0.206522,0.056250,0.190625,0.4762,0.333333,0.544428,0.2
70,Ferran Torres,Spain,FWD,0.135154,0.296612,0.086124,0.291866,0.4219,0.333333,0.437779,0.2
80,Pedri,Spain,MID,0.130506,0.144503,0.000000,0.142191,0.4219,0.000000,0.809270,0.0
42,Dayot Upamecano,France,DEF,0.121853,0.125641,0.000000,0.115970,0.4762,0.000000,0.907401,0.0
21,Nico O'Reilly,England,DEF,0.110921,0.133930,0.000000,0.134361,0.4049,0.000000,0.840173,0.0

In [66]:
position_yc_modifier = {
    "GK": 0.15,
    "FWD": 0.35,
    "DEF": 0.45,
    "MID": 0.55,
}

df["position_yc_modifier"] = df["position"].map(position_yc_modifier)

raw_yc = (
    0.4 * df["yc_per90"]
  + 0.25 * df["tackles_per90"]
  + 0.20 * df["opp_over_05_prob"]
  + 0.05 * df["rc_per90"]
  + 0.1 * df["position_yc_modifier"]
)

df["prob_yellow_card"] = raw_yc * df["prob_plays_60min"]

In [67]:
cols = [
    "name",
    "team",
    "position",
    "prob_yellow_card",
    "yc_per90",
    "stat_YC",
    "tackles_per90",
    "recent_tackles_per90",
    "opp_over_05_prob",
    "prob_plays_60min",
    "rc_per90",
]

df[cols].sort_values("prob_yellow_card", ascending=False).head(30)

,name,team,position,prob_yellow_card,yc_per90,stat_YC,tackles_per90,recent_tackles_per90,opp_over_05_prob,prob_plays_60min,rc_per90
78,Rodri,Spain,MID,0.275968,0.000000,0.0,0.212291,0.333333,1.000000,0.895788,0.0
80,Pedri,Spain,MID,0.245412,0.041958,0.5,0.125874,0.172249,1.000000,0.809270,0.0
69,Lamine Yamal,Spain,MID,0.241702,0.000000,0.0,0.118519,0.203774,1.000000,0.849180,0.0
68,Pau Cubarsí,Spain,DEF,0.238498,0.033333,0.5,0.033333,0.100000,1.000000,0.894366,0.0
65,Aymeric Laporte,Spain,DEF,0.236441,0.033395,0.5,0.055659,0.133829,1.000000,0.868398,0.0
67,Marc Cucurella,Spain,DEF,0.228484,0.000000,0.0,0.033333,0.033333,1.000000,0.901911,0.0
71,Mikel Oyarzabal,Spain,FWD,0.223655,0.000000,0.0,0.063966,0.104651,1.000000,0.891084,0.0
64,Pedro Porro,Spain,DEF,0.223623,0.000000,0.0,0.166667,0.233333,1.000000,0.780081,0.0
79,Dani Olmo,Spain,MID,0.216625,0.000000,0.0,0.105263,0.185950,1.000000,0.770041,0.0
62,Álex Baena,Spain,MID,0.213573,0.054878,0.5,0.128049,0.223881,1.000000,0.691256,0.0
75,Unai Simón,Spain,GK,0.190340,0.000000,0.0,0.000000,0.000000,1.000000,0.885303,0.0
60,Michael Olise,France,MID,0.138054,0.036885,0.5,0.086066,0.135849,0.312977,0.897238,0.0
42,Dayot Upamecano,France,DEF,0.133859,0.000000,0.0,0.159696,0.233333,0.312977,0.907401,0.0
19,Alexis Mac Allister,Argentina,MID,0.127688,0.000000,0.0,0.200371,0.272727,0.154135,0.939439,0.0
88,Jules Koundé,France,DEF,0.126451,0.000000,0.0,0.152344,0.142857,0.312977,0.868000,0.0
70,Ferran Torres,Spain,FWD,0.117959,0.086124,0.5,0.000000,0.000000,1.000000,0.437779,0.0
48,Ousmane Dembélé,France,MID,0.109766,0.000000,0.0,0.038961,0.036145,0.312977,0.862021,0.0
54,Adrien Rabiot,France,MID,0.107458,0.000000,0.0,0.040000,0.066667,0.312977,0.842181,0.0
56,Manu Koné,France,MID,0.106911,0.052786,0.5,0.140762,0.167702,0.312977,0.614781,0.0
81,Lisandro Martínez,Argentina,DEF,0.101295,0.000000,0.0,0.129412,0.218182,0.154135,0.936360,0.0
45,Lucas Digne,France,DEF,0.099915,0.000000,0.0,0.086207,0.174419,0.312977,0.773649,0.0
13,Leandro Paredes,Argentina,MID,0.098588,0.053892,0.5,0.089820,0.190678,0.154135,0.759312,0.0
0,Cristian Romero,Argentina,DEF,0.098051,0.000000,0.0,0.133038,0.200637,0.154135,0.898839,0.0
87,William Saliba,France,DEF,0.097494,0.000000,0.0,0.026667,0.033333,0.312977,0.853248,0.0
20,Enzo Fernández,Argentina,MID,0.097331,0.000000,0.0,0.087500,0.060000,0.154135,0.903705,0.0
39,Jude Bellingham,England,MID,0.096761,0.034951,0.5,0.151456,0.123711,0.000000,0.905626,0.0
89,Bradley Barcola,France,MID,0.092365,0.063830,0.5,0.085106,0.109756,0.312977,0.561818,0.0
2,Nahuel Molina,Argentina,DEF,0.092362,0.000000,0.0,0.151134,0.240458,0.154135,0.812974,0.0
37,Elliot Anderson,England,MID,0.090676,0.000000,0.0,0.180113,0.284211,0.000000,0.906508,0.0
47,Kylian Mbappé,France,FWD,0.090181,0.000000,0.0,0.011583,0.000000,0.312977,0.897406,0.0

In [68]:
raw_pw = (
    0.10 * df["stat_PW"]                    
  + 0.3 * df["anytime_scorer_prob"]      
  + 0.10 * df["chance_created_per90"]     
  + 0.2 * df["stat_CC"]                  # recent form in 
  + 0.2 * df["team_score_2_prob"]        # team expected to attack heavily
  + 0.10 * df["price"] # quality proxy
)

df["prob_pen_won"] = 0.4 * sigmoid((raw_pw - 0.65) * 5) * df["prob_plays_60min"]

In [69]:
cols = [
    "name",
    "team",
    "position",
    "prob_pen_won",
    "stat_PW",
    "anytime_scorer_prob",
    "assist_expectation",
    "chance_created_per90",
    "team_score_2_prob",
    "price_rank_team_position",
    "prob_plays_60min",
]

df[cols].sort_values("prob_pen_won", ascending=False).head(30)

,name,team,position,prob_pen_won,stat_PW,anytime_scorer_prob,assist_expectation,chance_created_per90,team_score_2_prob,price_rank_team_position,prob_plays_60min
5,Lionel Messi,Argentina,FWD,0.147839,0.0,0.4167,0.679279,0.690566,0.3846,1.000000,0.939772
47,Kylian Mbappé,France,FWD,0.110846,1.0,0.4950,0.127581,0.117761,0.4762,1.000000,0.897406
60,Michael Olise,France,MID,0.109278,0.0,0.2353,0.677121,0.625000,0.4762,0.909091,0.897238
48,Ousmane Dembélé,France,MID,0.083497,0.0,0.2899,0.429136,0.396104,0.4762,1.000000,0.862021
39,Jude Bellingham,England,MID,0.069046,0.0,0.2632,0.354198,0.355340,0.4049,0.900000,0.905626
27,Harry Kane,England,FWD,0.065644,0.0,0.3891,0.108000,0.108348,0.4049,1.000000,0.930088
85,Lautaro Martínez,Argentina,FWD,0.058062,1.0,0.2667,0.596056,0.605960,0.3846,0.750000,0.465996
67,Marc Cucurella,Spain,DEF,0.057427,0.0,0.0851,0.344400,0.338889,0.4219,0.625000,0.901911
30,Anthony Gordon,England,MID,0.056523,1.0,0.1786,0.371890,0.373089,0.4049,0.450000,0.693773
32,Noni Madueke,England,FWD,0.052796,1.0,0.1515,0.633375,0.635417,0.4049,0.250000,0.544112
71,Mikel Oyarzabal,Spain,FWD,0.052151,0.0,0.3448,0.132179,0.130064,0.4219,1.000000,0.891084
88,Jules Koundé,France,DEF,0.051509,0.0,0.0714,0.258152,0.238281,0.4762,1.000000,0.868000
38,Declan Rice,England,MID,0.046826,0.0,0.1143,0.472570,0.474093,0.4049,0.450000,0.785850
69,Lamine Yamal,Spain,MID,0.044955,0.0,0.2985,0.000000,0.000000,0.4219,1.000000,0.849180
79,Dani Olmo,Spain,MID,0.044509,0.0,0.1818,0.362526,0.356725,0.4219,0.727273,0.770041
42,Dayot Upamecano,France,DEF,0.043426,0.0,0.0800,0.125641,0.115970,0.4762,0.833333,0.907401
50,Désiré Doué,France,MID,0.042598,1.0,0.2353,0.206522,0.190625,0.4762,0.636364,0.544428
65,Aymeric Laporte,Spain,DEF,0.041791,0.0,0.0769,0.115013,0.113173,0.4219,0.875000,0.868398
28,Bukayo Saka,England,MID,0.039518,0.0,0.1852,0.455461,0.456929,0.4049,1.000000,0.567316
6,Julián Alvarez,Argentina,FWD,0.035832,0.0,0.2667,0.000000,0.000000,0.3846,0.500000,0.829565
10,Emiliano Martínez,Argentina,GK,0.035357,0.0,0.0606,0.000000,0.000000,0.3846,1.000000,0.947846
80,Pedri,Spain,MID,0.035240,0.0,0.1212,0.144503,0.142191,0.4219,0.909091,0.809270
51,Mike Maignan,France,GK,0.033348,0.0,0.0067,0.000000,0.000000,0.4762,1.000000,0.885303
54,Adrien Rabiot,France,MID,0.033323,0.0,0.1316,0.146860,0.135556,0.4762,0.409091,0.842181
19,Alexis Mac Allister,Argentina,MID,0.033285,0.0,0.1053,0.111323,0.113173,0.3846,0.909091,0.939439
81,Lisandro Martínez,Argentina,DEF,0.032669,0.0,0.0606,0.117653,0.119608,0.3846,0.750000,0.936360
21,Nico O'Reilly,England,DEF,0.032584,0.0,0.0976,0.133930,0.134361,0.4049,0.666667,0.840173
87,William Saliba,France,DEF,0.032335,0.0,0.0556,0.000000,0.000000,0.4762,0.833333,0.853248
37,Elliot Anderson,England,MID,0.032094,0.0,0.0976,0.114079,0.114447,0.4049,0.300000,0.906508
75,Unai Simón,Spain,GK,0.031743,0.0,0.0067,0.000000,0.000000,0.4219,0.833333,0.885303

In [70]:
raw_cs = (
    0.90 * df["team_cs_prob"]            # strongest signal
  + 0.05 * df["stat_CS"]               # tournament history
  + 0.05 * (1 - df["stat_GC"])         # fewer goals conceded is better
)

base_cs = sigmoid((raw_cs - 0.5) * 6)

df["prob_clean_sheet"] = base_cs * df["prob_plays_60min"]

df.loc[df["position"] == "FWD", "prob_clean_sheet"] = 0.0

In [71]:
cols = [
    "name",
    "team",
    "position",
    "prob_clean_sheet",
    "team_cs_prob",
    "prob_plays_60min",
    "stat_CS",
    "stat_GC",
    "minutes_rank_team_position",
    "tackles_per90",
]

df[cols].sort_values("prob_clean_sheet", ascending=False).head(30)

,name,team,position,prob_clean_sheet,team_cs_prob,prob_plays_60min,stat_CS,stat_GC,minutes_rank_team_position,tackles_per90
48,Ousmane Dembélé,France,MID,0.263663,0.3112,0.862021,0.833333,0.166667,0.909091,0.038961
42,Dayot Upamecano,France,DEF,0.258660,0.3112,0.907401,0.666667,0.333333,1.000000,0.159696
60,Michael Olise,France,MID,0.255763,0.3112,0.897238,0.666667,0.333333,1.000000,0.086066
51,Mike Maignan,France,GK,0.252361,0.3112,0.885303,0.666667,0.333333,1.000000,0.000000
87,William Saliba,France,DEF,0.252010,0.3112,0.853248,0.666667,0.166667,0.777778,0.026667
22,Marc Guéhi,England,DEF,0.250388,0.3333,0.897935,0.500000,0.666667,0.888889,0.000000
54,Adrien Rabiot,France,MID,0.248742,0.3112,0.842181,0.666667,0.166667,0.818182,0.040000
88,Jules Koundé,France,DEF,0.247428,0.3112,0.868000,0.666667,0.333333,0.888889,0.152344
19,Alexis Mac Allister,Argentina,MID,0.243844,0.3244,0.939439,0.500000,0.833333,1.000000,0.200371
45,Lucas Digne,France,DEF,0.236633,0.3112,0.773649,0.666667,0.000000,0.666667,0.086207
81,Lisandro Martínez,Argentina,DEF,0.234155,0.3244,0.936360,0.333333,0.833333,1.000000,0.129412
67,Marc Cucurella,Spain,DEF,0.231172,0.2657,0.901911,0.833333,0.166667,0.937500,0.033333
78,Rodri,Spain,MID,0.229602,0.2657,0.895788,0.833333,0.166667,1.000000,0.212291
68,Pau Cubarsí,Spain,DEF,0.229238,0.2657,0.894366,0.833333,0.166667,0.937500,0.033333
10,Emiliano Martínez,Argentina,GK,0.228252,0.3244,0.947846,0.333333,1.000000,1.000000,0.000000
33,Jordan Pickford,England,GK,0.227399,0.3333,0.910668,0.333333,1.000000,1.000000,0.000000
75,Unai Simón,Spain,GK,0.226915,0.2657,0.885303,0.833333,0.166667,1.000000,0.000000
37,Elliot Anderson,England,MID,0.226361,0.3333,0.906508,0.333333,1.000000,1.000000,0.180113
24,Ezri Konsa,England,DEF,0.226204,0.3333,0.905882,0.333333,1.000000,1.000000,0.033395
39,Jude Bellingham,England,MID,0.226140,0.3333,0.905626,0.333333,1.000000,0.900000,0.151456
20,Enzo Fernández,Argentina,MID,0.225989,0.3244,0.903705,0.333333,0.833333,0.909091,0.087500
0,Cristian Romero,Argentina,DEF,0.224772,0.3244,0.898839,0.333333,0.833333,0.875000,0.133038
80,Pedri,Spain,MID,0.223224,0.2657,0.809270,1.000000,0.000000,0.909091,0.125874
65,Aymeric Laporte,Spain,DEF,0.222582,0.2657,0.868398,0.833333,0.166667,0.750000,0.055659
14,Rodrigo De Paul,Argentina,MID,0.218288,0.3244,0.810613,0.333333,0.500000,0.818182,0.088452
69,Lamine Yamal,Spain,MID,0.217656,0.2657,0.849180,0.833333,0.166667,0.818182,0.118519
21,Nico O'Reilly,England,DEF,0.209796,0.3333,0.840173,0.333333,1.000000,0.777778,0.079295
2,Nahuel Molina,Argentina,DEF,0.203300,0.3244,0.812974,0.333333,0.833333,0.750000,0.151134
79,Dani Olmo,Spain,MID,0.197372,0.2657,0.770041,0.833333,0.166667,0.727273,0.105263
38,Declan Rice,England,MID,0.188963,0.3333,0.785850,0.166667,1.000000,0.800000,0.031088

In [72]:
position_rc_modifier = {
    "GK": 0.04,
    "FWD": 0.08,
    "DEF": 0.12,
    "MID": 0.14,
}

df["position_rc_modifier"] = df["position"].map(position_rc_modifier)

raw_rc = (
    0.10 * df["position_rc_modifier"]   # strongest prior
  + 0.25 * df["rc_per90"]              # direct history
  + 0.15 * df["tackles_per90"]         # physical involvement
  + 0.25 * df["prob_yellow_card"]      # disciplinary tendency
  + 0.25 * df["opp_over_05_prob"]      # more defending -> more challenges
)

df["prob_red_card"] = 0.1 * sigmoid((raw_rc - 0.5) * 5) * df["prob_plays_60min"]

In [73]:
cols = [
    "name",
    "team",
    "position",
    "prob_red_card",
    "position_rc_modifier",
    "rc_per90",
    "tackles_per90",
    "prob_yellow_card",
    "opp_over_05_prob",
    "prob_plays_any",
]

df[cols].sort_values("prob_red_card", ascending=False).head(30)

,name,team,position,prob_red_card,position_rc_modifier,rc_per90,tackles_per90,prob_yellow_card,opp_over_05_prob,prob_plays_any
78,Rodri,Spain,MID,0.030205,0.14,0.0,0.212291,0.275968,1.000000,0.850306
69,Lamine Yamal,Spain,MID,0.026527,0.14,0.0,0.118519,0.241702,1.000000,0.867872
68,Pau Cubarsí,Spain,DEF,0.026465,0.12,0.0,0.033333,0.238498,1.000000,0.849862
67,Marc Cucurella,Spain,DEF,0.026453,0.12,0.0,0.033333,0.228484,1.000000,0.877989
71,Mikel Oyarzabal,Spain,FWD,0.026079,0.08,0.0,0.063966,0.223655,1.000000,0.900628
65,Aymeric Laporte,Spain,DEF,0.025953,0.12,0.0,0.055659,0.236441,1.000000,0.859420
80,Pedri,Spain,MID,0.025457,0.14,0.0,0.125874,0.245412,1.000000,0.830091
64,Pedro Porro,Spain,DEF,0.024428,0.12,0.0,0.166667,0.223623,1.000000,0.789352
75,Unai Simón,Spain,GK,0.023948,0.04,0.0,0.000000,0.190340,1.000000,0.841212
79,Dani Olmo,Spain,MID,0.023378,0.14,0.0,0.105263,0.216625,1.000000,0.779370
62,Álex Baena,Spain,MID,0.021180,0.14,0.0,0.128049,0.213573,1.000000,0.678148
42,Dayot Upamecano,France,DEF,0.013301,0.12,0.0,0.159696,0.133859,0.312977,0.895974
60,Michael Olise,France,MID,0.012709,0.14,0.0,0.086066,0.138054,0.312977,0.893681
88,Jules Koundé,France,DEF,0.012564,0.12,0.0,0.152344,0.126451,0.312977,0.867318
19,Alexis Mac Allister,Argentina,MID,0.011934,0.14,0.0,0.200371,0.127688,0.154135,0.922397
48,Ousmane Dembélé,France,MID,0.011488,0.14,0.0,0.038961,0.109766,0.312977,0.871651
70,Ferran Torres,Spain,FWD,0.011243,0.08,0.0,0.000000,0.117959,1.000000,0.615416
47,Kylian Mbappé,France,FWD,0.011203,0.08,0.0,0.011583,0.090181,0.312977,0.905805
54,Adrien Rabiot,France,MID,0.011203,0.14,0.0,0.040000,0.107458,0.312977,0.774772
87,William Saliba,France,DEF,0.011035,0.12,0.0,0.026667,0.097494,0.312977,0.850340
81,Lisandro Martínez,Argentina,DEF,0.010931,0.12,0.0,0.129412,0.101295,0.154135,0.914217
51,Mike Maignan,France,GK,0.010526,0.04,0.0,0.000000,0.068695,0.312977,0.854118
0,Cristian Romero,Argentina,DEF,0.010481,0.12,0.0,0.133038,0.098051,0.154135,0.887905
45,Lucas Digne,France,DEF,0.010428,0.12,0.0,0.086207,0.099915,0.312977,0.737702
5,Lionel Messi,Argentina,FWD,0.010403,0.08,0.0,0.101887,0.085800,0.154135,0.930377
20,Enzo Fernández,Argentina,MID,0.010307,0.14,0.0,0.087500,0.097331,0.154135,0.897104
2,Nahuel Molina,Argentina,DEF,0.009534,0.12,0.0,0.151134,0.092362,0.154135,0.783157
37,Elliot Anderson,England,MID,0.009194,0.14,0.0,0.180113,0.090676,0.000000,0.837461
10,Emiliano Martínez,Argentina,GK,0.009177,0.04,0.0,0.000000,0.043437,0.154135,0.937027
14,Rodrigo De Paul,Argentina,MID,0.009150,0.14,0.0,0.088452,0.087498,0.154135,0.781318

In [74]:
position_og_modifier = {
    "GK": 0.05,
    "FWD": 0.02,
    "MID": 0.04,
    "DEF": 0.08,
}

df["position_og_modifier"] = df["position"].map(position_og_modifier)

raw_og = (
    0.4 * df["position_og_modifier"]
  + 0.5 * df["opp_over_05_prob"]
  + 0.10 * (1 - df["stat_GC"])
)

df["prob_own_goal"] = 0.03 * sigmoid((raw_og - 0.5) * 5) * df["prob_plays_60min"]

In [75]:
cols = [
    "name",
    "team",
    "position",
    "prob_own_goal",
    "position_og_modifier",
    "own_goal_rate",
    "opp_over_05_prob",
    "tackles_per90",
    "stat_GC",
    "prob_plays_any",
]

df[cols].sort_values("prob_own_goal", ascending=False).head(30)

,name,team,position,prob_own_goal,position_og_modifier,own_goal_rate,opp_over_05_prob,tackles_per90,stat_GC,prob_plays_any
67,Marc Cucurella,Spain,DEF,0.017325,0.08,0.0,1.000000,0.033333,0.166667,0.877989
68,Pau Cubarsí,Spain,DEF,0.017180,0.08,0.0,1.000000,0.033333,0.166667,0.849862
78,Rodri,Spain,MID,0.016707,0.04,0.0,1.000000,0.212291,0.166667,0.850306
65,Aymeric Laporte,Spain,DEF,0.016681,0.08,0.0,1.000000,0.055659,0.166667,0.859420
75,Unai Simón,Spain,GK,0.016636,0.05,0.0,1.000000,0.000000,0.166667,0.841212
71,Mikel Oyarzabal,Spain,FWD,0.016366,0.02,0.0,1.000000,0.063966,0.166667,0.900628
69,Lamine Yamal,Spain,MID,0.015837,0.04,0.0,1.000000,0.118519,0.166667,0.867872
80,Pedri,Spain,MID,0.015564,0.04,0.0,1.000000,0.125874,0.000000,0.830091
64,Pedro Porro,Spain,DEF,0.014985,0.08,0.0,1.000000,0.166667,0.166667,0.789352
79,Dani Olmo,Spain,MID,0.014361,0.04,0.0,1.000000,0.105263,0.166667,0.779370
62,Álex Baena,Spain,MID,0.012892,0.04,0.0,1.000000,0.128049,0.166667,0.678148
70,Ferran Torres,Spain,FWD,0.008298,0.02,0.0,1.000000,0.000000,0.000000,0.615416
87,William Saliba,France,DEF,0.006199,0.08,0.0,0.312977,0.026667,0.166667,0.850340
42,Dayot Upamecano,France,DEF,0.006185,0.08,0.0,0.312977,0.159696,0.333333,0.895974
45,Lucas Digne,France,DEF,0.005983,0.08,0.0,0.312977,0.086207,0.000000,0.737702
88,Jules Koundé,France,DEF,0.005916,0.08,0.0,0.312977,0.152344,0.333333,0.867318
48,Ousmane Dembélé,France,MID,0.005891,0.04,0.0,0.312977,0.038961,0.166667,0.871651
51,Mike Maignan,France,GK,0.005759,0.05,0.0,0.312977,0.000000,0.333333,0.854118
54,Adrien Rabiot,France,MID,0.005755,0.04,0.0,0.312977,0.040000,0.166667,0.774772
60,Michael Olise,France,MID,0.005746,0.04,0.0,0.312977,0.086066,0.333333,0.893681
98,Fabián Ruiz,Spain,MID,0.005700,0.04,0.0,1.000000,0.065934,0.166667,0.428494
47,Kylian Mbappé,France,FWD,0.005568,0.02,0.0,0.312977,0.011583,0.333333,0.905805
97,Mikel Merino,Spain,MID,0.004455,0.04,0.0,1.000000,0.088235,0.000000,0.372342
77,Marcos Llorente,Spain,DEF,0.004282,0.08,0.0,1.000000,0.200000,0.000000,0.420980
56,Manu Koné,France,MID,0.004201,0.04,0.0,0.312977,0.140762,0.166667,0.572686
89,Bradley Barcola,France,MID,0.003839,0.04,0.0,0.312977,0.085106,0.166667,0.658484
81,Lisandro Martínez,Argentina,DEF,0.003747,0.08,0.0,0.154135,0.129412,0.833333,0.914217
50,Désiré Doué,France,MID,0.003720,0.04,0.0,0.312977,0.112500,0.166667,0.642530
0,Cristian Romero,Argentina,DEF,0.003597,0.08,0.0,0.154135,0.133038,0.833333,0.887905
19,Alexis Mac Allister,Argentina,MID,0.003506,0.04,0.0,0.154135,0.200371,0.833333,0.922397

In [76]:
position_pc_modifier = {
    "GK": 0.08,
    "FWD": 0.01,
    "MID": 0.05,
    "DEF": 0.14,
}

df["position_pc_modifier"] = df["position"].map(position_pc_modifier)

raw_pc = (
    0.20 * df["position_pc_modifier"]
  + 0.15 * df["penalty_conceded_rate"]
  + 0.15 * df["tackles_per90"]
  + 0.35 * df["prob_yellow_card"]
  + 0.15 * df["opp_over_05_prob"]
)

df["prob_penalty_committed"] = 0.15 * sigmoid((raw_pc - 0.5) * 5) * df["prob_plays_60min"]

In [77]:
cols = [
    "name",
    "team",
    "position",
    "prob_penalty_committed",
    "position_pc_modifier",
    "penalty_conceded_rate",
    "tackles_per90",
    "prob_yellow_card",
    "opp_over_05_prob",
    "prob_plays_any",
]

df[cols].sort_values("prob_penalty_committed", ascending=False).head(30)

,name,team,position,prob_penalty_committed,position_pc_modifier,penalty_conceded_rate,tackles_per90,prob_yellow_card,opp_over_05_prob,prob_plays_any
78,Rodri,Spain,MID,0.034630,0.05,0.00000,0.212291,0.275968,1.000000,0.850306
68,Pau Cubarsí,Spain,DEF,0.031833,0.14,0.00000,0.033333,0.238498,1.000000,0.849862
67,Marc Cucurella,Spain,DEF,0.031674,0.14,0.00000,0.033333,0.228484,1.000000,0.877989
65,Aymeric Laporte,Spain,DEF,0.031219,0.14,0.00000,0.055659,0.236441,1.000000,0.859420
69,Lamine Yamal,Spain,MID,0.029754,0.05,0.00000,0.118519,0.241702,1.000000,0.867872
64,Pedro Porro,Spain,DEF,0.029362,0.14,0.00000,0.166667,0.223623,1.000000,0.789352
80,Pedri,Spain,MID,0.028618,0.05,0.00000,0.125874,0.245412,1.000000,0.830091
71,Mikel Oyarzabal,Spain,FWD,0.028612,0.01,0.00000,0.063966,0.223655,1.000000,0.900628
75,Unai Simón,Spain,GK,0.027624,0.08,0.00000,0.000000,0.190340,1.000000,0.841212
79,Dani Olmo,Spain,MID,0.025884,0.05,0.00000,0.105263,0.216625,1.000000,0.779370
62,Álex Baena,Spain,MID,0.023449,0.05,0.00000,0.128049,0.213573,1.000000,0.678148
42,Dayot Upamecano,France,DEF,0.019789,0.14,0.00000,0.159696,0.133859,0.312977,0.895974
88,Jules Koundé,France,DEF,0.018633,0.14,0.00000,0.152344,0.126451,0.312977,0.867318
19,Alexis Mac Allister,Argentina,MID,0.017388,0.05,0.00000,0.200371,0.127688,0.154135,0.922397
60,Michael Olise,France,MID,0.017372,0.05,0.00000,0.086066,0.138054,0.312977,0.893681
81,Lisandro Martínez,Argentina,DEF,0.017189,0.14,0.00000,0.129412,0.101295,0.154135,0.914217
0,Cristian Romero,Argentina,DEF,0.016457,0.14,0.00000,0.133038,0.098051,0.154135,0.887905
87,William Saliba,France,DEF,0.016157,0.14,0.00000,0.026667,0.097494,0.312977,0.850340
48,Ousmane Dembélé,France,MID,0.015496,0.05,0.00000,0.038961,0.109766,0.312977,0.871651
45,Lucas Digne,France,DEF,0.015287,0.14,0.00000,0.086207,0.099915,0.312977,0.737702
54,Adrien Rabiot,France,MID,0.015096,0.05,0.00000,0.040000,0.107458,0.312977,0.774772
51,Mike Maignan,France,GK,0.014945,0.08,0.00000,0.000000,0.068695,0.312977,0.854118
2,Nahuel Molina,Argentina,DEF,0.014933,0.14,0.00000,0.151134,0.092362,0.154135,0.783157
47,Kylian Mbappé,France,FWD,0.014833,0.01,0.00000,0.011583,0.090181,0.312977,0.905805
20,Enzo Fernández,Argentina,MID,0.014809,0.05,0.00000,0.087500,0.097331,0.154135,0.897104
5,Lionel Messi,Argentina,FWD,0.014736,0.01,0.00000,0.101887,0.085800,0.154135,0.930377
27,Harry Kane,England,FWD,0.014683,0.01,0.34103,0.031972,0.039987,0.000000,0.923055
37,Elliot Anderson,England,MID,0.014108,0.05,0.00000,0.180113,0.090676,0.000000,0.837461
39,Jude Bellingham,England,MID,0.013957,0.05,0.00000,0.151456,0.096761,0.000000,0.895923
10,Emiliano Martínez,Argentina,GK,0.013824,0.08,0.00000,0.000000,0.043437,0.154135,0.937027

In [78]:
df["lambda_opp"] = -np.log(df["team_cs_prob"].clip(lower=0.01))

df["prob_gc_0"] = np.exp(-df["lambda_opp"])
df["prob_gc_1"] = df["lambda_opp"] * np.exp(-df["lambda_opp"])
df["prob_gc_2"] = (df["lambda_opp"] ** 2 / 2) * np.exp(-df["lambda_opp"])
df["prob_gc_3"] = (df["lambda_opp"] ** 3 / 6) * np.exp(-df["lambda_opp"])
df["prob_gc_4plus"] = 1 - (
    df["prob_gc_0"]
    + df["prob_gc_1"]
    + df["prob_gc_2"]
    + df["prob_gc_3"]
)

# RAW expected goals conceded (true intensity)
df["expected_goals_conceded"] = df["lambda_opp"]

# Normalize ONLY as auxiliary feature (separate column)
scaler = MinMaxScaler()
df["expected_goals_conceded_norm"] = scaler.fit_transform(
    df[["expected_goals_conceded"]]
)

# Player exposure to goals conceded (correct)
df["expected_player_goals_conceded"] = (
    df["lambda_opp"] * df["prob_plays_60min"]
)

# GC penalty MUST use raw λ (correct Poisson expectation)
df["expected_gc_penalty"] = (
    -(df["lambda_opp"] - 1 + np.exp(-df["lambda_opp"]))
    * df["prob_plays_60min"]
)

df.loc[df["position"].isin(["MID", "FWD"]), [
    "expected_player_goals_conceded",
    "expected_gc_penalty"
]] = 0.0

In [79]:
cols = [
    "name",
    "team",
    "position",
    "prob_plays_60min",
    "team_cs_prob",
    "lambda_opp",
    "prob_gc_0",
    "prob_gc_1",
    "prob_gc_2",
    "prob_gc_3",
    "prob_gc_4plus",
    "expected_player_goals_conceded",
    "expected_gc_penalty",
]

df[df["position"].isin(["GK", "DEF"])][cols] \
    .sort_values("expected_gc_penalty") \
    .head(30)

,name,team,position,prob_plays_60min,team_cs_prob,lambda_opp,prob_gc_0,prob_gc_1,prob_gc_2,prob_gc_3,prob_gc_4plus,expected_player_goals_conceded,expected_gc_penalty
67,Marc Cucurella,Spain,DEF,0.901911,0.2657,1.325387,0.2657,0.352155,0.233371,0.103102,0.045671,1.195381,-0.533108
68,Pau Cubarsí,Spain,DEF,0.894366,0.2657,1.325387,0.2657,0.352155,0.233371,0.103102,0.045671,1.185382,-0.528649
75,Unai Simón,Spain,GK,0.885303,0.2657,1.325387,0.2657,0.352155,0.233371,0.103102,0.045671,1.173370,-0.523291
65,Aymeric Laporte,Spain,DEF,0.868398,0.2657,1.325387,0.2657,0.352155,0.233371,0.103102,0.045671,1.150963,-0.513299
64,Pedro Porro,Spain,DEF,0.780081,0.2657,1.325387,0.2657,0.352155,0.233371,0.103102,0.045671,1.033909,-0.461096
42,Dayot Upamecano,France,DEF,0.907401,0.3112,1.167319,0.3112,0.363270,0.212026,0.082501,0.031004,1.059227,-0.434209
10,Emiliano Martínez,Argentina,GK,0.947846,0.3244,1.125778,0.3244,0.365202,0.205568,0.077141,0.027688,1.067065,-0.426700
51,Mike Maignan,France,GK,0.885303,0.3112,1.167319,0.3112,0.363270,0.212026,0.082501,0.031004,1.033431,-0.423635
81,Lisandro Martínez,Argentina,DEF,0.936360,0.3244,1.125778,0.3244,0.365202,0.205568,0.077141,0.027688,1.054133,-0.421528
88,Jules Koundé,France,DEF,0.868000,0.3112,1.167319,0.3112,0.363270,0.212026,0.082501,0.031004,1.013234,-0.415355
87,William Saliba,France,DEF,0.853248,0.3112,1.167319,0.3112,0.363270,0.212026,0.082501,0.031004,0.996013,-0.408296
0,Cristian Romero,Argentina,DEF,0.898839,0.3244,1.125778,0.3244,0.365202,0.205568,0.077141,0.027688,1.011893,-0.404637
33,Jordan Pickford,England,GK,0.910668,0.3333,1.098712,0.3333,0.366201,0.201175,0.073678,0.025647,1.000562,-0.393420
24,Ezri Konsa,England,DEF,0.905882,0.3333,1.098712,0.3333,0.366201,0.201175,0.073678,0.025647,0.995304,-0.391352
22,Marc Guéhi,England,DEF,0.897935,0.3333,1.098712,0.3333,0.366201,0.201175,0.073678,0.025647,0.986572,-0.387919
45,Lucas Digne,France,DEF,0.773649,0.3112,1.167319,0.3112,0.363270,0.212026,0.082501,0.031004,0.903095,-0.370206
2,Nahuel Molina,Argentina,DEF,0.812974,0.3244,1.125778,0.3244,0.365202,0.205568,0.077141,0.027688,0.915229,-0.365983
21,Nico O'Reilly,England,DEF,0.840173,0.3333,1.098712,0.3333,0.366201,0.201175,0.073678,0.025647,0.923108,-0.362965
25,John Stones,England,DEF,0.546201,0.3333,1.098712,0.3333,0.366201,0.201175,0.073678,0.025647,0.600118,-0.235966
82,Facundo Medina,Argentina,DEF,0.408113,0.3244,1.125778,0.3244,0.365202,0.205568,0.077141,0.027688,0.459444,-0.183723
26,Djed Spence,England,DEF,0.402609,0.3333,1.098712,0.3333,0.366201,0.201175,0.073678,0.025647,0.442351,-0.173932
91,Reece James,England,DEF,0.332780,0.3333,1.098712,0.3333,0.366201,0.201175,0.073678,0.025647,0.365630,-0.143765
77,Marcos Llorente,Spain,DEF,0.216488,0.2657,1.325387,0.2657,0.352155,0.233371,0.103102,0.045671,0.286931,-0.127963
40,Theo Hernández,France,DEF,0.254379,0.3112,1.167319,0.3112,0.363270,0.212026,0.082501,0.031004,0.296941,-0.121725
83,Gonzalo Montiel,Argentina,DEF,0.200495,0.3244,1.125778,0.3244,0.365202,0.205568,0.077141,0.027688,0.225713,-0.090258
3,Nicolás Otamendi,Argentina,DEF,0.188370,0.3244,1.125778,0.3244,0.365202,0.205568,0.077141,0.027688,0.212063,-0.084800
74,David Raya,Spain,GK,0.134703,0.2657,1.325387,0.2657,0.352155,0.233371,0.103102,0.045671,0.178534,-0.079621
41,Maxence Lacroix,France,DEF,0.159538,0.3112,1.167319,0.3112,0.363270,0.212026,0.082501,0.031004,0.186232,-0.076342
96,Marc Pubill,Spain,DEF,0.124747,0.2657,1.325387,0.2657,0.352155,0.233371,0.103102,0.045671,0.165338,-0.073736
76,Joan García,Spain,GK,0.122389,0.2657,1.325387,0.2657,0.352155,0.233371,0.103102,0.045671,0.162213,-0.072343

In [80]:
raw_save = (
    0.35 * df["expected_goals_conceded_norm"]  # opportunity
  + 0.40 * df["saves_per90"]             # ability
  + 0.05 * df["recent_saves_per90"]      # recent form
  + 0.20 * df["price"]                   # overall GK quality
)

# Expected saves (λ)
df["expected_saves"] = (
    sigmoid((raw_save - 0.5) * 6) * 4
) * df["prob_plays_60min"]

df.loc[df["position"] != "GK", "expected_saves"] = 0.0

In [81]:
cols = [
    "name",
    "team",
    "expected_saves",
    "expected_goals_conceded",
    "saves_per90",
    "recent_saves_per90",
    "price",
    "expected_goals_conceded_norm",
]

df[df["position"] == "GK"][cols] \
    .sort_values("expected_saves", ascending=False) \
    .head(30)

,name,team,expected_saves,expected_goals_conceded,saves_per90,recent_saves_per90,price,expected_goals_conceded_norm
75,Unai Simón,Spain,3.088678,1.325387,0.615741,0.476190,1.000000,1.000000
51,Mike Maignan,France,2.536496,1.167319,0.791667,0.634921,1.000000,0.302667
33,Jordan Pickford,England,2.466074,1.098712,1.000000,1.000000,0.866667,0.000000
10,Emiliano Martínez,Argentina,2.125335,1.125778,0.633333,0.909091,1.000000,0.119403
74,David Raya,Spain,0.309517,1.325387,0.000000,0.000000,1.000000,1.000000
76,Joan García,Spain,0.184827,1.325387,0.000000,0.000000,0.333333,1.000000
52,Brice Samba,France,0.084701,1.167319,0.000000,0.000000,0.666667,0.302667
11,Gerónimo Rulli,Argentina,0.067155,1.125778,0.000000,0.000000,0.666667,0.119403
12,Juan Musso,Argentina,0.052970,1.125778,0.000000,0.000000,0.533333,0.119403
86,Robin Risser,France,0.046299,1.167319,0.000000,0.000000,0.000000,0.302667
34,Dean Henderson,England,0.039249,1.098712,0.000000,0.000000,0.466667,0.000000
35,James Trafford,England,0.037253,1.098712,0.000000,0.000000,0.333333,0.000000

In [82]:
raw_pen_save = (
    0.55 * df["price"]                    
  + 0.30 * df["expected_goals_conceded_norm"]
  + 0.15 * df["stat_PS"]
)

# Strong compression because penalty saves are exceptionally rare
df["prob_penalty_save"] = sigmoid((raw_pen_save - 0.5) * 3) / 20 * df["prob_plays_60min"]

df.loc[df["position"] != "GK", "prob_penalty_save"] = 0.0

In [83]:
cols = [
    "name",
    "team",
    "prob_penalty_save",
    "price",
    "expected_goals_conceded",
    "opp_over_05_prob",
    "prob_plays_60min",
    "stat_PS",
]

df[df["position"] == "GK"][cols] \
    .sort_values("prob_penalty_save", ascending=False) \
    .head(30)

,name,team,prob_penalty_save,price,expected_goals_conceded,opp_over_05_prob,prob_plays_60min,stat_PS
75,Unai Simón,Spain,0.032791,1.000000,1.325387,1.000000,0.885303,0.0
51,Mike Maignan,France,0.031218,1.000000,1.167319,0.312977,0.885303,1.0
10,Emiliano Martínez,Argentina,0.026730,1.000000,1.125778,0.154135,0.947846,0.0
33,Jordan Pickford,England,0.021970,0.866667,1.098712,0.000000,0.910668,0.0
74,David Raya,Spain,0.004989,1.000000,1.325387,1.000000,0.134703,0.0
76,Joan García,Spain,0.002983,0.333333,1.325387,1.000000,0.122389,0.0
11,Gerónimo Rulli,Argentina,0.002878,0.666667,1.125778,0.154135,0.134703,0.0
52,Brice Samba,France,0.002865,0.666667,1.167319,0.312977,0.122389,0.0
12,Juan Musso,Argentina,0.002292,0.533333,1.125778,0.154135,0.122389,0.0
34,Dean Henderson,England,0.001990,0.466667,1.098712,0.000000,0.122389,0.0
35,James Trafford,England,0.001878,0.333333,1.098712,0.000000,0.134703,0.0
86,Robin Risser,France,0.001526,0.000000,1.167319,0.312977,0.134703,0.0

In [84]:
raw_tackles = (
    0.50 * df["tackles_per90"]
  + 0.15 * df["recent_tackles_per90"]
  + 0.15 * df["expected_goals_conceded_norm"]
  + 0.20 * df["match_over_25_prob"]
)

df["lambda_tackles"] = -np.log(
    (1 - raw_tackles).clip(lower=0.001)
)

df["expected_tackles"] = (
    df["lambda_tackles"].clip(lower=0)
    * df["prob_plays_60min"] * 3
)

df.loc[df["position"] != "MID", "expected_tackles"] = 0.0

In [85]:
cols = [
    "name",
    "team",
    "expected_tackles",
    "tackles_per90",
    "recent_tackles_per90",
    "expected_goals_conceded",
    "match_over_25_prob",
    "price",
    "prob_plays_60min",
]

df[df["position"] == "MID"][cols] \
    .sort_values("expected_tackles", ascending=False) \
    .head(30)

,name,team,expected_tackles,tackles_per90,recent_tackles_per90,expected_goals_conceded,match_over_25_prob,price,prob_plays_60min
78,Rodri,Spain,1.404244,0.212291,0.333333,1.325387,0.5042,0.489796,0.895788
69,Lamine Yamal,Spain,1.061111,0.118519,0.203774,1.325387,0.5042,1.000000,0.849180
80,Pedri,Spain,1.007374,0.125874,0.172249,1.325387,0.5042,0.612245,0.809270
79,Dani Olmo,Spain,0.929861,0.105263,0.185950,1.325387,0.5042,0.530612,0.770041
62,Álex Baena,Spain,0.888394,0.128049,0.223881,1.325387,0.5042,0.183673,0.691256
19,Alexis Mac Allister,Argentina,0.792520,0.200371,0.272727,1.125778,0.4306,0.306122,0.939439
37,Elliot Anderson,England,0.671544,0.180113,0.284211,1.098712,0.4306,0.285714,0.906508
60,Michael Olise,France,0.633306,0.086066,0.135849,1.167319,0.5042,0.897959,0.897238
39,Jude Bellingham,England,0.540509,0.151456,0.123711,1.098712,0.4306,0.653061,0.905626
28,Bukayo Saka,England,0.525302,0.224719,0.447205,1.098712,0.4306,0.897959,0.567316
56,Manu Koné,France,0.510472,0.140762,0.167702,1.167319,0.5042,0.204082,0.614781
54,Adrien Rabiot,France,0.489837,0.040000,0.066667,1.167319,0.5042,0.265306,0.842181
48,Ousmane Dembélé,France,0.485422,0.038961,0.036145,1.167319,0.5042,1.000000,0.862021
50,Désiré Doué,France,0.463603,0.112500,0.297521,1.167319,0.5042,0.489796,0.544428
20,Enzo Fernández,Argentina,0.462321,0.087500,0.060000,1.125778,0.4306,0.489796,0.903705
13,Leandro Paredes,Argentina,0.445241,0.089820,0.190678,1.125778,0.4306,0.102041,0.759312
14,Rodrigo De Paul,Argentina,0.423264,0.088452,0.076596,1.125778,0.4306,0.163265,0.810613
89,Bradley Barcola,France,0.387210,0.085106,0.109756,1.167319,0.5042,0.591837,0.561818
58,Aurélien Tchouaméni,France,0.377216,0.311111,0.300000,1.167319,0.5042,0.285714,0.295254
30,Anthony Gordon,England,0.363908,0.091743,0.189474,1.098712,0.4306,0.387755,0.693773
98,Fabián Ruiz,Spain,0.334863,0.065934,0.147541,1.325387,0.5042,0.346939,0.305648
8,Nico González,Argentina,0.265782,0.098901,0.221311,1.125778,0.4306,0.102041,0.428761
38,Declan Rice,England,0.252756,0.031088,0.000000,1.098712,0.4306,0.387755,0.785850
57,Maghnes Akliouche,France,0.244716,0.857143,0.000000,1.167319,0.5042,0.265306,0.095381
97,Mikel Merino,Spain,0.242903,0.088235,0.000000,1.325387,0.5042,0.224490,0.231669
18,Thiago Almada,Argentina,0.228432,0.123457,0.000000,1.125778,0.4306,0.285714,0.420144
99,Gavi,Spain,0.205992,0.236842,0.000000,1.325387,0.5042,0.285714,0.148990
29,Marcus Rashford,England,0.137512,0.068182,0.147541,1.098712,0.4306,0.489796,0.298518
17,Exequiel Palacios,Argentina,0.131569,0.266667,0.000000,1.125778,0.4306,0.183673,0.161848
15,Nico Paz,Argentina,0.114853,0.253521,0.000000,1.125778,0.4306,0.163265,0.145904

In [86]:
raw_cc = (
    0.25 * df["recent_cc_per90"]
  + 0.25 * df["stat_CC"]
  + 0.25 * df["match_over_25_prob"]
  + 0.15 * df["anytime_scorer_prob"]
  + 0.10 * df["price"]
)

df["lambda_cc"] = -np.log(
    (1 - raw_cc).clip(lower=0.001)
)

df["expected_chances_created"] = (
    df["lambda_cc"].clip(lower=0)
    * df["prob_plays_60min"] * 2
)

df.loc[df["position"] != "MID", "expected_chances_created"] = 0.0

In [87]:
cols = [
    "name",
    "team",
    "position",
    "expected_chances_created",
    "cc_per90",
    "recent_cc_per90",
    "stat_CC",
    "match_over_25_prob",
    "anytime_scorer_prob",
    "price",
    "prob_plays_60min",
]

df[cols].sort_values("expected_chances_created", ascending=False).head(30)

,name,team,position,expected_chances_created,cc_per90,recent_cc_per90,stat_CC,match_over_25_prob,anytime_scorer_prob,price,prob_plays_60min
60,Michael Olise,France,MID,1.378714,0.625000,0.306918,0.833333,0.5042,0.2353,0.897959,0.897238
48,Ousmane Dembélé,France,MID,1.114828,0.396104,0.326640,0.500000,0.5042,0.2899,1.000000,0.862021
39,Jude Bellingham,England,MID,0.843698,0.355340,0.139748,0.500000,0.4306,0.2632,0.653061,0.905626
38,Declan Rice,England,MID,0.749668,0.474093,0.363095,0.500000,0.4306,0.1143,0.387755,0.785850
30,Anthony Gordon,England,MID,0.626998,0.373089,0.428070,0.333333,0.4306,0.1786,0.387755,0.693773
79,Dani Olmo,Spain,MID,0.620740,0.356725,0.168044,0.333333,0.5042,0.1818,0.530612,0.770041
69,Lamine Yamal,Spain,MID,0.536412,0.000000,0.000000,0.000000,0.5042,0.2985,1.000000,0.849180
28,Bukayo Saka,England,MID,0.527317,0.456929,0.252588,0.333333,0.4306,0.1852,0.897959,0.567316
80,Pedri,Spain,MID,0.459424,0.142191,0.000000,0.166667,0.5042,0.1212,0.612245,0.809270
50,Désiré Doué,France,MID,0.445879,0.190625,0.336088,0.166667,0.5042,0.2353,0.489796,0.544428
62,Álex Baena,Spain,MID,0.423652,0.185976,0.202322,0.166667,0.5042,0.1818,0.183673,0.691256
14,Rodrigo De Paul,Argentina,MID,0.414432,0.149877,0.173050,0.166667,0.4306,0.1111,0.163265,0.810613
19,Alexis Mac Allister,Argentina,MID,0.409244,0.113173,0.000000,0.166667,0.4306,0.1053,0.306122,0.939439
54,Adrien Rabiot,France,MID,0.405565,0.135556,0.000000,0.166667,0.5042,0.1316,0.265306,0.842181
37,Elliot Anderson,England,MID,0.387708,0.114447,0.000000,0.166667,0.4306,0.0976,0.285714,0.906508
78,Rodri,Spain,MID,0.384636,0.000000,0.000000,0.000000,0.5042,0.1212,0.489796,0.895788
20,Enzo Fernández,Argentina,MID,0.342062,0.000000,0.000000,0.000000,0.4306,0.1053,0.489796,0.903705
89,Bradley Barcola,France,MID,0.341671,0.216312,0.000000,0.166667,0.5042,0.2353,0.591837,0.561818
8,Nico González,Argentina,MID,0.265956,0.335165,0.333333,0.166667,0.4306,0.1587,0.102041,0.428761
13,Leandro Paredes,Argentina,MID,0.222056,0.000000,0.000000,0.000000,0.4306,0.1212,0.102041,0.759312
56,Manu Koné,France,MID,0.217681,0.000000,0.000000,0.000000,0.5042,0.1053,0.204082,0.614781
98,Fabián Ruiz,Spain,MID,0.155401,0.335165,0.000000,0.166667,0.5042,0.1471,0.346939,0.305648
18,Thiago Almada,Argentina,MID,0.150007,0.000000,0.000000,0.000000,0.4306,0.1818,0.285714,0.420144
29,Marcus Rashford,England,MID,0.125248,0.000000,0.000000,0.000000,0.4306,0.2174,0.489796,0.298518
97,Mikel Merino,Spain,MID,0.117427,0.448529,0.000000,0.166667,0.5042,0.2247,0.224490,0.231669
92,Eberechi Eze,England,MID,0.115155,0.000000,0.000000,0.000000,0.4306,0.2000,0.591837,0.262679
31,Morgan Rogers,England,MID,0.103264,0.388535,0.000000,0.166667,0.4306,0.2000,0.428571,0.205499
59,Rayan Cherki,France,MID,0.101403,1.000000,0.000000,0.166667,0.5042,0.2353,0.591837,0.166740
58,Aurélien Tchouaméni,France,MID,0.099891,0.000000,0.000000,0.000000,0.5042,0.0067,0.285714,0.295254
100,Nico Williams,Spain,MID,0.061191,0.000000,0.000000,0.000000,0.5042,0.2439,0.551020,0.124593

In [88]:
raw_sot = (
    0.35 * df["sot_per90"]
  + 0.15 * df["stat_GS"]
  + 0.20 * df["match_over_25_prob"]
  + 0.20 * df["anytime_scorer_prob"]
  + 0.10 * df["price"]
)

df["lambda_sot"] = -np.log(
    (1 - raw_sot).clip(lower=0.001)
)

df["expected_shots_on_target"] = (
    df["lambda_sot"].clip(lower=0)
    * df["prob_plays_60min"] * 2
)

df.loc[df["position"] != "FWD", "expected_shots_on_target"] = 0.0

In [89]:
cols = [
    "name",
    "team",
    "position",
    "expected_shots_on_target",
    "sot_per90",
    "goal_rate",
    "stat_GS",
    "match_over_25_prob",
    "anytime_scorer_prob",
    "price",
    "prob_plays_60min",
]

df[cols].sort_values("expected_shots_on_target", ascending=False).head(30)

,name,team,position,expected_shots_on_target,sot_per90,goal_rate,stat_GS,match_over_25_prob,anytime_scorer_prob,price,prob_plays_60min
47,Kylian Mbappé,France,FWD,2.281113,0.770270,0.926641,1.000,0.5042,0.4950,1.000000,0.897406
5,Lionel Messi,Argentina,FWD,2.035372,0.713208,0.905660,1.000,0.4306,0.4167,0.923077,0.939772
27,Harry Kane,England,FWD,1.416788,0.447602,0.639432,0.750,0.4306,0.3891,1.000000,0.930088
71,Mikel Oyarzabal,Spain,FWD,1.113372,0.447761,0.511727,0.500,0.5042,0.3448,0.630769,0.891084
6,Julián Alvarez,Argentina,FWD,0.593814,0.205379,0.146699,0.125,0.4306,0.2667,0.707692,0.829565
85,Lautaro Martínez,Argentina,FWD,0.364684,0.208609,0.397351,0.250,0.4306,0.2667,0.738462,0.465996
90,Jean-Philippe Mateta,France,FWD,0.355471,1.000000,0.000000,0.000,0.5042,0.2985,0.384615,0.223204
70,Ferran Torres,Spain,FWD,0.296936,0.200957,0.000000,0.000,0.5042,0.2899,0.584615,0.437779
32,Noni Madueke,England,FWD,0.208353,0.072917,0.000000,0.000,0.4306,0.1515,0.323077,0.544112
93,Ollie Watkins,England,FWD,0.080833,0.000000,0.000000,0.000,0.4306,0.3509,0.600000,0.165826
72,Borja Iglesias,Spain,FWD,0.073003,0.000000,0.000000,0.000,0.5042,0.3333,0.430769,0.154370
49,Marcus Thuram,France,FWD,0.067986,0.000000,0.000000,0.000,0.5042,0.2985,0.538462,0.140880
94,Ivan Toney,England,FWD,0.052165,0.000000,0.000000,0.000,0.4306,0.3509,0.538462,0.110563
9,José Manuel López,Argentina,FWD,0.042084,0.000000,0.000000,0.000,0.4306,0.2632,0.200000,0.121717
73,Víctor Muñoz,Spain,FWD,0.037482,0.000000,0.000000,0.000,0.5042,0.2247,0.000000,0.118941
3,Nicolás Otamendi,Argentina,DEF,0.000000,0.000000,0.000000,0.000,0.4306,0.0769,0.266667,0.188370
2,Nahuel Molina,Argentina,DEF,0.000000,0.000000,0.000000,0.000,0.4306,0.0606,0.266667,0.812974
10,Emiliano Martínez,Argentina,GK,0.000000,0.000000,0.000000,0.000,0.4306,0.0606,1.000000,0.947846
11,Gerónimo Rulli,Argentina,GK,0.000000,0.000000,0.000000,0.000,0.4306,0.0067,0.666667,0.134703
1,Marcos Senesi,Argentina,DEF,0.000000,0.000000,0.000000,0.000,0.4306,0.0976,0.466667,0.104098
0,Cristian Romero,Argentina,DEF,0.000000,0.046563,0.133038,0.125,0.4306,0.1111,0.600000,0.898839
21,Nico O'Reilly,England,DEF,0.000000,0.046256,0.000000,0.000,0.4306,0.0976,0.466667,0.840173
20,Enzo Fernández,Argentina,MID,0.000000,0.131250,0.125000,0.125,0.4306,0.1053,0.489796,0.903705
24,Ezri Konsa,England,DEF,0.000000,0.038961,0.000000,0.000,0.4306,0.0606,0.533333,0.905882
22,Marc Guéhi,England,DEF,0.000000,0.000000,0.000000,0.000,0.4306,0.0606,0.733333,0.897935
25,John Stones,England,DEF,0.000000,0.000000,0.000000,0.000,0.4306,0.0606,0.400000,0.546201
26,Djed Spence,England,DEF,0.000000,0.188341,0.000000,0.000,0.4306,0.0606,0.333333,0.402609
7,Giuliano Simeone,Argentina,MID,0.000000,0.000000,0.000000,0.000,0.4306,0.1923,0.102041,0.142206
8,Nico González,Argentina,MID,0.000000,0.000000,0.000000,0.000,0.4306,0.1587,0.102041,0.428761
14,Rodrigo De Paul,Argentina,MID,0.000000,0.051597,0.000000,0.000,0.4306,0.1111,0.163265,0.810613

In [90]:
df["expected_qualification_points"] = df["team_qualify_prob"] * 0

In [91]:
cols = [
    "name",
    "team",
    "position",
    "expected_qualification_points",
    "team_qualify_prob",
    "price",
    "prob_plays_60min",
]

df[cols].sort_values("team_qualify_prob", ascending=False).groupby("team").head(3).head(30)

,name,team,position,expected_qualification_points,team_qualify_prob,price,prob_plays_60min
44,Lucas Hernández,France,DEF,0.0,0.617284,0.800000,0.092233
42,Dayot Upamecano,France,DEF,0.0,0.617284,0.866667,0.907401
43,Ibrahima Konaté,France,DEF,0.0,0.617284,0.600000,0.113515
32,Noni Madueke,England,FWD,0.0,0.571429,0.323077,0.544112
25,John Stones,England,DEF,0.0,0.571429,0.400000,0.546201
26,Djed Spence,England,DEF,0.0,0.571429,0.333333,0.402609
6,Julián Alvarez,Argentina,FWD,0.0,0.549451,0.707692,0.829565
8,Nico González,Argentina,MID,0.0,0.549451,0.102041,0.428761
7,Giuliano Simeone,Argentina,MID,0.0,0.549451,0.102041,0.142206
69,Lamine Yamal,Spain,MID,0.0,0.505051,1.000000,0.849180
62,Álex Baena,Spain,MID,0.0,0.505051,0.183673,0.691256
61,Yéremy Pino,Spain,MID,0.0,0.505051,0.163265,0.120334

In [92]:
df.to_csv(OUT_CSV, index=False)

print(f"\nSaved {OUT_CSV} {df.shape[0]} rows x {df.shape[1]} cols")

Saved fantasy_enriched.csv 101 rows x 265 cols

In [93]:
BUDGET = 105.0
MAX_PER_COUNTRY = 6
SQUAD_SIZE = 15
XI_SIZE = 11
BENCH_WEIGHT = 0.9

def compute_total_expected_points(df):
    df = df.copy()

    cs_value = {"GK": 5, "DEF": 5, "MID": 1, "FWD": 0}
    goal_value = {"GK": 9, "DEF": 7, "MID": 6, "FWD": 5}

    df["goal_pts_value"] = df["position"].map(goal_value)
    df["cs_pts_value"] = df["position"].map(cs_value)

    # appearance: 1pt for playing any, +1 if 60+
    e_appearance = df["prob_plays_any"] * 1 + df["prob_plays_60min"] * 1

    # goal
    e_goal = df["prob_scores"] * df["goal_pts_value"]

    # assist
    e_assist = df["expected_assists"] * 3

    # clean sheet: gated by 60min, value depends on position
    e_cs = df["prob_clean_sheet"] * df["cs_pts_value"]

    # goals conceded penalty: GK and DEF only
    e_gc = df["expected_gc_penalty"].copy()
    e_gc[~df["position"].isin(["GK", "DEF"])] = 0.0

    # saves bonus: GK only, every 3 saves = +1
    e_saves = (df["expected_saves"] / 3).copy()
    e_saves[df["position"] != "GK"] = 0.0

    # penalty save: GK only
    e_pen_save = (df["prob_penalty_save"] * 3).copy()
    e_pen_save[df["position"] != "GK"] = 0.0

    # tackles bonus: MID only, every 3 tackles = +1
    e_tackles = (df["expected_tackles"] / 3).copy()
    e_tackles[df["position"] != "MID"] = 0.0

    # big chances created: MID only, every 2 = +1
    e_cc = (df["expected_chances_created"] / 2).copy()
    e_cc[df["position"] != "MID"] = 0.0

    # shots on target: FWD only, every 2 = +1
    e_sot = (df["expected_shots_on_target"] / 2).copy()
    e_sot[df["position"] != "FWD"] = 0.0

    # yellow card
    e_yc = df["prob_yellow_card"] * -1

    # red card
    e_rc = df["prob_red_card"] * -2

    # own goal
    e_og = df["prob_own_goal"] * -2

    # penalty won
    e_pw = df["prob_pen_won"] * 2

    # penalty committed
    e_pc = df["prob_penalty_committed"] * -1

    # qualification bonus: +2 per player in XI who advances, requires playing
    # captain's quali bonus is NOT doubled per rules
    e_quali = df["expected_qualification_points"] * df["prob_plays_any"]

    # scouting bonus: +2 if differential==1 AND player scores >4 base pts
    # model: use Poisson confidence interval on expected base points
    # base pts = everything except scouting and captain multiplier
    base_ep = (
        e_appearance + e_goal + e_assist + e_cs + e_gc +
        e_saves + e_pen_save + e_tackles + e_cc + e_sot +
        e_yc + e_rc + e_og + e_pw + e_pc + e_quali
    )

    # Poisson 90% CI: lower = ppf(0.05, mu), upper = ppf(0.95, mu)
    mu = base_ep.clip(lower=0.01)
    lower_ci = pd.Series(poisson.ppf(0.05, mu), index=df.index)
    upper_ci = pd.Series(poisson.ppf(0.95, mu), index=df.index)

    # if lower CI > 4: full +2 expected
    # if upper CI < 4: 0
    # if CI straddles 4: scale by P(X>4 | mu) * 2
    p_exceeds_4 = pd.Series(1 - poisson.cdf(4, mu), index=df.index)

    scouting_ep = pd.Series(0.0, index=df.index)
    eligible = df["differential"] == 1
    full_bonus = eligible & (lower_ci > 4)
    no_bonus = eligible & (upper_ci < 4)
    partial = eligible & ~full_bonus & ~no_bonus

    scouting_ep[full_bonus] = 2.0
    scouting_ep[no_bonus] = 0.0
    scouting_ep[partial] = p_exceeds_4[partial] * 2.0

    df["e_appearance"] = e_appearance
    df["e_goal"] = e_goal
    df["e_assist"] = e_assist
    df["e_cs"] = e_cs
    df["e_gc"] = e_gc
    df["e_saves"] = e_saves
    df["e_pen_save"] = e_pen_save
    df["e_tackles"] = e_tackles
    df["e_cc"] = e_cc
    df["e_sot"] = e_sot
    df["e_yc"] = e_yc
    df["e_rc"] = e_rc
    df["e_og"] = e_og
    df["e_pw"] = e_pw
    df["e_pc"] = e_pc
    df["e_quali"] = e_quali
    df["e_scouting"] = scouting_ep

    e_elim_risk = -1 * (1 - df["team_qualify_prob"])
    df["e_elim_risk"] = e_elim_risk

    df["expected_points"] = base_ep + scouting_ep + e_elim_risk

    return df

In [94]:

def optimize_squad(df, budget=BUDGET, max_per_country=MAX_PER_COUNTRY):
    idx = df.index.tolist()

    x = LpVariable.dicts("squad", idx, cat="Binary")
    s = LpVariable.dicts("xi", idx, cat="Binary")
    b = LpVariable.dicts("bench", idx, cat="Binary")    
    cap = LpVariable.dicts("cap", idx, cat="Binary")

    model = LpProblem("fantasy", LpMaximize)

    
    model += lpSum(
        df.loc[i, "expected_points"] * s[i]
        + df.loc[i, "expected_points"] * cap[i]
        + df.loc[i, "expected_points"] * BENCH_WEIGHT * b[i]
        for i in idx
    )

    # squad = 15, xi = 11, bench = 4
    model += lpSum(x[i] for i in idx) == 15
    model += lpSum(s[i] for i in idx) == 11
    model += lpSum(b[i] for i in idx) == 4

    for i in idx:
        model += s[i] + b[i] == x[i]

    # budget
    model += lpSum(df.loc[i, "price_raw"] * x[i] for i in idx) <= budget

    # squad composition: 2 GK, 5 DEF, 5 MID, 3 FWD
    for pos, count in [("GK", 2), ("DEF", 5), ("MID", 5), ("FWD", 3)]:
        p_idx = df[df["position"] == pos].index.tolist()
        model += lpSum(x[i] for i in p_idx) == count

    # country limit
    for country in df["team"].unique():
        c_idx = df[df["team"] == country].index.tolist()
        model += lpSum(x[i] for i in c_idx) <= max_per_country


    # max 2 GK+DEF combined from the same country
    for country in df["team"].unique():
        gkdef_idx = df[(df["team"] == country) & (df["position"].isin(["GK", "DEF"]))].index.tolist()
        model += lpSum(x[i] for i in gkdef_idx) <= 2

    # XI formation: 1 GK starts, valid outfield formation
    gk_idx = df[df["position"] == "GK"].index.tolist()
    model += lpSum(s[i] for i in gk_idx) == 1
    model += lpSum(b[i] for i in gk_idx) == 1

    for pos, lo, hi in [("DEF", 3, 5), ("MID", 3, 5), ("FWD", 1, 3)]:
        p_idx = df[df["position"] == pos].index.tolist()
        model += lpSum(s[i] for i in p_idx) >= lo
        model += lpSum(s[i] for i in p_idx) <= hi

    # captain: exactly 1, must be in XI
    model += lpSum(cap[i] for i in idx) == 1
    for i in idx:
        model += cap[i] <= s[i]

    model.solve(PULP_CBC_CMD(msg=0))

    if LpStatus[model.status] != "Optimal":
        print(f"Solver status: {LpStatus[model.status]}")
        return None

    in_squad = [i for i in idx if value(x[i]) > 0.5]
    in_xi = [i for i in idx if value(s[i]) > 0.5]
    on_bench = [i for i in idx if value(b[i]) > 0.5]
    captain = next(i for i in idx if value(cap[i]) > 0.5)

    return {
        "squad": df.loc[in_squad].copy(),
        "xi": df.loc[in_xi].copy(),
        "bench": df.loc[on_bench].copy(),
        "captain": captain,
        "total_ep": value(model.objective),
        "cost": df.loc[in_squad, "price_raw"].sum(),
    }

In [95]:
def optimize_ideal_xi(df, max_per_country=MAX_PER_COUNTRY):
    # best possible 11 ignoring bench constraint, just 11 players
    idx = df.index.tolist()

    s = LpVariable.dicts("xi", idx, cat="Binary")
    cap = LpVariable.dicts("cap", idx, cat="Binary")

    model = LpProblem("ideal_xi", LpMaximize)

    # optimize_ideal_xi objective — NO bench term
    model += lpSum(
        df.loc[i, "expected_points"] * s[i]
        + df.loc[i, "expected_points"] * cap[i]
        for i in idx
    )

    model += lpSum(s[i] for i in idx) == 11

    # no budget constraint for ideal XI comparison
    # country limit still applies
    for country in df["team"].unique():
        c_idx = df[df["team"] == country].index.tolist()
        model += lpSum(s[i] for i in c_idx) <= max_per_country

    gk_idx = df[df["position"] == "GK"].index.tolist()
    model += lpSum(s[i] for i in gk_idx) == 1

    for pos, lo, hi in [("DEF", 3, 5), ("MID", 3, 5), ("FWD", 1, 3)]:
        p_idx = df[df["position"] == pos].index.tolist()
        model += lpSum(s[i] for i in p_idx) >= lo
        model += lpSum(s[i] for i in p_idx) <= hi

    model += lpSum(cap[i] for i in idx) == 1
    for i in idx:
        model += cap[i] <= s[i]

    model.solve(PULP_CBC_CMD(msg=0))

    if LpStatus[model.status] != "Optimal":
        return None

    in_xi = [i for i in idx if value(s[i]) > 0.5]
    captain = next(i for i in idx if value(cap[i]) > 0.5)

    return {
        "xi": df.loc[in_xi].copy(),
        "captain": captain,
        "total_ep": value(model.objective),
    }


def print_team(result, ideal=None):
    pos_order = {"GK": 0, "DEF": 1, "MID": 2, "FWD": 3}
    cap = result["captain"]

    xi = result["xi"].copy()
    xi["_ord"] = xi["position"].map(pos_order)
    xi = xi.sort_values(["_ord", "expected_points"], ascending=[True, False])

    bench = result["bench"].copy()
    bench["_ord"] = bench["position"].map(pos_order)
    bench = bench.sort_values(["_ord", "expected_points"], ascending=[True, False])

    print(f"\nExpected points: {result['total_ep']:.2f}   Cost: ${result['cost']:.1f}M\n")

    print("Starting XI")
    for i, row in xi.iterrows():
        tag = " [C]" if i == cap else ""
        scout = " [SCOUT]" if row.get("differential", 0) == 1 else ""
        print(f"  {row['position']:3}  {row['name']:<28} {row['team']:<22} ${row['price_raw']:.1f}  EP:{row['expected_points']:.2f}{tag}{scout}")

    print("\nBench")
    for rank, (i, row) in enumerate(bench.iterrows(), 1):
        print(f"  [{rank}] {row['position']:3}  {row['name']:<28} {row['team']:<22} ${row['price_raw']:.1f}  EP:{row['expected_points']:.2f}")

    print(f"\nCountry breakdown: {dict(result['squad']['team'].value_counts())}")

    if ideal:
        ideal_xi = ideal["xi"].copy()
        ideal_xi["_ord"] = ideal_xi["position"].map(pos_order)
        ideal_xi = ideal_xi.sort_values(["_ord", "expected_points"], ascending=[True, False])
        ideal_cap = ideal["captain"]

        print(f"\nIdeal XI (no budget constraint, 11 only, EP: {ideal['total_ep']:.2f})")
        for i, row in ideal_xi.iterrows():
            tag = " [C]" if i == ideal_cap else ""
            in_squad = i in result["squad"].index
            flag = "" if in_squad else " [NOT IN SQUAD]"
            print(f"  {row['position']:3}  {row['name']:<28} {row['team']:<22} ${row['price_raw']:.1f}  EP:{row['expected_points']:.2f}{tag}{flag}")
            
if __name__ == "__main__":
    df = pd.read_csv("fantasy_enriched.csv")
    df = df[df["status"] == "playing"].copy()
    df = df.reset_index(drop=True)

    df = compute_total_expected_points(df)

    result = optimize_squad(df, budget=BUDGET, max_per_country=MAX_PER_COUNTRY)
    ideal = optimize_ideal_xi(df, max_per_country=MAX_PER_COUNTRY)

    print_team(result, ideal)

Expected points: 81.98   Cost: $105.0M

Starting XI
  GK   Mike Maignan                 France                 $5.0  EP:3.10
  DEF  Marc Cucurella               Spain                  $5.1  EP:3.36
  DEF  Lisandro Martínez            Argentina              $4.6  EP:3.24
  DEF  Cristian Romero              Argentina              $4.9  EP:3.22
  MID  Jude Bellingham              England                $8.3  EP:6.93
  MID  Michael Olise                France                 $9.5  EP:6.87
  MID  Ousmane Dembélé              France                 $10.0  EP:6.57
  MID  Dani Olmo                    Spain                  $7.7  EP:4.57 [SCOUT]
  FWD  Lionel Messi                 Argentina              $10.0  EP:9.19 [C]
  FWD  Kylian Mbappé                France                 $10.5  EP:8.91
  FWD  Mikel Oyarzabal              Spain                  $8.1  EP:5.30

Bench
  [1] GK   Jordan Pickford              England                $4.8  EP:3.02
  [2] DEF  Jules Koundé                 France                 $5.4  EP:3.18
  [3] DEF  Nico O'Reilly                England                $4.7  EP:2.83
  [4] MID  Adrien Rabiot                France                 $6.4  EP:3.76

Country breakdown: {'France': np.int64(6), 'Argentina': np.int64(3), 'England': np.int64(3), 'Spain': np.int64(3)}

Ideal XI (no budget constraint, 11 only, EP: 72.01)
  GK   Mike Maignan                 France                 $5.0  EP:3.10
  DEF  Marc Cucurella               Spain                  $5.1  EP:3.36
  DEF  Lisandro Martínez            Argentina              $4.6  EP:3.24
  DEF  Cristian Romero              Argentina              $4.9  EP:3.22
  MID  Jude Bellingham              England                $8.3  EP:6.93
  MID  Michael Olise                France                 $9.5  EP:6.87
  MID  Ousmane Dembélé              France                 $10.0  EP:6.57
  MID  Dani Olmo                    Spain                  $7.7  EP:4.57
  FWD  Lionel Messi                 Argentina              $10.0  EP:9.19 [C]
  FWD  Kylian Mbappé                France                 $10.5  EP:8.91
  FWD  Harry Kane                   England                $10.5  EP:6.85 [NOT IN SQUAD]

In [96]:
def optimize_with_transfers(df, current_team_names, free_transfers=5, budget=BUDGET, max_per_country=MAX_PER_COUNTRY):

    current_idx = set()
    unmatched = []
    for name in current_team_names:
        match = df[df["name"].str.lower().str.strip() == name.lower().strip()]
        if len(match) == 0:
            match = df[df["name"].str.lower().str.contains(name.lower().strip(), na=False)]
        if len(match) > 0:
            current_idx.add(match.index[0])
        else:
            unmatched.append(name)

  
    if unmatched:
        print(f"Eliminated players: {unmatched}")

    forced_transfers = len(unmatched)

    idx = df.index.tolist()

    x         = LpVariable.dicts("squad", idx, cat="Binary")
    s         = LpVariable.dicts("xi",    idx, cat="Binary")
    b         = LpVariable.dicts("bench", idx, cat="Binary")
    cap       = LpVariable.dicts("cap",   idx, cat="Binary")
    transfer_out = LpVariable.dicts("out", idx, cat="Binary")

    model = LpProblem("fantasy_transfers", LpMaximize)

    transfers_made = lpSum(transfer_out[i] for i in idx)   # voluntary drops only

    n_extra = LpVariable("n_extra", lowBound=0)

    # CHANGE 2: total transfers = voluntary + forced. Penalty fires when
    # (voluntary + forced) > free_transfers, not just voluntary > free_transfers.
    model += n_extra >= transfers_made + forced_transfers - free_transfers

    model += (
        lpSum(
            df.loc[i, "expected_points"] * s[i]
            + df.loc[i, "expected_points"] * cap[i]
            + df.loc[i, "expected_points"] * BENCH_WEIGHT * b[i]
            for i in idx
        )
        - 3 * n_extra
    )

    for i in idx:
        if i in current_idx:
            model += transfer_out[i] == 1 - x[i]
        else:
            model += transfer_out[i] == 0

    model += lpSum(x[i] for i in idx) == 15
    model += lpSum(s[i] for i in idx) == 11
    model += lpSum(b[i] for i in idx) == 4

    for i in idx:
        model += s[i] + b[i] == x[i]

    model += lpSum(df.loc[i, "price_raw"] * x[i] for i in idx) <= budget

    for pos, count in [("GK", 2), ("DEF", 5), ("MID", 5), ("FWD", 3)]:
        p_idx = df[df["position"] == pos].index.tolist()
        model += lpSum(x[i] for i in p_idx) == count

    for country in df["team"].unique():
        c_idx = df[df["team"] == country].index.tolist()
        model += lpSum(x[i] for i in c_idx) <= max_per_country

    gk_idx = df[df["position"] == "GK"].index.tolist()
    model += lpSum(s[i] for i in gk_idx) == 1
    model += lpSum(b[i] for i in gk_idx) == 1

    for pos, lo, hi in [("DEF", 3, 5), ("MID", 3, 5), ("FWD", 1, 3)]:
        p_idx = df[df["position"] == pos].index.tolist()
        model += lpSum(s[i] for i in p_idx) >= lo
        model += lpSum(s[i] for i in p_idx) <= hi

    model += lpSum(cap[i] for i in idx) == 1
    for i in idx:
        model += cap[i] <= s[i]

    model.solve(PULP_CBC_CMD(msg=0))

    if LpStatus[model.status] != "Optimal":
        print(f"Solver status: {LpStatus[model.status]}")
        return None

    in_squad  = [i for i in idx if value(x[i]) > 0.5]
    in_xi     = [i for i in idx if value(s[i]) > 0.5]
    on_bench  = [i for i in idx if value(b[i]) > 0.5]
    captain   = next(i for i in idx if value(cap[i]) > 0.5)

    new_squad_idx  = set(in_squad)
    voluntary_out  = [i for i in current_idx if i not in new_squad_idx]
    transfers_in   = [i for i in new_squad_idx if i not in current_idx]

    # CHANGE 3: total = voluntary drops of matched players + forced drops of eliminated.
    n_transfers = len(voluntary_out) + forced_transfers
    penalty     = max(0, n_transfers - free_transfers) * 3

    return {
        "squad":         df.loc[in_squad].copy(),
        "xi":            df.loc[in_xi].copy(),
        "bench":         df.loc[on_bench].copy(),
        "captain":       captain,
        "total_ep":      value(model.objective),
        "cost":          df.loc[in_squad, "price_raw"].sum(),
        "transfers_out": df.loc[voluntary_out, "name"].tolist() + unmatched,  # eliminated shown in OUT
        "transfers_in":  df.loc[transfers_in, "name"].tolist(),
        "n_transfers":   n_transfers,
        "penalty":       penalty,
        "forced_out":    unmatched,   # separate field for clarity
    }

def print_transfers(result):
    if result is None:
        print("No solution.")
        return

    print(f"\nTransfers made: {result['n_transfers']} ({result['n_transfers'] - 5} penalised at -3 each)" if result['n_transfers'] > 5 else f"\nTransfers made: {result['n_transfers']} (all free)")
    print(f"Point penalty: -{result['penalty']}")

    if result["transfers_out"]:
        print("\nOUT:")
        for name in result["transfers_out"]:
            print(f"  {name}")
        print("IN:")
        for name in result["transfers_in"]:
            print(f"  {name}")

    print_team(result)


if __name__ == "__main__":
    df = pd.read_csv("fantasy_enriched.csv")
    df = df[df["status"] == "playing"].copy()
    df = df.reset_index(drop=True)
    df = compute_total_expected_points(df)

    current_team = [
        "Emiliano Martínez", "Lisandro Martínez", "Achraf Hakimi", "Nico O'Reilly", "Marc Cucurella",
        "Ousmane Dembélé", "Michael Olise", "Unai Simón", "Jude Bellingham", "Kylian Mbappé", "Mikel Oyarzabal",
        "Dani Olmo", "Facundo Medina", "Lionel Messi", "Brahim Díaz"
    ]

    result = optimize_with_transfers(df, current_team, free_transfers=5, budget=BUDGET, max_per_country=MAX_PER_COUNTRY)
    ideal = optimize_ideal_xi(df, max_per_country=MAX_PER_COUNTRY)
    print_transfers(result)

    print("\nIdeal XI for comparison:")
    if ideal:
        pos_order = {"GK": 0, "DEF": 1, "MID": 2, "FWD": 3}
        xi = ideal["xi"].copy()
        xi["_ord"] = xi["position"].map(pos_order)
        xi = xi.sort_values(["_ord", "expected_points"], ascending=[True, False])
        cap = ideal["captain"]
        for i, row in xi.iterrows():
            tag = " [C]" if i == cap else ""
            in_squad = i in result["squad"].index if result else False
            flag = "" if in_squad else " [NOT IN SQUAD]"
            print(f"  {row['position']:3}  {row['name']:<28} {row['team']:<22} ${row['price_raw']:.1f}  EP:{row['expected_points']:.2f}{tag}{flag}")

Eliminated players: ['Achraf Hakimi', 'Brahim Díaz']

Transfers made: 5 (all free)
Point penalty: -0

OUT:
  Emiliano Martínez
  Unai Simón
  Facundo Medina
  Achraf Hakimi
  Brahim Díaz
IN:
  Cristian Romero
  Jordan Pickford
  Mike Maignan
  Adrien Rabiot
  Jules Koundé

Expected points: 81.98   Cost: $105.0M

Starting XI
  GK   Mike Maignan                 France                 $5.0  EP:3.10
  DEF  Marc Cucurella               Spain                  $5.1  EP:3.36
  DEF  Lisandro Martínez            Argentina              $4.6  EP:3.24
  DEF  Cristian Romero              Argentina              $4.9  EP:3.22
  MID  Jude Bellingham              England                $8.3  EP:6.93
  MID  Michael Olise                France                 $9.5  EP:6.87
  MID  Ousmane Dembélé              France                 $10.0  EP:6.57
  MID  Dani Olmo                    Spain                  $7.7  EP:4.57 [SCOUT]
  FWD  Lionel Messi                 Argentina              $10.0  EP:9.19 [C]
  FWD  Kylian Mbappé                France                 $10.5  EP:8.91
  FWD  Mikel Oyarzabal              Spain                  $8.1  EP:5.30

Bench
  [1] GK   Jordan Pickford              England                $4.8  EP:3.02
  [2] DEF  Jules Koundé                 France                 $5.4  EP:3.18
  [3] DEF  Nico O'Reilly                England                $4.7  EP:2.83
  [4] MID  Adrien Rabiot                France                 $6.4  EP:3.76

Country breakdown: {'France': np.int64(6), 'Argentina': np.int64(3), 'England': np.int64(3), 'Spain': np.int64(3)}

Ideal XI for comparison:
  GK   Mike Maignan                 France                 $5.0  EP:3.10
  DEF  Marc Cucurella               Spain                  $5.1  EP:3.36
  DEF  Lisandro Martínez            Argentina              $4.6  EP:3.24
  DEF  Cristian Romero              Argentina              $4.9  EP:3.22
  MID  Jude Bellingham              England                $8.3  EP:6.93
  MID  Michael Olise                France                 $9.5  EP:6.87
  MID  Ousmane Dembélé              France                 $10.0  EP:6.57
  MID  Dani Olmo                    Spain                  $7.7  EP:4.57
  FWD  Lionel Messi                 Argentina              $10.0  EP:9.19 [C]
  FWD  Kylian Mbappé                France                 $10.5  EP:8.91
  FWD  Harry Kane                   England                $10.5  EP:6.85 [NOT IN SQUAD]

In [97]:
def optimize_with_transfers(df, current_team_names, free_transfers=5, budget=BUDGET, max_per_country=MAX_PER_COUNTRY):

    current_idx = set()
    unmatched = []
    for name in current_team_names:
        match = df[df["name"].str.lower().str.strip() == name.lower().strip()]
        if len(match) == 0:
            match = df[df["name"].str.lower().str.contains(name.lower().strip(), na=False)]
        if len(match) > 0:
            current_idx.add(match.index[0])
        else:
            unmatched.append(name)

  
    if unmatched:
        print(f"Eliminated players: {unmatched}")

    forced_transfers = len(unmatched)

    idx = df.index.tolist()

    x         = LpVariable.dicts("squad", idx, cat="Binary")
    s         = LpVariable.dicts("xi",    idx, cat="Binary")
    b         = LpVariable.dicts("bench", idx, cat="Binary")
    cap       = LpVariable.dicts("cap",   idx, cat="Binary")
    transfer_out = LpVariable.dicts("out", idx, cat="Binary")

    model = LpProblem("fantasy_transfers", LpMaximize)

    transfers_made = lpSum(transfer_out[i] for i in idx)   # voluntary drops only

    n_extra = LpVariable("n_extra", lowBound=0)

    # CHANGE 2: total transfers = voluntary + forced. Penalty fires when
    # (voluntary + forced) > free_transfers, not just voluntary > free_transfers.
    model += n_extra >= transfers_made + forced_transfers - free_transfers

    model += (
        lpSum(
            df.loc[i, "expected_points"] * s[i]
            + df.loc[i, "expected_points"] * cap[i]
            + df.loc[i, "expected_points"] * BENCH_WEIGHT * b[i]
            for i in idx
        )
        - 3 * n_extra
    )

    for i in idx:
        if i in current_idx:
            model += transfer_out[i] == 1 - x[i]
        else:
            model += transfer_out[i] == 0

    model += lpSum(x[i] for i in idx) == 15
    model += lpSum(s[i] for i in idx) == 11
    model += lpSum(b[i] for i in idx) == 4

    for i in idx:
        model += s[i] + b[i] == x[i]

    model += lpSum(df.loc[i, "price_raw"] * x[i] for i in idx) <= budget

    for pos, count in [("GK", 2), ("DEF", 5), ("MID", 5), ("FWD", 3)]:
        p_idx = df[df["position"] == pos].index.tolist()
        model += lpSum(x[i] for i in p_idx) == count

    for country in df["team"].unique():
        c_idx = df[df["team"] == country].index.tolist()
        model += lpSum(x[i] for i in c_idx) <= max_per_country

    gk_idx = df[df["position"] == "GK"].index.tolist()
    model += lpSum(s[i] for i in gk_idx) == 1
    model += lpSum(b[i] for i in gk_idx) == 1

    for pos, lo, hi in [("DEF", 3, 5), ("MID", 3, 5), ("FWD", 1, 3)]:
        p_idx = df[df["position"] == pos].index.tolist()
        model += lpSum(s[i] for i in p_idx) >= lo
        model += lpSum(s[i] for i in p_idx) <= hi

    model += lpSum(cap[i] for i in idx) == 1
    for i in idx:
        model += cap[i] <= s[i]

    model.solve(PULP_CBC_CMD(msg=0))

    if LpStatus[model.status] != "Optimal":
        print(f"Solver status: {LpStatus[model.status]}")
        return None

    in_squad  = [i for i in idx if value(x[i]) > 0.5]
    in_xi     = [i for i in idx if value(s[i]) > 0.5]
    on_bench  = [i for i in idx if value(b[i]) > 0.5]
    captain   = next(i for i in idx if value(cap[i]) > 0.5)

    new_squad_idx  = set(in_squad)
    voluntary_out  = [i for i in current_idx if i not in new_squad_idx]
    transfers_in   = [i for i in new_squad_idx if i not in current_idx]

    # CHANGE 3: total = voluntary drops of matched players + forced drops of eliminated.
    n_transfers = len(voluntary_out) + forced_transfers
    penalty     = max(0, n_transfers - free_transfers) * 3

    return {
        "squad":         df.loc[in_squad].copy(),
        "xi":            df.loc[in_xi].copy(),
        "bench":         df.loc[on_bench].copy(),
        "captain":       captain,
        "total_ep":      value(model.objective),
        "cost":          df.loc[in_squad, "price_raw"].sum(),
        "transfers_out": df.loc[voluntary_out, "name"].tolist() + unmatched,  # eliminated shown in OUT
        "transfers_in":  df.loc[transfers_in, "name"].tolist(),
        "n_transfers":   n_transfers,
        "penalty":       penalty,
        "forced_out":    unmatched,   # separate field for clarity
    }

def print_transfers(result):
    if result is None:
        print("No solution.")
        return

    print(f"\nTransfers made: {result['n_transfers']} ({result['n_transfers'] - 5} penalised at -3 each)" if result['n_transfers'] > 5 else f"\nTransfers made: {result['n_transfers']} (all free)")
    print(f"Point penalty: -{result['penalty']}")

    if result["transfers_out"]:
        print("\nOUT:")
        for name in result["transfers_out"]:
            print(f"  {name}")
        print("IN:")
        for name in result["transfers_in"]:
            print(f"  {name}")

    print_team(result)


if __name__ == "__main__":
    df = pd.read_csv("fantasy_enriched.csv")
    df = df[df["status"] == "playing"].copy()
    df = df.reset_index(drop=True)
    df = compute_total_expected_points(df)

    current_team = [
        "Mike Maignan", "Lisandro Martínez", "Dayot Upamecano", "Nico O'Reilly", "Marc Cucurella",
        "Ousmane Dembélé", "Michael Olise", "Jude Bellingham", "Harry Kane", "Kylian Mbappé", "Álex Baena",
        "Unai Simón", "Cristian Romero", "Lionel Messi", "Patrick Berg"
    ]

    result = optimize_with_transfers(df, current_team, free_transfers=5, budget=BUDGET, max_per_country=MAX_PER_COUNTRY)
    ideal = optimize_ideal_xi(df, max_per_country=MAX_PER_COUNTRY)
    print_transfers(result)

Eliminated players: ['Patrick Berg']

Transfers made: 5 (all free)
Point penalty: -0

OUT:
  Dayot Upamecano
  Unai Simón
  Harry Kane
  Álex Baena
  Patrick Berg
IN:
  Jordan Pickford
  Mikel Oyarzabal
  Dani Olmo
  Adrien Rabiot
  Jules Koundé

Expected points: 81.98   Cost: $105.0M

Starting XI
  GK   Mike Maignan                 France                 $5.0  EP:3.10
  DEF  Marc Cucurella               Spain                  $5.1  EP:3.36
  DEF  Lisandro Martínez            Argentina              $4.6  EP:3.24
  DEF  Cristian Romero              Argentina              $4.9  EP:3.22
  MID  Jude Bellingham              England                $8.3  EP:6.93
  MID  Michael Olise                France                 $9.5  EP:6.87
  MID  Ousmane Dembélé              France                 $10.0  EP:6.57
  MID  Dani Olmo                    Spain                  $7.7  EP:4.57 [SCOUT]
  FWD  Lionel Messi                 Argentina              $10.0  EP:9.19 [C]
  FWD  Kylian Mbappé                France                 $10.5  EP:8.91
  FWD  Mikel Oyarzabal              Spain                  $8.1  EP:5.30

Bench
  [1] GK   Jordan Pickford              England                $4.8  EP:3.02
  [2] DEF  Jules Koundé                 France                 $5.4  EP:3.18
  [3] DEF  Nico O'Reilly                England                $4.7  EP:2.83
  [4] MID  Adrien Rabiot                France                 $6.4  EP:3.76

Country breakdown: {'France': np.int64(6), 'Argentina': np.int64(3), 'England': np.int64(3), 'Spain': np.int64(3)}

In [98]:
for pos in ["GK", "DEF", "MID", "FWD"]:
    print(f"\n-{pos}")
    print(df[df["position"] == pos].nlargest(10, "expected_points")[["name", "team", "price_raw", "expected_points"]].to_string(index=False))

-GK
             name      team  price_raw  expected_points
     Mike Maignan    France        5.0         3.104193
  Jordan Pickford   England        4.8         3.020973
Emiliano Martínez Argentina        5.0         2.942820
       Unai Simón     Spain        5.0         2.752497
   Gerónimo Rulli Argentina        4.5         0.106061
     Robin Risser    France        3.5         0.105903
      Brice Samba    France        4.5         0.099335
   James Trafford   England        4.0         0.091290
       David Raya     Spain        5.0         0.079971
   Dean Henderson   England        4.2         0.064162

-DEF
             name      team  price_raw  expected_points
   Marc Cucurella     Spain        5.1         3.361844
Lisandro Martínez Argentina        4.6         3.242980
  Cristian Romero Argentina        4.9         3.223169
     Jules Koundé    France        5.4         3.184782
  Dayot Upamecano    France        5.3         3.183290
       Marc Guéhi   England        5.1         2.844738
    Nico O'Reilly   England        4.7         2.827130
   William Saliba    France        5.3         2.750684
       Ezri Konsa   England        4.8         2.717396
  Aymeric Laporte     Spain        5.5         2.597344

-MID
               name      team  price_raw  expected_points
    Jude Bellingham   England        8.3         6.934430
      Michael Olise    France        9.5         6.870696
    Ousmane Dembélé    France       10.0         6.572444
          Dani Olmo     Spain        7.7         4.565600
       Lamine Yamal     Spain       10.0         4.564367
Alexis Mac Allister Argentina        6.6         3.830937
      Adrien Rabiot    France        6.4         3.762840
    Elliot Anderson   England        6.5         3.696191
     Anthony Gordon   England        7.0         3.627185
        Declan Rice   England        7.0         3.516398

-FWD
                name      team  price_raw  expected_points
        Lionel Messi Argentina       10.0         9.192555
       Kylian Mbappé    France       10.5         8.906275
          Harry Kane   England       10.5         6.846348
     Mikel Oyarzabal     Spain        8.1         5.297588
      Julián Alvarez Argentina        8.6         3.525949
    Lautaro Martínez Argentina        8.8         3.055234
        Noni Madueke   England        6.1         2.496431
       Ferran Torres     Spain        7.8         2.069327
Jean-Philippe Mateta    France        6.5         0.883951
       Ollie Watkins   England        7.9         0.600703

In [99]:
player1 = "Harry Kane"
player2 = "Mikel Oyarzabal"

cols = [
    "name", "team", "position", "price_raw", "expected_points",
    "e_appearance", "e_goal", "e_assist", "e_cs", "e_gc",
    "e_saves", "e_pen_save", "e_tackles", "e_cc", "e_sot",
    "e_yc", "e_rc", "e_og", "e_pw", "e_pc",
    "e_quali", "e_scouting"
]

comparison = df.loc[
    df["name"].isin([player1, player2]),
    cols
].set_index("name").T

print(comparison)

name            Harry Kane Mikel Oyarzabal
team               England           Spain
position               FWD             FWD
price_raw             10.5             8.1
expected_points   6.846348        5.297588
e_appearance      1.853143        1.791713
e_goal            3.938824        3.005051
e_assist          0.718003        0.671943
e_cs                   0.0             0.0
e_gc                   0.0             0.0
e_saves                0.0             0.0
e_pen_save             0.0             0.0
e_tackles              0.0             0.0
e_cc                   0.0             0.0
e_sot             0.708394        0.556686
e_yc             -0.039987       -0.223655
e_rc             -0.015671       -0.052159
e_og             -0.004392       -0.032733
e_pw              0.131289        0.104302
e_pc             -0.014683       -0.028612
e_quali                0.0             0.0
e_scouting             0.0             0.0