In [43]:
!jupyter nbconvert --to notebook --execute preprocess.ipynb --inplace

[NbConvertApp] Converting notebook preprocess.ipynb to notebook
[NbConvertApp] Writing 118580 bytes to preprocess.ipynb

In [44]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from pulp import *
from scipy.stats import poisson, norm
from pulp import LpProblem, LpMaximize, LpVariable, LpStatus, lpSum, value, PULP_CBC_CMD

In [45]:
OUT_CSV = "fantasy_enriched.csv"


| Position        | Point Source         | Points | Description                                                                 |
| --------------- | -------------------- | -----: | --------------------------------------------------------------------------- |
| **All Players** | Appearance (<60 min) |     +1 | Plays any minutes up to 59:59                                               |
| **All Players** | Appearance (60+ min) |     +1 | Additional point for reaching 60+ minutes (total appearance = **2 points**) |
| **All Players** | Assist               |     +3 | Provides an assist                                                          |
| **All Players** | Yellow Card          |     -1 | Receives a yellow card                                                      |
| **All Players** | Red Card             |     -2 | Receives a red card                                                         |
| **All Players** | Own Goal             |     -2 | Scores an own goal                                                          |
| **All Players** | Winning a Penalty    |     +2 | Wins a penalty for their team                                               |
| **All Players** | Conceding a Penalty  |     -1 | Commits a foul leading to a penalty                                         |

| Position       | Point Source                  | Points | Description                                        |
| -------------- | ----------------------------- | -----: | -------------------------------------------------- |
| **Goalkeeper** | Clean Sheet                   |     +5 | Plays 60+ minutes and team keeps a clean sheet     |
| **Goalkeeper** | First Goal Conceded           |      0 | No deduction for conceding the first goal          |
| **Goalkeeper** | Each Additional Goal Conceded |     -1 | Every goal conceded after the first                |
| **Goalkeeper** | Goal Scored                   |     +9 | Scores a goal                                      |
| **Goalkeeper** | Penalty Save                  |     +3 | Saves a penalty during normal play (not shootouts) |
| **Goalkeeper** | Every 3 Saves                 |     +1 | Earns 1 point for every 3 saves                    |

| Position     | Point Source                  | Points | Description                                    |
| ------------ | ----------------------------- | -----: | ---------------------------------------------- |
| **Defender** | Clean Sheet                   |     +5 | Plays 60+ minutes and team keeps a clean sheet |
| **Defender** | First Goal Conceded           |      0 | No deduction for conceding the first goal      |
| **Defender** | Each Additional Goal Conceded |     -1 | Every goal conceded after the first            |
| **Defender** | Goal Scored                   |     +7 | Scores a goal                                  |

| Position       | Point Source                | Points | Description                                    |
| -------------- | --------------------------- | -----: | ---------------------------------------------- |
| **Midfielder** | Clean Sheet                 |     +1 | Plays 60+ minutes and team keeps a clean sheet |
| **Midfielder** | Goal Scored                 |     +6 | Scores a goal                                  |
| **Midfielder** | Every 3 Tackles             |     +1 | Earns 1 point for every 3 tackles              |
| **Midfielder** | Every 2 Big Chances Created |     +1 | Earns 1 point for every 2 big chances created  |

| Position    | Point Source            | Points | Description                               |
| ----------- | ----------------------- | -----: | ----------------------------------------- |
| **Forward** | Goal Scored             |     +5 | Scores a goal                             |
| **Forward** | Every 2 Shots on Target |     +1 | Earns 1 point for every 2 shots on target |

| Position                | Point Source          | Points | Description                                                                                                                                                                        |
| ----------------------- | --------------------- | -----: | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **Bonus (All Players)** | Direct Free-Kick Goal |     +1 | Additional bonus for scoring directly from a free kick (on top of goal points)                                                                                                     |
| **Bonus (All Players)** | Scouting Bonus        |     +2 | Scores **more than 4 base fantasy points** in a match **and** is selected by **<5%** of fantasy teams. Captaincy and booster points do **not** count toward the 4-point threshold. |


## Core identity / player info

| Column | Type | Description |
|---|---|---|
| `fifa_id` | int | Unique FIFA fantasy player ID |
| `name` | str | Player name |
| `squad_id` | int | Internal squad/nation ID |
| `team` | str | National team |
| `position` | str | DEF / MID / FWD / GK |
| `price` | float | Fantasy price |
| `status` | str | Availability status |
| `total_points` | int | Total tournament points |
| `avg_points` | float | Average points per match |
| `matches_played` | int | Matches with participation |
| `percent_selected` | float | Selection rate (%) |
| `next_fixture` | int | Next match ID |


## Round fantasy points

| Column | Type | Description |
|---|---|---|
| `round_1_points` | int | Points in round 1 |
| `round_2_points` | int | Points in round 2 |
| `round_3_points` | int | Points in round 3 |
| `round_4_points` | int | Points in round 4 |


## Betting / scorer mapping

| Column | Type | Description |
|---|---|---|
| `betano_matched_name` | str | Matched Betano market name |
| `betano_match_score` | float | Name matching confidence (0–100) |
| `anytime_scorer_prob` | float | Probability player scores anytime |
| `first_scorer_prob` | float | Probability scores first goal |
| `last_scorer_prob` | float | Probability scores last goal |


## Match context

| Column | Type | Description |
|---|---|---|
| `match_home` | str | Home team |
| `match_away` | str | Away team |
| `is_home` | bool | Player team is home |
| `opponent` | str | Opponent team |


## Match probabilities 

| Column | Type | Description |
|---|---|---|
| `match_home_win_prob` | float | Home win probability |
| `match_draw_prob` | float | Draw probability |
| `match_away_win_prob` | float | Away win probability |
| `match_btts_prob` | float | Both teams score probability |
| `match_over_25_prob` | float | Over 2.5 goals probability |
| `match_over_35_prob` | float | Over 3.5 goals probability |
| `team_score_prob` | float | Team scores ≥1 goal probability |
| `team_score_2_prob` | float | Team scores ≥2 goals probability |
| `team_cs_prob` | float | Team clean sheet probability |
| `opp_score_prob` | float | Opponent scores ≥1 goal probability |
| `opp_cs_prob` | float | Opponent clean sheet probability |
| `team_over_05_prob` | float | Team scores ≥1 goal probability |
| `team_over_15_prob` | float | Team scores ≥2 goals probability |
| `team_qualify_prob` | float | Team advances probability |
| `team_win2_prob` | float | Team wins by 2+ goals probability |
| `opp_over_05_prob` | float | Opponent scores ≥1 goal probability |


## Raw cumulative stats

| Column | Type | Description |
|---|---|---|
| `stat_GS` | int | Goals |
| `stat_AS` | int | Assists |
| `stat_CS` | int | Clean sheets |
| `stat_GC` | int | Goals conceded |
| `stat_MP` | int | Minutes played |
| `stat_YC` | int | Yellow cards |
| `stat_RC` | int | Red cards |
| `stat_ST` | int | Shots on target |
| `stat_SB` | int | Shots blocked |
| `stat_CC` | int | Chances created |
| `stat_PS` | int | Penalties saved |
| `stat_T` | int | Tackles |
| `stat_S` | int | Saves |
| `stat_SXI` | int | Starts (XI appearances) |
| `stat_OG` | int | Own goals |
| `stat_PC` | int | Penalties committed |
| `stat_PW` | int | Penalties won |
| `stat_FK` | int | Free kicks won |



## Round-by-round stats (1–4)

| Pattern | Type | Description |
|---|---|---|
| `round_i_SXI` | int | Started (0/1) |
| `round_i_MP` | int | Minutes |
| `round_i_AS` | int | Assists |
| `round_i_YC` | int | Yellow cards |
| `round_i_RC` | int | Red cards |
| `round_i_OG` | int | Own goals |
| `round_i_PW` | int | Penalties won |
| `round_i_PC` | int | Penalties committed |
| `round_i_CS` | int | Clean sheets |
| `round_i_GS` | int | Goals |
| `round_i_GC` | int | Goals conceded |
| `round_i_PS` | int | Penalties saved |
| `round_i_T` | int | Tackles |
| `round_i_CC` | int | Chances created |
| `round_i_ST` | int | Shots on target |
| `round_i_FK` | int | Free kicks |
| `round_i_S` | int | Saves |
| `round_i_SB` | int | Shots blocked |



## External matching / enrichment

| Column | Type | Description |
|---|---|---|
| `clubstats_matched_player` | str | External player match |
| `clubs_match_dist` | float | Matching distance score |



## Form / usage trends

| Column | Type | Description |
|---|---|---|
| `started_last_match` | int | Started last match |
| `starts_last_3` | int | Starts last 3 matches |
| `starts_last_5` | int | Starts last 5 matches |
| `start_rate` | float | Start frequency |
| `minutes_last_3_avg` | float | Avg minutes last 3 |
| `minutes_last_5_avg` | float | Avg minutes last 5 |



## Performance rates

| Column | Type | Description |
|---|---|---|
| `goal_rate` | float | Goals per minute |
| `goals_per_start` | float | Goals per start |
| `shots_on_target_per90` | float | SOT per 90 |
| `goals_per_shot_on_target` | float | Conversion rate |
| `assist_rate` | float | Assists per minute |
| `chance_created_per90` | float | Chances per 90 |
| `tackles_per90` | float | Tackles per 90 |
| `cc_per90` | float | Chances created per 90 |
| `sot_per90` | float | Shots on target per 90 |
| `saves_per90` | float | Saves per 90 |
| `yc_per90` | float | Yellow cards per 90 |
| `rc_per90` | float | Red cards per 90 |
| `penalty_conceded_rate` | float | Penalties conceded per 90 |
| `own_goal_rate` | float | Own goals per 90 |
| `penalties_won_per90` | float | Penalties won per 90 |



## Recent / streak features

| Column | Type | Description |
|---|---|---|
| `recent_goals_last3` | int | Goals last 3 matches |
| `goal_streak` | int | Consecutive scoring matches |
| `recent_assists_last3` | int | Assists last 3 matches |
| `recent_chances_created_per90` | float | Recent creation rate |
| `recent_cs_rate` | float | Clean sheet rate |
| `recent_tackles_per90` | float | Recent tackles |
| `recent_cc_per90` | float | Recent chances created |
| `recent_sot_per90` | float | Recent shots on target |
| `recent_saves_per90` | float | Recent saves |
| `recent_penalties_won` | int | Penalties won last 3 |



## Expected value features

| Column | Type | Description |
|---|---|---|
| `goal_expectation` | float | Scoring proxy |
| `goal_expectation2` | float | Scoring proxy (2+ goals) |
| `assist_expectation` | float | Assist proxy |
| `cs_expectation` | float | Clean sheet proxy |
| `expected_minutes` | float | Expected minutes |
| `expected_gc_penalty` | float | Defensive penalty |
| `expected_tackle_points` | float | Tackles contribution |
| `expected_cc_points` | float | Chance creation points |
| `expected_sot_points` | float | Shot contribution points |
| `expected_save_points` | float | Save contribution points |



## Fantasy points dynamics

| Column | Type | Description |
|---|---|---|
| `points_last1` | int | Last match points |
| `points_last3_avg` | float | Avg last 3 |
| `points_last5_avg` | float | Avg last 5 |
| `weighted_points` | float | Recency weighted |
| `rolling_std_points` | float | Variance last 5 |
| `rolling_max_points` | int | Max last 5 |



## Team-position ranking features

| Column | Type | Description |
|---|---|---|
| `price_rank_team_position` | float | Price rank |
| `selected_rank_team_position` | float | Selection rank |
| `points_rank_team_position` | float | Points rank |
| `minutes_rank_team_position` | float | Minutes rank |
| `starts_rank_team_position` | float | Starts rank |
| `anytime_rank_team_position` | float | Scoring odds rank |
| `shots_rank_team_position` | float | Shooting rank |
| `cc_rank_team_position` | float | Chance creation rank |
| `tackles_rank_team_position` | float | Tackles rank |

In [46]:
df= pd.read_csv("fantasy_enriched.csv")

In [47]:
df = df[df["status"] == "playing"].copy()

In [48]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [49]:
# probability of playing a minute

raw_any = (
    0.15 * df["minutes_rank_team_position"]
  + 0.20 * df["stat_MP"]        # minutes needs to be very team stratified since while for other point sources players are all eligible
  + 0.10 * df["starts_rank_team_position"]
  + 0.15 * df["price_rank_team_position"]     # for minutes its a team stratified signal.
  + 0.20 * df["selected_rank_team_position"]
  + 0.15 * df["minutes_last_3_avg"]
  + 0.05 * df["anytime_rank_team_position"] # having odd at all means likeliness of playing is higher.

)

df["prob_plays_any"] = sigmoid((raw_any - 0.5) * 6)

In [50]:
df.loc[
    :,
    [
        "prob_plays_any",
        "name",
        "team",
        "position",
        "stat_MP",
        "minutes_rank_team_position",
        "starts_rank_team_position",
        "selected_rank_team_position",
        "price_rank_team_position",
        "anytime_rank_team_position",
    ],
].sort_values("prob_plays_any", ascending=False).head(30)

,prob_plays_any,name,team,position,stat_MP,minutes_rank_team_position,starts_rank_team_position,selected_rank_team_position,price_rank_team_position,anytime_rank_team_position
10,0.952574,Emiliano Martínez,Argentina,GK,1.000000,1.000000,1.000000,1.0,1.000000,1.000000
342,0.947350,Thibaut Courtois,Belgium,GK,1.000000,1.000000,1.000000,1.0,1.000000,0.633333
395,0.947350,Yassine Bounou,Morocco,GK,1.000000,1.000000,1.000000,1.0,1.000000,0.633333
149,0.940643,Kylian Mbappé,France,FWD,0.900000,1.000000,1.000000,1.0,1.000000,1.000000
134,0.937479,Jordan Pickford,England,GK,0.923077,1.000000,1.000000,1.0,1.000000,0.633333
70,0.937479,Maxime Crépeau,Canada,GK,0.923077,1.000000,1.000000,1.0,1.000000,0.633333
91,0.937479,Camilo Vargas,Colombia,GK,0.923077,1.000000,1.000000,1.0,1.000000,0.633333
348,0.937479,Diogo Costa,Portugal,GK,0.923077,1.000000,1.000000,1.0,1.000000,0.633333
289,0.937479,Gregor Kobel,Switzerland,GK,0.923077,1.000000,1.000000,1.0,1.000000,0.633333
153,0.937479,Mike Maignan,France,GK,0.923077,1.000000,1.000000,1.0,1.000000,0.633333
128,0.929234,Harry Kane,England,FWD,0.907692,1.000000,0.656250,1.0,1.000000,1.000000
266,0.927081,Unai Simón,Spain,GK,0.923077,1.000000,1.000000,1.0,0.816667,0.633333
212,0.926121,Gustavo Gómez,Paraguay,DEF,1.000000,1.000000,0.214286,1.0,1.000000,1.000000
56,0.923274,Alisson Becker,Brazil,GK,0.923077,1.000000,1.000000,1.0,0.816667,0.450000
396,0.923039,Achraf Hakimi,Morocco,DEF,1.000000,1.000000,0.140625,1.0,1.000000,1.000000
352,0.919309,Cristiano Ronaldo,Portugal,FWD,0.900000,1.000000,0.450000,1.0,1.000000,1.000000
286,0.917488,Breel Embolo,Switzerland,FWD,0.889744,1.000000,0.450000,1.0,1.000000,1.000000
5,0.916703,Lionel Messi,Argentina,FWD,0.820513,1.000000,0.656250,1.0,1.000000,1.000000
65,0.910190,Jonathan David,Canada,FWD,0.848718,1.000000,0.312500,1.0,1.000000,1.000000
113,0.909109,Omar Marmoush,Egypt,FWD,0.810256,1.000000,0.656250,1.0,1.000000,0.862500
262,0.904901,Mikel Oyarzabal,Spain,FWD,0.771795,1.000000,0.656250,1.0,1.000000,1.000000
228,0.902911,Orlando Gill,Paraguay,GK,1.000000,1.000000,1.000000,1.0,0.266667,0.633333
87,0.901014,Luis Díaz,Colombia,MID,0.917949,1.000000,0.000000,1.0,1.000000,1.000000
48,0.898940,Vinícius Júnior,Brazil,MID,0.900000,1.000000,0.037500,1.0,1.000000,1.000000
186,0.898341,Ismael Saibari,Morocco,MID,0.930769,0.877778,0.083333,1.0,1.000000,1.000000
313,0.896671,Matt Freese,USA,GK,0.692308,1.000000,1.000000,1.0,1.000000,0.633333
203,0.896671,Ørjan Nyland,Norway,GK,0.692308,1.000000,1.000000,1.0,1.000000,0.633333
278,0.894454,Manuel Akanji,Switzerland,DEF,0.923077,0.931250,0.140625,1.0,1.000000,0.656250
233,0.892531,Nuno Mendes,Portugal,DEF,0.874359,0.862500,0.140625,1.0,1.000000,1.000000
41,0.892491,Gabriel Magalhães,Brazil,DEF,0.923077,0.931250,0.140625,1.0,1.000000,0.587500

In [51]:
# probability of starting / playing 60 minutes

raw_any = (
    0.15 * df["minutes_rank_team_position"]
  + 0.10 * df["starts_rank_team_position"]
  + 0.25 * df["stat_MP"]
  + 0.10 * df["price_rank_team_position"]
  + 0.05 * df["selected_rank_team_position"]
  + 0.15 * df["minutes_last_3_avg"]
  + 0.15 * df["round_4_MP"]
  + 0.05 * df["anytime_rank_team_position"] # having odd at all means likeliness of playing is higher.

)

df["prob_plays_60min"] = sigmoid((raw_any - 0.5) * 6)

In [52]:
cols = [
    "name",
    "team",
    "position",
    "prob_plays_60min",
    "minutes_rank_team_position",
    "starts_rank_team_position",
    "price_rank_team_position",
    "selected_rank_team_position",
    "minutes_last_3_avg",
    "round_4_MP",
    "anytime_rank_team_position",
]

df[cols].sort_values("prob_plays_60min", ascending=False).head(30)

,name,team,position,prob_plays_60min,minutes_rank_team_position,starts_rank_team_position,price_rank_team_position,selected_rank_team_position,minutes_last_3_avg,round_4_MP,anytime_rank_team_position
10,Emiliano Martínez,Argentina,GK,0.952574,1.000000,1.000000,1.000000,1.0000,1.000000,1.000000,1.000000
342,Thibaut Courtois,Belgium,GK,0.947350,1.000000,1.000000,1.000000,1.0000,1.000000,1.000000,0.633333
395,Yassine Bounou,Morocco,GK,0.947350,1.000000,1.000000,1.000000,1.0000,1.000000,1.000000,0.633333
212,Gustavo Gómez,Paraguay,DEF,0.926121,1.000000,0.214286,1.000000,1.0000,1.000000,1.000000,1.000000
396,Achraf Hakimi,Morocco,DEF,0.923039,1.000000,0.140625,1.000000,1.0000,1.000000,1.000000,1.000000
149,Kylian Mbappé,France,FWD,0.922048,1.000000,1.000000,1.000000,1.0000,0.870000,0.708333,1.000000
289,Gregor Kobel,Switzerland,GK,0.921262,1.000000,1.000000,1.000000,1.0000,0.900000,0.750000,0.633333
134,Jordan Pickford,England,GK,0.921262,1.000000,1.000000,1.000000,1.0000,0.900000,0.750000,0.633333
153,Mike Maignan,France,GK,0.921262,1.000000,1.000000,1.000000,1.0000,0.900000,0.750000,0.633333
70,Maxime Crépeau,Canada,GK,0.921262,1.000000,1.000000,1.000000,1.0000,0.900000,0.750000,0.633333
348,Diogo Costa,Portugal,GK,0.921262,1.000000,1.000000,1.000000,1.0000,0.900000,0.750000,0.633333
91,Camilo Vargas,Colombia,GK,0.921262,1.000000,1.000000,1.000000,1.0000,0.900000,0.750000,0.633333
228,Orlando Gill,Paraguay,GK,0.920561,1.000000,1.000000,0.266667,1.0000,1.000000,1.000000,0.633333
266,Unai Simón,Spain,GK,0.912904,1.000000,1.000000,0.816667,1.0000,0.900000,0.750000,0.633333
5,Lionel Messi,Argentina,FWD,0.912498,1.000000,0.656250,1.000000,1.0000,0.800000,1.000000,1.000000
128,Harry Kane,England,FWD,0.910706,1.000000,0.656250,1.000000,1.0000,0.880000,0.750000,1.000000
56,Alisson Becker,Brazil,GK,0.908430,1.000000,1.000000,0.816667,1.0000,0.900000,0.750000,0.450000
118,Mostafa Shobeir,Egypt,GK,0.901699,1.000000,0.656250,0.312500,1.0000,1.000000,1.000000,0.450000
186,Ismael Saibari,Morocco,MID,0.896428,0.877778,0.083333,1.000000,1.0000,0.913333,1.000000,1.000000
113,Omar Marmoush,Egypt,FWD,0.894106,1.000000,0.656250,1.000000,1.0000,0.753333,0.875000,0.862500
352,Cristiano Ronaldo,Portugal,FWD,0.891920,1.000000,0.450000,1.000000,1.0000,0.870000,0.675000,1.000000
286,Breel Embolo,Switzerland,FWD,0.890720,1.000000,0.450000,1.000000,1.0000,0.856667,0.691667,1.000000
65,Jonathan David,Canada,FWD,0.885500,1.000000,0.312500,1.000000,1.0000,0.900000,0.750000,1.000000
361,Mohamed Salah,Egypt,MID,0.881791,0.890000,0.037500,1.000000,1.0000,0.873333,1.000000,1.000000
262,Mikel Oyarzabal,Spain,FWD,0.876473,1.000000,0.656250,1.000000,1.0000,0.703333,0.750000,1.000000
87,Luis Díaz,Colombia,MID,0.875602,1.000000,0.000000,1.000000,1.0000,0.896667,0.741667,1.000000
108,Mohamed Hany,Egypt,DEF,0.875242,1.000000,0.140625,0.450000,0.8625,1.000000,1.000000,0.450000
177,Raúl Rangel,Mexico,GK,0.874073,1.000000,1.000000,0.266667,1.0000,0.860000,0.750000,0.633333
39,Youri Tielemans,Belgium,MID,0.873335,1.000000,0.000000,0.700000,0.7000,0.983333,1.000000,0.450000
48,Vinícius Júnior,Brazil,MID,0.873305,1.000000,0.037500,1.000000,1.0000,0.870000,0.750000,1.000000

There is a phenomenon where a player will be overvalued, such as Lukaku here for belgium. He has not played much, but since Belgium only has 3 forward and only him has significative minutes he ranks number 1 for all ranks in BEL,FWD. Need to include more general sums and beware with manual selection.

In [53]:
raw_goal = (
    0.60 * df["anytime_scorer_prob"]
  + 0.05 * df["recent_goals_last3"]
  + 0.05 * df["team_score_2_prob"]
  + 0.02 * df["stat_GS"]
  + 0.03 * df["stat_ST"]
  + 0.05 * df["price"]
)

df["prob_scores"] = raw_goal * df["prob_plays_60min"]

In [54]:
cols = [
    "name",
    "team",
    "position",
    "prob_scores",
    "goal_expectation",
    "anytime_scorer_prob",
    "recent_goals_last3",
    "recent_sot_per90",
    "goal_rate",
    "shots_on_target_per90",
    "stat_GS",
    "stat_ST",
    "price_rank_team_position",
]

df[cols].sort_values("prob_scores", ascending=False).head(30)

,name,team,position,prob_scores,goal_expectation,anytime_scorer_prob,recent_goals_last3,recent_sot_per90,goal_rate,shots_on_target_per90,stat_GS,stat_ST,price_rank_team_position
149,Kylian Mbappé,France,FWD,0.731316,1.000000,1.000000,1.00,0.034483,0.324786,0.351852,0.857143,0.866667,1.000000
5,Lionel Messi,Argentina,FWD,0.686795,0.892827,0.943886,1.00,0.045833,0.415625,0.445312,1.000000,1.000000,1.000000
48,Vinícius Júnior,Brazil,MID,0.507463,0.661569,0.718813,0.75,0.034483,0.216524,0.270655,0.571429,0.666667,1.000000
262,Mikel Oyarzabal,Spain,FWD,0.505895,0.648677,0.725769,1.00,0.033175,0.252492,0.252492,0.571429,0.533333,1.000000
199,Erling Haaland,Norway,FWD,0.486610,0.552767,0.725769,0.75,0.027778,0.351852,0.316667,0.714286,0.600000,1.000000
128,Harry Kane,England,FWD,0.473286,0.500675,0.633792,0.75,0.022727,0.268362,0.241525,0.714286,0.600000,1.000000
150,Ousmane Dembélé,France,MID,0.471469,0.727227,0.725769,1.00,0.024038,0.263889,0.164931,0.571429,0.333333,1.000000
352,Cristiano Ronaldo,Portugal,FWD,0.424944,0.445133,0.591127,0.75,0.026820,0.162393,0.189459,0.428571,0.466667,1.000000
31,Romelu Lukaku,Belgium,FWD,0.407883,0.602884,0.698717,0.50,0.013072,0.214689,0.107345,0.285714,0.133333,1.000000
49,Matheus Cunha,Brazil,FWD,0.395733,0.583849,0.633792,0.75,0.024272,0.242553,0.202128,0.428571,0.333333,1.000000
186,Ismael Saibari,Morocco,MID,0.393416,0.508765,0.579688,0.50,0.007299,0.157025,0.078512,0.428571,0.200000,1.000000
320,Lautaro Martínez,Argentina,FWD,0.349557,0.656047,0.692224,0.25,0.005319,0.078189,0.078189,0.142857,0.133333,0.725000
162,Michael Olise,France,MID,0.343969,0.544097,0.541660,0.00,0.013761,0.000000,0.154221,0.000000,0.333333,0.900000
260,Lamine Yamal,Spain,MID,0.342007,0.533373,0.595919,0.25,0.029126,0.084444,0.253333,0.142857,0.400000,1.000000
87,Luis Díaz,Colombia,MID,0.329794,0.429023,0.513681,0.00,0.014870,0.053073,0.132682,0.142857,0.333333,1.000000
286,Breel Embolo,Switzerland,FWD,0.317779,0.347521,0.480445,0.25,0.011673,0.109510,0.109510,0.285714,0.266667,1.000000
346,Leandro Trossard,Belgium,MID,0.287308,0.358119,0.413201,0.50,0.011070,0.105263,0.078947,0.285714,0.200000,0.800000
65,Jonathan David,Canada,FWD,0.277949,0.246879,0.366672,0.75,0.022222,0.172205,0.200906,0.428571,0.466667,1.000000
333,Bradley Barcola,France,MID,0.273955,0.586381,0.584171,0.25,0.010101,0.182692,0.137019,0.285714,0.200000,0.750000
89,Luis Suárez,Colombia,FWD,0.269467,0.429023,0.513681,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.450000
6,Julián Alvarez,Argentina,FWD,0.266902,0.656047,0.692224,0.00,0.012121,0.000000,0.095000,0.000000,0.133333,0.450000
170,Julián Quiñones,Mexico,FWD,0.265805,0.318247,0.431288,0.50,0.011811,0.171171,0.142643,0.428571,0.333333,0.685714
141,Jude Bellingham,England,MID,0.260091,0.306152,0.385995,0.25,0.017094,0.121019,0.181529,0.285714,0.400000,0.890000
315,Christian Pulisic,USA,MID,0.250166,0.494136,0.584171,0.00,0.016667,0.000000,0.115152,0.000000,0.133333,1.000000
169,Raúl Jiménez,Mexico,FWD,0.247180,0.359995,0.488329,0.25,0.012987,0.165217,0.165217,0.285714,0.266667,1.000000
39,Youri Tielemans,Belgium,MID,0.240179,0.280064,0.322152,0.50,0.010169,0.098701,0.074026,0.285714,0.200000,0.700000
40,Kevin De Bruyne,Belgium,MID,0.239027,0.358119,0.413201,0.25,0.013953,0.063123,0.126246,0.142857,0.266667,0.950000
361,Mohamed Salah,Egypt,MID,0.237745,0.175303,0.329417,0.25,0.011450,0.056213,0.112426,0.142857,0.266667,1.000000
404,Brahim Díaz,Morocco,MID,0.235698,0.385206,0.437780,0.00,0.000000,0.000000,0.031879,0.000000,0.066667,0.877778
299,Weston McKennie,USA,MID,0.233374,0.327762,0.385995,0.00,0.003788,0.000000,0.026836,0.000000,0.066667,0.835000

In [55]:
prob_assists = (
    0.05 * df["chance_created_per90"]
  + 0.20 * df["stat_CC"]
  + 0.05 * df["recent_cc_per90"]
  + 0.15 * df["team_score_2_prob"]
  + 0.15 * df["recent_assists_last3"]
  + 0.15 * df["price"]
  + 0.10 * df["stat_AS"]
)

df["expected_assists"] = prob_assists * df["prob_plays_60min"]

In [56]:
cols = [
    "name",
    "team",
    "position",
    "expected_assists",
    "assist_expectation",
    "stat_CC",
    "recent_cc_per90",
    "team_score_2_prob",
    "recent_assists_last3",
    "price",
    "prob_plays_60min",
    "stat_AS",
]

df[cols].sort_values("expected_assists", ascending=False).head(30)

,name,team,position,expected_assists,assist_expectation,stat_CC,recent_cc_per90,team_score_2_prob,recent_assists_last3,price,prob_plays_60min,stat_AS
162,Michael Olise,France,MID,0.599446,0.194970,1.0,0.178899,1.000000,1.00,0.857143,0.803942,1.0
149,Kylian Mbappé,France,FWD,0.423141,0.034217,0.2,0.049808,1.000000,0.50,1.000000,0.922048,0.4
5,Lionel Messi,Argentina,FWD,0.397895,0.142004,0.8,0.216667,0.797880,0.00,0.928571,0.912498,0.0
323,Bruno Guimarães,Brazil,MID,0.397142,0.097390,0.6,0.150000,0.688782,0.75,0.471429,0.796764,0.8
258,Marc Cucurella,Spain,DEF,0.359103,0.089348,0.6,0.096296,0.628933,0.75,0.228571,0.834914,0.6
150,Ousmane Dembélé,France,MID,0.350990,0.041702,0.2,0.062500,1.000000,0.50,0.928571,0.781460,0.4
286,Breel Embolo,Switzerland,FWD,0.328416,0.074975,0.6,0.050584,0.274282,0.50,0.571429,0.890720,0.4
48,Vinícius Júnior,Brazil,MID,0.300433,0.031446,0.2,0.049808,0.688782,0.25,0.928571,0.873305,0.2
172,Roberto Alvarado,Mexico,FWD,0.296067,0.103965,0.8,0.156000,0.280267,0.50,0.257143,0.760523,0.6
141,Jude Bellingham,England,MID,0.290268,0.090558,0.6,0.166667,0.392613,0.25,0.685714,0.823783,0.2
371,Martin Ødegaard,Norway,MID,0.269244,0.070104,0.4,0.072222,0.323187,0.50,0.600000,0.745991,0.6
396,Achraf Hakimi,Morocco,DEF,0.260034,0.053913,0.4,0.086667,0.558311,0.25,0.357143,0.923039,0.2
19,Alexis Mac Allister,Argentina,MID,0.259663,0.034530,0.2,0.000000,0.797880,0.25,0.442857,0.850990,0.4
262,Mikel Oyarzabal,Spain,FWD,0.258694,0.035620,0.2,0.061611,0.628933,0.25,0.657143,0.876473,0.2
346,Leandro Trossard,Belgium,MID,0.250742,0.057346,0.4,0.095941,0.528728,0.25,0.442857,0.862233,0.2
251,Bruno Fernandes,Portugal,MID,0.246695,0.054269,0.4,0.106996,0.305233,0.25,0.714286,0.825673,0.2
361,Mohamed Salah,Egypt,MID,0.235691,0.018955,0.2,0.049618,0.043605,0.25,0.928571,0.881791,0.4
404,Brahim Díaz,Morocco,MID,0.232867,0.070558,0.4,0.055794,0.558311,0.25,0.414286,0.752313,0.4
199,Erling Haaland,Norway,FWD,0.224772,0.033884,0.2,0.072222,0.323187,0.00,1.000000,0.851601,0.2
332,Jules Koundé,France,DEF,0.221946,0.071702,0.4,0.053061,1.000000,0.00,0.271429,0.803128,0.0
186,Ismael Saibari,Morocco,MID,0.216900,0.057923,0.4,0.094891,0.558311,0.00,0.471429,0.896428,0.0
41,Gabriel Magalhães,Brazil,DEF,0.214376,0.030660,0.2,0.048148,0.688782,0.25,0.285714,0.866269,0.2
333,Bradley Barcola,France,MID,0.209646,0.057741,0.2,0.065657,1.000000,0.25,0.642857,0.599648,0.2
190,Patrick Berg,Norway,MID,0.202867,0.117289,0.6,0.173333,0.323187,0.50,0.300000,0.590492,0.4
87,Luis Díaz,Colombia,MID,0.199764,0.027933,0.2,0.000000,0.454514,0.00,0.657143,0.875602,0.2
144,Dayot Upamecano,France,DEF,0.197845,0.034711,0.2,0.050781,1.000000,0.00,0.257143,0.850742,0.0
316,Lisandro Martínez,Argentina,DEF,0.197510,0.037868,0.2,0.061905,0.797880,0.25,0.157143,0.804470,0.2
233,Nuno Mendes,Portugal,DEF,0.196024,0.079494,0.6,0.144981,0.305233,0.00,0.328571,0.864615,0.0
256,Aymeric Laporte,Spain,DEF,0.193634,0.029866,0.2,0.048327,0.628933,0.25,0.285714,0.811860,0.2
128,Harry Kane,England,FWD,0.190239,0.000000,0.0,0.000000,0.392613,0.00,1.000000,0.910706,0.0

In [57]:
position_yc_modifier = {
    "GK": 0.15,
    "FWD": 0.35,
    "DEF": 0.45,
    "MID": 0.55,
}

df["position_yc_modifier"] = df["position"].map(position_yc_modifier)

raw_yc = (
    0.35 * df["yc_per90"]
  + 0.15 * df["tackles_per90"]
  + 0.15 * df["opp_over_05_prob"]
  + 0.05 * df["rc_per90"]
  + 0.05 * df["position_yc_modifier"]
)

df["prob_yellow_card"] = sigmoid((raw_yc - 0.6) * 5) * df["prob_plays_60min"]

In [58]:
cols = [
    "name",
    "team",
    "position",
    "prob_yellow_card",
    "yc_per90",
    "stat_YC",
    "tackles_per90",
    "recent_tackles_per90",
    "opp_over_05_prob",
    "prob_plays_60min",
    "rc_per90",
]

df[cols].sort_values("prob_yellow_card", ascending=False).head(30)

,name,team,position,prob_yellow_card,yc_per90,stat_YC,tackles_per90,recent_tackles_per90,opp_over_05_prob,prob_plays_60min,rc_per90
210,Matías Galarza,Paraguay,MID,0.131623,0.255034,1.0,0.046980,0.234899,1.000000,0.804053,0.000000
112,Yasser Ibrahim,Egypt,DEF,0.112540,0.202128,1.0,0.018617,0.104895,0.895727,0.826859,0.000000
362,Andrés Cubas,Paraguay,MID,0.105619,0.097436,0.5,0.035897,0.150000,1.000000,0.822493,0.000000
219,Miguel Almirón,Paraguay,MID,0.098465,0.177570,0.5,0.032710,0.185185,1.000000,0.583723,0.728972
212,Gustavo Gómez,Paraguay,DEF,0.098385,0.000000,0.0,0.010256,0.050000,1.000000,0.926121,0.000000
213,Júnior Alonso,Paraguay,DEF,0.098055,0.126667,0.5,0.026667,0.142857,1.000000,0.750913,0.000000
217,Juan José Cáceres,Paraguay,DEF,0.097152,0.108883,0.5,0.051576,0.240741,1.000000,0.752093,0.000000
31,Romelu Lukaku,Belgium,FWD,0.094936,0.214689,0.5,0.000000,0.000000,0.704143,0.802544,0.000000
101,Marwan Attia,Egypt,MID,0.093430,0.110465,0.5,0.017442,0.059055,0.895727,0.773043,0.000000
228,Orlando Gill,Paraguay,GK,0.090798,0.000000,0.0,0.000000,0.000000,1.000000,0.920561,0.000000
381,Alistair Johnston,Canada,DEF,0.089434,0.105556,0.5,0.002778,0.000000,0.758707,0.843267,0.000000
361,Mohamed Salah,Egypt,MID,0.088875,0.000000,0.0,0.002959,0.000000,0.895727,0.881791,0.000000
108,Mohamed Hany,Egypt,DEF,0.088192,0.000000,0.0,0.035897,0.133333,0.895727,0.875242,0.000000
273,Granit Xhaka,Switzerland,MID,0.087461,0.105556,0.5,0.013889,0.092593,0.678150,0.844896,0.000000
28,Brandon Mechele,Belgium,DEF,0.087237,0.097436,0.5,0.007692,0.016667,0.704143,0.861364,0.000000
349,Rúben Dias,Portugal,DEF,0.086729,0.140741,0.5,0.018519,0.092593,0.802058,0.744304,0.000000
113,Omar Marmoush,Egypt,FWD,0.086713,0.000000,0.0,0.012658,0.066372,0.895727,0.894106,0.000000
230,Julio Enciso,Paraguay,MID,0.085833,0.000000,0.0,0.012270,0.042373,1.000000,0.789073,0.000000
22,Timothy Castagne,Belgium,DEF,0.085529,0.127517,0.5,0.033557,0.123967,0.704143,0.791747,0.000000
280,Nico Elvedi,Switzerland,DEF,0.084759,0.105556,0.5,0.008333,0.055556,0.678150,0.840522,0.000000
237,Renato Veiga,Portugal,DEF,0.083979,0.105556,0.5,0.008333,0.018519,0.802058,0.766337,0.000000
21,Maxim De Cuyper,Belgium,DEF,0.083957,0.130137,0.5,0.010274,0.038760,0.704143,0.786184,0.000000
231,Diego Gómez,Paraguay,MID,0.083473,0.322034,1.0,0.033898,0.192308,1.000000,0.466473,0.000000
118,Mostafa Shobeir,Egypt,GK,0.082862,0.000000,0.0,0.000000,0.000000,0.895727,0.901699,0.000000
59,Casemiro,Brazil,MID,0.082647,0.262976,1.0,0.041522,0.225410,0.537898,0.673935,0.000000
352,Cristiano Ronaldo,Portugal,FWD,0.080782,0.000000,0.0,0.005698,0.038314,0.802058,0.891920,0.000000
104,Emam Ashour,Egypt,MID,0.080610,0.000000,0.0,0.009346,0.040000,0.895727,0.796347,0.000000
233,Nuno Mendes,Portugal,DEF,0.080598,0.000000,0.0,0.014663,0.074349,0.802058,0.864615,0.000000
62,Derek Cornelius,Canada,DEF,0.080153,0.120635,0.5,0.015873,0.022222,0.758707,0.731729,0.000000
348,Diogo Costa,Portugal,GK,0.079412,0.000000,0.0,0.000000,0.000000,0.802058,0.921262,0.000000

In [59]:
raw_pw = (
    0.10 * df["stat_PW"]                    # tournament history
  + 0.25 * df["anytime_scorer_prob"]      # gets into dangerous areas
  + 0.10 * df["chance_created_per90"]     # attacking involvement
  + 0.15 * df["stat_CC"]                  # recent form in creation
  + 0.15 * df["team_score_2_prob"]        # team expected to attack heavily
  + 0.10 * df["price_rank_team_position"] # quality proxy
)

# Penalties are rare → heavily compress probabilities + minutes as external gate
df["prob_pen_won"] = 0.15 * sigmoid((raw_pw - 0.65) * 5) * df["prob_plays_60min"]

In [60]:
cols = [
    "name",
    "team",
    "position",
    "prob_pen_won",
    "stat_PW",
    "anytime_scorer_prob",
    "assist_expectation",
    "chance_created_per90",
    "team_score_2_prob",
    "price_rank_team_position",
    "prob_plays_60min",
]

df[cols].sort_values("prob_pen_won", ascending=False).head(30)

,name,team,position,prob_pen_won,stat_PW,anytime_scorer_prob,assist_expectation,chance_created_per90,team_score_2_prob,price_rank_team_position,prob_plays_60min
5,Lionel Messi,Argentina,FWD,0.057939,0.0,0.943886,0.142004,0.125000,0.797880,1.000000,0.912498
149,Kylian Mbappé,France,FWD,0.049460,0.0,1.000000,0.034217,0.028490,1.000000,1.000000,0.922048
162,Michael Olise,France,MID,0.044351,0.0,0.541660,0.194970,0.162338,1.000000,0.900000,0.803942
150,Ousmane Dembélé,France,MID,0.033273,0.0,0.725769,0.041702,0.034722,1.000000,1.000000,0.781460
320,Lautaro Martínez,Argentina,FWD,0.032755,1.0,0.692224,0.046750,0.041152,0.797880,0.725000,0.682138
48,Vinícius Júnior,Brazil,MID,0.031012,0.0,0.718813,0.031446,0.028490,0.688782,1.000000,0.873305
262,Mikel Oyarzabal,Spain,FWD,0.030328,0.0,0.725769,0.035620,0.033223,0.628933,1.000000,0.876473
186,Ismael Saibari,Morocco,MID,0.029273,0.0,0.579688,0.057923,0.055096,0.558311,1.000000,0.896428
286,Breel Embolo,Switzerland,FWD,0.025375,0.0,0.480445,0.074975,0.086455,0.274282,1.000000,0.890720
39,Youri Tielemans,Belgium,MID,0.025138,1.0,0.322152,0.026886,0.025974,0.528728,0.700000,0.873335
199,Erling Haaland,Norway,FWD,0.024629,0.0,0.725769,0.033884,0.037037,0.323187,1.000000,0.851601
49,Matheus Cunha,Brazil,FWD,0.022813,0.0,0.633792,0.000000,0.000000,0.688782,1.000000,0.794758
31,Romelu Lukaku,Belgium,FWD,0.022321,0.0,0.698717,0.000000,0.000000,0.528728,1.000000,0.802544
87,Luis Díaz,Colombia,MID,0.022007,0.0,0.513681,0.027933,0.027933,0.454514,1.000000,0.875602
141,Jude Bellingham,England,MID,0.021989,0.0,0.385995,0.090558,0.095541,0.392613,0.890000,0.823783
396,Achraf Hakimi,Morocco,DEF,0.021871,0.0,0.265729,0.053913,0.051282,0.558311,1.000000,0.923039
128,Harry Kane,England,FWD,0.021764,0.0,0.633792,0.000000,0.000000,0.392613,1.000000,0.910706
332,Jules Koundé,France,DEF,0.021582,0.0,0.118411,0.071702,0.059701,1.000000,1.000000,0.803128
346,Leandro Trossard,Belgium,MID,0.021559,0.0,0.413201,0.057346,0.055402,0.528728,0.800000,0.862233
19,Alexis Mac Allister,Argentina,MID,0.020771,0.0,0.318596,0.034530,0.030395,0.797880,0.900000,0.850990
333,Bradley Barcola,France,MID,0.020490,0.0,0.584171,0.057741,0.048077,1.000000,0.750000,0.599648
404,Brahim Díaz,Morocco,MID,0.020392,0.0,0.437780,0.070558,0.067114,0.558311,0.877778,0.752313
315,Christian Pulisic,USA,MID,0.020199,0.0,0.584171,0.122870,0.121212,0.508892,1.000000,0.617775
323,Bruno Guimarães,Brazil,MID,0.019743,0.0,0.227392,0.097390,0.088235,0.688782,0.670000,0.796764
260,Lamine Yamal,Spain,MID,0.019676,0.0,0.595919,0.000000,0.000000,0.628933,1.000000,0.739021
352,Cristiano Ronaldo,Portugal,FWD,0.019270,0.0,0.591127,0.000000,0.000000,0.305233,1.000000,0.891920
144,Dayot Upamecano,France,DEF,0.018942,0.0,0.144226,0.034711,0.028902,1.000000,0.816667,0.850742
20,Enzo Fernández,Argentina,MID,0.018850,0.0,0.349204,0.000000,0.000000,0.797880,1.000000,0.824023
233,Nuno Mendes,Portugal,DEF,0.018731,0.0,0.198485,0.079494,0.087977,0.305233,1.000000,0.864615
258,Marc Cucurella,Spain,DEF,0.017812,0.0,0.156748,0.089348,0.083333,0.628933,0.587500,0.834914

In [61]:
raw_cs = (
    0.8 * df["team_cs_prob"]            # strongest signal
  + 0.10 * df["stat_CS"]               # tournament history
  + 0.10 * (1 - df["stat_GC"])         # fewer goals conceded is better
)

base_cs = sigmoid((raw_cs - 0.5) * 6)

df["prob_clean_sheet"] = base_cs * df["prob_plays_60min"]

df.loc[df["position"] == "FWD", "prob_clean_sheet"] = 0.0

In [62]:
cols = [
    "name",
    "team",
    "position",
    "prob_clean_sheet",
    "team_cs_prob",
    "prob_plays_60min",
    "stat_CS",
    "stat_GC",
    "minutes_rank_team_position",
    "tackles_per90",
]

df[cols].sort_values("prob_clean_sheet", ascending=False).head(30)

,name,team,position,prob_clean_sheet,team_cs_prob,prob_plays_60min,stat_CS,stat_GC,minutes_rank_team_position,tackles_per90
153,Mike Maignan,France,GK,0.853200,1.000000,0.921262,0.50,0.285714,1.000000,0.000000
10,Emiliano Martínez,Argentina,GK,0.837330,0.904231,0.952574,0.50,0.428571,1.000000,0.000000
144,Dayot Upamecano,France,DEF,0.787890,1.000000,0.850742,0.50,0.285714,1.000000,0.020231
19,Alexis Mac Allister,Argentina,MID,0.767535,0.904231,0.850990,0.75,0.285714,1.000000,0.036474
162,Michael Olise,France,MID,0.744547,1.000000,0.803942,0.50,0.285714,1.000000,0.012987
332,Jules Koundé,France,DEF,0.743794,1.000000,0.803128,0.50,0.285714,0.877778,0.032836
150,Ousmane Dembélé,France,MID,0.735131,1.000000,0.781460,0.75,0.142857,0.900000,0.010417
20,Enzo Fernández,Argentina,MID,0.731602,0.904231,0.824023,0.50,0.285714,0.900000,0.020000
316,Lisandro Martínez,Argentina,DEF,0.714242,0.904231,0.804470,0.50,0.285714,1.000000,0.010000
0,Cristian Romero,Argentina,DEF,0.684211,0.904231,0.770646,0.50,0.285714,0.725000,0.019455
331,William Saliba,France,DEF,0.642594,1.000000,0.689645,0.50,0.142857,0.755556,0.007407
91,Camilo Vargas,Colombia,GK,0.584185,0.538672,0.921262,0.75,0.142857,1.000000,0.000000
395,Yassine Bounou,Morocco,GK,0.581252,0.636488,0.947350,0.25,0.571429,1.000000,0.000000
266,Unai Simón,Spain,GK,0.569084,0.479982,0.912904,1.00,0.000000,1.000000,0.000000
396,Achraf Hakimi,Morocco,DEF,0.566336,0.636488,0.923039,0.25,0.571429,1.000000,0.017949
333,Bradley Barcola,France,MID,0.564098,1.000000,0.599648,0.75,0.142857,0.500000,0.014423
87,Luis Díaz,Colombia,MID,0.555232,0.538672,0.875602,0.75,0.142857,1.000000,0.002793
186,Ismael Saibari,Morocco,MID,0.550009,0.636488,0.896428,0.25,0.571429,0.877778,0.008264
156,Adrien Rabiot,France,MID,0.546248,1.000000,0.586244,0.50,0.142857,0.750000,0.007407
160,Aurélien Tchouaméni,France,MID,0.543160,1.000000,0.593502,0.25,0.285714,0.750000,0.051852
2,Nahuel Molina,Argentina,DEF,0.538843,0.904231,0.606913,0.50,0.285714,0.587500,0.025105
83,Dávinson Sánchez,Colombia,DEF,0.536444,0.538672,0.845974,0.75,0.142857,0.931250,0.011111
317,Facundo Medina,Argentina,DEF,0.531505,0.904231,0.593133,0.50,0.142857,0.862500,0.031008
403,Neil El Aynaoui,Morocco,MID,0.524923,0.636488,0.855542,0.25,0.571429,1.000000,0.039164
398,Noussair Mazraoui,Morocco,DEF,0.524680,0.636488,0.764306,0.50,0.285714,0.587500,0.030303
258,Marc Cucurella,Spain,DEF,0.520468,0.479982,0.834914,1.00,0.000000,0.931250,0.005556
82,Jhon Lucumí,Colombia,DEF,0.518163,0.538672,0.817144,0.75,0.142857,0.931250,0.002778
18,Thiago Almada,Argentina,MID,0.516354,0.904231,0.567886,0.75,0.142857,0.700000,0.023474
14,Rodrigo De Paul,Argentina,MID,0.514234,0.904231,0.573859,0.50,0.142857,0.800000,0.019531
256,Aymeric Laporte,Spain,DEF,0.506096,0.479982,0.811860,1.00,0.000000,0.725000,0.011142

In [63]:
position_rc_modifier = {
    "GK": 0.04,
    "FWD": 0.08,
    "DEF": 0.12,
    "MID": 0.14,
}

df["position_rc_modifier"] = df["position"].map(position_rc_modifier)

raw_rc = (
    0.30 * df["position_rc_modifier"]   # strongest prior
  + 0.25 * df["rc_per90"]              # direct history
  + 0.15 * df["tackles_per90"]         # physical involvement
  + 0.15 * df["prob_yellow_card"]      # disciplinary tendency
  + 0.10 * df["opp_over_05_prob"]      # more defending -> more challenges
)

# Red cards are extremely rare → strong compression + external gate
df["prob_red_card"] = 0.05 * sigmoid((raw_rc - 0.5) * 5) * df["prob_plays_60min"]

In [64]:
cols = [
    "name",
    "team",
    "position",
    "prob_red_card",
    "position_rc_modifier",
    "rc_per90",
    "tackles_per90",
    "prob_yellow_card",
    "opp_over_05_prob",
    "prob_plays_any",
]

df[cols].sort_values("prob_red_card", ascending=False).head(30)

,name,team,position,prob_red_card,position_rc_modifier,rc_per90,tackles_per90,prob_yellow_card,opp_over_05_prob,prob_plays_any
219,Miguel Almirón,Paraguay,MID,0.009171,0.14,0.728972,0.032710,0.098465,1.000000,0.586649
165,César Montes,Mexico,DEF,0.007758,0.12,0.577778,0.007407,0.063807,0.593284,0.565440
212,Gustavo Gómez,Paraguay,DEF,0.006923,0.12,0.000000,0.010256,0.098385,1.000000,0.926121
210,Matías Galarza,Paraguay,MID,0.006444,0.14,0.000000,0.046980,0.131623,1.000000,0.785710
362,Andrés Cubas,Paraguay,MID,0.006439,0.14,0.000000,0.035897,0.105619,1.000000,0.678088
361,Mohamed Salah,Egypt,MID,0.006399,0.14,0.000000,0.002959,0.088875,0.895727,0.885897
108,Mohamed Hany,Egypt,DEF,0.006320,0.12,0.000000,0.035897,0.088192,0.895727,0.840154
228,Orlando Gill,Paraguay,GK,0.006137,0.04,0.000000,0.000000,0.090798,1.000000,0.902911
113,Omar Marmoush,Egypt,FWD,0.006034,0.08,0.000000,0.012658,0.086713,0.895727,0.909109
230,Julio Enciso,Paraguay,MID,0.006010,0.14,0.000000,0.012270,0.085833,1.000000,0.844803
112,Yasser Ibrahim,Egypt,DEF,0.005998,0.12,0.000000,0.018617,0.112540,0.895727,0.786872
233,Nuno Mendes,Portugal,DEF,0.005886,0.12,0.000000,0.014663,0.080598,0.802058,0.892531
39,Youri Tielemans,Belgium,MID,0.005822,0.14,0.000000,0.010390,0.077678,0.704143,0.828441
251,Bruno Fernandes,Portugal,MID,0.005798,0.14,0.000000,0.024024,0.079232,0.802058,0.883563
104,Emam Ashour,Egypt,MID,0.005772,0.14,0.000000,0.009346,0.080610,0.895727,0.747758
217,Juan José Cáceres,Paraguay,DEF,0.005767,0.12,0.000000,0.051576,0.097152,1.000000,0.610705
346,Leandro Trossard,Belgium,MID,0.005758,0.14,0.000000,0.013850,0.076872,0.704143,0.856776
352,Cristiano Ronaldo,Portugal,FWD,0.005731,0.08,0.000000,0.005698,0.080782,0.802058,0.919309
118,Mostafa Shobeir,Egypt,GK,0.005715,0.04,0.000000,0.000000,0.082862,0.895727,0.881843
299,Weston McKennie,USA,MID,0.005711,0.14,0.000000,0.022599,0.076789,0.730981,0.848801
101,Marwan Attia,Egypt,MID,0.005679,0.14,0.000000,0.017442,0.093430,0.895727,0.632385
213,Júnior Alonso,Paraguay,DEF,0.005671,0.12,0.000000,0.026667,0.098055,1.000000,0.616112
381,Alistair Johnston,Canada,DEF,0.005623,0.12,0.000000,0.002778,0.089434,0.758707,0.846049
28,Brandon Mechele,Belgium,DEF,0.005619,0.12,0.000000,0.007692,0.087237,0.704143,0.797111
273,Granit Xhaka,Switzerland,MID,0.005617,0.14,0.000000,0.013889,0.087461,0.678150,0.844971
278,Manuel Akanji,Switzerland,DEF,0.005600,0.12,0.000000,0.019444,0.074647,0.678150,0.894454
348,Diogo Costa,Portugal,GK,0.005591,0.04,0.000000,0.000000,0.079412,0.802058,0.937479
65,Jonathan David,Canada,FWD,0.005563,0.08,0.000000,0.003021,0.077718,0.758707,0.910190
199,Erling Haaland,Norway,FWD,0.005556,0.08,0.000000,0.000000,0.079256,0.847671,0.887407
342,Thibaut Courtois,Belgium,GK,0.005496,0.04,0.000000,0.000000,0.076344,0.704143,0.947350

In [65]:
position_og_modifier = {
    "GK": 0.01,
    "FWD": 0.02,
    "MID": 0.04,
    "DEF": 0.08,
}

df["position_og_modifier"] = df["position"].map(position_og_modifier)

raw_og = (
    0.4 * df["position_og_modifier"]
  + 0.25 * df["opp_over_05_prob"]
  + 0.10 * df["tackles_per90"]
  + 0.10 * (1 - df["stat_GC"])
)

df["prob_own_goal"] = 0.03 * sigmoid((raw_og - 0.5) * 5) * df["prob_plays_60min"]

In [66]:
cols = [
    "name",
    "team",
    "position",
    "prob_own_goal",
    "position_og_modifier",
    "own_goal_rate",
    "opp_over_05_prob",
    "tackles_per90",
    "stat_GC",
    "prob_plays_any",
]

df[cols].sort_values("prob_own_goal", ascending=False).head(30)

,name,team,position,prob_own_goal,position_og_modifier,own_goal_rate,opp_over_05_prob,tackles_per90,stat_GC,prob_plays_any
210,Matías Galarza,Paraguay,MID,0.007908,0.04,0.000000,1.000000,0.046980,0.142857,0.785710
212,Gustavo Gómez,Paraguay,DEF,0.007793,0.08,0.000000,1.000000,0.010256,0.714286,0.926121
108,Mohamed Hany,Egypt,DEF,0.007123,0.08,0.005128,0.895727,0.035897,0.571429,0.840154
233,Nuno Mendes,Portugal,DEF,0.007115,0.08,0.000000,0.802058,0.014663,0.285714,0.892531
112,Yasser Ibrahim,Egypt,DEF,0.007042,0.08,0.000000,0.895727,0.018617,0.428571,0.786872
228,Orlando Gill,Paraguay,GK,0.006964,0.01,0.000000,1.000000,0.000000,0.714286,0.902911
113,Omar Marmoush,Egypt,FWD,0.006962,0.02,0.000000,0.895727,0.012658,0.428571,0.909109
109,Ramy Rabia,Egypt,DEF,0.006856,0.08,0.000000,0.895727,0.014388,0.285714,0.648912
348,Diogo Costa,Portugal,GK,0.006798,0.01,0.000000,0.802058,0.000000,0.285714,0.937479
217,Juan José Cáceres,Paraguay,DEF,0.006756,0.08,0.000000,1.000000,0.051576,0.571429,0.610705
352,Cristiano Ronaldo,Portugal,FWD,0.006695,0.02,0.000000,0.802058,0.005698,0.285714,0.919309
361,Mohamed Salah,Egypt,MID,0.006683,0.04,0.000000,0.895727,0.002959,0.571429,0.885897
362,Andrés Cubas,Paraguay,MID,0.006592,0.04,0.000000,1.000000,0.035897,0.714286,0.678088
118,Mostafa Shobeir,Egypt,GK,0.006525,0.01,0.000000,0.895727,0.000000,0.571429,0.881843
349,Rúben Dias,Portugal,DEF,0.006456,0.08,0.000000,0.802058,0.018519,0.142857,0.737912
251,Bruno Fernandes,Portugal,MID,0.006429,0.04,0.000000,0.802058,0.024024,0.285714,0.883563
213,Júnior Alonso,Paraguay,DEF,0.006356,0.08,0.000000,1.000000,0.026667,0.714286,0.616112
381,Alistair Johnston,Canada,DEF,0.006297,0.08,0.000000,0.758707,0.002778,0.428571,0.846049
237,Renato Veiga,Portugal,DEF,0.006292,0.08,0.000000,0.802058,0.008333,0.285714,0.657476
313,Matt Freese,USA,GK,0.006287,0.01,0.000000,0.730981,0.000000,0.142857,0.896671
230,Julio Enciso,Paraguay,MID,0.006269,0.04,0.000000,1.000000,0.012270,0.714286,0.844803
101,Marwan Attia,Egypt,MID,0.006210,0.04,0.000000,0.895727,0.017442,0.428571,0.632385
70,Maxime Crépeau,Canada,GK,0.006181,0.01,0.000000,0.758707,0.002778,0.428571,0.937479
279,Ricardo Rodríguez,Switzerland,DEF,0.006075,0.08,0.000000,0.678150,0.022284,0.285714,0.828796
104,Emam Ashour,Egypt,MID,0.006050,0.04,0.000000,0.895727,0.009346,0.571429,0.747758
278,Manuel Akanji,Switzerland,DEF,0.006047,0.08,0.000000,0.678150,0.019444,0.428571,0.894454
65,Jonathan David,Canada,FWD,0.006035,0.02,0.000000,0.758707,0.003021,0.428571,0.910190
199,Erling Haaland,Norway,FWD,0.005977,0.02,0.000000,0.847671,0.000000,0.571429,0.887407
61,Richie Laryea,Canada,DEF,0.005976,0.08,0.000000,0.758707,0.025496,0.428571,0.766209
203,Ørjan Nyland,Norway,GK,0.005967,0.01,0.000000,0.847671,0.000000,0.571429,0.896671

In [67]:
position_pc_modifier = {
    "GK": 0.02,
    "FWD": 0.03,
    "MID": 0.06,
    "DEF": 0.10,
}

df["position_pc_modifier"] = df["position"].map(position_pc_modifier)

raw_pc = (
    0.30 * df["position_pc_modifier"]
  + 0.25 * df["penalty_conceded_rate"]
  + 0.05 * df["tackles_per90"]
  + 0.15 * df["prob_yellow_card"]
  + 0.15 * df["opp_over_05_prob"]
)

df["prob_penalty_committed"] = 0.08 * sigmoid((raw_pc - 0.5) * 5) * df["prob_plays_60min"]

In [68]:
cols = [
    "name",
    "team",
    "position",
    "prob_penalty_committed",
    "position_pc_modifier",
    "penalty_conceded_rate",
    "tackles_per90",
    "prob_yellow_card",
    "opp_over_05_prob",
    "prob_plays_any",
]

df[cols].sort_values("prob_penalty_committed", ascending=False).head(30)

,name,team,position,prob_penalty_committed,position_pc_modifier,penalty_conceded_rate,tackles_per90,prob_yellow_card,opp_over_05_prob,prob_plays_any
212,Gustavo Gómez,Paraguay,DEF,0.013256,0.10,0.0,0.010256,0.098385,1.000000,0.926121
228,Orlando Gill,Paraguay,GK,0.011846,0.02,0.0,0.000000,0.090798,1.000000,0.902911
108,Mohamed Hany,Egypt,DEF,0.011732,0.10,0.0,0.035897,0.088192,0.895727,0.840154
362,Andrés Cubas,Paraguay,MID,0.011315,0.06,0.0,0.035897,0.105619,1.000000,0.678088
210,Matías Galarza,Paraguay,MID,0.011267,0.06,0.0,0.046980,0.131623,1.000000,0.785710
112,Yasser Ibrahim,Egypt,DEF,0.011212,0.10,0.0,0.018617,0.112540,0.895727,0.786872
361,Mohamed Salah,Egypt,MID,0.011168,0.06,0.0,0.002959,0.088875,0.895727,0.885897
113,Omar Marmoush,Egypt,FWD,0.010909,0.03,0.0,0.012658,0.086713,0.895727,0.909109
217,Juan José Cáceres,Paraguay,DEF,0.010849,0.10,0.0,0.051576,0.097152,1.000000,0.610705
233,Nuno Mendes,Portugal,DEF,0.010826,0.10,0.0,0.014663,0.080598,0.802058,0.892531
118,Mostafa Shobeir,Egypt,GK,0.010807,0.02,0.0,0.000000,0.082862,0.895727,0.881843
213,Júnior Alonso,Paraguay,DEF,0.010783,0.10,0.0,0.026667,0.098055,1.000000,0.616112
230,Julio Enciso,Paraguay,MID,0.010670,0.06,0.0,0.012270,0.085833,1.000000,0.844803
348,Diogo Costa,Portugal,GK,0.010375,0.02,0.0,0.000000,0.079412,0.802058,0.937479
381,Alistair Johnston,Canada,DEF,0.010305,0.10,0.0,0.002778,0.089434,0.758707,0.846049
352,Cristiano Ronaldo,Portugal,FWD,0.010196,0.03,0.0,0.005698,0.080782,0.802058,0.919309
28,Brandon Mechele,Belgium,DEF,0.010162,0.10,0.0,0.007692,0.087237,0.704143,0.797111
109,Ramy Rabia,Egypt,DEF,0.010150,0.10,0.0,0.014388,0.076111,0.895727,0.648912
70,Maxime Crépeau,Canada,GK,0.010080,0.02,0.0,0.002778,0.077231,0.758707,0.937479
104,Emam Ashour,Egypt,MID,0.010047,0.06,0.0,0.009346,0.080610,0.895727,0.747758
278,Manuel Akanji,Switzerland,DEF,0.010023,0.10,0.0,0.019444,0.074647,0.678150,0.894454
199,Erling Haaland,Norway,FWD,0.010002,0.03,0.0,0.000000,0.079256,0.847671,0.887407
203,Ørjan Nyland,Norway,GK,0.009995,0.02,0.0,0.000000,0.076780,0.847671,0.896671
342,Thibaut Courtois,Belgium,GK,0.009993,0.02,0.0,0.000000,0.076344,0.704143,0.947350
101,Marwan Attia,Egypt,MID,0.009849,0.06,0.0,0.017442,0.093430,0.895727,0.632385
251,Bruno Fernandes,Portugal,MID,0.009837,0.06,0.0,0.024024,0.079232,0.802058,0.883563
65,Jonathan David,Canada,FWD,0.009819,0.03,0.0,0.003021,0.077718,0.758707,0.910190
280,Nico Elvedi,Switzerland,DEF,0.009739,0.10,0.0,0.008333,0.084759,0.678150,0.837816
39,Youri Tielemans,Belgium,MID,0.009733,0.06,0.0,0.010390,0.077678,0.704143,0.828441
61,Richie Laryea,Canada,DEF,0.009638,0.10,0.0,0.025496,0.072348,0.758707,0.766209

In [69]:
df["lambda_opp"] = -np.log(df["team_cs_prob"].clip(lower=0.01))

df["prob_gc_0"] = np.exp(-df["lambda_opp"])
df["prob_gc_1"] = df["lambda_opp"] * np.exp(-df["lambda_opp"])
df["prob_gc_2"] = (df["lambda_opp"] ** 2 / 2) * np.exp(-df["lambda_opp"])
df["prob_gc_3"] = (df["lambda_opp"] ** 3 / 6) * np.exp(-df["lambda_opp"])
df["prob_gc_4plus"] = 1 - (
    df["prob_gc_0"]
    + df["prob_gc_1"]
    + df["prob_gc_2"]
    + df["prob_gc_3"]
)

# RAW expected goals conceded (true intensity)
df["expected_goals_conceded"] = df["lambda_opp"]

# Normalize ONLY as auxiliary feature (separate column)
scaler = MinMaxScaler()
df["expected_goals_conceded_norm"] = scaler.fit_transform(
    df[["expected_goals_conceded"]]
)

# Player exposure to goals conceded (correct)
df["expected_player_goals_conceded"] = (
    df["lambda_opp"] * df["prob_plays_60min"]
)

# GC penalty MUST use raw λ (correct Poisson expectation)
df["expected_gc_penalty"] = (
    -(df["lambda_opp"] - 1 + np.exp(-df["lambda_opp"]))
    * df["prob_plays_60min"]
)

df.loc[df["position"].isin(["MID", "FWD"]), [
    "expected_player_goals_conceded",
    "expected_gc_penalty"
]] = 0.0

In [70]:
cols = [
    "name",
    "team",
    "position",
    "prob_plays_60min",
    "team_cs_prob",
    "lambda_opp",
    "prob_gc_0",
    "prob_gc_1",
    "prob_gc_2",
    "prob_gc_3",
    "prob_gc_4plus",
    "expected_player_goals_conceded",
    "expected_gc_penalty",
]

df[df["position"].isin(["GK", "DEF"])][cols] \
    .sort_values("expected_gc_penalty") \
    .head(30)

,name,team,position,prob_plays_60min,team_cs_prob,lambda_opp,prob_gc_0,prob_gc_1,prob_gc_2,prob_gc_3,prob_gc_4plus,expected_player_goals_conceded,expected_gc_penalty
212,Gustavo Gómez,Paraguay,DEF,0.926121,0.000000,4.605170,0.010000,0.046052,0.106038,0.162774,0.675136,4.264943,-3.348084
228,Orlando Gill,Paraguay,GK,0.920561,0.000000,4.605170,0.010000,0.046052,0.106038,0.162774,0.675136,4.239342,-3.327986
217,Juan José Cáceres,Paraguay,DEF,0.752093,0.000000,4.605170,0.010000,0.046052,0.106038,0.162774,0.675136,3.463517,-2.718945
213,Júnior Alonso,Paraguay,DEF,0.750913,0.000000,4.605170,0.010000,0.046052,0.106038,0.162774,0.675136,3.458083,-2.714679
214,Omar Alderete,Paraguay,DEF,0.461743,0.000000,4.605170,0.010000,0.046052,0.106038,0.162774,0.675136,2.126403,-1.669278
218,José Canale,Paraguay,DEF,0.342546,0.000000,4.605170,0.010000,0.046052,0.106038,0.162774,0.675136,1.577485,-1.238364
118,Mostafa Shobeir,Egypt,GK,0.901699,0.104868,2.255052,0.104868,0.236483,0.266641,0.200430,0.191579,2.033379,-1.226239
108,Mohamed Hany,Egypt,DEF,0.875242,0.104868,2.255052,0.104868,0.236483,0.266641,0.200430,0.191579,1.973717,-1.190259
112,Yasser Ibrahim,Egypt,DEF,0.826859,0.104868,2.255052,0.104868,0.236483,0.266641,0.200430,0.191579,1.864611,-1.124463
216,Gustavo Velázquez,Paraguay,DEF,0.310458,0.000000,4.605170,0.010000,0.046052,0.106038,0.162774,0.675136,1.429713,-1.122359
109,Ramy Rabia,Egypt,DEF,0.766402,0.104868,2.255052,0.104868,0.236483,0.266641,0.200430,0.191579,1.728277,-1.042246
226,Roberto Fernández,Paraguay,GK,0.266002,0.000000,4.605170,0.010000,0.046052,0.106038,0.162774,0.675136,1.224987,-0.961644
203,Ørjan Nyland,Norway,GK,0.863358,0.156961,1.851759,0.156961,0.290654,0.269110,0.166109,0.117166,1.598730,-0.870886
191,Kristoffer Ajer,Norway,DEF,0.741758,0.156961,1.851759,0.156961,0.290654,0.269110,0.166109,0.117166,1.373558,-0.748226
227,Gastón Olveira,Paraguay,GK,0.206689,0.000000,4.605170,0.010000,0.046052,0.106038,0.162774,0.675136,0.951838,-0.747216
348,Diogo Costa,Portugal,GK,0.921262,0.207916,1.570620,0.207916,0.326557,0.256449,0.134261,0.074816,1.446952,-0.717235
233,Nuno Mendes,Portugal,DEF,0.864615,0.207916,1.570620,0.207916,0.326557,0.256449,0.134261,0.074816,1.357982,-0.673134
195,David Møller Wolfe,Norway,DEF,0.646741,0.156961,1.851759,0.156961,0.290654,0.269110,0.166109,0.117166,1.197608,-0.652380
107,Ahmed Fatouh,Egypt,DEF,0.456862,0.104868,2.255052,0.104868,0.236483,0.266641,0.200430,0.191579,1.030248,-0.621296
70,Maxime Crépeau,Canada,GK,0.921262,0.241583,1.420541,0.241583,0.343179,0.243750,0.115419,0.056069,1.308690,-0.609990
237,Renato Veiga,Portugal,DEF,0.766337,0.207916,1.570620,0.207916,0.326557,0.256449,0.134261,0.074816,1.203624,-0.596621
193,Marcus Pedersen,Norway,DEF,0.586851,0.156961,1.851759,0.156961,0.290654,0.269110,0.166109,0.117166,1.086706,-0.591968
197,Torbjørn Heggem,Norway,DEF,0.578687,0.156961,1.851759,0.156961,0.290654,0.269110,0.166109,0.117166,1.071588,-0.583733
349,Rúben Dias,Portugal,DEF,0.744304,0.207916,1.570620,0.207916,0.326557,0.256449,0.134261,0.074816,1.169019,-0.579468
381,Alistair Johnston,Canada,DEF,0.843267,0.241583,1.420541,0.241583,0.343179,0.243750,0.115419,0.056069,1.197896,-0.558348
61,Richie Laryea,Canada,DEF,0.793486,0.241583,1.420541,0.241583,0.343179,0.243750,0.115419,0.056069,1.127179,-0.525386
313,Matt Freese,USA,GK,0.863358,0.267743,1.317726,0.267743,0.352812,0.232455,0.102104,0.044885,1.137669,-0.505470
62,Derek Cornelius,Canada,DEF,0.731729,0.241583,1.420541,0.241583,0.343179,0.243750,0.115419,0.056069,1.039451,-0.484496
357,Karim Hafez,Egypt,DEF,0.352290,0.104868,2.255052,0.104868,0.236483,0.266641,0.200430,0.191579,0.794431,-0.479086
234,João Cancelo,Portugal,DEF,0.611201,0.207916,1.570620,0.207916,0.326557,0.256449,0.134261,0.074816,0.959965,-0.475842

In [71]:
raw_save = (
    0.25 * df["expected_goals_conceded"]  # opportunity
  + 0.20 * df["saves_per90"]             # ability
  + 0.05 * df["recent_saves_per90"]      # recent form
  + 0.20 * df["price"]                   # overall GK quality
)

# Expected saves (λ)
df["expected_saves"] = (
    sigmoid((raw_save - 0.5) * 6) * 4
) * df["prob_plays_60min"]

df.loc[df["position"] != "GK", "expected_saves"] = 0.0

In [72]:
cols = [
    "name",
    "team",
    "expected_saves",
    "expected_goals_conceded",
    "saves_per90",
    "recent_saves_per90",
    "price",
    "prob_plays_any",
]

df[df["position"] == "GK"][cols] \
    .sort_values("expected_saves", ascending=False) \
    .head(30)

,name,team,expected_saves,expected_goals_conceded,saves_per90,recent_saves_per90,price,prob_plays_any
228,Orlando Gill,Paraguay,3.662987,4.605170,0.876923,0.960000,0.000000,0.902911
118,Mostafa Shobeir,Egypt,2.680404,2.255052,0.461538,0.420000,0.000000,0.881843
348,Diogo Costa,Portugal,2.458976,1.570620,0.700000,0.866667,0.200000,0.937479
203,Ørjan Nyland,Norway,2.196057,1.851759,0.400000,0.600000,0.100000,0.896671
289,Gregor Kobel,Switzerland,1.727008,1.125822,0.650000,0.666667,0.171429,0.937479
342,Thibaut Courtois,Belgium,1.574623,1.196268,0.415385,0.420000,0.200000,0.947350
70,Maxime Crépeau,Canada,1.458121,1.420541,0.250000,0.200000,0.071429,0.937479
313,Matt Freese,USA,1.424732,1.317726,0.333333,0.500000,0.100000,0.896671
56,Alisson Becker,Brazil,1.170635,0.772659,0.550000,0.600000,0.214286,0.923274
204,Egil Selvik,Norway,1.146995,1.851759,1.000000,1.000000,0.042857,0.449405
226,Roberto Fernández,Paraguay,1.044749,4.605170,0.000000,0.000000,0.071429,0.463813
177,Raúl Rangel,Mexico,0.851986,0.895133,0.310345,0.279070,0.057143,0.878122
227,Gastón Olveira,Paraguay,0.811278,4.605170,0.000000,0.000000,0.042857,0.285978
134,Jordan Pickford,England,0.756739,0.669320,0.300000,0.200000,0.185714,0.937479
266,Unai Simón,Spain,0.756639,0.734007,0.200000,0.200000,0.214286,0.927081
91,Camilo Vargas,Colombia,0.601262,0.618649,0.200000,0.200000,0.114286,0.937479
395,Yassine Bounou,Morocco,0.561826,0.451790,0.276923,0.120000,0.171429,0.947350
116,Mohamed El Shenawy,Egypt,0.500334,2.255052,0.000000,0.000000,0.014286,0.396517
117,El Mahdy Soliman,Egypt,0.438156,2.255052,0.000000,0.000000,0.014286,0.253506
312,Matt Turner,USA,0.408158,1.317726,0.000000,0.000000,0.071429,0.449405
119,Mohamed Alaa,Egypt,0.406569,2.255052,0.000000,0.000000,0.000000,0.253506
153,Mike Maignan,France,0.386932,-0.000000,0.400000,0.400000,0.214286,0.937479
10,Emiliano Martínez,Argentina,0.347738,0.100670,0.184615,0.240000,0.214286,0.952574
245,Rui Silva,Portugal,0.324198,1.570620,0.000000,0.000000,0.171429,0.345247
246,José Sá,Portugal,0.296818,1.570620,0.000000,0.000000,0.171429,0.253506
368,Sander Tangvik,Norway,0.293825,1.851759,0.000000,0.000000,0.000000,0.274881
71,Dayne St. Clair,Canada,0.253185,1.420541,0.000000,0.000000,0.042857,0.285978
36,Senne Lammens,Belgium,0.239373,1.196268,0.000000,0.000000,0.157143,0.383433
175,Guillermo Ochoa,Mexico,0.224306,0.895133,0.000000,0.000000,0.100000,0.523214
72,Owen Goodman,Canada,0.223616,1.420541,0.000000,0.000000,0.000000,0.308957

In [73]:
raw_pen_save = (
    0.40 * df["price"]                    
  + 0.25 * df["expected_goals_conceded"]
  + 0.15 * df["opp_over_05_prob"]
  + 0.05 * df["stat_PS"]
)

# Strong compression because penalty saves are exceptionally rare
df["prob_penalty_save"] = sigmoid((raw_pen_save - 0.5) * 3) / 20 * df["prob_plays_60min"]

df.loc[df["position"] != "GK", "prob_penalty_save"] = 0.0

In [74]:
cols = [
    "name",
    "team",
    "prob_penalty_save",
    "price",
    "expected_goals_conceded",
    "opp_over_05_prob",
    "prob_plays_60min",
    "stat_PS",
]

df[df["position"] == "GK"][cols] \
    .sort_values("prob_penalty_save", ascending=False) \
    .head(30)

,name,team,prob_penalty_save,price,expected_goals_conceded,opp_over_05_prob,prob_plays_60min,stat_PS
228,Orlando Gill,Paraguay,0.042213,0.000000,4.605170,1.000000,0.920561,0.0
118,Mostafa Shobeir,Egypt,0.030565,0.000000,2.255052,0.895727,0.901699,1.0
348,Diogo Costa,Portugal,0.026223,0.200000,1.570620,0.802058,0.921262,0.0
203,Ørjan Nyland,Norway,0.025743,0.100000,1.851759,0.847671,0.863358,0.0
342,Thibaut Courtois,Belgium,0.023140,0.200000,1.196268,0.704143,0.947350,0.0
70,Maxime Crépeau,Canada,0.022946,0.071429,1.420541,0.758707,0.921262,0.0
289,Gregor Kobel,Switzerland,0.021368,0.171429,1.125822,0.678150,0.921262,0.0
313,Matt Freese,USA,0.020907,0.100000,1.317726,0.730981,0.863358,0.0
56,Alisson Becker,Brazil,0.017996,0.214286,0.772659,0.537898,0.908430,0.0
266,Unai Simón,Spain,0.017717,0.214286,0.734007,0.527296,0.912904,0.0
134,Jordan Pickford,England,0.016786,0.185714,0.669320,0.486359,0.921262,0.0
177,Raúl Rangel,Mexico,0.016571,0.057143,0.895133,0.593284,0.874073,0.0
91,Camilo Vargas,Colombia,0.015354,0.114286,0.618649,0.457119,0.921262,0.0
395,Yassine Bounou,Morocco,0.014787,0.171429,0.451790,0.367721,0.947350,0.0
226,Roberto Fernández,Paraguay,0.012281,0.071429,4.605170,1.000000,0.266002,0.0
10,Emiliano Martínez,Argentina,0.011679,0.214286,0.100670,0.095599,0.952574,0.0
153,Mike Maignan,France,0.011566,0.214286,-0.000000,0.000000,0.921262,1.0
204,Egil Selvik,Norway,0.010512,0.042857,1.851759,0.847671,0.362658,0.0
227,Gastón Olveira,Paraguay,0.009517,0.042857,4.605170,1.000000,0.206689,0.0
312,Matt Turner,USA,0.008627,0.071429,1.317726,0.730981,0.362658,0.0
116,Mohamed El Shenawy,Egypt,0.006773,0.014286,2.255052,0.895727,0.208953,0.0
175,Guillermo Ochoa,Mexico,0.006202,0.100000,0.895133,0.593284,0.316945,0.0
117,El Mahdy Soliman,Egypt,0.005931,0.014286,2.255052,0.895727,0.182985,0.0
245,Rui Silva,Portugal,0.005796,0.171429,1.570620,0.802058,0.206689,0.0
119,Mohamed Alaa,Egypt,0.005508,0.000000,2.255052,0.895727,0.170973,0.0
36,Senne Lammens,Belgium,0.005359,0.157143,1.196268,0.704143,0.225308,0.0
246,José Sá,Portugal,0.005307,0.171429,1.570620,0.802058,0.189233,0.0
55,Ederson,Brazil,0.005270,0.214286,0.772659,0.537898,0.266002,0.0
71,Dayne St. Clair,Canada,0.005059,0.042857,1.420541,0.758707,0.206689,0.0
265,David Raya,Spain,0.004757,0.214286,0.734007,0.527296,0.245085,0.0

In [75]:
raw_tackles = (
    0.40 * df["tackles_per90"]
  + 0.20 * df["recent_tackles_per90"]
  + 0.05 * df["expected_goals_conceded"]
  + 0.10 * df["match_over_25_prob"]
  + 0.15 * df["price"]
)

lam_tackles = sigmoid((raw_tackles - 0.5) * 6) * 3
df["expected_tackle_points"] = (lam_tackles / 3) * df["prob_plays_60min"]
df.loc[df["position"] != "MID", "expected_tackle_points"] = 0.0

In [76]:
cols = [
    "name",
    "team",
    "expected_tackle_points",
    "tackles_per90",
    "recent_tackles_per90",
    "expected_goals_conceded",
    "match_over_25_prob",
    "price",
    "prob_plays_60min",
]

df[df["position"] == "MID"][cols] \
    .sort_values("expected_tackle_points", ascending=False) \
    .head(30)

,name,team,expected_tackle_points,tackles_per90,recent_tackles_per90,expected_goals_conceded,match_over_25_prob,price,prob_plays_60min
210,Matías Galarza,Paraguay,0.311792,0.046980,0.234899,4.605170,1.000000,0.185714,0.804053
362,Andrés Cubas,Paraguay,0.291820,0.035897,0.150000,4.605170,1.000000,0.171429,0.822493
230,Julio Enciso,Paraguay,0.290604,0.012270,0.042373,4.605170,1.000000,0.442857,0.789073
219,Miguel Almirón,Paraguay,0.234775,0.032710,0.185185,4.605170,1.000000,0.357143,0.583723
361,Mohamed Salah,Egypt,0.204819,0.002959,0.000000,2.255052,0.475278,0.928571,0.881791
231,Diego Gómez,Paraguay,0.200562,0.033898,0.192308,4.605170,1.000000,0.471429,0.466473
229,Damián Bobadilla,Paraguay,0.178130,0.036842,0.241379,4.605170,1.000000,0.285714,0.439449
251,Bruno Fernandes,Portugal,0.171847,0.024024,0.102881,1.570620,0.614339,0.714286,0.825673
48,Vinícius Júnior,Brazil,0.170297,0.005698,0.019157,0.772659,0.796663,0.928571,0.873305
371,Martin Ødegaard,Norway,0.167691,0.022989,0.111111,1.851759,0.796663,0.600000,0.745991
299,Weston McKennie,USA,0.146417,0.022599,0.151515,1.317726,0.796663,0.371429,0.840645
150,Ousmane Dembélé,France,0.144716,0.010417,0.048077,-0.000000,1.000000,0.928571,0.781460
269,Rodri,Spain,0.141730,0.039216,0.222222,0.734007,0.614339,0.571429,0.800285
162,Michael Olise,France,0.141649,0.012987,0.045872,-0.000000,1.000000,0.857143,0.803942
346,Leandro Trossard,Belgium,0.137187,0.013850,0.055351,1.196268,0.796663,0.442857,0.862233
250,João Neves,Portugal,0.135871,0.029900,0.189573,1.570620,0.614339,0.428571,0.729915
260,Lamine Yamal,Spain,0.135269,0.008889,0.048544,0.734007,0.614339,0.928571,0.739021
323,Bruno Guimarães,Brazil,0.130121,0.029412,0.134615,0.772659,0.796663,0.471429,0.796764
39,Youri Tielemans,Belgium,0.130081,0.010390,0.050847,1.196268,0.796663,0.371429,0.873335
271,Pedri,Spain,0.128701,0.025890,0.136986,0.734007,0.614339,0.657143,0.761870
40,Kevin De Bruyne,Belgium,0.125423,0.006645,0.046512,1.196268,0.796663,0.571429,0.732568
298,Malik Tillman,USA,0.122595,0.022556,0.163043,1.317726,0.796663,0.371429,0.695948
59,Casemiro,Brazil,0.117021,0.041522,0.225410,0.772659,0.796663,0.400000,0.673935
104,Emam Ashour,Egypt,0.110422,0.009346,0.040000,2.255052,0.475278,0.157143,0.796347
19,Alexis Mac Allister,Argentina,0.108584,0.036474,0.230126,0.100670,0.475278,0.442857,0.850990
101,Marwan Attia,Egypt,0.107535,0.017442,0.059055,2.255052,0.475278,0.114286,0.773043
160,Aurélien Tchouaméni,France,0.106234,0.051852,0.305556,-0.000000,1.000000,0.428571,0.593502
208,Maurício Magalhães Prado,Paraguay,0.105409,0.039216,0.185185,4.605170,1.000000,0.157143,0.290071
315,Christian Pulisic,USA,0.103983,0.012121,0.041667,1.317726,0.796663,0.500000,0.617775
206,Antonio Nusa,Norway,0.102974,0.013514,0.067114,1.851759,0.796663,0.371429,0.573427

In [77]:
raw_cc = (
    0.20 * df["cc_per90"]
  + 0.10 * df["recent_cc_per90"]
  + 0.10 * df["stat_CC"]
  + 0.25 * df["match_over_25_prob"]
  + 0.10 * df["anytime_scorer_prob"]
  + 0.10 * df["price"]
)
lam_cc = sigmoid((raw_cc - 0.5) * 6) * 3
df["expected_cc_points"] = (lam_cc / 2) * df["prob_plays_60min"]
df.loc[df["position"] != "MID", "expected_cc_points"] = 0.0

In [78]:
cols = [
    "name",
    "team",
    "position",
    "expected_cc_points",
    "cc_per90",
    "recent_cc_per90",
    "stat_CC",
    "match_over_25_prob",
    "anytime_scorer_prob",
    "price",
    "prob_plays_60min",
]

df[cols].sort_values("expected_cc_points", ascending=False).head(30)

,name,team,position,expected_cc_points,cc_per90,recent_cc_per90,stat_CC,match_over_25_prob,anytime_scorer_prob,price,prob_plays_60min
162,Michael Olise,France,MID,0.675390,0.162338,0.178899,1.0,1.000000,0.541660,0.857143,0.803942
150,Ousmane Dembélé,France,MID,0.496477,0.034722,0.062500,0.2,1.000000,0.725769,0.928571,0.781460
48,Vinícius Júnior,Brazil,MID,0.454481,0.028490,0.049808,0.2,0.796663,0.718813,0.928571,0.873305
230,Julio Enciso,Paraguay,MID,0.379423,0.061350,0.055085,0.4,1.000000,0.227392,0.442857,0.789073
346,Leandro Trossard,Belgium,MID,0.366623,0.055402,0.095941,0.4,0.796663,0.413201,0.442857,0.862233
323,Bruno Guimarães,Brazil,MID,0.362943,0.088235,0.150000,0.6,0.796663,0.227392,0.471429,0.796764
333,Bradley Barcola,France,MID,0.329775,0.048077,0.065657,0.2,1.000000,0.584171,0.642857,0.599648
371,Martin Ødegaard,Norway,MID,0.317972,0.076628,0.072222,0.4,0.796663,0.243005,0.600000,0.745991
251,Bruno Fernandes,Portugal,MID,0.310615,0.060060,0.106996,0.4,0.614339,0.298810,0.714286,0.825673
210,Matías Galarza,Paraguay,MID,0.301371,0.033557,0.043624,0.2,1.000000,0.171433,0.185714,0.804053
39,Youri Tielemans,Belgium,MID,0.294539,0.025974,0.000000,0.2,0.796663,0.322152,0.371429,0.873335
315,Christian Pulisic,USA,MID,0.293460,0.121212,0.000000,0.4,0.796663,0.584171,0.500000,0.617775
361,Mohamed Salah,Egypt,MID,0.272948,0.029586,0.049618,0.2,0.475278,0.329417,0.928571,0.881791
260,Lamine Yamal,Spain,MID,0.263806,0.000000,0.000000,0.0,0.614339,0.595919,0.928571,0.739021
299,Weston McKennie,USA,MID,0.259482,0.000000,0.000000,0.0,0.796663,0.385995,0.371429,0.840645
156,Adrien Rabiot,France,MID,0.256517,0.037037,0.000000,0.2,1.000000,0.333127,0.414286,0.586244
190,Patrick Berg,Norway,MID,0.255241,0.128205,0.173333,0.6,0.796663,0.171433,0.300000,0.590492
40,Kevin De Bruyne,Belgium,MID,0.251586,0.000000,0.000000,0.0,0.796663,0.413201,0.571429,0.732568
362,Andrés Cubas,Paraguay,MID,0.250449,0.000000,0.000000,0.0,1.000000,0.049158,0.171429,0.822493
298,Malik Tillman,USA,MID,0.237261,0.037594,0.000000,0.2,0.796663,0.322152,0.371429,0.695948
152,Désiré Doué,France,MID,0.228278,0.046729,0.102362,0.2,1.000000,0.584171,0.571429,0.421060
271,Pedri,Spain,MID,0.226946,0.032362,0.000000,0.2,0.614339,0.217035,0.657143,0.761870
219,Miguel Almirón,Paraguay,MID,0.207657,0.000000,0.000000,0.0,1.000000,0.195703,0.357143,0.583723
186,Ismael Saibari,Morocco,MID,0.202325,0.055096,0.094891,0.4,0.183560,0.579688,0.471429,0.896428
269,Rodri,Spain,MID,0.201784,0.000000,0.000000,0.0,0.614339,0.227392,0.571429,0.800285
19,Alexis Mac Allister,Argentina,MID,0.201591,0.030395,0.000000,0.2,0.475278,0.318596,0.442857,0.850990
60,Lucas Paquetá,Brazil,MID,0.200674,0.127119,0.222857,0.6,0.796663,0.000000,0.428571,0.463364
160,Aurélien Tchouaméni,France,MID,0.199362,0.000000,0.000000,0.0,1.000000,0.000000,0.428571,0.593502
59,Casemiro,Brazil,MID,0.195429,0.000000,0.000000,0.0,0.796663,0.227392,0.400000,0.673935
20,Enzo Fernández,Argentina,MID,0.185389,0.000000,0.000000,0.0,0.475278,0.349204,0.571429,0.824023

In [79]:
raw_sot = (
    0.35 * df["sot_per90"]
  + 0.20 * df["goal_rate"]
  + 0.15 * df["stat_GS"]
  + 0.20 * df["match_over_25_prob"]
  + 0.10 * df["anytime_scorer_prob"]
  + 0.10 * df["price"]
)
lam_sot = sigmoid((raw_sot - 0.5) * 6) * 3  # expected SoT volume per game
df["expected_sot_points"] = (lam_sot / 2) * df["prob_plays_60min"]
df.loc[~df["position"].isin(["FWD"]), "expected_sot_points"] = 0.0

In [80]:
cols = [
    "name",
    "team",
    "position",
    "expected_sot_points",
    "sot_per90",
    "goal_rate",
    "stat_GS",
    "match_over_25_prob",
    "anytime_scorer_prob",
    "price",
    "prob_plays_60min",
]

df[cols].sort_values("expected_sot_points", ascending=False).head(30)

,name,team,position,expected_sot_points,sot_per90,goal_rate,stat_GS,match_over_25_prob,anytime_scorer_prob,price,prob_plays_60min
149,Kylian Mbappé,France,FWD,1.086880,0.351852,0.324786,0.857143,1.000000,1.000000,1.000000,0.922048
5,Lionel Messi,Argentina,FWD,1.008044,0.445312,0.415625,1.000000,0.475278,0.943886,0.928571,0.912498
199,Erling Haaland,Norway,FWD,0.859621,0.316667,0.351852,0.714286,0.796663,0.725769,1.000000,0.851601
262,Mikel Oyarzabal,Spain,FWD,0.629257,0.252492,0.252492,0.571429,0.614339,0.725769,0.657143,0.876473
352,Cristiano Ronaldo,Portugal,FWD,0.545762,0.189459,0.162393,0.428571,0.614339,0.591127,0.928571,0.891920
49,Matheus Cunha,Brazil,FWD,0.525831,0.202128,0.242553,0.428571,0.796663,0.633792,0.542857,0.794758
128,Harry Kane,England,FWD,0.500544,0.241525,0.268362,0.714286,0.000000,0.633792,1.000000,0.910706
31,Romelu Lukaku,Belgium,FWD,0.440351,0.107345,0.214689,0.285714,0.796663,0.698717,0.557143,0.802544
65,Jonathan David,Canada,FWD,0.296846,0.200906,0.172205,0.428571,0.183560,0.366672,0.500000,0.885500
320,Lautaro Martínez,Argentina,FWD,0.241714,0.078189,0.078189,0.142857,0.475278,0.692224,0.757143,0.682138
286,Breel Embolo,Switzerland,FWD,0.228240,0.109510,0.109510,0.285714,0.142151,0.480445,0.571429,0.890720
170,Julián Quiñones,Mexico,FWD,0.190535,0.142643,0.171171,0.428571,0.000000,0.431288,0.300000,0.802170
239,Gonçalo Ramos,Portugal,FWD,0.185689,0.279412,0.558824,0.142857,0.614339,0.496522,0.571429,0.280551
113,Omar Marmoush,Egypt,FWD,0.185534,0.030063,0.000000,0.000000,0.475278,0.281342,0.614286,0.894106
200,Alexander Sørloth,Norway,FWD,0.182796,0.000000,0.000000,0.000000,0.796663,0.401917,0.471429,0.679053
53,Rayan,Brazil,FWD,0.175689,0.042793,0.000000,0.000000,0.796663,0.488329,0.300000,0.632242
169,Raúl Jiménez,Mexico,FWD,0.173194,0.165217,0.165217,0.285714,0.000000,0.488329,0.500000,0.690014
114,Trezeguet,Egypt,FWD,0.163072,0.197917,0.131944,0.142857,0.475278,0.281342,0.300000,0.540125
6,Julián Alvarez,Argentina,FWD,0.162659,0.095000,0.000000,0.000000,0.475278,0.692224,0.728571,0.538481
288,Dan Ndoye,Switzerland,FWD,0.162026,0.203863,0.081545,0.142857,0.142151,0.349204,0.471429,0.689044
261,Ferran Torres,Spain,FWD,0.153813,0.119497,0.000000,0.000000,0.614339,0.584171,0.614286,0.476090
309,Ricardo Pepi,USA,FWD,0.150470,0.000000,0.000000,0.000000,0.796663,0.584171,0.342857,0.544431
33,Dodi Lukébakio,Belgium,FWD,0.145320,0.098958,0.000000,0.000000,0.796663,0.385995,0.342857,0.489309
223,Gabriel Ávalos,Paraguay,FWD,0.134342,0.000000,0.000000,0.000000,1.000000,0.227392,0.200000,0.508822
407,Soufiane Rahimi,Morocco,FWD,0.122101,0.311475,0.311475,0.142857,0.183560,0.496522,0.300000,0.337292
66,Cyle Larin,Canada,FWD,0.112225,0.234568,0.234568,0.285714,0.183560,0.305148,0.385714,0.358835
89,Luis Suárez,Colombia,FWD,0.103141,0.000000,0.000000,0.000000,0.142151,0.513681,0.314286,0.777350
220,Antonio Sanabria,Paraguay,FWD,0.100852,0.000000,0.000000,0.000000,1.000000,0.227392,0.428571,0.341642
184,Ayoub El Kaabi,Morocco,FWD,0.095384,0.271429,0.000000,0.000000,0.183560,0.522646,0.342857,0.408355
67,Tajon Buchanan,Canada,FWD,0.093736,0.064626,0.000000,0.000000,0.183560,0.231102,0.285714,0.707292

In [81]:
df["expected_qualification_points"] = df["team_qualify_prob"] * 2

In [82]:
cols = [
    "name",
    "team",
    "position",
    "expected_qualification_points",
    "team_qualify_prob",
    "price",
    "prob_plays_60min",
]

df[cols].sort_values("expected_qualification_points", ascending=False).head(30)

,name,team,position,expected_qualification_points,team_qualify_prob,price,prob_plays_60min
334,Jean-Philippe Mateta,France,FWD,2.000000,1.000000,0.428571,0.212867
331,William Saliba,France,DEF,2.000000,1.000000,0.257143,0.689645
332,Jules Koundé,France,DEF,2.000000,1.000000,0.271429,0.803128
333,Bradley Barcola,France,MID,2.000000,1.000000,0.642857,0.599648
154,Brice Samba,France,GK,2.000000,1.000000,0.142857,0.206689
158,Manu Koné,France,MID,2.000000,1.000000,0.371429,0.226586
156,Adrien Rabiot,France,MID,2.000000,1.000000,0.414286,0.586244
142,Theo Hernández,France,DEF,2.000000,1.000000,0.214286,0.363809
330,Robin Risser,France,GK,2.000000,1.000000,0.000000,0.189233
153,Mike Maignan,France,GK,2.000000,1.000000,0.214286,0.921262
152,Désiré Doué,France,MID,2.000000,1.000000,0.571429,0.421060
151,Marcus Thuram,France,FWD,2.000000,1.000000,0.571429,0.181956
150,Ousmane Dembélé,France,MID,2.000000,1.000000,0.928571,0.781460
149,Kylian Mbappé,France,FWD,2.000000,1.000000,1.000000,0.922048
148,Malo Gusto,France,DEF,2.000000,1.000000,0.228571,0.127526
147,Lucas Digne,France,DEF,2.000000,1.000000,0.214286,0.437451
146,Lucas Hernández,France,DEF,2.000000,1.000000,0.242857,0.089752
145,Ibrahima Konaté,France,DEF,2.000000,1.000000,0.200000,0.076152
157,Warren Zaïre-Emery,France,MID,2.000000,1.000000,0.371429,0.060370
143,Maxence Lacroix,France,DEF,2.000000,1.000000,0.142857,0.140576
144,Dayot Upamecano,France,DEF,2.000000,1.000000,0.257143,0.850742
161,Rayan Cherki,France,MID,2.000000,1.000000,0.642857,0.191551
160,Aurélien Tchouaméni,France,MID,2.000000,1.000000,0.428571,0.593502
159,Maghnes Akliouche,France,MID,2.000000,1.000000,0.414286,0.082256
162,Michael Olise,France,MID,2.000000,1.000000,0.857143,0.803942
155,N'Golo Kanté,France,MID,2.000000,1.000000,0.228571,0.058690
9,José Manuel López,Argentina,FWD,1.806934,0.903467,0.257143,0.101198
12,Juan Musso,Argentina,GK,1.806934,0.903467,0.114286,0.165205
11,Gerónimo Rulli,Argentina,GK,1.806934,0.903467,0.142857,0.215853
6,Julián Alvarez,Argentina,FWD,1.806934,0.903467,0.728571,0.538481

In [83]:
df.to_csv(OUT_CSV, index=False)

print(f"\nSaved {OUT_CSV} {df.shape[0]} rows x {df.shape[1]} cols")

Saved fantasy_enriched.csv 414 rows x 219 cols

In [84]:
BUDGET = 105.0
MAX_PER_COUNTRY = 4
SQUAD_SIZE = 15
XI_SIZE = 11


def compute_total_expected_points(df):
    df = df.copy()

    cs_value = {"GK": 5, "DEF": 5, "MID": 1, "FWD": 0}
    goal_value = {"GK": 9, "DEF": 7, "MID": 6, "FWD": 5}

    df["goal_pts_value"] = df["position"].map(goal_value)
    df["cs_pts_value"] = df["position"].map(cs_value)

    # appearance: 1pt for playing any, +1 if 60+
    e_appearance = df["prob_plays_any"] * 1 + df["prob_plays_60min"] * 1

    # goal
    e_goal = df["prob_scores"] * df["goal_pts_value"]

    # assist
    e_assist = df["expected_assists"] * 3

    # clean sheet: gated by 60min, value depends on position
    e_cs = df["prob_clean_sheet"] * df["cs_pts_value"]

    # goals conceded penalty: GK and DEF only
    e_gc = df["expected_gc_penalty"].copy()
    e_gc[~df["position"].isin(["GK", "DEF"])] = 0.0

    # saves bonus: GK only, every 3 saves = +1
    e_saves = (df["expected_saves"] / 3).copy()
    e_saves[df["position"] != "GK"] = 0.0

    # penalty save: GK only
    e_pen_save = (df["prob_penalty_save"] * 3).copy()
    e_pen_save[df["position"] != "GK"] = 0.0

    # tackles bonus: MID only, every 3 tackles = +1
    e_tackles = df["expected_tackle_points"].copy()
    e_tackles[df["position"] != "MID"] = 0.0

    # big chances created: MID only, every 2 = +1
    e_cc = df["expected_cc_points"].copy()
    e_cc[df["position"] != "MID"] = 0.0

    # shots on target: FWD only, every 2 = +1
    e_sot = df["expected_sot_points"].copy()
    e_sot[df["position"] != "FWD"] = 0.0

    # yellow card
    e_yc = df["prob_yellow_card"] * -1

    # red card
    e_rc = df["prob_red_card"] * -2

    # own goal
    e_og = df["prob_own_goal"] * -2

    # penalty won
    e_pw = df["prob_pen_won"] * 2

    # penalty committed
    e_pc = df["prob_penalty_committed"] * -1

    # qualification bonus: +2 per player in XI who advances, requires playing
    # captain's quali bonus is NOT doubled per rules
    e_quali = df["expected_qualification_points"] * df["prob_plays_any"]

    # scouting bonus: +2 if differential==1 AND player scores >4 base pts
    # model: use Poisson confidence interval on expected base points
    # base pts = everything except scouting and captain multiplier
    base_ep = (
        e_appearance + e_goal + e_assist + e_cs + e_gc +
        e_saves + e_pen_save + e_tackles + e_cc + e_sot +
        e_yc + e_rc + e_og + e_pw + e_pc + e_quali
    )

    # Poisson 90% CI: lower = ppf(0.05, mu), upper = ppf(0.95, mu)
    mu = base_ep.clip(lower=0.01)
    lower_ci = pd.Series(poisson.ppf(0.05, mu), index=df.index)
    upper_ci = pd.Series(poisson.ppf(0.95, mu), index=df.index)

    # if lower CI > 4: full +2 expected
    # if upper CI < 4: 0
    # if CI straddles 4: scale by P(X>4 | mu) * 2
    p_exceeds_4 = pd.Series(1 - poisson.cdf(4, mu), index=df.index)

    scouting_ep = pd.Series(0.0, index=df.index)
    eligible = df["differential"] == 1
    full_bonus = eligible & (lower_ci > 4)
    no_bonus = eligible & (upper_ci < 4)
    partial = eligible & ~full_bonus & ~no_bonus

    scouting_ep[full_bonus] = 2.0
    scouting_ep[no_bonus] = 0.0
    scouting_ep[partial] = p_exceeds_4[partial] * 2.0

    df["e_appearance"] = e_appearance
    df["e_goal"] = e_goal
    df["e_assist"] = e_assist
    df["e_cs"] = e_cs
    df["e_gc"] = e_gc
    df["e_saves"] = e_saves
    df["e_pen_save"] = e_pen_save
    df["e_tackles"] = e_tackles
    df["e_cc"] = e_cc
    df["e_sot"] = e_sot
    df["e_yc"] = e_yc
    df["e_rc"] = e_rc
    df["e_og"] = e_og
    df["e_pw"] = e_pw
    df["e_pc"] = e_pc
    df["e_quali"] = e_quali
    df["e_scouting"] = scouting_ep
    df["expected_points"] = base_ep + scouting_ep

    return df

In [ ]:

def optimize_squad(df, budget=BUDGET, max_per_country=MAX_PER_COUNTRY):
    idx = df.index.tolist()

    x = LpVariable.dicts("squad", idx, cat="Binary")
    s = LpVariable.dicts("xi", idx, cat="Binary")
    b = LpVariable.dicts("bench", idx, cat="Binary")
    cap = LpVariable.dicts("cap", idx, cat="Binary")

    model = LpProblem("fantasy", LpMaximize)

    # objective: XI points + captain doubling + bench at 0 (bench value is implicit
    # through squad construction — we select best 15 then best 11 starts)
    model += lpSum(
        df.loc[i, "expected_points"] * s[i]
        + df.loc[i, "expected_points"] * cap[i]
        for i in idx
    )

    # squad = 15, xi = 11, bench = 4
    model += lpSum(x[i] for i in idx) == 15
    model += lpSum(s[i] for i in idx) == 11
    model += lpSum(b[i] for i in idx) == 4

    for i in idx:
        model += s[i] + b[i] == x[i]

    # budget
    model += lpSum(df.loc[i, "price_raw"] * x[i] for i in idx) <= budget

    # squad composition: 2 GK, 5 DEF, 5 MID, 3 FWD
    for pos, count in [("GK", 2), ("DEF", 5), ("MID", 5), ("FWD", 3)]:
        p_idx = df[df["position"] == pos].index.tolist()
        model += lpSum(x[i] for i in p_idx) == count

    # country limit
    for country in df["team"].unique():
        c_idx = df[df["team"] == country].index.tolist()
        model += lpSum(x[i] for i in c_idx) <= max_per_country

    # XI formation: 1 GK starts, valid outfield formation
    gk_idx = df[df["position"] == "GK"].index.tolist()
    model += lpSum(s[i] for i in gk_idx) == 1
    model += lpSum(b[i] for i in gk_idx) == 1

    for pos, lo, hi in [("DEF", 3, 5), ("MID", 3, 5), ("FWD", 1, 3)]:
        p_idx = df[df["position"] == pos].index.tolist()
        model += lpSum(s[i] for i in p_idx) >= lo
        model += lpSum(s[i] for i in p_idx) <= hi

    # captain: exactly 1, must be in XI
    model += lpSum(cap[i] for i in idx) == 1
    for i in idx:
        model += cap[i] <= s[i]

    model.solve(PULP_CBC_CMD(msg=0))

    if LpStatus[model.status] != "Optimal":
        print(f"Solver status: {LpStatus[model.status]}")
        return None

    in_squad = [i for i in idx if value(x[i]) > 0.5]
    in_xi = [i for i in idx if value(s[i]) > 0.5]
    on_bench = [i for i in idx if value(b[i]) > 0.5]
    captain = next(i for i in idx if value(cap[i]) > 0.5)

    return {
        "squad": df.loc[in_squad].copy(),
        "xi": df.loc[in_xi].copy(),
        "bench": df.loc[on_bench].copy(),
        "captain": captain,
        "total_ep": value(model.objective),
        "cost": df.loc[in_squad, "price_raw"].sum(),
    }

In [ ]:
def optimize_ideal_xi(df, max_per_country=MAX_PER_COUNTRY):
    # best possible 11 ignoring bench constraint, just 11 players
    idx = df.index.tolist()

    s = LpVariable.dicts("xi", idx, cat="Binary")
    cap = LpVariable.dicts("cap", idx, cat="Binary")

    model = LpProblem("ideal_xi", LpMaximize)

    model += lpSum(
        df.loc[i, "expected_points"] * s[i]
        + df.loc[i, "expected_points"] * cap[i]
        for i in idx
    )

    model += lpSum(s[i] for i in idx) == 11

    # no budget constraint for ideal XI comparison
    # country limit still applies
    for country in df["team"].unique():
        c_idx = df[df["team"] == country].index.tolist()
        model += lpSum(s[i] for i in c_idx) <= max_per_country

    gk_idx = df[df["position"] == "GK"].index.tolist()
    model += lpSum(s[i] for i in gk_idx) == 1

    for pos, lo, hi in [("DEF", 3, 5), ("MID", 3, 5), ("FWD", 1, 3)]:
        p_idx = df[df["position"] == pos].index.tolist()
        model += lpSum(s[i] for i in p_idx) >= lo
        model += lpSum(s[i] for i in p_idx) <= hi

    model += lpSum(cap[i] for i in idx) == 1
    for i in idx:
        model += cap[i] <= s[i]

    model.solve(PULP_CBC_CMD(msg=0))

    if LpStatus[model.status] != "Optimal":
        return None

    in_xi = [i for i in idx if value(s[i]) > 0.5]
    captain = next(i for i in idx if value(cap[i]) > 0.5)

    return {
        "xi": df.loc[in_xi].copy(),
        "captain": captain,
        "total_ep": value(model.objective),
    }


def print_team(result, ideal=None):
    pos_order = {"GK": 0, "DEF": 1, "MID": 2, "FWD": 3}
    cap = result["captain"]

    xi = result["xi"].copy()
    xi["_ord"] = xi["position"].map(pos_order)
    xi = xi.sort_values(["_ord", "expected_points"], ascending=[True, False])

    bench = result["bench"].copy()
    bench["_ord"] = bench["position"].map(pos_order)
    bench = bench.sort_values(["_ord", "expected_points"], ascending=[True, False])

    print(f"\nExpected points: {result['total_ep']:.2f}   Cost: ${result['cost']:.1f}M\n")

    print("Starting XI")
    for i, row in xi.iterrows():
        tag = " [C]" if i == cap else ""
        scout = " [SCOUT]" if row.get("differential", 0) == 1 else ""
        print(f"  {row['position']:3}  {row['name']:<28} {row['team']:<22} ${row['price_raw']:.1f}  EP:{row['expected_points']:.2f}{tag}{scout}")

    print("\nBench")
    for rank, (i, row) in enumerate(bench.iterrows(), 1):
        print(f"  [{rank}] {row['position']:3}  {row['name']:<28} {row['team']:<22} ${row['price_raw']:.1f}  EP:{row['expected_points']:.2f}")

    print(f"\nCountry breakdown: {dict(result['squad']['team'].value_counts())}")

    if ideal:
        ideal_xi = ideal["xi"].copy()
        ideal_xi["_ord"] = ideal_xi["position"].map(pos_order)
        ideal_xi = ideal_xi.sort_values(["_ord", "expected_points"], ascending=[True, False])
        ideal_cap = ideal["captain"]

        print(f"\nIdeal XI (no budget constraint, 11 only, EP: {ideal['total_ep']:.2f})")
        for i, row in ideal_xi.iterrows():
            tag = " [C]" if i == ideal_cap else ""
            in_squad = i in result["squad"].index
            flag = "" if in_squad else " [NOT IN SQUAD]"
            print(f"  {row['position']:3}  {row['name']:<28} {row['team']:<22} ${row['price_raw']:.1f}  EP:{row['expected_points']:.2f}{tag}{flag})

In [87]:
if __name__ == "__main__":
    df = pd.read_csv("fantasy_enriched.csv")
    df = df[df["status"] == "playing"].copy()
    df = df.reset_index(drop=True)

    df = compute_total_expected_points(df)

    result = optimize_squad(df, budget=BUDGET, max_per_country=MAX_PER_COUNTRY)
    ideal = optimize_ideal_xi(df, max_per_country=MAX_PER_COUNTRY)

    print_team(result, ideal)

Expected points: 104.13   Cost: $6.6M

Starting XI
  GK   Emiliano Martínez            Argentina              $0.2  EP:9.55
  DEF  Dayot Upamecano              France                 $0.3  EP:8.83
  DEF  Achraf Hakimi                Morocco                $0.4  EP:8.15
  DEF  Lisandro Martínez            Argentina              $0.2  EP:7.99
  DEF  Dávinson Sánchez             Colombia               $0.1  EP:7.63 [SCOUT]
  MID  Michael Olise                France                 $0.9  EP:8.79
  MID  Ousmane Dembélé              France                 $0.9  EP:8.54
  MID  Vinícius Júnior              Brazil                 $0.9  EP:8.00
  MID  Alexis Mac Allister          Argentina              $0.4  EP:7.90 [SCOUT]
  FWD  Kylian Mbappé                France                 $1.0  EP:9.79 [C]
  FWD  Lionel Messi                 Argentina              $0.9  EP:9.16

Bench
  [1] GK   Mohamed El Shenawy           Egypt                  $0.0  EP:0.71
  [2] DEF  Mohamed Abdelmonem           Egypt                  $0.1  EP:0.39
  [3] MID  Hamdi Fathy                  Egypt                  $0.1  EP:1.12
  [4] FWD  Guillermo Martínez           Mexico                 $0.2  EP:0.88

Country breakdown: {'Argentina': np.int64(4), 'France': np.int64(4), 'Egypt': np.int64(3), 'Brazil': np.int64(1), 'Colombia': np.int64(1), 'Mexico': np.int64(1), 'Morocco': np.int64(1)}

Ideal XI (no budget constraint, 11 only, EP: 104.13)
  GK   Emiliano Martínez            Argentina              $0.2  EP:9.55
  DEF  Dayot Upamecano              France                 $0.3  EP:8.83
  DEF  Achraf Hakimi                Morocco                $0.4  EP:8.15
  DEF  Lisandro Martínez            Argentina              $0.2  EP:7.99
  DEF  Dávinson Sánchez             Colombia               $0.1  EP:7.63
  MID  Michael Olise                France                 $0.9  EP:8.79
  MID  Ousmane Dembélé              France                 $0.9  EP:8.54
  MID  Vinícius Júnior              Brazil                 $0.9  EP:8.00
  MID  Alexis Mac Allister          Argentina              $0.4  EP:7.90
  FWD  Kylian Mbappé                France                 $1.0  EP:9.79 [C]
  FWD  Lionel Messi                 Argentina              $0.9  EP:9.16