In [195]:
!jupyter nbconvert --to notebook --execute preprocess.ipynb --inplace

[NbConvertApp] Converting notebook preprocess.ipynb to notebook
[NbConvertApp] Writing 116043 bytes to preprocess.ipynb

In [385]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from scipy.stats import poisson
from pulp import *

In [386]:
OUT_CSV = "fantasy_enriched.csv"


| Position        | Point Source         | Points | Description                                                                 |
| --------------- | -------------------- | -----: | --------------------------------------------------------------------------- |
| **All Players** | Appearance (<60 min) |     +1 | Plays any minutes up to 59:59                                               |
| **All Players** | Appearance (60+ min) |     +1 | Additional point for reaching 60+ minutes (total appearance = **2 points**) |
| **All Players** | Assist               |     +3 | Provides an assist                                                          |
| **All Players** | Yellow Card          |     -1 | Receives a yellow card                                                      |
| **All Players** | Red Card             |     -2 | Receives a red card                                                         |
| **All Players** | Own Goal             |     -2 | Scores an own goal                                                          |
| **All Players** | Winning a Penalty    |     +2 | Wins a penalty for their team                                               |
| **All Players** | Conceding a Penalty  |     -1 | Commits a foul leading to a penalty                                         |

| Position       | Point Source                  | Points | Description                                        |
| -------------- | ----------------------------- | -----: | -------------------------------------------------- |
| **Goalkeeper** | Clean Sheet                   |     +5 | Plays 60+ minutes and team keeps a clean sheet     |
| **Goalkeeper** | First Goal Conceded           |      0 | No deduction for conceding the first goal          |
| **Goalkeeper** | Each Additional Goal Conceded |     -1 | Every goal conceded after the first                |
| **Goalkeeper** | Goal Scored                   |     +9 | Scores a goal                                      |
| **Goalkeeper** | Penalty Save                  |     +3 | Saves a penalty during normal play (not shootouts) |
| **Goalkeeper** | Every 3 Saves                 |     +1 | Earns 1 point for every 3 saves                    |

| Position     | Point Source                  | Points | Description                                    |
| ------------ | ----------------------------- | -----: | ---------------------------------------------- |
| **Defender** | Clean Sheet                   |     +5 | Plays 60+ minutes and team keeps a clean sheet |
| **Defender** | First Goal Conceded           |      0 | No deduction for conceding the first goal      |
| **Defender** | Each Additional Goal Conceded |     -1 | Every goal conceded after the first            |
| **Defender** | Goal Scored                   |     +7 | Scores a goal                                  |

| Position       | Point Source                | Points | Description                                    |
| -------------- | --------------------------- | -----: | ---------------------------------------------- |
| **Midfielder** | Clean Sheet                 |     +1 | Plays 60+ minutes and team keeps a clean sheet |
| **Midfielder** | Goal Scored                 |     +6 | Scores a goal                                  |
| **Midfielder** | Every 3 Tackles             |     +1 | Earns 1 point for every 3 tackles              |
| **Midfielder** | Every 2 Big Chances Created |     +1 | Earns 1 point for every 2 big chances created  |

| Position    | Point Source            | Points | Description                               |
| ----------- | ----------------------- | -----: | ----------------------------------------- |
| **Forward** | Goal Scored             |     +5 | Scores a goal                             |
| **Forward** | Every 2 Shots on Target |     +1 | Earns 1 point for every 2 shots on target |

| Position                | Point Source          | Points | Description                                                                                                                                                                        |
| ----------------------- | --------------------- | -----: | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **Bonus (All Players)** | Direct Free-Kick Goal |     +1 | Additional bonus for scoring directly from a free kick (on top of goal points)                                                                                                     |
| **Bonus (All Players)** | Scouting Bonus        |     +2 | Scores **more than 4 base fantasy points** in a match **and** is selected by **<5%** of fantasy teams. Captaincy and booster points do **not** count toward the 4-point threshold. |


## Core identity / player info

| Column | Type | Description |
|---|---|---|
| `fifa_id` | int | Unique FIFA fantasy player ID |
| `name` | str | Player name |
| `squad_id` | int | Internal squad/nation ID |
| `team` | str | National team |
| `position` | str | DEF / MID / FWD / GK |
| `price` | float | Fantasy price |
| `status` | str | Availability status |
| `total_points` | int | Total tournament points |
| `avg_points` | float | Average points per match |
| `matches_played` | int | Matches with participation |
| `percent_selected` | float | Selection rate (%) |
| `next_fixture` | int | Next match ID |


## Round fantasy points

| Column | Type | Description |
|---|---|---|
| `round_1_points` | int | Points in round 1 |
| `round_2_points` | int | Points in round 2 |
| `round_3_points` | int | Points in round 3 |
| `round_4_points` | int | Points in round 4 |


## Betting / scorer mapping

| Column | Type | Description |
|---|---|---|
| `betano_matched_name` | str | Matched Betano market name |
| `betano_match_score` | float | Name matching confidence (0–100) |
| `anytime_scorer_prob` | float | Probability player scores anytime |
| `first_scorer_prob` | float | Probability scores first goal |
| `last_scorer_prob` | float | Probability scores last goal |


## Match context

| Column | Type | Description |
|---|---|---|
| `match_home` | str | Home team |
| `match_away` | str | Away team |
| `is_home` | bool | Player team is home |
| `opponent` | str | Opponent team |


## Match probabilities 

| Column | Type | Description |
|---|---|---|
| `match_home_win_prob` | float | Home win probability |
| `match_draw_prob` | float | Draw probability |
| `match_away_win_prob` | float | Away win probability |
| `match_btts_prob` | float | Both teams score probability |
| `match_over_25_prob` | float | Over 2.5 goals probability |
| `match_over_35_prob` | float | Over 3.5 goals probability |
| `team_score_prob` | float | Team scores ≥1 goal probability |
| `team_score_2_prob` | float | Team scores ≥2 goals probability |
| `team_cs_prob` | float | Team clean sheet probability |
| `opp_score_prob` | float | Opponent scores ≥1 goal probability |
| `opp_cs_prob` | float | Opponent clean sheet probability |
| `team_over_05_prob` | float | Team scores ≥1 goal probability |
| `team_over_15_prob` | float | Team scores ≥2 goals probability |
| `team_qualify_prob` | float | Team advances probability |
| `team_win2_prob` | float | Team wins by 2+ goals probability |
| `opp_over_05_prob` | float | Opponent scores ≥1 goal probability |


## Raw cumulative stats

| Column | Type | Description |
|---|---|---|
| `stat_GS` | int | Goals |
| `stat_AS` | int | Assists |
| `stat_CS` | int | Clean sheets |
| `stat_GC` | int | Goals conceded |
| `stat_MP` | int | Minutes played |
| `stat_YC` | int | Yellow cards |
| `stat_RC` | int | Red cards |
| `stat_ST` | int | Shots on target |
| `stat_SB` | int | Shots blocked |
| `stat_CC` | int | Chances created |
| `stat_PS` | int | Penalties saved |
| `stat_T` | int | Tackles |
| `stat_S` | int | Saves |
| `stat_SXI` | int | Starts (XI appearances) |
| `stat_OG` | int | Own goals |
| `stat_PC` | int | Penalties committed |
| `stat_PW` | int | Penalties won |
| `stat_FK` | int | Free kicks won |



## Round-by-round stats (1–4)

| Pattern | Type | Description |
|---|---|---|
| `round_i_SXI` | int | Started (0/1) |
| `round_i_MP` | int | Minutes |
| `round_i_AS` | int | Assists |
| `round_i_YC` | int | Yellow cards |
| `round_i_RC` | int | Red cards |
| `round_i_OG` | int | Own goals |
| `round_i_PW` | int | Penalties won |
| `round_i_PC` | int | Penalties committed |
| `round_i_CS` | int | Clean sheets |
| `round_i_GS` | int | Goals |
| `round_i_GC` | int | Goals conceded |
| `round_i_PS` | int | Penalties saved |
| `round_i_T` | int | Tackles |
| `round_i_CC` | int | Chances created |
| `round_i_ST` | int | Shots on target |
| `round_i_FK` | int | Free kicks |
| `round_i_S` | int | Saves |
| `round_i_SB` | int | Shots blocked |



## External matching / enrichment

| Column | Type | Description |
|---|---|---|
| `clubstats_matched_player` | str | External player match |
| `clubs_match_dist` | float | Matching distance score |



## Form / usage trends

| Column | Type | Description |
|---|---|---|
| `started_last_match` | int | Started last match |
| `starts_last_3` | int | Starts last 3 matches |
| `starts_last_5` | int | Starts last 5 matches |
| `start_rate` | float | Start frequency |
| `minutes_last_3_avg` | float | Avg minutes last 3 |
| `minutes_last_5_avg` | float | Avg minutes last 5 |



## Performance rates

| Column | Type | Description |
|---|---|---|
| `goal_rate` | float | Goals per minute |
| `goals_per_start` | float | Goals per start |
| `shots_on_target_per90` | float | SOT per 90 |
| `goals_per_shot_on_target` | float | Conversion rate |
| `assist_rate` | float | Assists per minute |
| `chance_created_per90` | float | Chances per 90 |
| `tackles_per90` | float | Tackles per 90 |
| `cc_per90` | float | Chances created per 90 |
| `sot_per90` | float | Shots on target per 90 |
| `saves_per90` | float | Saves per 90 |
| `yc_per90` | float | Yellow cards per 90 |
| `rc_per90` | float | Red cards per 90 |
| `penalty_conceded_rate` | float | Penalties conceded per 90 |
| `own_goal_rate` | float | Own goals per 90 |
| `penalties_won_per90` | float | Penalties won per 90 |



## Recent / streak features

| Column | Type | Description |
|---|---|---|
| `recent_goals_last3` | int | Goals last 3 matches |
| `goal_streak` | int | Consecutive scoring matches |
| `recent_assists_last3` | int | Assists last 3 matches |
| `recent_chances_created_per90` | float | Recent creation rate |
| `recent_cs_rate` | float | Clean sheet rate |
| `recent_tackles_per90` | float | Recent tackles |
| `recent_cc_per90` | float | Recent chances created |
| `recent_sot_per90` | float | Recent shots on target |
| `recent_saves_per90` | float | Recent saves |
| `recent_penalties_won` | int | Penalties won last 3 |



## Expected value features

| Column | Type | Description |
|---|---|---|
| `goal_expectation` | float | Scoring proxy |
| `goal_expectation2` | float | Scoring proxy (2+ goals) |
| `assist_expectation` | float | Assist proxy |
| `cs_expectation` | float | Clean sheet proxy |
| `expected_minutes` | float | Expected minutes |
| `expected_gc_penalty` | float | Defensive penalty |
| `expected_tackle_points` | float | Tackles contribution |
| `expected_cc_points` | float | Chance creation points |
| `expected_sot_points` | float | Shot contribution points |
| `expected_save_points` | float | Save contribution points |



## Fantasy points dynamics

| Column | Type | Description |
|---|---|---|
| `points_last1` | int | Last match points |
| `points_last3_avg` | float | Avg last 3 |
| `points_last5_avg` | float | Avg last 5 |
| `weighted_points` | float | Recency weighted |
| `rolling_std_points` | float | Variance last 5 |
| `rolling_max_points` | int | Max last 5 |



## Team-position ranking features

| Column | Type | Description |
|---|---|---|
| `price_rank_team_position` | float | Price rank |
| `selected_rank_team_position` | float | Selection rank |
| `points_rank_team_position` | float | Points rank |
| `minutes_rank_team_position` | float | Minutes rank |
| `starts_rank_team_position` | float | Starts rank |
| `anytime_rank_team_position` | float | Scoring odds rank |
| `shots_rank_team_position` | float | Shooting rank |
| `cc_rank_team_position` | float | Chance creation rank |
| `tackles_rank_team_position` | float | Tackles rank |

In [387]:
df= pd.read_csv("fantasy_enriched.csv")

In [388]:
df = df[df["status"] == "playing"].copy()

In [389]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [390]:
# probability of playing a minute

raw_any = (
    0.15 * df["minutes_rank_team_position"]
  + 0.20 * df["stat_MP"]        # minutes needs to be very team stratified since while for other point sources players are all eligible
  + 0.10 * df["starts_rank_team_position"]
  + 0.15 * df["price_rank_team_position"]     # for minutes its a team stratified signal.
  + 0.20 * df["selected_rank_team_position"]
  + 0.15 * df["minutes_last_3_avg"]
  + 0.05 * df["anytime_rank_team_position"] # having odd at all means likeliness of playing is higher.

)

df["prob_plays_any"] = sigmoid((raw_any - 0.5) * 6)

In [391]:
df.loc[
    :,
    [
        "prob_plays_any",
        "name",
        "team",
        "position",
        "stat_MP",
        "minutes_rank_team_position",
        "starts_rank_team_position",
        "selected_rank_team_position",
        "price_rank_team_position",
        "anytime_rank_team_position",
    ],
].sort_values("prob_plays_any", ascending=False).head(30)

,prob_plays_any,name,team,position,stat_MP,minutes_rank_team_position,starts_rank_team_position,selected_rank_team_position,price_rank_team_position,anytime_rank_team_position
340,0.947350,Yassine Bounou,Morocco,GK,1.000000,1.000000,1.000000,1.00,1.000000,0.633333
272,0.947350,Thibaut Courtois,Belgium,GK,1.000000,1.000000,1.000000,1.00,1.000000,0.633333
106,0.940643,Kylian Mbappé,France,FWD,0.900000,1.000000,1.000000,1.00,1.000000,1.000000
278,0.937479,Diogo Costa,Portugal,GK,0.923077,1.000000,1.000000,1.00,1.000000,0.633333
110,0.937479,Mike Maignan,France,GK,0.923077,1.000000,1.000000,1.00,1.000000,0.633333
49,0.937479,Maxime Crépeau,Canada,GK,0.923077,1.000000,1.000000,1.00,1.000000,0.633333
91,0.937479,Jordan Pickford,England,GK,0.923077,1.000000,1.000000,1.00,1.000000,0.633333
85,0.929234,Harry Kane,England,FWD,0.907692,1.000000,0.656250,1.00,1.000000,1.000000
224,0.927081,Unai Simón,Spain,GK,0.923077,1.000000,1.000000,1.00,0.816667,0.633333
170,0.926121,Gustavo Gómez,Paraguay,DEF,1.000000,1.000000,0.214286,1.00,1.000000,1.000000
35,0.923274,Alisson Becker,Brazil,GK,0.923077,1.000000,1.000000,1.00,0.816667,0.450000
341,0.923039,Achraf Hakimi,Morocco,DEF,1.000000,1.000000,0.140625,1.00,1.000000,1.000000
282,0.919309,Cristiano Ronaldo,Portugal,FWD,0.900000,1.000000,0.450000,1.00,1.000000,1.000000
44,0.910190,Jonathan David,Canada,FWD,0.848718,1.000000,0.312500,1.00,1.000000,1.000000
220,0.904901,Mikel Oyarzabal,Spain,FWD,0.771795,1.000000,0.656250,1.00,1.000000,1.000000
186,0.902911,Orlando Gill,Paraguay,GK,1.000000,1.000000,1.000000,1.00,0.266667,0.633333
27,0.898940,Vinícius Júnior,Brazil,MID,0.900000,1.000000,0.037500,1.00,1.000000,1.000000
144,0.898341,Ismael Saibari,Morocco,MID,0.930769,0.877778,0.083333,1.00,1.000000,1.000000
161,0.896671,Ørjan Nyland,Norway,GK,0.692308,1.000000,1.000000,1.00,1.000000,0.633333
247,0.896671,Matt Freese,USA,GK,0.692308,1.000000,1.000000,1.00,1.000000,0.633333
69,0.896671,Camilo Vargas,Colombia,GK,0.692308,1.000000,1.000000,1.00,1.000000,0.633333
191,0.892531,Nuno Mendes,Portugal,DEF,0.874359,0.862500,0.140625,1.00,1.000000,1.000000
20,0.892491,Gabriel Magalhães,Brazil,DEF,0.923077,0.931250,0.140625,1.00,1.000000,0.587500
157,0.887407,Erling Haaland,Norway,FWD,0.692308,1.000000,0.656250,1.00,1.000000,1.000000
209,0.883563,Bruno Fernandes,Portugal,MID,0.853846,1.000000,0.037500,1.00,1.000000,0.835000
135,0.878122,Raúl Rangel,Mexico,GK,0.892308,1.000000,1.000000,1.00,0.266667,0.633333
10,0.870300,Romelu Lukaku,Belgium,FWD,0.453846,1.000000,1.000000,1.00,1.000000,1.000000
28,0.867390,Matheus Cunha,Brazil,FWD,0.602564,1.000000,0.450000,1.00,1.000000,0.890000
98,0.857252,Jude Bellingham,England,MID,0.805128,0.890000,0.037500,1.00,0.890000,1.000000
234,0.857078,Weston McKennie,USA,MID,0.907692,1.000000,0.037500,0.89,0.835000,0.560000

In [392]:
# probability of starting / playing 60 minutes

raw_any = (
    0.15 * df["minutes_rank_team_position"]
  + 0.10 * df["starts_rank_team_position"]
  + 0.25 * df["stat_MP"]
  + 0.10 * df["price_rank_team_position"]
  + 0.05 * df["selected_rank_team_position"]
  + 0.15 * df["minutes_last_3_avg"]
  + 0.15 * df["round_4_MP"]
  + 0.05 * df["anytime_rank_team_position"] # having odd at all means likeliness of playing is higher.

)

df["prob_plays_60min"] = sigmoid((raw_any - 0.5) * 6)

In [393]:
cols = [
    "name",
    "team",
    "position",
    "prob_plays_60min",
    "minutes_rank_team_position",
    "starts_rank_team_position",
    "price_rank_team_position",
    "selected_rank_team_position",
    "minutes_last_3_avg",
    "round_4_MP",
    "anytime_rank_team_position",
]

df[cols].sort_values("prob_plays_60min", ascending=False).head(30)

,name,team,position,prob_plays_60min,minutes_rank_team_position,starts_rank_team_position,price_rank_team_position,selected_rank_team_position,minutes_last_3_avg,round_4_MP,anytime_rank_team_position
272,Thibaut Courtois,Belgium,GK,0.947350,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.633333
340,Yassine Bounou,Morocco,GK,0.947350,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.633333
170,Gustavo Gómez,Paraguay,DEF,0.926121,1.000000,0.214286,1.000000,1.000000,1.000000,1.000000,1.000000
341,Achraf Hakimi,Morocco,DEF,0.923039,1.000000,0.140625,1.000000,1.000000,1.000000,1.000000,1.000000
106,Kylian Mbappé,France,FWD,0.922048,1.000000,1.000000,1.000000,1.000000,0.870000,0.708333,1.000000
49,Maxime Crépeau,Canada,GK,0.921262,1.000000,1.000000,1.000000,1.000000,0.900000,0.750000,0.633333
91,Jordan Pickford,England,GK,0.921262,1.000000,1.000000,1.000000,1.000000,0.900000,0.750000,0.633333
110,Mike Maignan,France,GK,0.921262,1.000000,1.000000,1.000000,1.000000,0.900000,0.750000,0.633333
278,Diogo Costa,Portugal,GK,0.921262,1.000000,1.000000,1.000000,1.000000,0.900000,0.750000,0.633333
186,Orlando Gill,Paraguay,GK,0.920561,1.000000,1.000000,0.266667,1.000000,1.000000,1.000000,0.633333
224,Unai Simón,Spain,GK,0.912904,1.000000,1.000000,0.816667,1.000000,0.900000,0.750000,0.633333
85,Harry Kane,England,FWD,0.910706,1.000000,0.656250,1.000000,1.000000,0.880000,0.750000,1.000000
35,Alisson Becker,Brazil,GK,0.908430,1.000000,1.000000,0.816667,1.000000,0.900000,0.750000,0.450000
144,Ismael Saibari,Morocco,MID,0.896428,0.877778,0.083333,1.000000,1.000000,0.913333,1.000000,1.000000
282,Cristiano Ronaldo,Portugal,FWD,0.891920,1.000000,0.450000,1.000000,1.000000,0.870000,0.675000,1.000000
44,Jonathan David,Canada,FWD,0.885500,1.000000,0.312500,1.000000,1.000000,0.900000,0.750000,1.000000
220,Mikel Oyarzabal,Spain,FWD,0.876473,1.000000,0.656250,1.000000,1.000000,0.703333,0.750000,1.000000
135,Raúl Rangel,Mexico,GK,0.874073,1.000000,1.000000,0.266667,1.000000,0.860000,0.750000,0.633333
18,Youri Tielemans,Belgium,MID,0.873335,1.000000,0.000000,0.700000,0.700000,0.983333,1.000000,0.450000
27,Vinícius Júnior,Brazil,MID,0.873305,1.000000,0.037500,1.000000,1.000000,0.870000,0.750000,1.000000
20,Gabriel Magalhães,Brazil,DEF,0.866269,0.931250,0.140625,1.000000,1.000000,0.900000,0.750000,0.587500
191,Nuno Mendes,Portugal,DEF,0.864615,0.862500,0.140625,1.000000,1.000000,0.896667,0.750000,1.000000
161,Ørjan Nyland,Norway,GK,0.863358,1.000000,1.000000,1.000000,1.000000,0.600000,0.750000,0.633333
247,Matt Freese,USA,GK,0.863358,1.000000,1.000000,1.000000,1.000000,0.600000,0.750000,0.633333
7,Brandon Mechele,Belgium,DEF,0.861364,1.000000,0.083333,0.205556,0.755556,1.000000,1.000000,0.755556
276,Leandro Trossard,Belgium,MID,0.860441,0.900000,0.000000,0.800000,0.850000,0.903333,0.908333,0.850000
157,Erling Haaland,Norway,FWD,0.851601,1.000000,0.656250,1.000000,1.000000,0.600000,0.750000,1.000000
348,Neil El Aynaoui,Morocco,MID,0.846240,1.000000,0.083333,0.388889,0.388889,0.976667,1.000000,0.511111
101,Dayot Upamecano,France,DEF,0.846026,1.000000,0.083333,0.816667,0.755556,0.853333,0.750000,0.877778
303,Alistair Johnston,Canada,DEF,0.843267,1.000000,0.140625,0.656250,0.862500,0.900000,0.750000,0.587500

There is a phenomenon where a player will be overvalued, such as Lukaku here for belgium. He has not played much, but since Belgium only has 3 forward and only him has significative minutes he ranks number 1 for all ranks in BEL,FWD. Need to include more general sums and beware with manual selection.

In [394]:
raw_goal = (
    0.60 * df["anytime_scorer_prob"]
  + 0.05 * df["recent_goals_last3"]
  + 0.05 * df["team_score_2_prob"]
  + 0.02 * df["stat_GS"]
  + 0.03 * df["stat_ST"]
  + 0.05 * df["price"]
)

df["prob_scores"] = raw_goal * df["prob_plays_60min"]

In [395]:
cols = [
    "name",
    "team",
    "position",
    "prob_scores",
    "goal_expectation",
    "anytime_scorer_prob",
    "recent_goals_last3",
    "recent_sot_per90",
    "goal_rate",
    "shots_on_target_per90",
    "stat_GS",
    "stat_ST",
    "price_rank_team_position",
]

df[cols].sort_values("prob_scores", ascending=False).head(30)

,name,team,position,prob_scores,goal_expectation,anytime_scorer_prob,recent_goals_last3,recent_sot_per90,goal_rate,shots_on_target_per90,stat_GS,stat_ST,price_rank_team_position
106,Kylian Mbappé,France,FWD,0.737638,1.000000,1.000000,1.00,0.402299,0.307692,0.518519,1.000000,1.000000,1.000000
220,Mikel Oyarzabal,Spain,FWD,0.515971,0.663987,0.736435,1.00,0.387046,0.239203,0.372093,0.666667,0.615385,1.000000
27,Vinícius Júnior,Brazil,MID,0.512489,0.664927,0.718813,0.75,0.402299,0.205128,0.398860,0.666667,0.769231,1.000000
157,Erling Haaland,Norway,FWD,0.491637,0.548897,0.725769,0.75,0.324074,0.333333,0.466667,0.833333,0.692308,1.000000
85,Harry Kane,England,FWD,0.478226,0.506153,0.633792,0.75,0.265152,0.254237,0.355932,0.833333,0.692308,1.000000
107,Ousmane Dembélé,France,MID,0.466114,0.710163,0.708610,1.00,0.280449,0.250000,0.243056,0.666667,0.384615,1.000000
282,Cristiano Ronaldo,Portugal,FWD,0.424381,0.435538,0.584171,0.75,0.312899,0.153846,0.279202,0.500000,0.538462,1.000000
10,Romelu Lukaku,Belgium,FWD,0.419346,0.623027,0.718813,0.50,0.152505,0.203390,0.158192,0.333333,0.153846,1.000000
28,Matheus Cunha,Brazil,FWD,0.398705,0.586817,0.633792,0.75,0.283172,0.229787,0.297872,0.500000,0.384615,1.000000
144,Ismael Saibari,Morocco,MID,0.386342,0.492985,0.562220,0.50,0.085158,0.148760,0.115702,0.500000,0.230769,1.000000
119,Michael Olise,France,MID,0.345206,0.544103,0.541660,0.00,0.160550,0.000000,0.227273,0.000000,0.384615,0.900000
218,Lamine Yamal,Spain,MID,0.344263,0.538116,0.595919,0.25,0.339806,0.080000,0.373333,0.166667,0.461538,1.000000
65,Luis Díaz,Colombia,MID,0.305903,0.597598,0.633792,0.00,0.129630,0.066914,0.156134,0.166667,0.230769,1.000000
276,Leandro Trossard,Belgium,MID,0.298229,0.375395,0.431288,0.50,0.129151,0.099723,0.116343,0.333333,0.230769,0.800000
44,Jonathan David,Canada,FWD,0.287119,0.253827,0.376101,0.75,0.259259,0.163142,0.296073,0.500000,0.538462,1.000000
262,Bradley Barcola,France,MID,0.273467,0.581928,0.579688,0.25,0.117845,0.173077,0.201923,0.333333,0.230769,0.750000
128,Julián Quiñones,Mexico,FWD,0.266029,0.317247,0.431288,0.50,0.137795,0.162162,0.210210,0.500000,0.384615,0.685714
98,Jude Bellingham,England,MID,0.262622,0.309529,0.385995,0.25,0.199430,0.114650,0.267516,0.333333,0.461538,0.890000
127,Raúl Jiménez,Mexico,FWD,0.252624,0.358864,0.488329,0.25,0.151515,0.156522,0.243478,0.333333,0.307692,1.000000
19,Kevin De Bruyne,Belgium,MID,0.249703,0.375395,0.431288,0.25,0.162791,0.059801,0.186047,0.166667,0.307692,0.950000
249,Christian Pulisic,USA,MID,0.242808,0.478980,0.562220,0.00,0.194444,0.000000,0.169697,0.000000,0.153846,1.000000
18,Youri Tielemans,Belgium,MID,0.242391,0.281402,0.322152,0.50,0.118644,0.093506,0.109091,0.333333,0.230769,0.700000
234,Weston McKennie,USA,MID,0.234786,0.330032,0.385995,0.00,0.044192,0.000000,0.039548,0.000000,0.076923,0.835000
349,Brahim Díaz,Morocco,MID,0.227665,0.368496,0.419076,0.00,0.000000,0.000000,0.046980,0.000000,0.076923,0.877778
67,Luis Suárez,Colombia,FWD,0.225179,0.597598,0.633792,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.450000
341,Achraf Hakimi,Morocco,DEF,0.215510,0.239436,0.270676,0.25,0.155556,0.046154,0.143590,0.166667,0.307692,1.000000
32,Rayan,Brazil,FWD,0.209938,0.438835,0.472716,0.00,0.052553,0.000000,0.063063,0.000000,0.076923,0.340000
244,Ricardo Pepi,USA,FWD,0.203290,0.478980,0.562220,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.725000
219,Ferran Torres,Spain,FWD,0.199010,0.527592,0.584171,0.00,0.149573,0.000000,0.176101,0.000000,0.153846,0.725000
209,Bruno Fernandes,Portugal,MID,0.195804,0.224102,0.298810,0.00,0.144033,0.000000,0.126126,0.000000,0.230769,1.000000

In [396]:
prob_assists = (
    0.05 * df["chance_created_per90"]
  + 0.20 * df["stat_CC"]
  + 0.05 * df["recent_cc_per90"]
  + 0.15 * df["team_score_2_prob"]
  + 0.15 * df["recent_assists_last3"]
  + 0.15 * df["price"]
  + 0.10 * df["stat_AS"]
)

df["expected_assists"] = prob_assists * df["prob_plays_60min"]

In [397]:
cols = [
    "name",
    "team",
    "position",
    "expected_assists",
    "assist_expectation",
    "stat_CC",
    "recent_cc_per90",
    "team_score_2_prob",
    "recent_assists_last3",
    "price",
    "prob_plays_60min",
    "stat_AS",
]

df[cols].sort_values("expected_assists", ascending=False).head(30)

,name,team,position,expected_assists,assist_expectation,stat_CC,recent_cc_per90,team_score_2_prob,recent_assists_last3,price,prob_plays_60min,stat_AS
119,Michael Olise,France,MID,0.599446,0.172615,1.0,0.178899,1.000000,1.00,0.857143,0.803942,1.0
106,Kylian Mbappé,France,FWD,0.423141,0.030294,0.2,0.049808,1.000000,0.50,1.000000,0.922048,0.4
252,Bruno Guimarães,Brazil,MID,0.398990,0.086657,0.6,0.150000,0.704250,0.75,0.471429,0.796764,0.8
216,Marc Cucurella,Spain,DEF,0.360932,0.079799,0.6,0.096296,0.643539,0.75,0.228571,0.834914,0.6
107,Ousmane Dembélé,France,MID,0.350990,0.036920,0.2,0.062500,1.000000,0.50,0.928571,0.781460,0.4
27,Vinícius Júnior,Brazil,MID,0.302459,0.027980,0.2,0.049808,0.704250,0.25,0.928571,0.873305,0.2
130,Roberto Alvarado,Mexico,FWD,0.293765,0.091757,0.8,0.156000,0.289853,0.50,0.257143,0.751832,0.6
98,Jude Bellingham,England,MID,0.290945,0.081042,0.6,0.166667,0.398092,0.25,0.685714,0.823783,0.2
293,Martin Ødegaard,Norway,MID,0.270929,0.061634,0.4,0.072222,0.338248,0.50,0.600000,0.745991,0.6
341,Achraf Hakimi,Morocco,DEF,0.260691,0.047676,0.4,0.086667,0.563053,0.25,0.357143,0.923039,0.2
220,Mikel Oyarzabal,Spain,FWD,0.260614,0.031814,0.2,0.061611,0.643539,0.25,0.657143,0.876473,0.2
276,Leandro Trossard,Belgium,MID,0.251919,0.051007,0.4,0.095941,0.541891,0.25,0.442857,0.860441,0.2
209,Bruno Fernandes,Portugal,MID,0.246595,0.047572,0.4,0.106996,0.304423,0.25,0.714286,0.825673,0.2
349,Brahim Díaz,Morocco,MID,0.233402,0.062395,0.4,0.055794,0.563053,0.25,0.414286,0.752313,0.4
157,Erling Haaland,Norway,FWD,0.226696,0.029790,0.2,0.072222,0.338248,0.00,1.000000,0.851601,0.2
261,Jules Koundé,France,DEF,0.223531,0.063481,0.4,0.053061,1.000000,0.00,0.271429,0.808861,0.0
144,Ismael Saibari,Morocco,MID,0.217538,0.051223,0.4,0.094891,0.563053,0.00,0.471429,0.896428,0.0
20,Gabriel Magalhães,Brazil,DEF,0.216386,0.027281,0.2,0.048148,0.704250,0.25,0.285714,0.866269,0.2
262,Bradley Barcola,France,MID,0.209646,0.051120,0.2,0.065657,1.000000,0.25,0.642857,0.599648,0.2
148,Patrick Berg,Norway,MID,0.204201,0.103119,0.6,0.173333,0.338248,0.50,0.300000,0.590492,0.4
101,Dayot Upamecano,France,DEF,0.196748,0.030731,0.2,0.050781,1.000000,0.00,0.257143,0.846026,0.0
191,Nuno Mendes,Portugal,DEF,0.195919,0.069683,0.6,0.144981,0.304423,0.00,0.328571,0.864615,0.0
214,Aymeric Laporte,Spain,DEF,0.195412,0.026674,0.2,0.048327,0.643539,0.25,0.285714,0.811860,0.2
85,Harry Kane,England,FWD,0.190988,0.000000,0.0,0.000000,0.398092,0.00,1.000000,0.910706,0.0
32,Rayan,Brazil,FWD,0.186423,0.088478,0.4,0.117117,0.704250,0.25,0.300000,0.624536,0.2
65,Luis Díaz,Colombia,MID,0.182468,0.037175,0.2,0.000000,0.766522,0.00,0.657143,0.662536,0.2
188,Julio Enciso,Paraguay,MID,0.181987,0.031485,0.4,0.055085,0.000000,0.25,0.442857,0.792108,0.4
229,Pedri,Spain,MID,0.180350,0.030990,0.2,0.000000,0.643539,0.00,0.657143,0.761870,0.0
97,Declan Rice,England,MID,0.179265,0.101384,0.6,0.145251,0.398092,0.00,0.500000,0.622550,0.2
10,Romelu Lukaku,Belgium,FWD,0.178450,0.000000,0.0,0.000000,0.541891,0.25,0.557143,0.802544,0.2

In [398]:
position_yc_modifier = {
    "GK": 0.15,
    "FWD": 0.35,
    "DEF": 0.45,
    "MID": 0.55,
}

df["position_yc_modifier"] = df["position"].map(position_yc_modifier)

raw_yc = (
    0.35 * df["yc_per90"]
  + 0.15 * df["tackles_per90"]
  + 0.15 * df["opp_over_05_prob"]
  + 0.05 * df["rc_per90"]
  + 0.05 * df["position_yc_modifier"]
)

df["prob_yellow_card"] = sigmoid((raw_yc - 0.6) * 5) * df["prob_plays_60min"]

In [399]:
cols = [
    "name",
    "team",
    "position",
    "prob_yellow_card",
    "yc_per90",
    "stat_YC",
    "tackles_per90",
    "recent_tackles_per90",
    "opp_over_05_prob",
    "prob_plays_60min",
    "rc_per90",
]

df[cols].sort_values("prob_yellow_card", ascending=False).head(30)

,name,team,position,prob_yellow_card,yc_per90,stat_YC,tackles_per90,recent_tackles_per90,opp_over_05_prob,prob_plays_60min,rc_per90
168,Matías Galarza,Paraguay,MID,0.130667,0.255034,1.0,0.046980,0.281879,1.000000,0.798212,0.000000
284,Andrés Cubas,Paraguay,MID,0.104211,0.097436,0.5,0.035897,0.180000,1.000000,0.811533,0.000000
177,Miguel Almirón,Paraguay,MID,0.099216,0.177570,0.5,0.032710,0.222222,1.000000,0.588171,0.728972
171,Júnior Alonso,Paraguay,DEF,0.098627,0.126667,0.5,0.026667,0.171429,1.000000,0.755296,0.000000
170,Gustavo Gómez,Paraguay,DEF,0.098385,0.000000,0.0,0.010256,0.060000,1.000000,0.926121,0.000000
175,Juan José Cáceres,Paraguay,DEF,0.097152,0.108883,0.5,0.051576,0.288889,1.000000,0.752093,0.000000
10,Romelu Lukaku,Belgium,FWD,0.095095,0.214689,0.5,0.000000,0.000000,0.706667,0.802544,0.000000
186,Orlando Gill,Paraguay,GK,0.090798,0.000000,0.0,0.000000,0.000000,1.000000,0.920561,0.000000
303,Alistair Johnston,Canada,DEF,0.089558,0.105556,0.5,0.002778,0.000000,0.760766,0.843267,0.000000
7,Brandon Mechele,Belgium,DEF,0.087385,0.097436,0.5,0.007692,0.020000,0.706667,0.861364,0.000000
279,Rúben Dias,Portugal,DEF,0.086826,0.140741,0.5,0.018519,0.111111,0.803747,0.744304,0.000000
188,Julio Enciso,Paraguay,MID,0.086163,0.000000,0.0,0.012270,0.050847,1.000000,0.792108,0.000000
1,Timothy Castagne,Belgium,DEF,0.085673,0.127517,0.5,0.033557,0.148760,0.706667,0.791747,0.000000
189,Diego Gómez,Paraguay,MID,0.085108,0.322034,1.0,0.033898,0.230769,1.000000,0.475609,0.000000
0,Maxim De Cuyper,Belgium,DEF,0.084099,0.130137,0.5,0.010274,0.046512,0.706667,0.786184,0.000000
195,Renato Veiga,Portugal,DEF,0.084074,0.105556,0.5,0.008333,0.022222,0.803747,0.766337,0.000000
38,Casemiro,Brazil,MID,0.082290,0.262976,1.0,0.041522,0.270492,0.531328,0.673935,0.000000
282,Cristiano Ronaldo,Portugal,FWD,0.080875,0.000000,0.0,0.005698,0.045977,0.803747,0.891920,0.000000
191,Nuno Mendes,Portugal,DEF,0.080690,0.000000,0.0,0.014663,0.089219,0.803747,0.864615,0.000000
41,Derek Cornelius,Canada,DEF,0.080263,0.120635,0.5,0.015873,0.026667,0.760766,0.731729,0.000000
236,Antonee Robinson,USA,DEF,0.080253,0.146154,0.5,0.015385,0.141176,0.746908,0.709921,0.000000
278,Diogo Costa,Portugal,GK,0.079504,0.000000,0.0,0.000000,0.000000,0.803747,0.921262,0.000000
157,Erling Haaland,Norway,FWD,0.079326,0.000000,0.0,0.000000,0.000000,0.848970,0.851601,0.000000
209,Bruno Fernandes,Portugal,MID,0.079323,0.000000,0.0,0.024024,0.123457,0.803747,0.825673,0.000000
23,Danilo,Brazil,DEF,0.079046,0.241270,1.0,0.006349,0.044444,0.531328,0.700497,0.000000
345,Issa Diop,Morocco,DEF,0.078161,0.253333,1.0,0.000000,0.000000,0.373114,0.758843,0.000000
234,Weston McKennie,USA,MID,0.077830,0.000000,0.0,0.022599,0.181818,0.746908,0.842843,0.000000
44,Jonathan David,Canada,FWD,0.077828,0.000000,0.0,0.003021,0.000000,0.760766,0.885500,0.000000
18,Youri Tielemans,Belgium,MID,0.077812,0.000000,0.0,0.010390,0.061017,0.706667,0.873335,0.000000
49,Maxime Crépeau,Canada,GK,0.077340,0.000000,0.0,0.002778,0.000000,0.760766,0.921262,0.000000

In [400]:
raw_pw = (
    0.10 * df["stat_PW"]                    # tournament history
  + 0.25 * df["anytime_scorer_prob"]      # gets into dangerous areas
  + 0.10 * df["chance_created_per90"]     # attacking involvement
  + 0.15 * df["stat_CC"]                  # recent form in creation
  + 0.15 * df["team_score_2_prob"]        # team expected to attack heavily
  + 0.10 * df["price_rank_team_position"] # quality proxy
)

# Penalties are rare → heavily compress probabilities + minutes as external gate
df["prob_pen_won"] = 0.15 * sigmoid((raw_pw - 0.65) * 5) * df["prob_plays_60min"]

In [401]:
cols = [
    "name",
    "team",
    "position",
    "prob_pen_won",
    "stat_PW",
    "anytime_scorer_prob",
    "assist_expectation",
    "chance_created_per90",
    "team_score_2_prob",
    "price_rank_team_position",
    "prob_plays_60min",
]

df[cols].sort_values("prob_pen_won", ascending=False).head(30)

,name,team,position,prob_pen_won,stat_PW,anytime_scorer_prob,assist_expectation,chance_created_per90,team_score_2_prob,price_rank_team_position,prob_plays_60min
106,Kylian Mbappé,France,FWD,0.049460,0.0,1.000000,0.030294,0.028490,1.000000,1.000000,0.922048
119,Michael Olise,France,MID,0.044351,0.0,0.541660,0.172615,0.162338,1.000000,0.900000,0.803942
107,Ousmane Dembélé,France,MID,0.032764,0.0,0.708610,0.036920,0.034722,1.000000,1.000000,0.781460
27,Vinícius Júnior,Brazil,MID,0.031287,0.0,0.718813,0.027980,0.028490,0.704250,1.000000,0.873305
220,Mikel Oyarzabal,Spain,FWD,0.030898,0.0,0.736435,0.031814,0.033223,0.643539,1.000000,0.876473
144,Ismael Saibari,Morocco,MID,0.028857,0.0,0.562220,0.051223,0.055096,0.563053,1.000000,0.896428
18,Youri Tielemans,Belgium,MID,0.025339,1.0,0.322152,0.023914,0.025974,0.541891,0.700000,0.873335
157,Erling Haaland,Norway,FWD,0.024854,0.0,0.725769,0.029790,0.037037,0.338248,1.000000,0.851601
28,Matheus Cunha,Brazil,FWD,0.023028,0.0,0.633792,0.000000,0.000000,0.704250,1.000000,0.794758
10,Romelu Lukaku,Belgium,FWD,0.022964,0.0,0.718813,0.000000,0.000000,0.541891,1.000000,0.802544
65,Luis Díaz,Colombia,MID,0.022753,0.0,0.633792,0.037175,0.037175,0.766522,1.000000,0.662536
276,Leandro Trossard,Belgium,MID,0.022103,0.0,0.431288,0.051007,0.055402,0.541891,0.800000,0.860441
98,Jude Bellingham,England,MID,0.022064,0.0,0.385995,0.081042,0.095541,0.398092,0.890000,0.823783
341,Achraf Hakimi,Morocco,DEF,0.022051,0.0,0.270676,0.047676,0.051282,0.563053,1.000000,0.923039
85,Harry Kane,England,FWD,0.021839,0.0,0.633792,0.000000,0.000000,0.398092,1.000000,0.910706
261,Jules Koundé,France,DEF,0.021736,0.0,0.118411,0.063481,0.059701,1.000000,1.000000,0.808861
262,Bradley Barcola,France,MID,0.020402,0.0,0.579688,0.051120,0.048077,1.000000,0.750000,0.599648
349,Brahim Díaz,Morocco,MID,0.020063,0.0,0.419076,0.062395,0.067114,0.563053,0.877778,0.752313
252,Bruno Guimarães,Brazil,MID,0.019935,0.0,0.227392,0.086657,0.088235,0.704250,0.670000,0.796764
249,Christian Pulisic,USA,MID,0.019919,0.0,0.562220,0.109520,0.121212,0.521769,1.000000,0.617775
218,Lamine Yamal,Spain,MID,0.019854,0.0,0.595919,0.000000,0.000000,0.643539,1.000000,0.739021
282,Cristiano Ronaldo,Portugal,FWD,0.019117,0.0,0.584171,0.000000,0.000000,0.304423,1.000000,0.891920
101,Dayot Upamecano,France,DEF,0.018837,0.0,0.144226,0.030731,0.028902,1.000000,0.816667,0.846026
191,Nuno Mendes,Portugal,DEF,0.018666,0.0,0.195703,0.069683,0.087977,0.304423,1.000000,0.864615
216,Marc Cucurella,Spain,DEF,0.017980,0.0,0.156748,0.079799,0.083333,0.643539,0.587500,0.834914
20,Gabriel Magalhães,Brazil,DEF,0.017753,0.0,0.171433,0.027281,0.027778,0.704250,1.000000,0.866269
209,Bruno Fernandes,Portugal,MID,0.017297,0.0,0.298810,0.047572,0.060060,0.304423,1.000000,0.825673
110,Mike Maignan,France,GK,0.016473,0.0,0.000000,0.000000,0.000000,1.000000,1.000000,0.921262
130,Roberto Alvarado,Mexico,FWD,0.016340,0.0,0.298810,0.091757,0.117647,0.289853,0.450000,0.751832
90,Noni Madueke,England,FWD,0.015985,1.0,0.322152,0.104721,0.123457,0.398092,0.175000,0.560666

In [402]:
raw_cs = (
    0.8 * df["team_cs_prob"]            # strongest signal
  + 0.10 * df["stat_CS"]               # tournament history
  + 0.10 * (1 - df["stat_GC"])         # fewer goals conceded is better
)

base_cs = sigmoid((raw_cs - 0.5) * 6)

df["prob_clean_sheet"] = base_cs * df["prob_plays_60min"]

df.loc[df["position"] == "FWD", "prob_clean_sheet"] = 0.0

In [403]:
cols = [
    "name",
    "team",
    "position",
    "prob_clean_sheet",
    "team_cs_prob",
    "prob_plays_60min",
    "stat_CS",
    "stat_GC",
    "minutes_rank_team_position",
    "tackles_per90",
]

df[cols].sort_values("prob_clean_sheet", ascending=False).head(30)

,name,team,position,prob_clean_sheet,team_cs_prob,prob_plays_60min,stat_CS,stat_GC,minutes_rank_team_position,tackles_per90
110,Mike Maignan,France,GK,0.853200,1.000000,0.921262,0.50,0.285714,1.000000,0.000000
101,Dayot Upamecano,France,DEF,0.783523,1.000000,0.846026,0.50,0.285714,1.000000,0.020231
261,Jules Koundé,France,DEF,0.749103,1.000000,0.808861,0.50,0.285714,0.877778,0.032836
119,Michael Olise,France,MID,0.744547,1.000000,0.803942,0.50,0.285714,1.000000,0.012987
107,Ousmane Dembélé,France,MID,0.735131,1.000000,0.781460,0.75,0.142857,0.900000,0.010417
69,Camilo Vargas,Colombia,GK,0.661550,0.846259,0.762867,0.50,0.142857,1.000000,0.000000
260,William Saliba,France,DEF,0.642594,1.000000,0.689645,0.50,0.142857,0.755556,0.007407
224,Unai Simón,Spain,GK,0.582435,0.493063,0.912904,1.00,0.000000,1.000000,0.000000
340,Yassine Bounou,Morocco,GK,0.575933,0.631567,0.947350,0.25,0.571429,1.000000,0.000000
65,Luis Díaz,Colombia,MID,0.574544,0.846259,0.662536,0.50,0.142857,1.000000,0.003717
262,Bradley Barcola,France,MID,0.564098,1.000000,0.599648,0.75,0.142857,0.500000,0.014423
341,Achraf Hakimi,Morocco,DEF,0.561153,0.631567,0.923039,0.25,0.571429,1.000000,0.017949
113,Adrien Rabiot,France,MID,0.546248,1.000000,0.586244,0.50,0.142857,0.750000,0.007407
144,Ismael Saibari,Morocco,MID,0.544975,0.631567,0.896428,0.25,0.571429,0.877778,0.008264
117,Aurélien Tchouaméni,France,MID,0.539844,1.000000,0.589878,0.25,0.285714,0.750000,0.051852
216,Marc Cucurella,Spain,DEF,0.532677,0.493063,0.834914,1.00,0.000000,0.931250,0.005556
61,Dávinson Sánchez,Colombia,DEF,0.525994,0.846259,0.606551,0.50,0.142857,0.931250,0.014815
343,Noussair Mazraoui,Morocco,DEF,0.518233,0.631567,0.760570,0.50,0.285714,0.587500,0.030303
214,Aymeric Laporte,Spain,DEF,0.517969,0.493063,0.811860,1.00,0.000000,0.725000,0.011142
348,Neil El Aynaoui,Morocco,MID,0.514464,0.631567,0.846240,0.25,0.571429,1.000000,0.039164
227,Rodri,Spain,MID,0.510584,0.493063,0.800285,1.00,0.000000,1.000000,0.039216
217,Pau Cubarsí,Spain,DEF,0.500381,0.493063,0.784294,1.00,0.000000,0.931250,0.005556
345,Issa Diop,Morocco,DEF,0.491701,0.631567,0.758843,0.25,0.285714,0.725000,0.000000
91,Jordan Pickford,England,GK,0.487192,0.515124,0.921262,0.50,0.428571,1.000000,0.000000
229,Pedri,Spain,MID,0.486075,0.493063,0.761870,1.00,0.000000,0.900000,0.025890
60,Jhon Lucumí,Colombia,DEF,0.478089,0.846259,0.551309,0.50,0.142857,0.931250,0.003704
80,Marc Guéhi,England,DEF,0.475523,0.515124,0.782733,0.75,0.142857,0.755556,0.000000
218,Lamine Yamal,Spain,MID,0.471497,0.493063,0.739021,1.00,0.000000,0.800000,0.008889
351,Bilal El Khannouss,Morocco,MID,0.469230,0.631567,0.771836,0.25,0.571429,0.755556,0.026393
349,Brahim Díaz,Morocco,MID,0.457362,0.631567,0.752313,0.25,0.571429,0.633333,0.006711

In [404]:
position_rc_modifier = {
    "GK": 0.04,
    "FWD": 0.08,
    "DEF": 0.12,
    "MID": 0.14,
}

df["position_rc_modifier"] = df["position"].map(position_rc_modifier)

raw_rc = (
    0.30 * df["position_rc_modifier"]   # strongest prior
  + 0.25 * df["rc_per90"]              # direct history
  + 0.15 * df["tackles_per90"]         # physical involvement
  + 0.15 * df["prob_yellow_card"]      # disciplinary tendency
  + 0.10 * df["opp_over_05_prob"]      # more defending -> more challenges
)

# Red cards are extremely rare → strong compression + external gate
df["prob_red_card"] = 0.05 * sigmoid((raw_rc - 0.5) * 5) * df["prob_plays_60min"]

In [405]:
cols = [
    "name",
    "team",
    "position",
    "prob_red_card",
    "position_rc_modifier",
    "rc_per90",
    "tackles_per90",
    "prob_yellow_card",
    "opp_over_05_prob",
    "prob_plays_any",
]

df[cols].sort_values("prob_red_card", ascending=False).head(30)

,name,team,position,prob_red_card,position_rc_modifier,rc_per90,tackles_per90,prob_yellow_card,opp_over_05_prob,prob_plays_any
177,Miguel Almirón,Paraguay,MID,0.009245,0.14,0.728972,0.032710,0.099216,1.000000,0.604311
123,César Montes,Mexico,DEF,0.007806,0.12,0.577778,0.007407,0.064460,0.608231,0.565440
170,Gustavo Gómez,Paraguay,DEF,0.006923,0.12,0.000000,0.010256,0.098385,1.000000,0.926121
168,Matías Galarza,Paraguay,MID,0.006394,0.14,0.000000,0.046980,0.130667,1.000000,0.769872
284,Andrés Cubas,Paraguay,MID,0.006348,0.14,0.000000,0.035897,0.104211,1.000000,0.611035
186,Orlando Gill,Paraguay,GK,0.006137,0.04,0.000000,0.000000,0.090798,1.000000,0.902911
188,Julio Enciso,Paraguay,MID,0.006034,0.14,0.000000,0.012270,0.086163,1.000000,0.854177
191,Nuno Mendes,Portugal,DEF,0.005891,0.12,0.000000,0.014663,0.080690,0.803747,0.892531
18,Youri Tielemans,Belgium,MID,0.005829,0.14,0.000000,0.010390,0.077812,0.706667,0.828441
209,Bruno Fernandes,Portugal,MID,0.005803,0.14,0.000000,0.024024,0.079323,0.803747,0.883563
234,Weston McKennie,USA,MID,0.005770,0.14,0.000000,0.022599,0.077830,0.746908,0.857078
175,Juan José Cáceres,Paraguay,DEF,0.005767,0.12,0.000000,0.051576,0.097152,1.000000,0.610705
276,Leandro Trossard,Belgium,MID,0.005752,0.14,0.000000,0.013850,0.076844,0.706667,0.849255
282,Cristiano Ronaldo,Portugal,FWD,0.005736,0.08,0.000000,0.005698,0.080875,0.803747,0.919309
171,Júnior Alonso,Paraguay,DEF,0.005706,0.12,0.000000,0.026667,0.098627,1.000000,0.621671
303,Alistair Johnston,Canada,DEF,0.005629,0.12,0.000000,0.002778,0.089558,0.760766,0.846049
7,Brandon Mechele,Belgium,DEF,0.005626,0.12,0.000000,0.007692,0.087385,0.706667,0.797111
278,Diogo Costa,Portugal,GK,0.005596,0.04,0.000000,0.000000,0.079504,0.803747,0.937479
44,Jonathan David,Canada,FWD,0.005568,0.08,0.000000,0.003021,0.077828,0.760766,0.910190
157,Erling Haaland,Norway,FWD,0.005559,0.08,0.000000,0.000000,0.079326,0.848970,0.887407
272,Thibaut Courtois,Belgium,GK,0.005502,0.04,0.000000,0.000000,0.076477,0.706667,0.947350
49,Maxime Crépeau,Canada,GK,0.005493,0.04,0.000000,0.002778,0.077340,0.760766,0.937479
27,Vinícius Júnior,Brazil,MID,0.005351,0.14,0.000000,0.005698,0.068755,0.531328,0.898940
161,Ørjan Nyland,Norway,GK,0.005340,0.04,0.000000,0.000000,0.076848,0.848970,0.896671
293,Martin Ødegaard,Norway,MID,0.005323,0.14,0.000000,0.022989,0.073843,0.848970,0.802434
40,Richie Laryea,Canada,DEF,0.005316,0.12,0.000000,0.025496,0.072449,0.760766,0.766209
1,Timothy Castagne,Belgium,DEF,0.005253,0.12,0.000000,0.033557,0.085673,0.706667,0.724373
195,Renato Veiga,Portugal,DEF,0.005212,0.12,0.000000,0.008333,0.084074,0.803747,0.657476
20,Gabriel Magalhães,Brazil,DEF,0.005182,0.12,0.000000,0.011111,0.066897,0.531328,0.892491
341,Achraf Hakimi,Morocco,DEF,0.005163,0.12,0.000000,0.017949,0.064163,0.373114,0.923039

In [406]:
position_og_modifier = {
    "GK": 0.01,
    "FWD": 0.02,
    "MID": 0.04,
    "DEF": 0.08,
}

df["position_og_modifier"] = df["position"].map(position_og_modifier)

raw_og = (
    0.4 * df["position_og_modifier"]
  + 0.25 * df["opp_over_05_prob"]
  + 0.10 * df["tackles_per90"]
  + 0.10 * (1 - df["stat_GC"])
)

df["prob_own_goal"] = 0.03 * sigmoid((raw_og - 0.5) * 5) * df["prob_plays_60min"]

In [407]:
cols = [
    "name",
    "team",
    "position",
    "prob_own_goal",
    "position_og_modifier",
    "own_goal_rate",
    "opp_over_05_prob",
    "tackles_per90",
    "stat_GC",
    "prob_plays_any",
]

df[cols].sort_values("prob_own_goal", ascending=False).head(30)

,name,team,position,prob_own_goal,position_og_modifier,own_goal_rate,opp_over_05_prob,tackles_per90,stat_GC,prob_plays_any
168,Matías Galarza,Paraguay,MID,0.007851,0.04,0.0,1.000000,0.046980,0.142857,0.769872
170,Gustavo Gómez,Paraguay,DEF,0.007793,0.08,0.0,1.000000,0.010256,0.714286,0.926121
191,Nuno Mendes,Portugal,DEF,0.007126,0.08,0.0,0.803747,0.014663,0.285714,0.892531
186,Orlando Gill,Paraguay,GK,0.006964,0.01,0.0,1.000000,0.000000,0.714286,0.902911
278,Diogo Costa,Portugal,GK,0.006809,0.01,0.0,0.803747,0.000000,0.285714,0.937479
175,Juan José Cáceres,Paraguay,DEF,0.006756,0.08,0.0,1.000000,0.051576,0.571429,0.610705
282,Cristiano Ronaldo,Portugal,FWD,0.006706,0.02,0.0,0.803747,0.005698,0.285714,0.919309
284,Andrés Cubas,Paraguay,MID,0.006504,0.04,0.0,1.000000,0.035897,0.714286,0.611035
279,Rúben Dias,Portugal,DEF,0.006466,0.08,0.0,0.803747,0.018519,0.142857,0.737912
209,Bruno Fernandes,Portugal,MID,0.006439,0.04,0.0,0.803747,0.024024,0.285714,0.883563
171,Júnior Alonso,Paraguay,DEF,0.006393,0.08,0.0,1.000000,0.026667,0.714286,0.621671
247,Matt Freese,USA,GK,0.006382,0.01,0.0,0.746908,0.000000,0.142857,0.896671
303,Alistair Johnston,Canada,DEF,0.006309,0.08,0.0,0.760766,0.002778,0.428571,0.846049
195,Renato Veiga,Portugal,DEF,0.006301,0.08,0.0,0.803747,0.008333,0.285714,0.657476
188,Julio Enciso,Paraguay,MID,0.006293,0.04,0.0,1.000000,0.012270,0.714286,0.854177
49,Maxime Crépeau,Canada,GK,0.006194,0.01,0.0,0.760766,0.002778,0.428571,0.937479
124,Jesús Gallardo,Mexico,DEF,0.006054,0.08,0.0,0.608231,0.007092,0.000000,0.780947
44,Jonathan David,Canada,FWD,0.006047,0.02,0.0,0.760766,0.003021,0.428571,0.910190
40,Richie Laryea,Canada,DEF,0.005987,0.08,0.0,0.760766,0.025496,0.428571,0.766209
157,Erling Haaland,Norway,FWD,0.005984,0.02,0.0,0.848970,0.000000,0.571429,0.887407
135,Raúl Rangel,Mexico,GK,0.005978,0.01,0.0,0.608231,0.000000,0.000000,0.878122
161,Ørjan Nyland,Norway,GK,0.005975,0.01,0.0,0.848970,0.000000,0.571429,0.896671
234,Weston McKennie,USA,MID,0.005901,0.04,0.0,0.746908,0.022599,0.428571,0.857078
236,Antonee Robinson,USA,DEF,0.005854,0.08,0.0,0.746908,0.015385,0.142857,0.731059
242,Alexander Freeman,USA,DEF,0.005828,0.08,0.0,0.746908,0.028269,0.285714,0.747395
7,Brandon Mechele,Belgium,DEF,0.005806,0.08,0.0,0.706667,0.007692,0.571429,0.797111
216,Marc Cucurella,Spain,DEF,0.005803,0.08,0.0,0.510749,0.005556,0.000000,0.851345
10,Romelu Lukaku,Belgium,FWD,0.005798,0.02,0.0,0.706667,0.000000,0.142857,0.870300
276,Leandro Trossard,Belgium,MID,0.005775,0.04,0.0,0.706667,0.013850,0.428571,0.849255
149,Kristoffer Ajer,Norway,DEF,0.005762,0.08,0.0,0.848970,0.025926,0.571429,0.739320

In [408]:
position_pc_modifier = {
    "GK": 0.02,
    "FWD": 0.03,
    "MID": 0.06,
    "DEF": 0.10,
}

df["position_pc_modifier"] = df["position"].map(position_pc_modifier)

raw_pc = (
    0.30 * df["position_pc_modifier"]
  + 0.25 * df["penalty_conceded_rate"]
  + 0.05 * df["tackles_per90"]
  + 0.15 * df["prob_yellow_card"]
  + 0.15 * df["opp_over_05_prob"]
)

df["prob_penalty_committed"] = 0.08 * sigmoid((raw_pc - 0.5) * 5) * df["prob_plays_60min"]

In [409]:
cols = [
    "name",
    "team",
    "position",
    "prob_penalty_committed",
    "position_pc_modifier",
    "penalty_conceded_rate",
    "tackles_per90",
    "prob_yellow_card",
    "opp_over_05_prob",
    "prob_plays_any",
]

df[cols].sort_values("prob_penalty_committed", ascending=False).head(30)

,name,team,position,prob_penalty_committed,position_pc_modifier,penalty_conceded_rate,tackles_per90,prob_yellow_card,opp_over_05_prob,prob_plays_any
170,Gustavo Gómez,Paraguay,DEF,0.013256,0.10,0.0,0.010256,0.098385,1.000000,0.926121
186,Orlando Gill,Paraguay,GK,0.011846,0.02,0.0,0.000000,0.090798,1.000000,0.902911
168,Matías Galarza,Paraguay,MID,0.011178,0.06,0.0,0.046980,0.130667,1.000000,0.769872
284,Andrés Cubas,Paraguay,MID,0.011154,0.06,0.0,0.035897,0.104211,1.000000,0.611035
171,Júnior Alonso,Paraguay,DEF,0.010849,0.10,0.0,0.026667,0.098627,1.000000,0.621671
175,Juan José Cáceres,Paraguay,DEF,0.010849,0.10,0.0,0.051576,0.097152,1.000000,0.610705
191,Nuno Mendes,Portugal,DEF,0.010839,0.10,0.0,0.014663,0.080690,0.803747,0.892531
188,Julio Enciso,Paraguay,MID,0.010713,0.06,0.0,0.012270,0.086163,1.000000,0.854177
278,Diogo Costa,Portugal,GK,0.010387,0.02,0.0,0.000000,0.079504,0.803747,0.937479
303,Alistair Johnston,Canada,DEF,0.010319,0.10,0.0,0.002778,0.089558,0.760766,0.846049
282,Cristiano Ronaldo,Portugal,FWD,0.010208,0.03,0.0,0.005698,0.080875,0.803747,0.919309
7,Brandon Mechele,Belgium,DEF,0.010180,0.10,0.0,0.007692,0.087385,0.706667,0.797111
49,Maxime Crépeau,Canada,GK,0.010094,0.02,0.0,0.002778,0.077340,0.760766,0.937479
157,Erling Haaland,Norway,FWD,0.010011,0.03,0.0,0.000000,0.079326,0.848970,0.887407
272,Thibaut Courtois,Belgium,GK,0.010011,0.02,0.0,0.000000,0.076477,0.706667,0.947350
161,Ørjan Nyland,Norway,GK,0.010004,0.02,0.0,0.000000,0.076848,0.848970,0.896671
209,Bruno Fernandes,Portugal,MID,0.009849,0.06,0.0,0.024024,0.079323,0.803747,0.883563
44,Jonathan David,Canada,FWD,0.009833,0.03,0.0,0.003021,0.077828,0.760766,0.910190
18,Youri Tielemans,Belgium,MID,0.009750,0.06,0.0,0.010390,0.077812,0.706667,0.828441
234,Weston McKennie,USA,MID,0.009682,0.06,0.0,0.022599,0.077830,0.746908,0.857078
40,Richie Laryea,Canada,DEF,0.009651,0.10,0.0,0.025496,0.072449,0.760766,0.766209
195,Renato Veiga,Portugal,DEF,0.009614,0.10,0.0,0.008333,0.084074,0.803747,0.657476
276,Leandro Trossard,Belgium,MID,0.009607,0.06,0.0,0.013850,0.076844,0.706667,0.849255
149,Kristoffer Ajer,Norway,DEF,0.009538,0.10,0.0,0.025926,0.071930,0.848970,0.739320
1,Timothy Castagne,Belgium,DEF,0.009398,0.10,0.0,0.033557,0.085673,0.706667,0.724373
279,Rúben Dias,Portugal,DEF,0.009374,0.10,0.0,0.018519,0.086826,0.803747,0.737912
247,Matt Freese,USA,GK,0.009335,0.02,0.0,0.000000,0.071655,0.746908,0.896671
0,Maxim De Cuyper,Belgium,DEF,0.009277,0.10,0.0,0.010274,0.084099,0.706667,0.837189
293,Martin Ødegaard,Norway,MID,0.009124,0.06,0.0,0.022989,0.073843,0.848970,0.802434
20,Gabriel Magalhães,Brazil,DEF,0.009028,0.10,0.0,0.011111,0.066897,0.531328,0.892491

In [410]:
df["lambda_opp"] = -np.log(df["team_cs_prob"].clip(lower=0.01))

df["prob_gc_0"] = np.exp(-df["lambda_opp"])
df["prob_gc_1"] = df["lambda_opp"] * np.exp(-df["lambda_opp"])
df["prob_gc_2"] = (df["lambda_opp"] ** 2 / 2) * np.exp(-df["lambda_opp"])
df["prob_gc_3"] = (df["lambda_opp"] ** 3 / 6) * np.exp(-df["lambda_opp"])
df["prob_gc_4plus"] = 1 - (
    df["prob_gc_0"]
    + df["prob_gc_1"]
    + df["prob_gc_2"]
    + df["prob_gc_3"]
)

# RAW expected goals conceded (true intensity)
df["expected_goals_conceded"] = df["lambda_opp"]

# Normalize ONLY as auxiliary feature (separate column)
scaler = MinMaxScaler()
df["expected_goals_conceded_norm"] = scaler.fit_transform(
    df[["expected_goals_conceded"]]
)

# Player exposure to goals conceded (correct)
df["expected_player_goals_conceded"] = (
    df["lambda_opp"] * df["prob_plays_60min"]
)

# GC penalty MUST use raw λ (correct Poisson expectation)
df["expected_gc_penalty"] = (
    -(df["lambda_opp"] - 1 + np.exp(-df["lambda_opp"]))
    * df["prob_plays_60min"]
)

df.loc[df["position"].isin(["MID", "FWD"]), [
    "expected_player_goals_conceded",
    "expected_gc_penalty"
]] = 0.0

In [411]:
cols = [
    "name",
    "team",
    "position",
    "prob_plays_60min",
    "team_cs_prob",
    "lambda_opp",
    "prob_gc_0",
    "prob_gc_1",
    "prob_gc_2",
    "prob_gc_3",
    "prob_gc_4plus",
    "expected_player_goals_conceded",
    "expected_gc_penalty",
]

df[df["position"].isin(["GK", "DEF"])][cols] \
    .sort_values("expected_gc_penalty") \
    .head(30)

,name,team,position,prob_plays_60min,team_cs_prob,lambda_opp,prob_gc_0,prob_gc_1,prob_gc_2,prob_gc_3,prob_gc_4plus,expected_player_goals_conceded,expected_gc_penalty
170,Gustavo Gómez,Paraguay,DEF,0.926121,0.000000,4.605170,0.010000,0.046052,0.106038,0.162774,0.675136,4.264943,-3.348084
186,Orlando Gill,Paraguay,GK,0.920561,0.000000,4.605170,0.010000,0.046052,0.106038,0.162774,0.675136,4.239342,-3.327986
171,Júnior Alonso,Paraguay,DEF,0.755296,0.000000,4.605170,0.010000,0.046052,0.106038,0.162774,0.675136,3.478267,-2.730524
175,Juan José Cáceres,Paraguay,DEF,0.752093,0.000000,4.605170,0.010000,0.046052,0.106038,0.162774,0.675136,3.463517,-2.718945
172,Omar Alderete,Paraguay,DEF,0.461743,0.000000,4.605170,0.010000,0.046052,0.106038,0.162774,0.675136,2.126403,-1.669278
176,José Canale,Paraguay,DEF,0.337258,0.000000,4.605170,0.010000,0.046052,0.106038,0.162774,0.675136,1.553130,-1.219244
174,Gustavo Velázquez,Paraguay,DEF,0.310458,0.000000,4.605170,0.010000,0.046052,0.106038,0.162774,0.675136,1.429713,-1.122359
184,Roberto Fernández,Paraguay,GK,0.266002,0.000000,4.605170,0.010000,0.046052,0.106038,0.162774,0.675136,1.224987,-0.961644
161,Ørjan Nyland,Norway,GK,0.863358,0.147601,1.913245,0.147601,0.282396,0.270147,0.172286,0.127571,1.651815,-0.915889
120,Benjamin Asare,Ghana,GK,0.672692,0.115078,2.162141,0.115078,0.248816,0.268988,0.193863,0.173255,1.454454,-0.859175
149,Kristoffer Ajer,Norway,DEF,0.741758,0.147601,1.913245,0.147601,0.282396,0.270147,0.172286,0.127571,1.419166,-0.786891
278,Diogo Costa,Portugal,GK,0.921262,0.192176,1.649341,0.192176,0.316965,0.261391,0.143708,0.085760,1.519475,-0.775258
185,Gastón Olveira,Paraguay,GK,0.206689,0.000000,4.605170,0.010000,0.046052,0.106038,0.162774,0.675136,0.951838,-0.747216
191,Nuno Mendes,Portugal,DEF,0.864615,0.192176,1.649341,0.192176,0.316965,0.261391,0.143708,0.085760,1.426045,-0.727589
319,Gideon Mensah,Ghana,DEF,0.562618,0.115078,2.162141,0.115078,0.248816,0.268988,0.193863,0.173255,1.216460,-0.718587
153,David Møller Wolfe,Norway,DEF,0.646741,0.147601,1.913245,0.147601,0.282396,0.270147,0.172286,0.127571,1.237374,-0.686092
195,Renato Veiga,Portugal,DEF,0.766337,0.192176,1.649341,0.192176,0.316965,0.261391,0.143708,0.085760,1.263951,-0.644886
279,Rúben Dias,Portugal,DEF,0.744304,0.192176,1.649341,0.192176,0.316965,0.261391,0.143708,0.085760,1.227612,-0.626345
317,Marvin Senaya,Ghana,DEF,0.489066,0.115078,2.162141,0.115078,0.248816,0.268988,0.193863,0.173255,1.057429,-0.624644
151,Marcus Pedersen,Norway,DEF,0.586851,0.147601,1.913245,0.147601,0.282396,0.270147,0.172286,0.127571,1.122789,-0.622558
155,Torbjørn Heggem,Norway,DEF,0.578687,0.147601,1.913245,0.147601,0.282396,0.270147,0.172286,0.127571,1.107170,-0.613897
49,Maxime Crépeau,Canada,GK,0.921262,0.242893,1.415135,0.242893,0.343726,0.243209,0.114725,0.055447,1.303710,-0.606216
303,Alistair Johnston,Canada,DEF,0.843267,0.242893,1.415135,0.242893,0.343726,0.243209,0.114725,0.055447,1.193337,-0.554893
247,Matt Freese,USA,GK,0.863358,0.259268,1.349894,0.259268,0.349984,0.236221,0.106291,0.048237,1.165441,-0.525925
40,Richie Laryea,Canada,DEF,0.793486,0.242893,1.415135,0.242893,0.343726,0.243209,0.114725,0.055447,1.122890,-0.522136
315,Jonas Adjetey,Ghana,DEF,0.404613,0.115078,2.162141,0.115078,0.248816,0.268988,0.193863,0.173255,0.874830,-0.516779
192,João Cancelo,Portugal,DEF,0.611201,0.192176,1.649341,0.192176,0.316965,0.261391,0.143708,0.085760,1.008080,-0.514337
272,Thibaut Courtois,Belgium,GK,0.947350,0.290425,1.236409,0.290425,0.359084,0.221988,0.091489,0.037014,1.171312,-0.499096
41,Derek Cornelius,Canada,DEF,0.731729,0.242893,1.415135,0.242893,0.343726,0.243209,0.114725,0.055447,1.035495,-0.481498
7,Brandon Mechele,Belgium,DEF,0.861364,0.290425,1.236409,0.290425,0.359084,0.221988,0.091489,0.037014,1.064998,-0.453796

In [412]:
raw_save = (
    0.25 * df["expected_goals_conceded"]  # opportunity
  + 0.20 * df["saves_per90"]             # ability
  + 0.05 * df["recent_saves_per90"]      # recent form
  + 0.20 * df["price"]                   # overall GK quality
)

# Expected saves (λ)
df["expected_saves"] = (
    sigmoid((raw_save - 0.5) * 6) * 4
) * df["prob_plays_60min"]

df.loc[df["position"] != "GK", "expected_saves"] = 0.0

In [413]:
cols = [
    "name",
    "team",
    "expected_saves",
    "expected_goals_conceded",
    "saves_per90",
    "recent_saves_per90",
    "price",
    "prob_plays_any",
]

df[df["position"] == "GK"][cols] \
    .sort_values("expected_saves", ascending=False) \
    .head(30)

,name,team,expected_saves,expected_goals_conceded,saves_per90,recent_saves_per90,price,prob_plays_any
186,Orlando Gill,Paraguay,3.662987,4.605170,0.876923,0.960000,0.000000,0.902911
278,Diogo Costa,Portugal,2.553604,1.649341,0.700000,0.866667,0.200000,0.937479
161,Ørjan Nyland,Norway,2.268837,1.913245,0.400000,0.600000,0.100000,0.896671
120,Benjamin Asare,Ghana,2.073951,2.162141,0.640000,0.500000,0.042857,0.813408
272,Thibaut Courtois,Belgium,1.630302,1.236409,0.415385,0.420000,0.200000,0.947350
247,Matt Freese,USA,1.465280,1.349894,0.333333,0.500000,0.100000,0.896671
49,Maxime Crépeau,Canada,1.450981,1.415135,0.250000,0.200000,0.071429,0.937479
162,Egil Selvik,Norway,1.168544,1.913245,1.000000,1.000000,0.042857,0.449405
35,Alisson Becker,Brazil,1.147800,0.753374,0.550000,0.600000,0.214286,0.923274
184,Roberto Fernández,Paraguay,1.044749,4.605170,0.000000,0.000000,0.071429,0.463813
310,Lawrence Ati Zigi,Ghana,0.966818,2.162141,0.400000,0.000000,0.071429,0.593502
135,Raúl Rangel,Mexico,0.895277,0.939180,0.310345,0.279070,0.057143,0.878122
185,Gastón Olveira,Paraguay,0.811278,4.605170,0.000000,0.000000,0.042857,0.285978
91,Jordan Pickford,England,0.751365,0.663348,0.300000,0.200000,0.185714,0.937479
224,Unai Simón,Spain,0.732729,0.707117,0.200000,0.200000,0.214286,0.927081
340,Yassine Bounou,Morocco,0.567420,0.459551,0.276923,0.120000,0.171429,0.947350
246,Matt Turner,USA,0.422460,1.349894,0.000000,0.000000,0.071429,0.449405
110,Mike Maignan,France,0.386932,-0.000000,0.400000,0.400000,0.214286,0.937479
203,Rui Silva,Portugal,0.347741,1.649341,0.000000,0.000000,0.171429,0.345247
311,Joseph Anang,Ghana,0.340161,2.162141,0.000000,0.000000,0.014286,0.196234
204,José Sá,Portugal,0.318373,1.649341,0.000000,0.000000,0.171429,0.253506
290,Sander Tangvik,Norway,0.308942,1.913245,0.000000,0.000000,0.000000,0.274881
69,Camilo Vargas,Colombia,0.303711,0.166930,0.266667,0.300000,0.114286,0.896671
50,Dayne St. Clair,Canada,0.251763,1.415135,0.000000,0.000000,0.042857,0.285978
15,Senne Lammens,Belgium,0.250106,1.236409,0.000000,0.000000,0.157143,0.383433
133,Guillermo Ochoa,Mexico,0.236765,0.939180,0.000000,0.000000,0.100000,0.523214
51,Owen Goodman,Canada,0.222340,1.415135,0.000000,0.000000,0.000000,0.308957
248,Chris Brady,USA,0.180968,1.349894,0.000000,0.000000,0.000000,0.274881
34,Ederson,Brazil,0.176839,0.753374,0.000000,0.000000,0.214286,0.450166
273,Mike Penders,Belgium,0.166935,1.236409,0.000000,0.000000,0.000000,0.223567

In [414]:
raw_pen_save = (
    0.40 * df["price"]                    
  + 0.25 * df["expected_goals_conceded"]
  + 0.15 * df["opp_over_05_prob"]
  + 0.05 * df["stat_PS"]
)

# Strong compression because penalty saves are exceptionally rare
df["prob_penalty_save"] = sigmoid((raw_pen_save - 0.5) * 3) / 20 * df["prob_plays_60min"]

df.loc[df["position"] != "GK", "prob_penalty_save"] = 0.0

In [415]:
cols = [
    "name",
    "team",
    "prob_penalty_save",
    "price",
    "expected_goals_conceded",
    "opp_over_05_prob",
    "prob_plays_60min",
    "stat_PS",
]

df[df["position"] == "GK"][cols] \
    .sort_values("prob_penalty_save", ascending=False) \
    .head(30)

,name,team,prob_penalty_save,price,expected_goals_conceded,opp_over_05_prob,prob_plays_60min,stat_PS
186,Orlando Gill,Paraguay,0.042213,0.000000,4.605170,1.000000,0.920561,0.0
278,Diogo Costa,Portugal,0.026895,0.200000,1.649341,0.803747,0.921262,0.0
161,Ørjan Nyland,Norway,0.026226,0.100000,1.913245,0.848970,0.863358,0.0
272,Thibaut Courtois,Belgium,0.023510,0.200000,1.236409,0.706667,0.947350,0.0
49,Maxime Crépeau,Canada,0.022910,0.071429,1.415135,0.760766,0.921262,0.0
120,Benjamin Asare,Ghana,0.021479,0.042857,2.162141,0.880453,0.672692,0.0
247,Matt Freese,USA,0.021244,0.100000,1.349894,0.746908,0.863358,0.0
35,Alisson Becker,Brazil,0.017807,0.214286,0.753374,0.531328,0.908430,0.0
224,Unai Simón,Spain,0.017419,0.214286,0.707117,0.510749,0.912904,0.0
135,Raúl Rangel,Mexico,0.016982,0.057143,0.939180,0.608231,0.874073,0.0
91,Jordan Pickford,England,0.016712,0.185714,0.663348,0.480944,0.921262,0.0
340,Yassine Bounou,Morocco,0.014871,0.171429,0.459551,0.373114,0.947350,0.0
184,Roberto Fernández,Paraguay,0.012281,0.071429,4.605170,1.000000,0.266002,0.0
110,Mike Maignan,France,0.011566,0.214286,-0.000000,0.000000,0.921262,1.0
310,Lawrence Ati Zigi,Ghana,0.011292,0.071429,2.162141,0.880453,0.349344,0.0
162,Egil Selvik,Norway,0.010718,0.042857,1.913245,0.848970,0.362658,0.0
185,Gastón Olveira,Paraguay,0.009517,0.042857,4.605170,1.000000,0.206689,0.0
69,Camilo Vargas,Colombia,0.009059,0.114286,0.166930,0.158268,0.762867,0.0
246,Matt Turner,USA,0.008768,0.071429,1.349894,0.746908,0.362658,0.0
133,Guillermo Ochoa,Mexico,0.006352,0.100000,0.939180,0.608231,0.316945,0.0
203,Rui Silva,Portugal,0.005948,0.171429,1.649341,0.803747,0.206689,0.0
15,Senne Lammens,Belgium,0.005447,0.157143,1.236409,0.706667,0.225308,0.0
204,José Sá,Portugal,0.005445,0.171429,1.649341,0.803747,0.189233,0.0
34,Ederson,Brazil,0.005214,0.214286,0.753374,0.531328,0.266002,0.0
50,Dayne St. Clair,Canada,0.005051,0.042857,1.415135,0.760766,0.206689,0.0
290,Sander Tangvik,Norway,0.004779,0.000000,1.913245,0.848970,0.165205,0.0
311,Joseph Anang,Ghana,0.004748,0.014286,2.162141,0.880453,0.150588,0.0
223,David Raya,Spain,0.004676,0.214286,0.707117,0.510749,0.245085,0.0
51,Owen Goodman,Canada,0.004503,0.000000,1.415135,0.760766,0.189233,0.0
248,Chris Brady,USA,0.003818,0.000000,1.349894,0.746908,0.165205,0.0

In [416]:
raw_tackles = (
    0.40 * df["tackles_per90"]
  + 0.20 * df["recent_tackles_per90"]
  + 0.05 * df["expected_goals_conceded"]
  + 0.10 * df["match_over_25_prob"]
  + 0.15 * df["price"]
)

lam_tackles = sigmoid((raw_tackles - 0.5) * 6) * 3
df["expected_tackle_points"] = (lam_tackles / 3) * df["prob_plays_60min"]
df.loc[df["position"] != "MID", "expected_tackle_points"] = 0.0

In [417]:
cols = [
    "name",
    "team",
    "expected_tackle_points",
    "tackles_per90",
    "recent_tackles_per90",
    "expected_goals_conceded",
    "match_over_25_prob",
    "price",
    "prob_plays_60min",
]

df[df["position"] == "MID"][cols] \
    .sort_values("expected_tackle_points", ascending=False) \
    .head(30)

,name,team,expected_tackle_points,tackles_per90,recent_tackles_per90,expected_goals_conceded,match_over_25_prob,price,prob_plays_60min
168,Matías Galarza,Paraguay,0.320275,0.046980,0.281879,4.605170,1.000000,0.185714,0.798212
284,Andrés Cubas,Paraguay,0.294653,0.035897,0.180000,4.605170,1.000000,0.171429,0.811533
188,Julio Enciso,Paraguay,0.293598,0.012270,0.050847,4.605170,1.000000,0.442857,0.792108
177,Miguel Almirón,Paraguay,0.242876,0.032710,0.222222,4.605170,1.000000,0.357143,0.588171
189,Diego Gómez,Paraguay,0.209887,0.033898,0.230769,4.605170,1.000000,0.471429,0.475609
187,Damián Bobadilla,Paraguay,0.186194,0.036842,0.289655,4.605170,1.000000,0.285714,0.443970
209,Bruno Fernandes,Portugal,0.179227,0.024024,0.123457,1.649341,0.622824,0.714286,0.825673
293,Martin Ødegaard,Norway,0.176394,0.022989,0.133333,1.913245,0.831077,0.600000,0.745991
27,Vinícius Júnior,Brazil,0.172980,0.005698,0.022989,0.753374,0.831077,0.928571,0.873305
234,Weston McKennie,USA,0.155058,0.022599,0.181818,1.349894,0.831077,0.371429,0.842843
227,Rodri,Spain,0.147699,0.039216,0.266667,0.707117,0.622824,0.571429,0.800285
107,Ousmane Dembélé,France,0.146082,0.010417,0.057692,-0.000000,1.000000,0.928571,0.781460
208,João Neves,Portugal,0.144268,0.029900,0.227488,1.649341,0.622824,0.428571,0.729915
119,Michael Olise,France,0.142938,0.012987,0.055046,-0.000000,1.000000,0.857143,0.803942
276,Leandro Trossard,Belgium,0.142278,0.013850,0.066421,1.236409,0.831077,0.442857,0.860441
218,Lamine Yamal,Spain,0.136231,0.008889,0.058252,0.707117,0.622824,0.928571,0.739021
252,Bruno Guimarães,Brazil,0.135338,0.029412,0.161538,0.753374,0.831077,0.471429,0.796764
18,Youri Tielemans,Belgium,0.135129,0.010390,0.061017,1.236409,0.831077,0.371429,0.873335
229,Pedri,Spain,0.131931,0.025890,0.164384,0.707117,0.622824,0.657143,0.761870
19,Kevin De Bruyne,Belgium,0.130567,0.006645,0.055814,1.236409,0.831077,0.571429,0.735497
233,Malik Tillman,USA,0.129766,0.022556,0.195652,1.349894,0.831077,0.371429,0.695948
38,Casemiro,Brazil,0.123840,0.041522,0.270492,0.753374,0.831077,0.400000,0.673935
117,Aurélien Tchouaméni,France,0.112092,0.051852,0.366667,-0.000000,1.000000,0.428571,0.589878
164,Antonio Nusa,Norway,0.109986,0.013514,0.080537,1.913245,0.831077,0.371429,0.585489
249,Christian Pulisic,USA,0.107515,0.012121,0.050000,1.349894,0.831077,0.500000,0.617775
145,Sander Berge,Norway,0.106856,0.022222,0.166667,1.913245,0.831077,0.171429,0.595310
148,Patrick Berg,Norway,0.105940,0.017094,0.080000,1.913245,0.831077,0.300000,0.590492
166,Maurício Magalhães Prado,Paraguay,0.105609,0.039216,0.222222,4.605170,1.000000,0.157143,0.282579
98,Jude Bellingham,England,0.104374,0.028662,0.153846,0.663348,0.000000,0.685714,0.823783
207,Vitinha,Portugal,0.102517,0.006711,0.055814,1.649341,0.622824,0.414286,0.650140

In [418]:
raw_cc = (
    0.20 * df["cc_per90"]
  + 0.10 * df["recent_cc_per90"]
  + 0.10 * df["stat_CC"]
  + 0.25 * df["match_over_25_prob"]
  + 0.10 * df["anytime_scorer_prob"]
  + 0.10 * df["price"]
)
lam_cc = sigmoid((raw_cc - 0.5) * 6) * 3
df["expected_cc_points"] = (lam_cc / 2) * df["prob_plays_60min"]
df.loc[df["position"] != "MID", "expected_cc_points"] = 0.0

In [419]:
cols = [
    "name",
    "team",
    "position",
    "expected_cc_points",
    "cc_per90",
    "recent_cc_per90",
    "stat_CC",
    "match_over_25_prob",
    "anytime_scorer_prob",
    "price",
    "prob_plays_60min",
]

df[cols].sort_values("expected_cc_points", ascending=False).head(30)

,name,team,position,expected_cc_points,cc_per90,recent_cc_per90,stat_CC,match_over_25_prob,anytime_scorer_prob,price,prob_plays_60min
119,Michael Olise,France,MID,0.675390,0.162338,0.178899,1.0,1.000000,0.541660,0.857143,0.803942
107,Ousmane Dembélé,France,MID,0.493533,0.034722,0.062500,0.2,1.000000,0.708610,0.928571,0.781460
27,Vinícius Júnior,Brazil,MID,0.469921,0.028490,0.049808,0.2,0.831077,0.718813,0.928571,0.873305
276,Leandro Trossard,Belgium,MID,0.382458,0.055402,0.095941,0.4,0.831077,0.431288,0.442857,0.860441
188,Julio Enciso,Paraguay,MID,0.378749,0.061350,0.055085,0.4,1.000000,0.213634,0.442857,0.792108
252,Bruno Guimarães,Brazil,MID,0.376119,0.088235,0.150000,0.6,0.831077,0.227392,0.471429,0.796764
293,Martin Ødegaard,Norway,MID,0.329291,0.076628,0.072222,0.4,0.831077,0.238986,0.600000,0.745991
262,Bradley Barcola,France,MID,0.329213,0.048077,0.065657,0.2,1.000000,0.579688,0.642857,0.599648
209,Bruno Fernandes,Portugal,MID,0.313586,0.060060,0.106996,0.4,0.622824,0.298810,0.714286,0.825673
18,Youri Tielemans,Belgium,MID,0.306492,0.025974,0.000000,0.2,0.831077,0.322152,0.371429,0.873335
249,Christian Pulisic,USA,MID,0.301224,0.121212,0.000000,0.4,0.831077,0.562220,0.500000,0.617775
168,Matías Galarza,Paraguay,MID,0.297209,0.033557,0.043624,0.2,1.000000,0.156748,0.185714,0.798212
234,Weston McKennie,USA,MID,0.270989,0.000000,0.000000,0.0,0.831077,0.385995,0.371429,0.842843
218,Lamine Yamal,Spain,MID,0.266373,0.000000,0.000000,0.0,0.622824,0.595919,0.928571,0.739021
19,Kevin De Bruyne,Belgium,MID,0.264965,0.000000,0.000000,0.0,0.831077,0.431288,0.571429,0.735497
148,Patrick Berg,Norway,MID,0.264722,0.128205,0.173333,0.6,0.831077,0.171433,0.300000,0.590492
113,Adrien Rabiot,France,MID,0.252792,0.037037,0.000000,0.2,1.000000,0.298810,0.414286,0.586244
233,Malik Tillman,USA,MID,0.246858,0.037594,0.000000,0.2,0.831077,0.322152,0.371429,0.695948
284,Andrés Cubas,Paraguay,MID,0.246382,0.000000,0.000000,0.0,1.000000,0.042974,0.171429,0.811533
229,Pedri,Spain,MID,0.229270,0.032362,0.000000,0.2,0.622824,0.217035,0.657143,0.761870
109,Désiré Doué,France,MID,0.227886,0.046729,0.102362,0.2,1.000000,0.579688,0.571429,0.421060
117,Aurélien Tchouaméni,France,MID,0.215527,0.000000,0.000000,0.0,1.000000,0.182872,0.428571,0.589878
39,Lucas Paquetá,Brazil,MID,0.208122,0.127119,0.222857,0.6,0.831077,0.000000,0.428571,0.463364
177,Miguel Almirón,Paraguay,MID,0.207453,0.000000,0.000000,0.0,1.000000,0.176998,0.357143,0.588171
227,Rodri,Spain,MID,0.203930,0.000000,0.000000,0.0,0.622824,0.227392,0.571429,0.800285
38,Casemiro,Brazil,MID,0.203696,0.000000,0.000000,0.0,0.831077,0.227392,0.400000,0.673935
144,Ismael Saibari,Morocco,MID,0.202568,0.055096,0.094891,0.4,0.191489,0.562220,0.471429,0.896428
11,Jérémy Doku,Belgium,MID,0.192208,0.000000,0.000000,0.0,0.831077,0.353378,0.571429,0.552935
65,Luis Díaz,Colombia,MID,0.180166,0.037175,0.000000,0.2,0.368794,0.633792,0.657143,0.662536
164,Antonio Nusa,Norway,MID,0.180105,0.000000,0.000000,0.0,0.831077,0.292781,0.371429,0.585489

In [420]:
raw_sot = (
    0.35 * df["sot_per90"]
  + 0.20 * df["goal_rate"]
  + 0.15 * df["stat_GS"]
  + 0.20 * df["match_over_25_prob"]
  + 0.10 * df["anytime_scorer_prob"]
  + 0.10 * df["price"]
)
lam_sot = sigmoid((raw_sot - 0.5) * 6) * 3  # expected SoT volume per game
df["expected_sot_points"] = (lam_sot / 2) * df["prob_plays_60min"]
df.loc[~df["position"].isin(["FWD"]), "expected_sot_points"] = 0.0

In [421]:
cols = [
    "name",
    "team",
    "position",
    "expected_sot_points",
    "sot_per90",
    "goal_rate",
    "stat_GS",
    "match_over_25_prob",
    "anytime_scorer_prob",
    "price",
    "prob_plays_60min",
]

df[cols].sort_values("expected_sot_points", ascending=False).head(30)

,name,team,position,expected_sot_points,sot_per90,goal_rate,stat_GS,match_over_25_prob,anytime_scorer_prob,price,prob_plays_60min
106,Kylian Mbappé,France,FWD,1.179724,0.518519,0.307692,1.000000,1.000000,1.000000,1.000000,0.922048
157,Erling Haaland,Norway,FWD,0.973166,0.466667,0.333333,0.833333,0.831077,0.725769,1.000000,0.851601
220,Mikel Oyarzabal,Spain,FWD,0.739737,0.372093,0.239203,0.666667,0.622824,0.736435,0.657143,0.876473
282,Cristiano Ronaldo,Portugal,FWD,0.627510,0.279202,0.153846,0.500000,0.622824,0.584171,0.928571,0.891920
28,Matheus Cunha,Brazil,FWD,0.612324,0.297872,0.229787,0.500000,0.831077,0.633792,0.542857,0.794758
85,Harry Kane,England,FWD,0.609149,0.355932,0.254237,0.833333,0.000000,0.633792,1.000000,0.910706
10,Romelu Lukaku,Belgium,FWD,0.494468,0.158192,0.203390,0.333333,0.831077,0.718813,0.557143,0.802544
44,Jonathan David,Canada,FWD,0.363252,0.296073,0.163142,0.500000,0.191489,0.376101,0.500000,0.885500
128,Julián Quiñones,Mexico,FWD,0.221873,0.210210,0.162162,0.500000,0.000000,0.431288,0.300000,0.794582
197,Gonçalo Ramos,Portugal,FWD,0.213910,0.411765,0.529412,0.166667,0.622824,0.488329,0.571429,0.280551
127,Raúl Jiménez,Mexico,FWD,0.206400,0.243478,0.156522,0.333333,0.000000,0.488329,0.500000,0.700007
158,Alexander Sørloth,Norway,FWD,0.189587,0.000000,0.000000,0.000000,0.831077,0.407482,0.471429,0.679053
32,Rayan,Brazil,FWD,0.184329,0.063063,0.000000,0.000000,0.831077,0.472716,0.300000,0.624536
219,Ferran Torres,Spain,FWD,0.169958,0.176101,0.000000,0.000000,0.622824,0.584171,0.614286,0.476090
12,Dodi Lukébakio,Belgium,FWD,0.162295,0.145833,0.000000,0.000000,0.831077,0.385995,0.342857,0.489309
244,Ricardo Pepi,USA,FWD,0.151055,0.000000,0.000000,0.000000,0.831077,0.562220,0.342857,0.534182
352,Soufiane Rahimi,Morocco,FWD,0.147197,0.459016,0.295082,0.166667,0.191489,0.472716,0.300000,0.325110
45,Cyle Larin,Canada,FWD,0.135368,0.345679,0.222222,0.333333,0.191489,0.298810,0.385714,0.352533
181,Gabriel Ávalos,Paraguay,FWD,0.134589,0.000000,0.000000,0.000000,1.000000,0.231102,0.200000,0.508822
142,Ayoub El Kaabi,Morocco,FWD,0.121028,0.400000,0.000000,0.000000,0.191489,0.504869,0.342857,0.415016
330,Antoine Semenyo,Ghana,FWD,0.114776,0.000000,0.000000,0.000000,0.368794,0.298810,0.528571,0.677479
178,Antonio Sanabria,Paraguay,FWD,0.101033,0.000000,0.000000,0.000000,1.000000,0.231102,0.428571,0.341642
46,Tajon Buchanan,Canada,FWD,0.100836,0.095238,0.000000,0.000000,0.191489,0.227392,0.285714,0.712953
198,João Félix,Portugal,FWD,0.098212,0.104478,0.000000,0.000000,0.622824,0.322152,0.428571,0.384234
309,Promise David,Canada,FWD,0.093722,0.656250,0.281250,0.166667,0.191489,0.333127,0.271429,0.169899
67,Luis Suárez,Colombia,FWD,0.093639,0.000000,0.000000,0.000000,0.368794,0.633792,0.314286,0.518468
182,Gustavo Caballero,Paraguay,FWD,0.092641,0.215385,0.000000,0.000000,1.000000,0.156748,0.100000,0.265515
33,Endrick,Brazil,FWD,0.089838,0.000000,0.000000,0.000000,0.831077,0.633792,0.285714,0.315473
66,Jhon Córdoba,Colombia,FWD,0.084573,0.152174,0.000000,0.000000,0.368794,0.607977,0.371429,0.350031
159,Andreas Schjelderup,Norway,FWD,0.080523,0.000000,0.000000,0.000000,0.831077,0.275931,0.385714,0.321098

In [422]:
df["expected_qualification_points"] = df["team_qualify_prob"] * 2

In [423]:
cols = [
    "name",
    "team",
    "position",
    "expected_qualification_points",
    "team_qualify_prob",
    "price",
    "prob_plays_60min",
]

df[cols].sort_values("expected_qualification_points", ascending=False).head(30)

,name,team,position,expected_qualification_points,team_qualify_prob,price,prob_plays_60min
100,Maxence Lacroix,France,DEF,2.000000,1.000000,0.142857,0.140576
110,Mike Maignan,France,GK,2.000000,1.000000,0.214286,0.921262
111,Brice Samba,France,GK,2.000000,1.000000,0.142857,0.206689
112,N'Golo Kanté,France,MID,2.000000,1.000000,0.228571,0.059524
113,Adrien Rabiot,France,MID,2.000000,1.000000,0.414286,0.586244
114,Warren Zaïre-Emery,France,MID,2.000000,1.000000,0.371429,0.060370
263,Jean-Philippe Mateta,France,FWD,2.000000,1.000000,0.428571,0.212867
99,Theo Hernández,France,DEF,2.000000,1.000000,0.214286,0.363809
116,Maghnes Akliouche,France,MID,2.000000,1.000000,0.414286,0.082256
115,Manu Koné,France,MID,2.000000,1.000000,0.371429,0.226586
118,Rayan Cherki,France,MID,2.000000,1.000000,0.642857,0.191551
117,Aurélien Tchouaméni,France,MID,2.000000,1.000000,0.428571,0.589878
119,Michael Olise,France,MID,2.000000,1.000000,0.857143,0.803942
106,Kylian Mbappé,France,FWD,2.000000,1.000000,1.000000,0.922048
107,Ousmane Dembélé,France,MID,2.000000,1.000000,0.928571,0.781460
108,Marcus Thuram,France,FWD,2.000000,1.000000,0.571429,0.181956
109,Désiré Doué,France,MID,2.000000,1.000000,0.571429,0.421060
104,Lucas Digne,France,DEF,2.000000,1.000000,0.214286,0.419495
105,Malo Gusto,France,DEF,2.000000,1.000000,0.228571,0.127526
103,Lucas Hernández,France,DEF,2.000000,1.000000,0.242857,0.094348
102,Ibrahima Konaté,France,DEF,2.000000,1.000000,0.200000,0.077452
101,Dayot Upamecano,France,DEF,2.000000,1.000000,0.257143,0.846026
262,Bradley Barcola,France,MID,2.000000,1.000000,0.642857,0.599648
261,Jules Koundé,France,DEF,2.000000,1.000000,0.271429,0.808861
260,William Saliba,France,DEF,2.000000,1.000000,0.257143,0.689645
259,Robin Risser,France,GK,2.000000,1.000000,0.000000,0.189233
65,Luis Díaz,Colombia,MID,1.786818,0.893409,0.657143,0.662536
58,Richard Ríos,Colombia,MID,1.786818,0.893409,0.171429,0.136797
59,Daniel Muñoz,Colombia,DEF,1.786818,0.893409,0.157143,0.479941
60,Jhon Lucumí,Colombia,DEF,1.786818,0.893409,0.114286,0.551309

In [424]:
df["ep_appearance"] = df["prob_plays_any"] + df["prob_plays_60min"]

GOAL_PTS = {"GK": 9, "DEF": 7, "MID": 6, "FWD": 5}
df["ep_goal"] = df["prob_scores"] * df["position"].map(GOAL_PTS)

df["ep_assist"] = df["expected_assists"] * 3

df["ep_yellow_card"]  = df["prob_yellow_card"]        * (-1)
df["ep_red_card"]     = df["prob_red_card"]           * (-2)
df["ep_own_goal"]     = df["prob_own_goal"]           * (-2)
df["ep_pen_won"]      = df["prob_pen_won"]            *   2
df["ep_pen_conceded"] = df["prob_penalty_committed"]  * (-1)


CS_PTS = {"GK": 5, "DEF": 5, "MID": 1, "FWD": 0}
df["ep_clean_sheet"] = df["prob_clean_sheet"] * df["position"].map(CS_PTS)



df["ep_gc_penalty"] = df["expected_gc_penalty"]       # already zeroed for MID/FWD

df["ep_penalty_save"] = 0.0
df["ep_saves"]        = 0.0
gk = df["position"] == "GK"
df.loc[gk, "ep_penalty_save"] = df.loc[gk, "prob_penalty_save"] * 3
df.loc[gk, "ep_saves"]        = df.loc[gk, "expected_saves"] / 3

df["ep_tackles"] = 0.0
df["ep_cc"]      = 0.0
mid = df["position"] == "MID"
df.loc[mid, "ep_tackles"] = df.loc[mid, "expected_tackle_points"]   # already /3
df.loc[mid, "ep_cc"]      = df.loc[mid, "expected_cc_points"]       # already /2

df["ep_sot"] = 0.0
fwd = df["position"] == "FWD"
df.loc[fwd, "ep_sot"] = df.loc[fwd, "expected_sot_points"]         # already /2


df["ep_qualification"] = df["expected_qualification_points"] * df["prob_plays_any"]

EP_COLS = [
    "ep_appearance",
    "ep_goal",
    "ep_assist",
    "ep_yellow_card",
    "ep_red_card",
    "ep_own_goal",
    "ep_pen_won",
    "ep_pen_conceded",
    "ep_clean_sheet",
    "ep_gc_penalty",
    "ep_penalty_save",
    "ep_saves",
    "ep_tackles",
    "ep_cc",
    "ep_sot",
    "ep_qualification",
]
df["expected_points"] = df[EP_COLS].sum(axis=1)

In [425]:
EP_COLS = [c for c in df.columns if c.startswith("ep_") and c != "ep_scouting"]
df["expected_points"] = df[EP_COLS].sum(axis=1)
df.to_parquet("fantasy_optimizer.parquet", index=False)

In [426]:
df.to_csv(OUT_CSV, index=False)

print(f"\nSaved {OUT_CSV} {df.shape[0]} rows x {df.shape[1]} cols")

Saved fantasy_enriched.csv 362 rows x 235 cols

In [ ]:
# ── Scouting bonus expected value ─────────────────────────────────────────────
# Rule: +2 if player scores >4 BASE points AND is in <5% of teams.
# Ownership is known pre-round. The >4pt threshold requires a probability
# estimate: model points as Poisson(mu=expected_points) — standard in soccer
# fantasy literature. E[scouting] = I(ownership<5%) * P(X>4|mu) * 2.

def add_scouting_ep(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df["scouting_eligible"] = (df["percent_selected"] < 5.0).astype(float)
    df["prob_exceeds_4pts"] = df["expected_points"].apply(
        lambda mu: float(1 - poisson.cdf(4, max(mu, 1e-9)))
    )
    df["ep_scouting"] = df["scouting_eligible"] * df["prob_exceeds_4pts"] * 2
    return df


# ── ILP Optimizer ─────────────────────────────────────────────────────────────

def optimize_squad(
    df: pd.DataFrame,
    budget: float = 100.0,        # $100M group stage | $105M knockout
    max_per_country: int = 3,     # 3 group/R32 | 4 R16 | 5 QF | 6 SF | 8 F
    vc_dnp_prob: float = 0.10,    # P(captain DNP): approximation for VC bonus
    bench_weight: float = 0.05,   # discount factor for bench auto-sub value
    solver=None,
) -> dict | None:
    """
    Integer linear programme solving the FIFA WC Fantasy 2026 squad selection.

    Decision variables
    ─────────────────
    x[i] ∈ {0,1}  player i in 15-man squad
    s[i] ∈ {0,1}  player i in starting XI          (implies x[i]=1)
    b[i] ∈ {0,1}  player i on bench                (x[i] = s[i] + b[i])
    c[i] ∈ {0,1}  player i is captain              (must be in XI)
    v[i] ∈ {0,1}  player i is vice-captain         (must be in XI, ≠ captain)

    Objective (all in expected-points space)
    ──────────────────────────────────────
    max  Σ ep[i]·s[i]                              # XI base
       + Σ ep[i]·c[i]                              # captain doubling extra
       + Σ ep[i]·vc_dnp_prob·v[i]                 # VC expected extra (approx)
       + Σ ep_scouting[i]·s[i]                    # scouting bonus
       + Σ ep[i]·bench_weight·b[i]                # bench auto-sub upside
    """
    if "ep_scouting" not in df.columns:
        df = add_scouting_ep(df)

    idx = df.index.tolist()

    # ── Decision variables ────────────────────────────────────────────────────
    x = LpVariable.dicts("squad", idx, cat="Binary")
    s = LpVariable.dicts("xi",    idx, cat="Binary")
    b = LpVariable.dicts("bench", idx, cat="Binary")
    c = LpVariable.dicts("cap",   idx, cat="Binary")
    v = LpVariable.dicts("vc",    idx, cat="Binary")

    model = LpProblem("FIFA_WC_Fantasy_2026", LpMaximize)

    # ── Objective ─────────────────────────────────────────────────────────────
    model += lpSum(
        df.loc[i, "expected_points"]                          * s[i]
        + df.loc[i, "expected_points"]                        * c[i]
        + df.loc[i, "expected_points"] * vc_dnp_prob          * v[i]
        + df.loc[i, "ep_scouting"]                            * s[i]
        + df.loc[i, "expected_points"] * bench_weight          * b[i]
        for i in idx
    )

    # ── Squad size ────────────────────────────────────────────────────────────
    model += lpSum(x[i] for i in idx) == 15
    model += lpSum(s[i] for i in idx) == 11
    model += lpSum(b[i] for i in idx) == 4

    for i in idx:
        model += s[i] + b[i] == x[i]   # partition: every squad player is XI or bench

    # ── Budget ────────────────────────────────────────────────────────────────
    model += lpSum(df.loc[i, "price"] * x[i] for i in idx) <= budget

    # ── Squad position composition (15-man) ───────────────────────────────────
    for pos, count in [("GK", 2), ("DEF", 5), ("MID", 5), ("FWD", 3)]:
        p_idx = df[df["position"] == pos].index.tolist()
        model += lpSum(x[i] for i in p_idx) == count

    # ── Country limit ─────────────────────────────────────────────────────────
    for country in df["team"].unique():
        c_idx = df[df["team"] == country].index.tolist()
        if c_idx:
            model += lpSum(x[i] for i in c_idx) <= max_per_country

    # ── Starting XI: goalkeeper ───────────────────────────────────────────────
    gk_idx = df[df["position"] == "GK"].index.tolist()
    model += lpSum(s[i] for i in gk_idx) == 1    # exactly 1 GK starts
    model += lpSum(b[i] for i in gk_idx) == 1    # exactly 1 GK on bench

    # ── Starting XI: valid outfield formation ─────────────────────────────────
    # The 7 permitted formations are: 4-4-2, 4-3-3, 4-5-1, 3-4-3,
    # 3-5-2, 5-4-1, 5-3-2. All satisfy:
    #   DEF ∈ [3,5], MID ∈ [3,5], FWD ∈ [1,3], DEF+MID+FWD = 10 (implicit).
    # These bounds are tight — no invalid combination passes both constraints.
    for pos, lo, hi in [("DEF", 3, 5), ("MID", 3, 5), ("FWD", 1, 3)]:
        p_idx = df[df["position"] == pos].index.tolist()
        model += lpSum(s[i] for i in p_idx) >= lo
        model += lpSum(s[i] for i in p_idx) <= hi

    # ── Captain ───────────────────────────────────────────────────────────────
    model += lpSum(c[i] for i in idx) == 1
    for i in idx:
        model += c[i] <= s[i]       # captain must be in XI

    # ── Vice-captain ──────────────────────────────────────────────────────────
    model += lpSum(v[i] for i in idx) == 1
    for i in idx:
        model += v[i] <= s[i]       # VC must be in XI
        model += c[i] + v[i] <= 1  # captain ≠ vice-captain

    # ── Solve ─────────────────────────────────────────────────────────────────
    solver = solver or PULP_CBC_CMD(msg=0)
    model.solve(solver)

    if LpStatus[model.status] != "Optimal":
        print(f"[!] Solver status: {LpStatus[model.status]}")
        return None

    # ── Extract solution ──────────────────────────────────────────────────────
    in_squad = [i for i in idx if value(x[i]) > 0.5]
    in_xi    = [i for i in idx if value(s[i]) > 0.5]
    on_bench = [i for i in idx if value(b[i]) > 0.5]
    captain  = next(i for i in idx if value(c[i]) > 0.5)
    vc       = next(i for i in idx if value(v[i]) > 0.5)

    return {
        "squad":    df.loc[in_squad].copy(),
        "xi":       df.loc[in_xi].copy(),
        "bench":    df.loc[on_bench].copy(),
        "captain":  captain,
        "vc":       vc,
        "total_ep": value(model.objective),
        "cost":     df.loc[in_squad, "price"].sum(),
        "status":   LpStatus[model.status],
    }


# ── Display ───────────────────────────────────────────────────────────────────

POS_ORDER = {"GK": 0, "DEF": 1, "MID": 2, "FWD": 3}

def print_solution(result: dict, show_bench: bool = True) -> None:
    if result is None:
        print("No solution found.")
        return

    xi    = result["xi"].copy()
    bench = result["bench"].copy()
    cap   = result["captain"]
    vc    = result["vc"]

    xi["_ord"]    = xi["position"].map(POS_ORDER)
    bench["_ord"] = bench["position"].map(POS_ORDER)
    xi    = xi.sort_values(["_ord", "expected_points"], ascending=[True, False])
    bench = bench.sort_values(["_ord", "expected_points"], ascending=[True, False])

    def row_str(i, row):
        tag   = " [C]" if i == cap else " [V]" if i == vc else ""
        scout = " ★SCOUT" if row.get("scouting_eligible", 0) > 0.5 else ""
        return (f"  {row['position']:3}  {row['name']:<28} {row['team']:<22}"
                f"${row['price']:.1f}  EP:{row['expected_points']:.2f}{tag}{scout}")

    w = 72
    print(f"\n{'═'*w}")
    print(f"  EXPECTED POINTS: {result['total_ep']:.2f}   COST: ${result['cost']:.1f}M")
    print(f"{'═'*w}")

    print(f"\n  STARTING XI")
    print(f"  {'─'*68}")
    for i, row in xi.iterrows():
        print(row_str(i, row))

    if show_bench:
        print(f"\n  BENCH  (auto-sub priority: 1 → 4)")
        print(f"  {'─'*68}")
        for rank, (i, row) in enumerate(bench.iterrows(), 1):
            print(f"  [{rank}]" + row_str(i, row)[4:])

    print(f"\n  Country breakdown:")
    counts = result["squad"]["team"].value_counts()
    for team, n in counts.items():
        print(f"    {team}: {n}")
    print(f"{'═'*w}\n")


# ── Usage ─────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    df = pd.read_parquet("fantasy_optimizer.parquet")
    df = df[df["status"] == "playing"].copy()

    # expected_points must exist before add_scouting_ep
    # If it's not in the parquet, compute it here:
    EP_COLS = [c for c in df.columns if c.startswith("ep_") and c != "ep_scouting"]
    assert EP_COLS, f"No ep_ columns found. Run the EP computation cells first. Columns: {df.columns.tolist()}"
    df["expected_points"] = df[EP_COLS].sum(axis=1)

    df = add_scouting_ep(df)
    result = optimize_squad(df, budget=105.0, max_per_country=4)
    print_solution(result)

    # Round of 16 (budget +5M, country limit +1)
    # result = optimize_squad(df, budget=105.0, max_per_country=4)

════════════════════════════════════════════════════════════════════════
  EXPECTED POINTS: 118.63   COST: $8.2M
════════════════════════════════════════════════════════════════════════

  STARTING XI
  ────────────────────────────────────────────────────────────────────
  GK   Camilo Vargas                Colombia              $0.1  EP:7.26 ★SCOUT
  DEF  Dayot Upamecano              France                $0.3  EP:8.74 ★SCOUT
  DEF  Achraf Hakimi                Morocco               $0.4  EP:8.14 ★SCOUT
  DEF  Marc Cucurella               Spain                 $0.2  EP:7.22 ★SCOUT
  DEF  Aymeric Laporte              Spain                 $0.3  EP:6.52 ★SCOUT
  MID  Michael Olise                France                $0.9  EP:8.80 [V] ★SCOUT
  MID  Ousmane Dembélé              France                $0.9  EP:8.51 ★SCOUT
  MID  Vinícius Júnior              Brazil                $0.9  EP:8.08 ★SCOUT
  MID  Ismael Saibari               Morocco               $0.5  EP:6.86 ★SCOUT
  FWD  Kylian Mbappé                France                $1.0  EP:9.91 [C] ★SCOUT
  FWD  Mikel Oyarzabal              Spain                 $0.7  EP:7.10 ★SCOUT

  BENCH  (auto-sub priority: 1 → 4)
  ────────────────────────────────────────────────────────────────────
  [1]   Yassine Bounou               Morocco               $0.2  EP:6.85 ★SCOUT
  [2]F  Gabriel Magalhães            Brazil                $0.3  EP:6.50 ★SCOUT
  [3]D  Luis Díaz                    Colombia              $0.7  EP:6.21 ★SCOUT
  [4]D  Harry Kane                   England               $1.0  EP:6.41 ★SCOUT

  Country breakdown:
    France: 4
    Morocco: 3
    Spain: 3
    Brazil: 2
    Colombia: 2
    England: 1
════════════════════════════════════════════════════════════════════════