In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
!python fifa_fantasy_data.py
!python betano_parser.py
!python build_parquet.py

0/1489

50/1489

100/1489

150/1489

200/1489

250/1489

300/1489

350/1489

400/1489

450/1489

500/1489

550/1489

600/1489

650/1489

700/1489

750/1489

800/1489

850/1489

900/1489

950/1489

1000/1489

1050/1489

1100/1489

1150/1489

1200/1489

1250/1489

1300/1489

1350/1489

1400/1489

1450/1489

Done. 1489 players saved to fifa_players_full.json

Warmup: HTTP 200

Competition API: HTTP 200

Matches found: 8

[1/8] canada-marrocos

  'Canadá' → 'Canada'  vs  'Marrocos' → 'Morocco'
  1x2:         [('1', 4.8), ('X', 3.3), ('2', 1.85)]
  btts:        [('Sim', 1.85), ('Não', 1.7)]
  total >2.5:  [('Mais de 2.5', 2.02), ('Menos 2.5', 1.57)]
  home >0.5:   [('Mais de 0.5', 1.6), ('Menos 0.5', 2.07)]
  away >0.5:   [('Mais de 0.5', 1.21), ('Menos 0.5', 3.55)]
  win_by_2:    []
  handicap:    [-3.0, -2.0, -1.0, 1.0, 2.0, 3.0]
  scorers (45): [('Ismael Saibari', 2.67), ('Ayoub El Kaabi', 3.05), ('Soufiane Rahimi', 3.15), ('Brahim Díaz', 3.45), ('Jonathan David', 3.75)]

[2/8] paraguai-franca

  'Paraguai' → 'Paraguay'  vs  'França' → 'France'
  1x2:         [('1', 15.0), ('X', 6.4), ('2', 1.21)]
  btts:        [('Sim', 2.22), ('Não', 1.47)]
  total >2.5:  [('Mais de 2.5', 1.55), ('Menos 2.5', 2.07)]
  home >0.5:   [('Mais de 0.5', 2.18), ('Menos 0.5', 1.53)]
  away >0.5:   [('Mais de 0.5', 1.05), ('Menos 0.5', 6.2)]
  win_by_2:    []
  handicap:    [-5.0, -4.0, -3.0, -2.0, -1.0, 1.0, 2.0, 3.0, 4.0, 5.0]
  scorers (43): [('Kylian Mbappe', 1.53), ('Ousmane Dembélé', 2.15), ('Jean-Philippe Mateta', 2.15), ('Bradley Barcola', 2.62), ('Désiré Doué', 2.62)]

[3/8] brasil-noruega

  'Brasil' → 'Brazil'  vs  'Noruega' → 'Norway'
  1x2:         [('1', 1.88), ('X', 3.55), ('2', 4.2)]
  btts:        [('Sim', 1.57), ('Não', 2.02)]
  total >2.5:  [('Mais de 2.5', 1.65), ('Menos 2.5', 1.91)]
  home >0.5:   [('Mais de 0.5', 1.15), ('Menos 0.5', 4.15)]
  away >0.5:   [('Mais de 0.5', 1.39), ('Menos 0.5', 2.57)]
  win_by_2:    []
  handicap:    [-3.0, -2.0, -1.0, 1.0, 2.0, 3.0]
  scorers (43): [('Erling Haaland', 2.27), ('Vinícius Júnior', 2.3), ('Matheus Cunha', 2.65), ('Endrick', 2.65), ('Neymar', 2.77)]

[4/8] mexico-inglaterra

  'México' → 'Mexico'  vs  'Inglaterra' → 'England'
  1x2:         [('1', 3.15), ('X', 3.15), ('2', 2.42)]
  btts:        [('Sim', 1.9), ('Não', 1.65)]
  total >2.5:  [('Mais de 2.5', 2.18), ('Menos 2.5', 1.5)]
  home >0.5:   [('Mais de 0.5', 1.44), ('Menos 0.5', 2.42)]
  away >0.5:   [('Mais de 0.5', 1.34), ('Menos 0.5', 2.75)]
  win_by_2:    []
  handicap:    [-3.0, -2.0, -1.0, 1.0, 2.0, 3.0]
  scorers (44): [('Harry Kane', 2.62), ('Ivan Toney', 2.87), ('Ollie Watkins', 2.87), ('Raul Jimenez', 3.5), ('Armando Gonzalez', 3.8)]

[5/8] portugal-espanha

  'Portugal' → 'Portugal'  vs  'Espanha' → 'Spain'
  1x2:         [('1', 3.95), ('X', 3.65), ('2', 1.98)]
  btts:        [('Sim', 1.6), ('Não', 1.98)]
  total >2.5:  [('Mais de 2.5', 1.7), ('Menos 2.5', 1.85)]
  home >0.5:   [('Mais de 0.5', 1.39), ('Menos 0.5', 2.57)]
  away >0.5:   [('Mais de 0.5', 1.17), ('Menos 0.5', 3.95)]
  win_by_2:    []
  handicap:    [-3.0, -2.0, -1.0, 1.0, 2.0, 3.0]
  scorers (44): [('Mikel Oyarzabal', 2.02), ('Cristiano Ronaldo', 2.55), ('Lamine Yamal', 2.55), ('Ferran Torres', 2.6), ('Gonçalo Ramos', 3.05)]

[6/8] eua-belgica

  'EUA' → 'USA'  vs  'Bélgica' → 'Belgium'
  1x2:         [('1', 2.7), ('X', 3.4), ('2', 2.57)]
  btts:        [('Sim', 1.52), ('Não', 2.12)]
  total >2.5:  [('Mais de 2.5', 1.65), ('Menos 2.5', 1.91)]
  home >0.5:   [('Mais de 0.5', 1.24), ('Menos 0.5', 3.3)]
  away >0.5:   [('Mais de 0.5', 1.23), ('Menos 0.5', 3.35)]
  win_by_2:    []
  handicap:    [-3.0, -2.0, -1.0, 1.0, 2.0, 3.0]
  scorers (43): [('Romelu Lukaku', 2.18), ('Ricardo Pepi', 2.6), ('Christian Pulišić', 2.6), ('Haji Wright', 2.7), ('Giovanni Reyna', 3.35)]

[7/8] argentina-egito

  'Argentina' → 'Argentina'  vs  'Egito' → 'Egypt'
  1x2:         [('1', 1.35), ('X', 4.85), ('2', 9.5)]
  btts:        [('Sim', 2.18), ('Não', 1.5)]
  total >2.5:  [('Mais de 2.5', 1.83), ('Menos 2.5', 1.72)]
  home >0.5:   [('Mais de 0.5', 1.11), ('Menos 0.5', 4.7)]
  away >0.5:   [('Mais de 0.5', 1.98), ('Menos 0.5', 1.65)]
  win_by_2:    []
  handicap:    [-4.0, -3.0, -2.0, -1.0, 1.0, 2.0, 3.0, 4.0]
  scorers (43): [('Lionel Messi', 1.62), ('Julián Álvarez', 2.18), ('Lautaro Martínez', 2.18), ('Flaco Lopez', 2.4), ('Giuliano Simeone', 3.35)]

[8/8] suica-colombia

  'Suíça' → 'Switzerland'  vs  'Colômbia' → 'Colombia'
  1x2:         [('1', 3.5), ('X', 3.15), ('2', 2.25)]
  btts:        [('Sim', 1.83), ('Não', 1.72)]
  total >2.5:  [('Mais de 2.5', 2.1), ('Menos 2.5', 1.53)]
  home >0.5:   [('Mais de 0.5', 1.47), ('Menos 0.5', 2.32)]
  away >0.5:   [('Mais de 0.5', 1.28), ('Menos 0.5', 3.05)]
  win_by_2:    []
  handicap:    [-3.0, -2.0, -1.0, 1.0, 2.0, 3.0]
  scorers (44): [('Luis Díaz', 2.95), ('Luis Suárez', 2.95), ('Cucho Hernández', 3.05), ('Breel Embolo', 3.1), ('Cedric Itten', 3.5)]

Done. 8/8 saved to betano_odds.json

Loading betano_odds.json...
Loading fifa_players_full.json...

Match log written: 1492 lines

Total FIFA players:           1489
Players with upcoming match:  534
Players with Betano odds:     355
Unmatched Betano players:     2

Saved fantasy_optimizer.parquet and .csv

Sample (10 rows):
                     name       team position  price  anytime_scorer_odd  anytime_scorer_prob  team_cs_prob  team_score_prob
27        Cristian Romero  Argentina      DEF    4.9                6.80               0.1471        0.5455            0.809
28          Marcos Senesi  Argentina      DEF    4.7                6.80               0.1471        0.5455            0.809
29          Nahuel Molina  Argentina      DEF    4.4                9.75               0.1026        0.5455            0.809
30       Nicolás Otamendi  Argentina      DEF    4.4                7.80               0.1282        0.5455            0.809
31           Marcos Acuña  Argentina      DEF    4.3              150.00               0.0067        0.5455            0.809
32  Lucas Martínez Quarta  Argentina      DEF    4.3              150.00               0.0067        0.5455            0.809
33     Nicolás Tagliafico  Argentina      DEF    4.3                7.80               0.1282        0.5455            0.809
34          Gabriel Rojas  Argentina      DEF    4.0              150.00               0.0067        0.5455            0.809
35           Agustín Giay  Argentina      DEF    3.7              150.00               0.0067        0.5455            0.809
36           Lionel Messi  Argentina      FWD   10.0                1.62               0.6173        0.5455            0.809

Betano 'francisco trincao' -> FIFA '('frans putros', 62.06896551724138, 518)'
Betano 'martin odegaard' -> FIFA '('ronaldo martinez', 64.51612903225806, 1323)'
Betano 'leo skiri ostigard' -> FIFA '('leo stigard', 75.86206896551724, 693)'
Betano 'alex grimaldo' -> FIFA '('alejandro grimaldo', 77.41935483870968, 891)'
Betano 'pape sarr' -> FIFA '('pape matar sarr', 75.0, 842)'
Betano 'juan quintero' -> FIFA '('juan fernando quintero', 74.28571428571429, 232)'
['fifa_id', 'name', 'squad_id', 'team', 'position', 'price', 'status', 'total_points', 'avg_points', 'matches_played', 'percent_selected', 'round_1_points', 'round_2_points', 'round_3_points', 'round_4_points', 'next_fixture', 'betano_matched_name', 'betano_match_score', 'anytime_scorer_odd', 'anytime_scorer_prob', 'first_scorer_odd', 'first_scorer_prob', 'last_scorer_odd', 'match_home', 'match_away', 'is_home', 'opponent', 'match_home_win_odd', 'match_draw_odd', 'match_away_win_odd', 'match_btts_prob', 'match_over_25_odd', 'match_over_25_prob', 'match_over_35_odd', 'team_over_05_odd', 'team_over_15_odd', 'team_score_prob', 'team_score_2_prob', 'team_cs_prob', 'team_qualify_odd', 'team_win2_odd', 'opp_over_05_odd', 'opp_score_prob', 'opp_cs_prob', 'stat_GS', 'stat_AS', 'stat_CS', 'stat_GC', 'stat_MP', 'stat_YC', 'stat_RC', 'stat_ST', 'stat_SB', 'stat_CC', 'stat_PS', 'stat_T', 'stat_S', 'stat_SXI', 'stat_OG', 'stat_PC', 'stat_PW', 'stat_FK', 'round_1_SXI', 'round_1_MP', 'round_1_AS', 'round_1_YC', 'round_1_RC', 'round_1_OG', 'round_1_PW', 'round_1_PC', 'round_1_CS', 'round_1_GS', 'round_1_GC', 'round_1_PS', 'round_1_T', 'round_1_CC', 'round_1_ST', 'round_1_FK', 'round_1_S', 'round_1_SB', 'round_2_SXI', 'round_2_MP', 'round_2_AS', 'round_2_YC', 'round_2_RC', 'round_2_OG', 'round_2_PW', 'round_2_PC', 'round_2_CS', 'round_2_GS', 'round_2_GC', 'round_2_PS', 'round_2_T', 'round_2_CC', 'round_2_ST', 'round_2_FK', 'round_2_S', 'round_2_SB', 'round_3_SXI', 'round_3_MP', 'round_3_AS', 'round_3_YC', 'round_3_RC', 'round_3_OG', 'round_3_PW', 'round_3_PC', 'round_3_CS', 'round_3_GS', 'round_3_GC', 'round_3_PS', 'round_3_T', 'round_3_CC', 'round_3_ST', 'round_3_FK', 'round_3_S', 'round_3_SB', 'round_4_SXI', 'round_4_MP', 'round_4_AS', 'round_4_YC', 'round_4_RC', 'round_4_OG', 'round_4_PW', 'round_4_PC', 'round_4_CS', 'round_4_GS', 'round_4_GC', 'round_4_PS', 'round_4_T', 'round_4_CC', 'round_4_ST', 'round_4_FK', 'round_4_S', 'round_4_SB']

Total columns: 134

In [3]:
!jupyter nbconvert --to notebook --execute final_data_merging.ipynb --inplace

[NbConvertApp] Converting notebook final_data_merging.ipynb to notebook

[NbConvertApp] Writing 32794 bytes to final_data_merging.ipynb

| Column | Type | Description |
|---|---|---|
| `fifa_id` | int | FIFA fantasy platform unique player identifier |
| `name` | str | Player display name from FIFA fantasy (knownName or firstName + lastName) |
| `squad_id` | int | FIFA fantasy internal squad/nation identifier |
| `team` | str | Nation name in English, mapped from squad_id |
| `position` | str | Fantasy position: DEF, MID, FWD, GK |
| `price` | float | Fantasy selection price in FIFA fantasy currency |
| `status` | str | Player availability: playing, transferred |
| `total_points` | int | Total fantasy points accumulated across all completed rounds |
| `avg_points` | float | Average fantasy points per round played |
| `matches_played` | int | Number of rounds with non-empty stat entries |
| `percent_selected` | float | Percentage of fantasy teams that have selected this player |
| `round_i_points` | int | Fantasy points earned in round i; one column per round played; missing if player did not participate (filled to 0 post-processing) |
| `next_fixture` | int | FIFA fantasy fixture ID for the next scheduled match |

| Column | Type | Description |
|---|---|---|
| `betano_matched_name` | str | Player name as it appears in Betano scorer markets |
| `betano_match_score` | float | Fuzzy match confidence score 0 to 100; 100 indicates exact or manual override match |

| Column | Type | Description |
|---|---|---|
| `anytime_scorer_odd` | float | Betano decimal odd for player to score at any point; defaults to 150.0 if team has a match but player has no Betano entry |
| `anytime_scorer_prob` | float | Raw implied probability from anytime scorer odd (1 / odd) |
| `first_scorer_odd` | float | Betano decimal odd for player to score the first goal of the match |
| `first_scorer_prob` | float | Raw implied probability from first scorer odd (1 / odd) |
| `last_scorer_odd` | float | Betano decimal odd for player to score the last goal of the match |

| Column | Type | Description |
|---|---|---|
| `match_home` | str | Home team name for the player's next match |
| `match_away` | str | Away team name for the player's next match |
| `is_home` | bool | True if the player's team is the home side |
| `opponent` | str | Opposing team name |
| `match_home_win_odd` | float | Betano decimal odd for home team victory |
| `match_draw_odd` | float | Betano decimal odd for a draw |
| `match_away_win_odd` | float | Betano decimal odd for away team victory |
| `match_btts_prob` | float | De-vigged probability that both teams score |
| `match_over_25_odd` | float | Betano decimal odd for over 2.5 total goals |
| `match_over_25_prob` | float | De-vigged probability of over 2.5 total goals |
| `match_over_35_odd` | float | Betano decimal odd for over 3.5 total goals |
| `team_over_05_odd` | float | Betano decimal odd for the player's team to score at least 1 goal |
| `team_over_15_odd` | float | Betano decimal odd for the player's team to score at least 2 goals |
| `team_score_prob` | float | De-vigged probability the player's team scores at least once |
| `team_score_2_prob` | float | Implied probability the player's team scores 2 or more goals (1 / team_over_15_odd) |
| `team_cs_prob` | float | De-vigged probability the player's team keeps a clean sheet |
| `team_qualify_odd` | float | Betano decimal odd for the player's team to advance to the next round |
| `team_win2_odd` | float | Betano decimal odd for the player's team to win by 2 or more goals |
| `opp_over_05_odd` | float | Betano decimal odd for the opponent to score at least 1 goal |
| `opp_score_prob` | float | De-vigged probability the opponent scores at least once |
| `opp_cs_prob` | float | De-vigged probability the opponent keeps a clean sheet |

| Column | Type | Description |
|---|---|---|
| `stat_GS` | int | Goals scored during the tournament, cumulative across all rounds |
| `stat_AS` | int | Assists, cumulative |
| `stat_CS` | int | Clean sheets, cumulative |
| `stat_GC` | int | Goals conceded, cumulative |
| `stat_MP` | int | Minutes played, cumulative |
| `stat_YC` | int | Yellow cards, cumulative |
| `stat_RC` | int | Red cards, cumulative |
| `stat_ST` | int | Shots on target, cumulative |
| `stat_SB` | int | Shots blocked, cumulative |
| `stat_CC` | int | Chances created, cumulative |
| `stat_PS` | int | Penalties saved, cumulative (GK) |
| `stat_T` | int | Tackles, cumulative |
| `stat_S` | int | Saves, cumulative (GK) |
| `stat_SXI` | int | Times named in the starting XI, cumulative |
| `stat_OG` | int | Own goals, cumulative |
| `stat_PC` | int | Penalties committed, cumulative |
| `stat_PW` | int | Penalties won, cumulative |
| `stat_FK` | int | Free kicks earned, cumulative |

| Column | Type | Description |
|---|---|---|
| `round_i_GS` | int | Goals scored in round i; one column per round; absent (NaN) if player did not play that round |
| `round_i_AS` | int | Assists in round i |
| `round_i_CS` | int | Clean sheet in round i |
| `round_i_GC` | int | Goals conceded in round i |
| `round_i_MP` | int | Minutes played in round i |
| `round_i_YC` | int | Yellow cards in round i |
| `round_i_RC` | int | Red cards in round i |
| `round_i_ST` | int | Shots on target in round i |
| `round_i_SB` | int | Shots blocked in round i |
| `round_i_CC` | int | Chances created in round i |
| `round_i_PS` | int | Penalties saved in round i (GK) |
| `round_i_T` | int | Tackles in round i |
| `round_i_S` | int | Saves in round i (GK) |
| `round_i_SXI` | int | 1 if named in starting XI in round i, 0 otherwise |
| `round_i_OG` | int | Own goals in round i |
| `round_i_PC` | int | Penalties committed in round i |
| `round_i_PW` | int | Penalties won in round i |
| `round_i_FK` | int | Free kicks earned in round i |


| Column                         | Type  | Description                                                                                           |
| ------------------------------ | ----- | ----------------------------------------------------------------------------------------------------- |
| `started_last_match`           | int   | 1 if the player started the most recent round, 0 otherwise                                            |
| `starts_last_3`                | int   | Number of starts across the last 3 rounds                                                             |
| `starts_last_5`                | int   | Number of starts across the last 5 rounds                                                             |
| `start_rate`                   | float | Fraction of matches in which the player has started (`stat_SXI / matches_played`)                     |
| `minutes_last_3_avg`           | float | Average minutes played over the last 3 rounds                                                         |
| `minutes_last_5_avg`           | float | Average minutes played over the last 5 rounds                                                         |
| `goal_rate`                    | float | Goals scored per minute played (`stat_GS / stat_MP`)                                                  |
| `goals_per_start`              | float | Goals scored per start (`stat_GS / stat_SXI`)                                                         |
| `shots_on_target_per90`        | float | Shots on target per 90 minutes                                                                        |
| `goals_per_shot_on_target`     | float | Goals scored divided by shots on target                                                               |
| `recent_goals_last3`           | int   | Goals scored across the last 3 rounds                                                                 |
| `goal_streak`                  | int   | Number of consecutive rounds ending with the most recent in which the player scored at least one goal |
| `goal_expectation`             | float | Goal scoring proxy computed as `anytime_scorer_prob × team_score_prob`                                |
| `goal_expectation2`            | float | Goal scoring proxy computed as `anytime_scorer_prob × team_score_2_prob`                              |
| `assist_rate`                  | float | Assists per minute played (`stat_AS / stat_MP`)                                                       |
| `recent_assists_last3`         | int   | Assists recorded across the last 3 rounds                                                             |
| `chance_created_per90`         | float | Chances created per 90 minutes                                                                        |
| `recent_chances_created_per90` | float | Chances created per 90 minutes across the last 3 rounds                                               |
| `assist_expectation`           | float | Assist proxy computed as `chance_created_per90 × team_score_prob`                                     |
| `cs_rate`                      | float | Clean sheets per start (`stat_CS / stat_SXI`)                                                         |
| `recent_cs_rate`               | float | Average clean sheets across the last 3 rounds                                                         |
| `expected_minutes`             | float | Average minutes played over the last 3 rounds                                                         |
| `cs_expectation`               | float | Clean sheet proxy computed as `team_cs_prob × expected_minutes`                                       |
| `gc_per90`                     | float | Goals conceded per 90 minutes                                                                         |
| `expected_gc_penalty`          | float | Expected goals conceded penalty proxy computed as `opp_score_prob × (1 − team_cs_prob)`               |
| `tackles_per90`                | float | Tackles per 90 minutes                                                                                |
| `recent_tackles_per90`         | float | Tackles per 90 minutes across the last 3 rounds                                                       |
| `expected_tackle_points`       | float | Expected FIFA tackle points (`tackles_per90 / 3`)                                                     |
| `cc_per90`                     | float | Chances created per 90 minutes                                                                        |
| `recent_cc_per90`              | float | Chances created per 90 minutes across the last 3 rounds                                               |
| `expected_cc_points`           | float | Expected FIFA chance creation points (`cc_per90 / 2`)                                                 |
| `sot_per90`                    | float | Shots on target per 90 minutes                                                                        |
| `recent_sot_per90`             | float | Shots on target per 90 minutes across the last 3 rounds                                               |
| `expected_sot_points`          | float | Expected FIFA shot-on-target points (`sot_per90 / 2`)                                                 |
| `saves_per90`                  | float | Saves per 90 minutes                                                                                  |
| `recent_saves_per90`           | float | Saves per 90 minutes across the last 3 rounds                                                         |
| `expected_save_points`         | float | Expected FIFA save points (`saves_per90 / 3`)                                                         |
| `yc_per90`                     | float | Yellow cards per 90 minutes                                                                           |
| `rc_per90`                     | float | Red cards per 90 minutes                                                                              |
| `penalty_conceded_rate`        | float | Penalties conceded per 90 minutes                                                                     |
| `own_goal_rate`                | float | Own goals per 90 minutes                                                                              |
| `penalties_won_per90`          | float | Penalties won per 90 minutes                                                                          |
| `recent_penalties_won`         | int   | Penalties won across the last 3 rounds                                                                |
| `points_last1`                 | int   | Fantasy points scored in the most recent round                                                        |
| `points_last3_avg`             | float | Average fantasy points across the last 3 rounds                                                       |
| `points_last5_avg`             | float | Average fantasy points across the last 5 rounds                                                       |
| `weighted_points`              | float | Weighted recent fantasy points (`4×last1 + 3×last2 + 2×last3 + 1×last4`)                              |
| `rolling_std_points`           | float | Standard deviation of fantasy points across the last 5 rounds                                         |
| `rolling_max_points`           | int   | Maximum fantasy points scored in the last 5 rounds                                                    |
| `team_win_prob`                | float | Raw implied probability that the player's team wins its next match (`1 / win odd`)                    |
| `goal_involvement`             | float | Combined attacking proxy (`anytime_scorer_prob + assist_rate`)                                        |
| `attacking_match`              | float | Attacking environment proxy (`team_score_prob × match_over_25_prob`)                                  |
| `price_rank_team_position`     | float | Player price rank within players of the same team and fantasy position (1 = highest price)            |
| `points_rank_team_position`    | float | Total fantasy points rank within players of the same team and fantasy position (1 = most points)      |
| `minutes_rank_team_position`   | float | Minutes played rank within players of the same team and fantasy position (1 = most minutes)           |
| `starts_rank_team_position`    | float | Starts rank within players of the same team and fantasy position (1 = most starts)                    |
| `anytime_rank_team_position`   | float | Anytime scorer odds rank within players of the same team and fantasy position (1 = lowest odds)       |
| `shots_rank_team_position`     | float | Shots on target rank within players of the same team and fantasy position (1 = most shots on target)  |
| `cc_rank_team_position`        | float | Chances created rank within players of the same team and fantasy position (1 = most chances created)  |
| `tackles_rank_team_position`   | float | Tackles rank within players of the same team and fantasy position (1 = most tackles)                  |

In [4]:
df= pd.read_csv("fantasy_enriched.csv")

In [5]:
OUT_CSV = "fantasy_enriched.csv"

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 416 entries, 0 to 415
Columns: 178 entries, fifa_id to clubs_match_dist
dtypes: bool(1), float64(160), int64(4), object(1), str(12)
memory usage: 610.4+ KB

In [7]:
print(f"Dataset shape: {df.shape[0]:,} rows x {df.shape[1]} columns")
print("\n".join(df.columns))

Dataset shape: 416 rows x 178 columns
fifa_id
name
squad_id
team
position
price
status
total_points
avg_points
matches_played
percent_selected
round_1_points
round_2_points
round_3_points
round_4_points
next_fixture
betano_matched_name
betano_match_score
anytime_scorer_odd
anytime_scorer_prob
first_scorer_odd
first_scorer_prob
last_scorer_odd
match_home
match_away
is_home
opponent
match_home_win_odd
match_draw_odd
match_away_win_odd
match_btts_prob
match_over_25_odd
match_over_25_prob
match_over_35_odd
team_over_05_odd
team_over_15_odd
team_score_prob
team_score_2_prob
team_cs_prob
team_qualify_odd
team_win2_odd
opp_over_05_odd
opp_score_prob
opp_cs_prob
stat_GS
stat_AS
stat_CS
stat_GC
stat_MP
stat_YC
stat_RC
stat_ST
stat_SB
stat_CC
stat_PS
stat_T
stat_S
stat_SXI
stat_OG
stat_PC
stat_PW
stat_FK
round_1_SXI
round_1_MP
round_1_AS
round_1_YC
round_1_RC
round_1_OG
round_1_PW
round_1_PC
round_1_CS
round_1_GS
round_1_GC
round_1_PS
round_1_T
round_1_CC
round_1_ST
round_1_FK
round_1_S
round_1_SB
round_2_SXI
round_2_MP
round_2_AS
round_2_YC
round_2_RC
round_2_OG
round_2_PW
round_2_PC
round_2_CS
round_2_GS
round_2_GC
round_2_PS
round_2_T
round_2_CC
round_2_ST
round_2_FK
round_2_S
round_2_SB
round_3_SXI
round_3_MP
round_3_AS
round_3_YC
round_3_RC
round_3_OG
round_3_PW
round_3_PC
round_3_CS
round_3_GS
round_3_GC
round_3_PS
round_3_T
round_3_CC
round_3_ST
round_3_FK
round_3_S
round_3_SB
round_4_SXI
round_4_MP
round_4_AS
round_4_YC
round_4_RC
round_4_OG
round_4_PW
round_4_PC
round_4_CS
round_4_GS
round_4_GC
round_4_PS
round_4_T
round_4_CC
round_4_ST
round_4_FK
round_4_S
round_4_SB
club_MP
club_Starts
club_Min
club_90s
club_Gls
club_Ast
club_G+A
club_G-PK
club_TklW
club_Int
club_GA
club_Saves
club_CS
club_PKA
club_PKsv
club_CrdY
club_CrdR
club_PK
club_PKatt
club_SoTA
club_PKm
club_Sh
club_SoT
club_Fls
club_Fld
club_Off
club_Crs
club_OG
club_2CrdY
club_Save%
club_CS%
club_GA90
club_SoT%
club_Sh/90
club_SoT/90
club_G/Sh
club_G/SoT
club_Pos
club_Squad
club_Comp
club_Age
club_fbref_multi_club
clubstats_matched_player
clubs_match_dist

In [8]:
print(df.shape)

(416, 178)

In [9]:
df.isnull().sum().sum()

np.int64(22292)

In [10]:
categorical_cols = df.select_dtypes(include="object").columns.tolist()
numerical_cols = df.select_dtypes(include=np.number).columns.tolist()

/tmp/ipykernel_56130/2784395380.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include="object").columns.tolist()

In [11]:
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)
missing_df = pd.DataFrame({"n_missing": missing, "%_missing": missing_pct})
missing_df = missing_df[missing_df["n_missing"] > 0].sort_values("n_missing", ascending=False)

pd.set_option("display.max_rows", None)

pd.set_option("display.max_columns", None)

missing_df

                          n_missing  %_missing
next_fixture                    416     100.00
team_win2_odd                   416     100.00
club_GA90                       396      95.19
club_Save%                      396      95.19
club_CS%                        396      95.19
club_G/SoT                      214      51.44
club_G/Sh                       205      49.28
club_SoT%                       205      49.28
club_Sh                         182      43.75
club_PKm                        182      43.75
club_Fld                        182      43.75
club_90s                        182      43.75
club_Min                        182      43.75
club_CS                         182      43.75
club_PKA                        182      43.75
club_TklW                       182      43.75
club_Int                        182      43.75
club_GA                         182      43.75
club_Saves                      182      43.75
clubs_match_dist                182      43.75
clubstats_matched_player        182      43.75
club_fbref_multi_club           182      43.75
club_Age                        182      43.75
club_2CrdY                      182      43.75
club_Sh/90                      182      43.75
club_PKsv                       182      43.75
club_CrdY                       182      43.75
club_CrdR                       182      43.75
club_PK                         182      43.75
club_PKatt                      182      43.75
club_SoTA                       182      43.75
club_OG                         182      43.75
club_Crs                        182      43.75
club_Off                        182      43.75
club_Fls                        182      43.75
club_G-PK                       182      43.75
club_G+A                        182      43.75
club_Starts                     182      43.75
club_MP                         182      43.75
club_Ast                        182      43.75
club_Gls                        182      43.75
club_SoT                        182      43.75
club_SoT/90                     182      43.75
club_Comp                       182      43.75
club_Squad                      182      43.75
club_Pos                        182      43.75
round_1_points                  166      39.90
round_1_T                       166      39.90
round_1_CC                      166      39.90
round_1_ST                      166      39.90
round_1_FK                      166      39.90
round_1_SXI                     166      39.90
round_1_MP                      166      39.90
round_1_AS                      166      39.90
round_1_YC                      166      39.90
round_1_PS                      166      39.90
round_1_GC                      166      39.90
round_1_GS                      166      39.90
round_1_CS                      166      39.90
round_1_PC                      166      39.90
round_1_PW                      166      39.90
round_1_OG                      166      39.90
round_1_RC                      166      39.90
round_1_SB                      166      39.90
round_1_S                       166      39.90
round_4_GC                      165      39.66
round_4_PS                      165      39.66
round_4_RC                      165      39.66
round_4_OG                      165      39.66
round_4_FK                      165      39.66
round_4_ST                      165      39.66
round_4_T                       165      39.66
round_4_points                  165      39.66
round_4_SXI                     165      39.66
round_4_MP                      165      39.66
round_4_AS                      165      39.66
round_4_YC                      165      39.66
round_4_SB                      165      39.66
round_4_S                       165      39.66
round_4_PC                      165      39.66
round_4_CC                      165      39.66
round_4_CS                      165      39.66
round_4_GS                      165      39.66
round_4_PW                      165      39.66
round_2_AS                      162      38.94
round_2_MP                      162      38.94
round_2_SXI                     162      38.94
round_2_points                  162      38.94
round_2_YC                      162      38.94
round_2_RC                      162      38.94
round_2_OG                      162      38.94
round_2_PW                      162      38.94
round_2_PC                      162      38.94
round_2_PS                      162      38.94
round_2_GC                      162      38.94
round_2_GS                      162      38.94
round_2_CS                      162      38.94
round_2_FK                      162      38.94
round_2_ST                      162      38.94
round_2_CC                      162      38.94
round_2_T                       162      38.94
round_2_SB                      162      38.94
round_2_S                       162      38.94
round_3_YC                      160      38.46
round_3_AS                      160      38.46
round_3_points                  160      38.46
round_3_RC                      160      38.46
round_3_MP                      160      38.46
round_3_FK                      160      38.46
round_3_GS                      160      38.46
round_3_CS                      160      38.46
round_3_PC                      160      38.46
round_3_PW                      160      38.46
round_3_OG                      160      38.46
round_3_T                       160      38.46
round_3_PS                      160      38.46
round_3_SXI                     160      38.46
round_3_CC                      160      38.46
round_3_ST                      160      38.46
round_3_SB                      160      38.46
round_3_GC                      160      38.46
round_3_S                       160      38.46
betano_matched_name              65      15.62
betano_match_score               65      15.62
first_scorer_odd                 65      15.62
last_scorer_odd                  65      15.62
first_scorer_prob                65      15.62

In [12]:
IMPOSSIBLE_ODD = 150.0

scorer_odd_cols = sorted([c for c in df.columns if c.endswith("_scorer_odd")])
for col in scorer_odd_cols:
    n_filled = df[col].isna().sum()
    df[col] = df[col].fillna(IMPOSSIBLE_ODD)
    prob_col = col.replace("_odd", "_prob")
    if prob_col in df.columns:
        df[prob_col] = (1 / df[col]).round(4)
    print(f"  {col}: filled {n_filled} NaN to {IMPOSSIBLE_ODD}  (prob = {round(1/IMPOSSIBLE_ODD, 4)})")

  anytime_scorer_odd: filled 0 NaN to 150.0  (prob = 0.0067)
  first_scorer_odd: filled 65 NaN to 150.0  (prob = 0.0067)
  last_scorer_odd: filled 65 NaN to 150.0  (prob = 0.0067)

In [13]:
club_columns = []

for column in df.columns:
    if column.startswith("club_"):
        club_columns.append(column)

df = df.drop(columns=club_columns)

In [14]:
round_cols = [c for c in df.columns if c.startswith("round_")]
df[round_cols] = df[round_cols].fillna(0)

In [15]:
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)
missing_df = pd.DataFrame({"n_missing": missing, "%_missing": missing_pct})
missing_df = missing_df[missing_df["n_missing"] > 0].sort_values("n_missing", ascending=False)

pd.set_option("display.max_rows", None)

pd.set_option("display.max_columns", None)

missing_df

                          n_missing  %_missing
next_fixture                    416     100.00
team_win2_odd                   416     100.00
clubs_match_dist                182      43.75
clubstats_matched_player        182      43.75
betano_matched_name              65      15.62
betano_match_score               65      15.62

In [16]:
df["has_betano_match"] = df["betano_matched_name"].notna().astype(int)

/tmp/ipykernel_56130/560769160.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["has_betano_match"] = df["betano_matched_name"].notna().astype(int)

In [17]:
df["last_scorer_prob"]    = 1 / df["last_scorer_odd"]
df["match_home_win_prob"] = 1 / df["match_home_win_odd"]
df["match_draw_prob"]     = 1 / df["match_draw_odd"]
df["match_away_win_prob"] = 1 / df["match_away_win_odd"]
df["match_over_35_prob"]  = 1 / df["match_over_35_odd"]
df["team_over_05_prob"]   = 1 / df["team_over_05_odd"]
df["team_over_15_prob"]   = 1 / df["team_over_15_odd"]
df["team_qualify_prob"]   = 1 / df["team_qualify_odd"]
df["team_win2_prob"]      = 1 / df["team_win2_odd"]
df["opp_over_05_prob"]    = 1 / df["opp_over_05_odd"]

df = df.copy()

/tmp/ipykernel_56130/3729540695.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["last_scorer_prob"]    = 1 / df["last_scorer_odd"]
/tmp/ipykernel_56130/3729540695.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["match_home_win_prob"] = 1 / df["match_home_win_odd"]
/tmp/ipykernel_56130/3729540695.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["match_draw_prob"]     = 1 / df["match_draw_odd"]
/tmp/ipykernel_56130/3729540695.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["match_away_win_prob"] = 1 / df["match_away_win_odd"]
/tmp/ipykernel_56130/3729540695.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["match_over_35_prob"]  = 1 / df["match_over_35_odd"]
/tmp/ipykernel_56130/3729540695.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["team_over_05_prob"]   = 1 / df["team_over_05_odd"]
/tmp/ipykernel_56130/3729540695.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["team_over_15_prob"]   = 1 / df["team_over_15_odd"]
/tmp/ipykernel_56130/3729540695.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["team_qualify_prob"]   = 1 / df["team_qualify_odd"]
/tmp/ipykernel_56130/3729540695.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["team_win2_prob"]      = 1 / df["team_win2_odd"]
/tmp/ipykernel_56130/3729540695.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["opp_over_05_prob"]    = 1 / df["opp_over_05_odd"]

In [18]:
print(f"Dataset shape: {df.shape[0]:,} rows x {df.shape[1]} columns")
print("\n".join(df.columns))

Dataset shape: 416 rows x 147 columns
fifa_id
name
squad_id
team
position
price
status
total_points
avg_points
matches_played
percent_selected
round_1_points
round_2_points
round_3_points
round_4_points
next_fixture
betano_matched_name
betano_match_score
anytime_scorer_odd
anytime_scorer_prob
first_scorer_odd
first_scorer_prob
last_scorer_odd
match_home
match_away
is_home
opponent
match_home_win_odd
match_draw_odd
match_away_win_odd
match_btts_prob
match_over_25_odd
match_over_25_prob
match_over_35_odd
team_over_05_odd
team_over_15_odd
team_score_prob
team_score_2_prob
team_cs_prob
team_qualify_odd
team_win2_odd
opp_over_05_odd
opp_score_prob
opp_cs_prob
stat_GS
stat_AS
stat_CS
stat_GC
stat_MP
stat_YC
stat_RC
stat_ST
stat_SB
stat_CC
stat_PS
stat_T
stat_S
stat_SXI
stat_OG
stat_PC
stat_PW
stat_FK
round_1_SXI
round_1_MP
round_1_AS
round_1_YC
round_1_RC
round_1_OG
round_1_PW
round_1_PC
round_1_CS
round_1_GS
round_1_GC
round_1_PS
round_1_T
round_1_CC
round_1_ST
round_1_FK
round_1_S
round_1_SB
round_2_SXI
round_2_MP
round_2_AS
round_2_YC
round_2_RC
round_2_OG
round_2_PW
round_2_PC
round_2_CS
round_2_GS
round_2_GC
round_2_PS
round_2_T
round_2_CC
round_2_ST
round_2_FK
round_2_S
round_2_SB
round_3_SXI
round_3_MP
round_3_AS
round_3_YC
round_3_RC
round_3_OG
round_3_PW
round_3_PC
round_3_CS
round_3_GS
round_3_GC
round_3_PS
round_3_T
round_3_CC
round_3_ST
round_3_FK
round_3_S
round_3_SB
round_4_SXI
round_4_MP
round_4_AS
round_4_YC
round_4_RC
round_4_OG
round_4_PW
round_4_PC
round_4_CS
round_4_GS
round_4_GC
round_4_PS
round_4_T
round_4_CC
round_4_ST
round_4_FK
round_4_S
round_4_SB
clubstats_matched_player
clubs_match_dist
has_betano_match
last_scorer_prob
match_home_win_prob
match_draw_prob
match_away_win_prob
match_over_35_prob
team_over_05_prob
team_over_15_prob
team_qualify_prob
team_win2_prob
opp_over_05_prob

this code is held by strings from beggining to end any introdction of didferent format different national teams differnnt names itd break

In [19]:
def minutes_engineered(df):

    # Find all SXI columns in order
    sxi_cols = sorted(
        [c for c in df.columns if c.startswith("round_") and c.endswith("_SXI")],
        key=lambda x: int(x.split("_")[1])
    )

    # Find all MP columns in order
    mp_cols = sorted(
        [c for c in df.columns if c.startswith("round_") and c.endswith("_MP")],
        key=lambda x: int(x.split("_")[1])
    )

    # Last match
    df["started_last_match"] = df[sxi_cols[-1]]

    # Last 3 starts
    df["starts_last_3"] = df[sxi_cols[-3:]].sum(axis=1)

    # Last 5 starts
    df["starts_last_5"] = df[sxi_cols[-5:]].sum(axis=1)

    df["start_rate"] = (
    df["stat_SXI"] / df["matches_played"].replace(0, np.nan)
).fillna(0)

    # Average minutes last 3 matches
    df["minutes_last_3_avg"] = df[mp_cols[-3:]].mean(axis=1)

    # Average minutes last 5 matches
    df["minutes_last_5_avg"] = df[mp_cols[-5:]].mean(axis=1)

    return df

In [20]:
def goals_engineered(df):

    # Find goal columns in order
    goal_cols = sorted(
        [c for c in df.columns if c.startswith("round_") and c.endswith("_GS")],
        key=lambda x: int(x.split("_")[1])
    )

    # Goals per minute
    df["goal_rate"] = (
        df["stat_GS"] / df["stat_MP"].replace(0, np.nan)
    ).fillna(0)

    # Goals per start
    df["goals_per_start"] = (
        df["stat_GS"] / df["stat_SXI"].replace(0, np.nan)
    ).fillna(0)

    # Shots on target per 90
    df["shots_on_target_per90"] = (
        df["stat_ST"] * 90 / df["stat_MP"].replace(0, np.nan)
    ).fillna(0)

    # Goals per shot on target
    df["goals_per_shot_on_target"] = (
        df["stat_GS"] / df["stat_ST"].replace(0, np.nan)
    ).fillna(0)

    # Goals in last 3 rounds
    df["recent_goals_last3"] = df[goal_cols[-3:]].sum(axis=1)

    # Goal streak (number of consecutive matches with a goal, starting from most recent)
    streak = []
    for _, row in df.iterrows():
        s = 0
        for col in reversed(goal_cols):
            if row[col] > 0:
                s += 1
            else:
                break
        streak.append(s)
    df["goal_streak"] = streak

    # Rank of anytime scorer odds within team and position (1 = favourite)
    df["anytime_rank_team_position"] = (
        df.groupby(["team", "position"])["anytime_scorer_odd"]
          .rank(method="dense")
    )

    # Percentile of anytime scorer odds within team and position
    df["anytime_percentile_team_position"] = (
        df.groupby(["team", "position"])["anytime_scorer_odd"]
          .rank(pct=True)
    )

    # Expected goal involvement proxies
    df["goal_expectation"] = (
        df["anytime_scorer_prob"] * df["team_score_prob"]
    )

    df["goal_expectation2"] = (
        df["anytime_scorer_prob"] * df["team_score_2_prob"]
    )

    return df

In [21]:
def assists_engineered(df):

    # Find assist, chance created and minutes columns in order
    assist_cols = sorted(
        [c for c in df.columns if c.startswith("round_") and c.endswith("_AS")],
        key=lambda x: int(x.split("_")[1])
    )

    cc_cols = sorted(
        [c for c in df.columns if c.startswith("round_") and c.endswith("_CC")],
        key=lambda x: int(x.split("_")[1])
    )

    mp_cols = sorted(
        [c for c in df.columns if c.startswith("round_") and c.endswith("_MP")],
        key=lambda x: int(x.split("_")[1])
    )

    # Assists per minute
    df["assist_rate"] = (
        df["stat_AS"] / df["stat_MP"].replace(0, np.nan)
    ).fillna(0)

    # Assists in last 3 rounds
    df["recent_assists_last3"] = df[assist_cols[-3:]].sum(axis=1)

    # Chances created per 90
    df["chance_created_per90"] = (
        df["stat_CC"] * 90 / df["stat_MP"].replace(0, np.nan)
    ).fillna(0)

    # Chances created per 90 over the last 3 rounds
    df["recent_chances_created_per90"] = (
        df[cc_cols[-3:]].sum(axis=1) * 90 /
        df[mp_cols[-3:]].sum(axis=1).replace(0, np.nan)
    ).fillna(0)

    # Assist expectation
    df["assist_expectation"] = (
        df["chance_created_per90"] * df["team_score_prob"]
    )

    return df

In [22]:
def clean_sheet_engineered(df):

    # Find clean sheet columns in order
    cs_cols = sorted(
        [c for c in df.columns if c.startswith("round_") and c.endswith("_CS")],
        key=lambda x: int(x.split("_")[1])
    )

    # Clean sheet rate
    df["cs_rate"] = (
        df["stat_CS"] / df["stat_SXI"].replace(0, np.nan)
    ).fillna(0)

    # Clean sheet rate over last 3 matches
    df["recent_cs_rate"] = df[cs_cols[-3:]].mean(axis=1)

    # Expected minutes (use last 3 matches)
    mp_cols = sorted(
        [c for c in df.columns if c.startswith("round_") and c.endswith("_MP")],
        key=lambda x: int(x.split("_")[1])
    )

    df["expected_minutes"] = df[mp_cols[-3:]].mean(axis=1)

    # Clean sheet expectation
    df["cs_expectation"] = (
        df["team_cs_prob"] * df["expected_minutes"]
    )

    return df


def goals_conceded_engineered(df):

    # Goals conceded per 90
    df["gc_per90"] = (
        df["stat_GC"] * 90 / df["stat_MP"].replace(0, np.nan)
    ).fillna(0)

    # Expected goals conceded penalty
    df["expected_gc_penalty"] = (
        df["opp_score_prob"] * (1 - df["team_cs_prob"])
    )

    return df

In [23]:
def midfield_engineered(df):

    # Find tackle, chance created and minutes columns in order
    tackle_cols = sorted(
        [c for c in df.columns if c.startswith("round_") and c.endswith("_T")],
        key=lambda x: int(x.split("_")[1])
    )

    cc_cols = sorted(
        [c for c in df.columns if c.startswith("round_") and c.endswith("_CC")],
        key=lambda x: int(x.split("_")[1])
    )

    mp_cols = sorted(
        [c for c in df.columns if c.startswith("round_") and c.endswith("_MP")],
        key=lambda x: int(x.split("_")[1])
    )

    # Tackles per 90
    df["tackles_per90"] = (
        df["stat_T"] * 90 / df["stat_MP"].replace(0, np.nan)
    ).fillna(0)

    # Recent tackles per 90
    df["recent_tackles_per90"] = (
        df[tackle_cols[-3:]].sum(axis=1) * 90 /
        df[mp_cols[-3:]].sum(axis=1).replace(0, np.nan)
    ).fillna(0)

    # Expected tackle points
    df["expected_tackle_points"] = df["tackles_per90"] / 3

    # Chances created per 90
    df["cc_per90"] = (
        df["stat_CC"] * 90 / df["stat_MP"].replace(0, np.nan)
    ).fillna(0)

    # Recent chances created per 90
    df["recent_cc_per90"] = (
        df[cc_cols[-3:]].sum(axis=1) * 90 /
        df[mp_cols[-3:]].sum(axis=1).replace(0, np.nan)
    ).fillna(0)

    # Expected chance creation points
    df["expected_cc_points"] = df["cc_per90"] / 2

    return df

In [24]:
def forward_engineered(df):

    # Find shots on target and minutes columns in order
    sot_cols = sorted(
        [c for c in df.columns if c.startswith("round_") and c.endswith("_ST")],
        key=lambda x: int(x.split("_")[1])
    )

    mp_cols = sorted(
        [c for c in df.columns if c.startswith("round_") and c.endswith("_MP")],
        key=lambda x: int(x.split("_")[1])
    )

    # Shots on target per 90
    df["sot_per90"] = (
        df["stat_ST"] * 90 / df["stat_MP"].replace(0, np.nan)
    ).fillna(0)

    # Recent shots on target per 90
    df["recent_sot_per90"] = (
        df[sot_cols[-3:]].sum(axis=1) * 90 /
        df[mp_cols[-3:]].sum(axis=1).replace(0, np.nan)
    ).fillna(0)

    # Expected shot points
    df["expected_sot_points"] = df["sot_per90"] / 2

    return df

In [25]:
def goalkeeper_engineered(df):

    # Find saves and minutes columns in order
    save_cols = sorted(
        [c for c in df.columns if c.startswith("round_") and c.endswith("_S")],
        key=lambda x: int(x.split("_")[1])
    )

    mp_cols = sorted(
        [c for c in df.columns if c.startswith("round_") and c.endswith("_MP")],
        key=lambda x: int(x.split("_")[1])
    )

    # Saves per 90
    df["saves_per90"] = (
        df["stat_S"] * 90 / df["stat_MP"].replace(0, np.nan)
    ).fillna(0)

    # Recent saves per 90
    df["recent_saves_per90"] = (
        df[save_cols[-3:]].sum(axis=1) * 90 /
        df[mp_cols[-3:]].sum(axis=1).replace(0, np.nan)
    ).fillna(0)

    # Expected save points
    df["expected_save_points"] = df["saves_per90"] / 3

    return df

In [26]:
def discipline_engineered(df):

    # Yellow cards per 90
    df["yc_per90"] = (
        df["stat_YC"] * 90 / df["stat_MP"].replace(0, np.nan)
    ).fillna(0)

    # Red cards per 90
    df["rc_per90"] = (
        df["stat_RC"] * 90 / df["stat_MP"].replace(0, np.nan)
    ).fillna(0)

    # Penalties conceded per 90
    df["penalty_conceded_rate"] = (
        df["stat_PC"] * 90 / df["stat_MP"].replace(0, np.nan)
    ).fillna(0)

    # Own goals per 90
    df["own_goal_rate"] = (
        df["stat_OG"] * 90 / df["stat_MP"].replace(0, np.nan)
    ).fillna(0)

    return df

In [27]:
def penalties_engineered(df):

    # Find penalty won and minutes columns in order
    pw_cols = sorted(
        [c for c in df.columns if c.startswith("round_") and c.endswith("_PW")],
        key=lambda x: int(x.split("_")[1])
    )

    # Penalties won per 90
    df["penalties_won_per90"] = df["stat_PW"] * 90 / df["stat_MP"].replace(0, 1)

    # Penalties won in last 3 rounds
    df["recent_penalties_won"] = df[pw_cols[-3:]].sum(axis=1)

    return df

In [28]:
def form_engineered(df):

    # Find points columns in order
    point_cols = sorted(
        [c for c in df.columns if c.startswith("round_") and c.endswith("_points")],
        key=lambda x: int(x.split("_")[1])
    )

    # Last match points
    df["points_last1"] = df[point_cols[-1]]

    # Average points last 3 matches
    df["points_last3_avg"] = df[point_cols[-3:]].mean(axis=1)

    # Average points last 5 matches
    df["points_last5_avg"] = df[point_cols[-5:]].mean(axis=1)

    # Weighted recent points (4,3,2,1)
    df["weighted_points"] = (
        df[point_cols[-1]] * 4 +
        df[point_cols[-2]] * 3 +
        df[point_cols[-3]] * 2 +
        df[point_cols[-4]] * 1
    )

    # Standard deviation over last 5 matches
    df["rolling_std_points"] = df[point_cols[-5:]].std(axis=1, skipna=True)

    # Maximum points over last 5 matches
    df["rolling_max_points"] = df[point_cols[-5:]].max(axis=1)

    return df

In [29]:
def relative_team_engineered(df):

    def pct_rank_best(s, ascending=False):
        r = s.rank(method="average", pct=True, ascending=ascending)
        return 1 - r + (1 / len(s))

    df["price_rank_team_position"] = (
        df.groupby(["team", "position"])["price"]
          .transform(lambda x: pct_rank_best(x, ascending=False))
    )

    df["points_rank_team_position"] = (
        df.groupby(["team", "position"])["total_points"]
          .transform(lambda x: pct_rank_best(x, ascending=False))
    )

    df["minutes_rank_team_position"] = (
        df.groupby(["team", "position"])["stat_MP"]
          .transform(lambda x: pct_rank_best(x, ascending=False))
    )

    df["starts_rank_team_position"] = (
        df.groupby(["team", "position"])["stat_SXI"]
          .transform(lambda x: pct_rank_best(x, ascending=False))
    )

    df["anytime_rank_team_position"] = (
        df.groupby(["team", "position"])["anytime_scorer_odd"]
          .transform(lambda x: pct_rank_best(x, ascending=True))   # lower odds = better
    )

    df["shots_rank_team_position"] = (
        df.groupby(["team", "position"])["stat_ST"]
          .transform(lambda x: pct_rank_best(x, ascending=False))
    )

    df["cc_rank_team_position"] = (
        df.groupby(["team", "position"])["stat_CC"]
          .transform(lambda x: pct_rank_best(x, ascending=False))
    )

    df["tackles_rank_team_position"] = (
        df.groupby(["team", "position"])["stat_T"]
          .transform(lambda x: pct_rank_best(x, ascending=False))
    )

    df["selected_rank_team_position"] = (
        df.groupby(["team", "position"])["percent_selected"]
          .transform(lambda x: pct_rank_best(x, ascending=False))
    )

    return df

In [30]:
feature_functions = [
    minutes_engineered,
    goals_engineered,
    assists_engineered,
    clean_sheet_engineered,
    goals_conceded_engineered,
    midfield_engineered,
    forward_engineered,
    goalkeeper_engineered,
    discipline_engineered,
    penalties_engineered,
    form_engineered,
    relative_team_engineered,
]

for func in feature_functions:
    df = func(df)


df = df.copy()

In [31]:
# Table for missing values distribution and percentage.
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)
missing_df = pd.DataFrame({"n_missing": missing, "%_missing": missing_pct})
missing_df = missing_df[missing_df["n_missing"] > 0].sort_values("n_missing", ascending=False)

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

missing_df

                          n_missing  %_missing
next_fixture                    416     100.00
team_win2_prob                  416     100.00
team_win2_odd                   416     100.00
clubstats_matched_player        182      43.75
clubs_match_dist                182      43.75
betano_match_score               65      15.62
betano_matched_name              65      15.62

In [32]:
df = df.drop(columns=[c for c in df.columns if c.endswith("odd")])

In [33]:
df["differential"] = (df["percent_selected"] < 5).astype(int)

In [34]:
from sklearn.preprocessing import MinMaxScaler

df["price_raw"] = df["price"]

already_normalized = [
    "anytime_scorer_prob", "first_scorer_prob", "last_scorer_prob",
    "team_cs_prob", "team_score_prob", "team_score_2_prob",
    "opp_score_prob", "opp_cs_prob",
    "match_btts_prob", "match_over_25_prob",
    "team_qualify_prob", "team_win2_prob",
    "start_rate", "cs_rate", "recent_cs_rate",
    "goal_expectation", "goal_expectation2", "assist_expectation",
    "goals_per_shot_on_target",
    "price_rank_team_position", "points_rank_team_position",
    "minutes_rank_team_position", "starts_rank_team_position",
    "anytime_rank_team_position", "shots_rank_team_position",
    "cc_rank_team_position", "tackles_rank_team_position",
    "attacking_match", "team_win_prob",
]

exclude_cols = ["price_raw", "price", "squad_id", "percent_selected"] + already_normalized

num_cols = df.select_dtypes(include="number").columns.difference(exclude_cols)

scaler = MinMaxScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])

# Normalize price within each position
price_scaler = MinMaxScaler()
df["price"] = (
    df.groupby("position")["price_raw"]
      .transform(lambda x: price_scaler.fit_transform(x.to_frame()).ravel())
)

/home/pedrosalgado22/.local/lib/python3.14/site-packages/sklearn/utils/_array_api.py:794: RuntimeWarning: All-NaN slice encountered
  return xp.asarray(numpy.nanmin(X, axis=axis))
/home/pedrosalgado22/.local/lib/python3.14/site-packages/sklearn/utils/_array_api.py:814: RuntimeWarning: All-NaN slice encountered
  return xp.asarray(numpy.nanmax(X, axis=axis))

In [35]:
print(f"Dataset shape: {df.shape[0]:,} rows x {df.shape[1]} columns")
print("\n".join(df.columns))

Dataset shape: 416 rows x 195 columns
fifa_id
name
squad_id
team
position
price
status
total_points
avg_points
matches_played
percent_selected
round_1_points
round_2_points
round_3_points
round_4_points
next_fixture
betano_matched_name
betano_match_score
anytime_scorer_prob
first_scorer_prob
match_home
match_away
is_home
opponent
match_btts_prob
match_over_25_prob
team_score_prob
team_score_2_prob
team_cs_prob
opp_score_prob
opp_cs_prob
stat_GS
stat_AS
stat_CS
stat_GC
stat_MP
stat_YC
stat_RC
stat_ST
stat_SB
stat_CC
stat_PS
stat_T
stat_S
stat_SXI
stat_OG
stat_PC
stat_PW
stat_FK
round_1_SXI
round_1_MP
round_1_AS
round_1_YC
round_1_RC
round_1_OG
round_1_PW
round_1_PC
round_1_CS
round_1_GS
round_1_GC
round_1_PS
round_1_T
round_1_CC
round_1_ST
round_1_FK
round_1_S
round_1_SB
round_2_SXI
round_2_MP
round_2_AS
round_2_YC
round_2_RC
round_2_OG
round_2_PW
round_2_PC
round_2_CS
round_2_GS
round_2_GC
round_2_PS
round_2_T
round_2_CC
round_2_ST
round_2_FK
round_2_S
round_2_SB
round_3_SXI
round_3_MP
round_3_AS
round_3_YC
round_3_RC
round_3_OG
round_3_PW
round_3_PC
round_3_CS
round_3_GS
round_3_GC
round_3_PS
round_3_T
round_3_CC
round_3_ST
round_3_FK
round_3_S
round_3_SB
round_4_SXI
round_4_MP
round_4_AS
round_4_YC
round_4_RC
round_4_OG
round_4_PW
round_4_PC
round_4_CS
round_4_GS
round_4_GC
round_4_PS
round_4_T
round_4_CC
round_4_ST
round_4_FK
round_4_S
round_4_SB
clubstats_matched_player
clubs_match_dist
has_betano_match
last_scorer_prob
match_home_win_prob
match_draw_prob
match_away_win_prob
match_over_35_prob
team_over_05_prob
team_over_15_prob
team_qualify_prob
team_win2_prob
opp_over_05_prob
started_last_match
starts_last_3
starts_last_5
start_rate
minutes_last_3_avg
minutes_last_5_avg
goal_rate
goals_per_start
shots_on_target_per90
goals_per_shot_on_target
recent_goals_last3
goal_streak
anytime_rank_team_position
anytime_percentile_team_position
goal_expectation
goal_expectation2
assist_rate
recent_assists_last3
chance_created_per90
recent_chances_created_per90
assist_expectation
cs_rate
recent_cs_rate
expected_minutes
cs_expectation
gc_per90
expected_gc_penalty
tackles_per90
recent_tackles_per90
expected_tackle_points
cc_per90
recent_cc_per90
expected_cc_points
sot_per90
recent_sot_per90
expected_sot_points
saves_per90
recent_saves_per90
expected_save_points
yc_per90
rc_per90
penalty_conceded_rate
own_goal_rate
penalties_won_per90
recent_penalties_won
points_last1
points_last3_avg
points_last5_avg
weighted_points
rolling_std_points
rolling_max_points
price_rank_team_position
points_rank_team_position
minutes_rank_team_position
starts_rank_team_position
shots_rank_team_position
cc_rank_team_position
tackles_rank_team_position
selected_rank_team_position
differential
price_raw

In [36]:
df.to_csv(OUT_CSV, index=False)

print(f"\nSaved {OUT_CSV} {df.shape[0]} rows x {df.shape[1]} cols")

Saved fantasy_enriched.csv 416 rows x 195 cols